### ISSUE TITLE
Settings not saving after restart

### ISSUE THREAD

**Issue by n3rd3x3** [siavash79/AOSPMods#10]
**Describe the bug**
After rebooting / powering off and back on my phone, all of the AOSP mods app settings are cleared and I have to reapply them.

**To Reproduce**
1. Turn on settings such as light qs background
2. Reboot your phone
3. Observe

**Expected behavior**
Like in previous versions (I never tested Canary 6, so talking about Canary 5), settings stayed the same and were still applied after rebooting.

 - Device: Pixel 4a (5g) *bramble*
 - OS: Stock pixel (12L)

**LSPosed Log**
Will add later if relevant when I have time to reproduce.

**Comment by siavash79** [comment]
Lsposed has made some changes on 1.8, which conflicts with our app. I guess this is related to XSharedpreferences that they introduced

Next release has XSharedpreferences disabled and currently works fine with new Lsposed
