### ISSUE TITLE
Bootloop on stock Android 12 ROG Phone 5

### ISSUE THREAD

**Issue by marekpietrzak48** [siavash79/AOSPMods#107]
After installing module (I tried version 12 and 13) and rebooting, system bootloops.

**To Reproduce**
Install module in Magisk Manager
Reboot

**Expected behavior**
System boots normally and at least some features of this module work

 - Device: ROG Phone 5
 - OS: Stock Android 12, https://dlcdnets.asus.com/pub/ASUS/ZenFone/ZS673KS/UL-ASUS_I005_1-ASUS-31.0810.1226.77-1.1.138-2203-user.zip
As this module is meant to be used with pure AOSP, feel free to close this issue if fixing it is out of scope for this project.

Log: 
[log.txt](https://github.com/siavash79/AOSPMods/files/8598588/log.txt)

**Comment by siavash79** [comment]
Thanks for sharing

The log you sent me seems to be about 12. Because the kind of error logged is addressed in 13 and shouldn't happen there.

It'll be good if you try 13 again, if bootloop happened, share lsposed log here (open lsposed, go to log tab and press save. It will give you a zip file)

**Comment by marekpietrzak48** [comment]
The log I've attached previously was grabbed on version 13, I've installed module once more and grabbed a new log file (log1.txt). I also attached LSPosed log. There seems to be mention of this module in log.old folder in LSPosed logs, I am not sure if it is complete log because device bootloops. From my observations it seems that bootloop is caused by SystemUI crash, because system boots almost completly, and after boot there is a message "Powering off" and device goes to recovery. If You need some other logs or SystemUI.apk from my device, please let me know.

[log1.txt](https://github.com/siavash79/AOSPMods/files/8599037/log1.txt)
[LSPosed_2022-05-01T15_37_31.339.zip](https://github.com/siavash79/AOSPMods/files/8599038/LSPosed_2022-05-01T15_37_31.339.zip)

**Comment by siavash79** [comment]
the bootloop as you mentioned happens in systemui. there's nothing else to cause it

I'll look at the logs soon

**Comment by siavash79** [comment]
please deactivate all other Xposed modules you're using, and install this file:

https://github.com/siavash79/AOSPMods/suites/6333679044/artifacts/227951054

Let me know the result, and if it failed, share the logcat and lsposed log files

Cheers

**Comment by marekpietrzak48** [comment]
Unfortunatelly, same behavior with this (https://github.com/siavash79/AOSPMods/suites/6333679044/artifacts/227951054) version. I disabled almost all Xposed modules, I kept enabled only those which are related to signature spoofing and bypassing signature checks.

[LSPosed_2022-05-01T18_37_20.781.zip](https://github.com/siavash79/AOSPMods/files/8599315/LSPosed_2022-05-01T18_37_20.781.zip)
[log2.txt](https://github.com/siavash79/AOSPMods/files/8599316/log2.txt)

**Comment by siavash79** [comment]
From what I can see, there might be conflicts with other modules

**Comment by calebj** [comment]
I also had this problem earlier today, ended up having to revert to A11 via EDL mode because neither safe mode nor running `adb wait-for-device shell magisk --remove-modules` worked. I might consider trying A12 again since I haven't done very much migration yet. @marekpietrzak48 how did you revert?

**Comment by siavash79** [comment]
If you were up to it, you might want to give this a try:
https://github.com/siavash79/AOSPMods/actions/runs/2256269712

I'd also suggest that you ensure about adb access prior to test, just in case you needed it

**Comment by marekpietrzak48** [comment]
I tried it, now there is no bootloop but device boots to home screen, and SystemUI constantly crashes and navbar and statusbar is not visible. @calebj Use ADB, but connect with side USB port, not bottom one, ADB works fine during bootlop.

**Comment by marekpietrzak48** [comment]
I fotgot to mention, during last test I've disabled the lock screen password, to be able to access /data in TWRP, this can be a reason that device does not bootloop, because during previous tests lockscreen was enabled and SystemUI crash and bootloop occurred just when device booted to lockscreen. But ADB access works both when password is set and when there is no screen lock.

**Comment by calebj** [comment]
I get the same result using your latest debug apk. No navbar or statusbar the first boot after installing (no other modules or lsposed), and it restarted itself. The second time, it didn't even get to a home screen, but I recorded the logs: [logcat.log](https://github.com/siavash79/AOSPMods/files/8603927/logcat.log).

**Comment by siavash79** [comment]
Sorry guys. It seems that we can't make it compatible with ROG
