### ISSUE TITLE
Feature Request: dialer - on call vibration alerts

### ISSUE THREAD

**Issue by omartinsGH** [siavash79/AOSPMods#108]
Hello,

Just to centralize information, as already requested in the [XDA thread](https://forum.xda-developers.com/t/mod-xposed-magisk-pre-release-aosp-mods-system-modifications-for-aosp-based-android-12.4421743/post-86822231), if possible, I think it would be great if we could have a "vibrate when answered feature" feature. 
Assuming the involved variables are the same /similar, also having a vibration alert on call waiting, and, vibrate on each outgoing calling minute, would be a plus. So, per order of relevance the requests would be:

1. vibrate when answered
2. vibrate on call waiting
3. vibrate on each outgoing calling minute

Thank you!

**Comment by siavash79** [comment]
Added
