### ISSUE TITLE
Feature request: NavBar Transparency 

### ISSUE THREAD

**Issue by EleoXDA** [siavash79/AOSPMods#109]
I want to change transparency of navbar to 100% (fully invisible) to preserve screen burn-in.

I tried hiding navbar using AOSPmods, but that time the gestures through navbar were hit-and-miss. Sometimes it worked, sometimes it didn't. And every time I try a navbar gesture (like go to homescreen or open recents) when there is a text box, it would put one space (click spacebar) because the button is in the middle of the keyboard (and it would say I am typing...)

It is possible with https://github.com/Magisk-Modules-Repo/G-VisualMod but it is no longer supported. When I try, it was possible to go until 90% transparency, but not 100% 

[Screenshot_20220501-192834.png](https://user-images.githubusercontent.com/27622683/166158864-87931e2d-b11f-4290-886a-b27fd8626f28.png)

**Comment by siavash79** [comment]
Been there! With hidden navbar you get so close to the bottom that pressing space is inevitable

Also, you should try sending a WhatsApp touchless voice message: good luck with that

**Comment by EleoXDA** [comment]
![Screenshot_20220521-203451.png](https://user-images.githubusercontent.com/27622683/169664861-50e9d262-ab0c-4586-9b21-39ba5c911c30.png)
I noticed that this option completely fixes the problem with getting rid of the gesture pill without introducing transparency. This feature request can be marked as finished 👍
