### ISSUE TITLE
Add option to hide disabled mobile data icon

### ISSUE THREAD

**Issue by old4error** [siavash79/AOSPMods#120]
I mean this exclamation point at signal icon
![Screenshot_20220504-194530_Brave~2](https://user-images.githubusercontent.com/58698398/166733316-0b57dba9-7edb-4514-9bf2-c5c79cefed9c.png)
This option is in derpfest, evox, crdroid and many other roms

**Comment by EleoXDA** [comment]
This is a useful addition as I also sometimes dont use mobile data on both sims and when you add signal icon mods in AOSPMods, this "exclamation mark" can be a real deal breaker.
