### ISSUE TITLE
Magisk's "Update AOSP Mods" ChangeLog is displaying plain HTML; not showing any ChangeLog

### ISSUE THREAD

**Issue by EvilDennisR** [siavash79/AOSPMods#122]
Hello Everyone!

So this is a minor bug. I'm not sure if it's a Magisk upstream issue, or an issue with AOSPMods.

When I update AOSPMods in Magisk, the dialog that displays the ChangeLog is showing plain HTML instead of rendering a plain text ChangeLog or ChangeLog.md format.

Pixel 4a, unlocked, magisk rooted. Everything is up to date.

Here's all the info in the screenshots:

![Screenshot_20220504-234549](https://user-images.githubusercontent.com/19556705/166861731-8ca73cf7-c104-475a-867d-2975faf92e30.jpg)
![Screenshot_20220504-234759 (1)](https://user-images.githubusercontent.com/19556705/166861732-5870c169-5714-4d8e-8065-3854914e82f5.jpg)
![Screenshot_20220504-234714](https://user-images.githubusercontent.com/19556705/166861733-b9c50ed4-f4c5-4111-b353-ebab0ad53c75.jpg)
![Screenshot_20220504-233351](https://user-images.githubusercontent.com/19556705/166861734-43536038-127b-4987-8d12-c1b41dd77cfb.jpg)

**Comment by EvilDennisR** [comment]
Uhh, oops. Those are HUGE screenshots, haha. Apologies!

**Comment by EvilDennisR** [comment]
Also, I should mention that this has been persistent since AOSPMods came out of the first few canary, and was able to update via Magisk.

**Comment by siavash79** [comment]
You're right. The change log is supposed to be text format, but it's not prepared yet. so it's linked to the download web page

**Comment by EvilDennisR** [comment]
Yup, okay. I figured it was just pointing to the wrong location.

You and the group are really working hard, and doing great work on getting this mod pushed out. I thank you all!
