### ISSUE TITLE
White QS for light mode on 12.1 media control issue

### ISSUE THREAD

**Issue by velikidizel** [siavash79/AOSPMods#126]
When media control buttons are toggled, when it skips a song, when theres an animation on the media playback control "tile": the usually black parts glitch out and flicker white/black for a split second.

**Comment by siavash79** [comment]
Couldn't reproduce the glitch. Works perfectly fine at my end

Would be good if you share more information such as rom, version and possible screenshots

**Comment by siavash79** [comment]
Since it's discussed in telegram, we can safely close this
