### ISSUE TITLE
Status Bar Height - Left padding and bar height detection issue

### ISSUE THREAD

**Issue by omartinsGH** [siavash79/AOSPMods#127]
When status bar is set to other that non default, even with "correct left side padding" set on, there are some miss alignments on QS and QQS panels. Also some apps simply stop detecting the status bar, apparently assuming it does not exist or has height equal to zero.

1. Set status bar height as medium (or small)
2. pull QQS panel down - hour is missing (Red circle represents an approximated location of the camera hole)
![QQS-leftpadding-STBar-Med](https://user-images.githubusercontent.com/83125078/167252176-9924eb37-f65f-448c-898a-6790d21eee8b.jpeg)

3. pull QS panel down - week day is missing (Red circle represents an approximated location of the camera hole)
![QS-leftpadding-STBar-Med](https://user-images.githubusercontent.com/83125078/167252203-abb7f0da-4b84-406d-bdb4-9ab8f0d38f04.jpeg)

5. launch app "[Graph 89](https://play.google.com/store/apps/details?id=com.Bisha.TI89Emu)" - app assumes status bar height as zero
![Graph89-STBar-Med](https://user-images.githubusercontent.com/83125078/167252215-c5340e09-8a82-45e8-bfeb-d56d4a71da49.jpeg)

5.1 for reference, a print of the same app with Status Bar height as default:
![Graph89-STBar-Default](https://user-images.githubusercontent.com/83125078/167252242-44af9192-c5ab-4d5c-b795-c08178468de9.jpeg)

 - Device: Pixel 5
 - OS: Stock Android 12.1 with May 2022 update.
 - AOSPMods 1.0.0-beta-02
 - LSPosed-v1.8.2-6519
 - Magisk 24300

LSPosed Log
[LSPosed_2022-05-07T12_22_53.149.zip](https://github.com/siavash79/AOSPMods/files/8645015/LSPosed_2022-05-07T12_22_53.149.zip)

**Comment by siavash79** [comment]
What you're pointing out is correct: both statusbar size and statusbar left padding are overlays that get applied on top of the statusbar.
Since they are not linked with each other the outcome of using them both would not be pleasing. It's better to choose one of them
