### ISSUE TITLE
Pixel launcher mod icons issue

### ISSUE THREAD

**Issue by qwert89** [siavash79/AOSPMods#130]
Aosp mods removes mod pl icons
![Screenshot_20220507-222209_Pixel Launcher](https://user-images.githubusercontent.com/72342901/167268985-c20fb8aa-ace8-45d3-974f-eb65d62c1af4.png)

**Comment by EleoXDA** [comment]
The image is not self-explanatory. Please provide much more information about what setup you are using (device+android version+ROM name if you are using a custom one), what you are trying to do, what you expect to happen, and what happens instead.
