### ISSUE TITLE
Feature Request: QS Panel Footer To Today's Data Usage

### ISSUE THREAD

**Issue by topsy-turvy99** [siavash79/AOSPMods#134]
What's on your mind?
Currently AOSP Mods, Provides a way to change the qs panel footer to custom text, it would be cool if we could show Today's Data Usage 

Is this feature implemented on any other app/mod/rom? please specify

Vayu (poco x3 pro) Fork lineageOS
![Screenshot_20220506-215202_Nekogram.png](https://user-images.githubusercontent.com/96917972/167410896-118806c3-5d82-40e0-baa2-c7b849f68d41.png)
I have seen it in quite a few other roms too.

I have the systemui apk of this rom, i can share that if that could help

**Comment by Fxsch** [comment]
Can you also add data usage per month?
