### ISSUE TITLE
Add option to quick unlock

### ISSUE THREAD

**Issue by old4error** [siavash79/AOSPMods#139]
This feature is on lot of roms in security section of settings

Little explanation: after entering right pin or password, phone should unlock automatically, without pressing this button
![Screenshot_20220509-211855_Brave~2](https://user-images.githubusercontent.com/58698398/167473134-aaf3fdd4-3e0d-4bed-adc2-cb0ffa5f0ea4.png)

**Comment by mingaldrichgan** [comment]
+1 to this request. I am currently using [Dark Tricks](https://modules.lsposed.org/module/com.darkeyes.tricks) for this feature, and the two mods are cross-compatible with each other (FYI). GravityBox also had this feature, for another example of prior art.

**Comment by EleoXDA** [comment]
Duplicate issue: https://github.com/siavash79/AOSPMods/issues/86
