### ISSUE TITLE
Lastest Update Makes The System Unstable

### ISSUE THREAD

**Issue by topsy-turvy99** [siavash79/AOSPMods#140]
Lineage OS 19.1 A12.1

The lastest update broke something off, changing any settings makes the system ui restarts, and sometimes takes it to phone recovery,

With previous version almost all the things can be changed without restarting the systemui, everything worked fine

**Comment by siavash79** [comment]
Hi

One of the most essential objects is the Lsposed zip logs. otherwise how can anyone know why it breaks the system.

Also, the update not working on lineageos is expected, as the two are not supposed to be compatible with each other

**Comment by topsy-turvy99** [comment]
> Hi
> 
> One of the most essential objects is the Lsposed zip logs. otherwise how can anyone know why it breaks the system.
> 
> Also, the update not working on lineageos is expected, as the two are not supposed to be compatible with each other 

Oh, sorry i don't have much idea about sharing the log, and i uninstalled the module as my phone was nor working properly with mod,

I have been using the AOSP Mod on my Device from Day 1, Everything worked fine without any issues, only some few status bar tweaks were not working, which you explained the reason,

Ii thought I'll bring it to your notice, 

If you want i can reinstall the module and share you the log, I'll just have to save the Log From Lsposed and share the zip file here?

**Comment by topsy-turvy99** [comment]
> Hi
> 
> One of the most essential objects is the Lsposed zip logs. otherwise how can anyone know why it breaks the system.
> 
> Also, the update not working on lineageos is expected, as the two are not supposed to be compatible with each other 

Hey, indeed it was an AOSP Mod Bug, The latest update fixed the issue, it back to normal now,

I hope it never stops running on lineage os, there are some pretty useful tweaks in aosp mods that i don't want to lose 🙂

Thank You For Fixing and sharing a such a wonderful project
