### ISSUE TITLE
Change width of preserved center space on status bar

### ISSUE THREAD

**Issue by madriemx** [siavash79/AOSPMods#148]
Hi, I have a Galaxy S10+, running LineageOS 19.1, and the device has a wide camera cutout in the upper right.

The centre of the status bar is far too large, when it could for sure fit another system icon and a few notifications in there. Could an option to scale the centre's reserved space be added? :)

(Thanks for these tweaks! 3 column QS tiles is a godsend and I'm loving having the day name and number visible!)

![Screenshot_20220511-170611_Firefox_1](https://user-images.githubusercontent.com/74277456/167896476-9d70647e-8ce8-432b-a827-caf6b1d8cf3b.png)

**Comment by madriemx** [comment]
I don't know anything under the hood, so I'm entirely speculating, but my ideas are either that
- it's so large because it's compensating for the size of the notch even though it's already spaced for that on the side?
- or, it's because LineageOS is based on Android 12L, so designed for large-screen devices where a separator that size would just typically be fine?

I've already tried moving the centre area, but 0% is still unfortunately the best balance in my opinion (moving it either cuts off the notification icon or dot, or I lose being able to see if I'm connected to WiFi or mobile data) :/

**Comment by EleoXDA** [comment]
This is now possible with multi-row statusbar mod
