### ISSUE TITLE
Brightness slider on QS not animating correctly

### ISSUE THREAD

**Issue by RobMann94** [siavash79/AOSPMods#149]
On first pull down of quick settings, the brightness slider does not show animation when changing brightness. Once fully extended the QS panel, the slider works as expected.

1. Open QS panel (one swipe)
2. Adjust brightness slider

Brightness slider in previous versions showed animation when changing brightness.

 - Device: Google Pixel 6 Pro
 - OS: Android 12L (May release)
 - Module Version: 1.0.0-beta-03

**Comment by siavash79** [comment]
As far as I remember it never animated correctly. 

Getting a bit technical, the objects for animation are created in the system using dagger injection, and because of that I didn't have access to create one for QQS brightness

 so the slider from QS is stolen: That means the animation does happen, but it's on main QS which we don't see

**Comment by RobMann94** [comment]
> As far as I remember it never animated correctly. 
> 
> Getting a bit technical, the objects for animation are created in the system using dagger injection, and because of that I didn't have access to create one for QQS brightness
> 
>  so the slider from QS is stolen: That means the animation does happen, but it's on main QS which we don't see 

Let me go back to the previous version I was on (1.0.0-canary-013) and check as now I'm doubting whether it did or not.

**Comment by RobMann94** [comment]
> As far as I remember it never animated correctly. 
> 
> Getting a bit technical, the objects for animation are created in the system using dagger injection, and because of that I didn't have access to create one for QQS brightness
> 
>  so the slider from QS is stolen: That means the animation does happen, but it's on main QS which we don't see 

Just reverted back to 1.0.0-canary-013 and the slider is animating correctly on the first pull down of the QS panel. I'm not sure which update since then broke it as I went straight to canary 03.

**Comment by EleoXDA** [comment]
I just checked on pixel stock firmware, and here are the results:
- the brightness bar works in all conditions whichever you chose
- the only thing that fails to function is just the animation while you drag the brightness icon left abd right. And it is also bound to conditions:
1) if you don't bring the brightness bar below qs toggles, the animation works flawless
2) if you bring the brightness bar below qs toggles, the animations (and it is ONLY animations), don't work but the brightness bar itself and its function does again work flawlessly.
3) if you bring the brightness bar above qs toggles and dont restart UI and phone, the animations still will be frozen.
4)  if you bring the brightness bar above qs toggles and restart UI but not restart phone, the animations still will be frozen on qs toggles but will work flawlessly on extended qs panel
5)  if you bring the brightness bar above qs toggles and dont phone, the animations will work flawlessly as it was working before.

Here are the screenrecords:

**Comment by EleoXDA** [comment]
> > As far as I remember it never animated correctly. 
> > 
> > Getting a bit technical, the objects for animation are created in the system using dagger injection, and because of that I didn't have access to create one for QQS brightness
> > 
> >  so the slider from QS is stolen: That means the animation does happen, but it's on main QS which we don't see 
> 
> Just reverted back to 1.0.0-canary-013 and the slider is animating correctly on the first pull down of the QS panel. I'm not sure which update since then broke it as I went straight to beta-03.

So, in your case the brightness bar animations don't work at all with the new version? Doesn't matter whether it is above or below the QS panel? What is the android version, device name and ROM name that you are using?

**Comment by siavash79** [comment]
Your feedbacks are exactly in par with my results

As stated, I have big limitations when it comes to working with annotations in the code. Maybe there's a way that hasn't crossed my mind yet

Anyway, the important thing is that it works correctly. Though without proper animation

**Comment by RobMann94** [comment]
> Your feedbacks are exactly in par with my results
> 
> As stated, I have big limitations when it comes to working with annotations in the code. Maybe there's a way that hasn't crossed my mind yet
> 
> Anyway, the important thing is that it works correctly. Though without proper animation 

Completely understand. Didn't see it raised so thought I would raise it, not the end of the world if the bar doesn't animate and certainly doesn't affect the functionality of it.

For reference to your above comments, I'm running stock pixel firmware (May security update) as well and haven't used the below QS option once. Just updated back to the latest release and tested straight after the restart and does not animate. Tested below and above QS (restarting UI) and does not animate either.

Thanks for the mod anyway, definitely am not complaining considering I couldn't even create the mod in the first place!

**Comment by EleoXDA** [comment]
> > Your feedbacks are exactly in par with my results
> > 
> > As stated, I have big limitations when it comes to working with annotations in the code. Maybe there's a way that hasn't crossed my mind yet
> > 
> > Anyway, the important thing is that it works correctly. Though without proper animation 
> 
> Completely understand. Didn't see it raised so thought I would raise it, not the end of the world if the bar doesn't animate and certainly doesn't affect the functionality of it.
> 
> For reference to your above comments, I'm running stock pixel firmware (May security update) as well and haven't used the below QS option once. Just updated back to the latest release and tested straight after the restart and does not animate. Tested below and above QS (restarting UI) and does not animate either.
> 
> Thanks for the mod anyway, definitely am not complaining considering I couldn't even create the mod in the first place!
> 
> Build
> ![Screenshot_20220514-090802.png](https://user-images.githubusercontent.com/105352130/168417780-93c31f1e-f2a0-4b6d-aa37-78fffdd512d6.png)

I am exactly on the same firmware as you on pixel 6. Could you provide your xposed and lsposed modules list and if also possible the lsposed log? I don't think there could be so many differences between two devices running exactly the same firmware

**Comment by RobMann94** [comment]
That's what is confusing me as I am definitely running stock firmware on Pixel 6 Pro. The icons look different because I'm using 'Liv' icons style and 'Xperia' signal icons theme within AOSPMods.

![Screenshot_20220514-101811](https://user-images.githubusercontent.com/105352130/168419919-3e85690b-0c42-40c7-8c41-dd6dad7e8769.png)

![Screenshot_20220514-101949](https://user-images.githubusercontent.com/105352130/168419925-a6084566-3f0e-4835-8860-2a5f0c9a49e9.png)

[LSPosed_2022-05-14T10_18_53.034.zip](https://github.com/siavash79/AOSPMods/files/8692640/LSPosed_2022-05-14T10_18_53.034.zip)

**Comment by siavash79** [comment]
Luckily, the animation is very smooth on Android 13

**Comment by v1-valux** [comment]
I'm having the exact same bug, running on LineageOS 19.1 (Android 12).
Fresh install via Magisk and also tried a clean reinstall of the ROM without anything else, but results are the same.

Is this mod not incompatible to LineageOS?
Also why is the issue closed? Is the original problem considered solved?

BR

**Comment by v1-valux** [comment]
Alright just I saw the note about the "broken" features with ROMs like LineageOS.
Nevermind then :)

Good work altogether anyways.

I am curious about what could make the animation not work on a pixel phone and if there is an "easy" way to fix it..
If I make any progress I will post here..

You could leave this issue open for others to see and maybe give feedback.

cheers
o/

**Comment by EleoXDA** [comment]
> Alright just I saw the note about the "broken" features with ROMs like LineageOS. Nevermind then :)
> 
> Good work altogether anyways.
> 
> I am curious about what could make the animation not work on a pixel phone and if there is an "easy" way to fix it.. If I make any progress I will post here..
> 
> You could leave this issue open for others to see and maybe give feedback.
> 
> cheers o/

Brightness slider animates flawlessly on pixel stock firmware android 13. If there are issues on your custom ROM, please consider mentioning it to your custom ROM developer/maintainer

Maybe if you switch to Android 13 you will also see the bug resolved on your ROM. Since it no longer requires attention with coming android 13, there is no reason to focus on it
