### ISSUE TITLE
4G/LTE icon not working

### ISSUE THREAD

**Issue by Kiroolos** [siavash79/AOSPMods#15]
**Describe the bug**
It always shows **LTE** even after restarting SystemUI. 

**Screenshots**

![Screenshot_20220401-004538.png](https://user-images.githubusercontent.com/43939903/161163142-3aa65bfa-ed1c-40c7-904f-3f499221a20e.png)

 - Device: Pixel 6
 - OS: 12.1

**Comment by siavash79** [comment]
Please send the Lsposed log. (When it's set to Force 4g)

**Comment by Kiroolos** [comment]
https://drive.google.com/file/d/1FNi9tAjb5W6IKpwRmTLgtfGnmEdcg3ZS/view?usp=drivesdk

**Comment by siavash79** [comment]
Thanks!
From your log, it seems that there's no error in execution of AOSPMods. However, I can see that there are several Xposed modules installed and running on your phone at the same time.

While this is not generally a bad thing, I guess one of the modules conflict with AOSPMods in this department.

Can you please temporarily disable all other Xposed modules (and reboot) and see if the problem still persists?

**Comment by Kiroolos** [comment]
Yes you are right,
I disabled all Xposed modules, restarted SystemUI and it  has been fixed. 
Then, I enabled all the modules, rebooted and it works great. Thank you 😊
