### ISSUE TITLE
SystemUI won't start after module install

### ISSUE THREAD

**Issue by nin0-dev** [siavash79/AOSPMods#150]
**Describe the bug**
Basically after rebooting after AOSPMods install, the device just bootloops (systemUI can't load). Only module that I have installed is Zygisk LSPosed.

**To Reproduce**
1. Install the module
2. Reboot

**Expected behavior**
The SystemUI would open, allowing me to unlock and use my phone.

**Screenshots**
*Can't screenshot*

 - Device: Google Pixel 2 XL (taimen)
 - OS: crDroid 8.4 (Android 12L) 

**LSPosed Log**
*Can't access LSPosed*

**Comment by siavash79** [comment]
The module isn't compatible with CrDroid because of customizations done by CrDroid team

**Comment by nin0-dev** [comment]
Nevermind. I managed to get it to work. I am not logged in right now, could
you close the issue please?
