### ISSUE TITLE
Keeps clock text color consistent in QS header

### ISSUE THREAD

**Issue by Jnss98b** [siavash79/AOSPMods#153]
**What's on your mind?**
Ensure the clock in QS header stays in sync with the rest of the text color
![Screenshot_20220512-213910](https://user-images.githubusercontent.com/24306400/168212368-cfc032cf-3ea5-4cf8-89e9-ec9e66239224.png)

**Is this feature implemented on any other app/mod/rom? please specify**
It was implemented on typhus/eltifo's Addon Features for Pixel Devices mod

**Comment by siavash79** [comment]
It must be something else I guess. Because this mod never touches the clock color. On the contrary, in AOSPMods the clock color is used as the reference color for other stuff, such as battery bar and battery icon

**Comment by Jnss98b** [comment]
@siavash79  I'm not saying it's a bug caused by your mod. This is actually a bug in aosp bc I've had it on my device since updating to android 12 before I even root it again. I was just requesting that you mod it for consistency. This was fixed by @ElTifo in his addons mod like I said so I'm sure there's a way to do it

**Comment by siavash79** [comment]
I see. Let me check more.

The important thing is to find a consistent reference to use for the correct color. then color errors can be fixed accordingly

Why is it tricky? Because so far the clock is the only thing that's always present in the statusbar. Other shapes and info can disappear on demand

**Comment by Jnss98b** [comment]
Maybe @ElTifo can chime in

**Comment by Jnss98b** [comment]
Also I need to mention that a systemUI restart fixes it

**Comment by Jnss98b** [comment]
Just an update on something new I found. Apparently, this isn't an issue at all if you have light QS enabled. Now I do wonder if this was the same case with @ElTifo's old mod since I enabled the light QS option all the time with his mod so maybe I just didn't notice?

**Comment by EleoXDA** [comment]
Did you check with the latest canary version?

**Comment by siavash79** [comment]
Since this is a bug of ROM, it can't be covered by AOSPMods
