### ISSUE TITLE
Lockscreen weather 

### ISSUE THREAD

**Issue by hellobot09** [siavash79/AOSPMods#156]
Lockscreen weather 
Roms like lineage, arrow don't have lockscreen weather

![IMG_20220516_085730_121~2](https://user-images.githubusercontent.com/104545685/168514992-e7fc3d05-0f90-4a49-8777-f7c22f20b8b1.jpg)

Is this feature implemented on any other rom ?
Cr droid, pixel experience and many

**Comment by EleoXDA** [comment]
Off-topic:
Just out of curiosity, how could you both "like" and "love" your own GitHub request? I thought you could do only one☺️
