### ISSUE TITLE
Feature request_battery lanscape icon with percentage inside

### ISSUE THREAD

**Issue by nhanntt0401** [siavash79/AOSPMods#158]
Please help to add a layout of lanscape batter icon with percentage inside. It would be greater if we can change the fill color based on the current percentage.

**Comment by EleoXDA** [comment]
What is the difference with respect to the battery circle with the number inside? What is the actual usefulness of the mod other than a graphic interpretation of battery level?

**Comment by nhanntt0401** [comment]
The battery circle with number inside is great. Actually, the landscaple battery icon would make the experience from computer, phone (ios and other android roms), watch...be the same. It is just a suggestion to make the tweak greater (if possible).
