### ISSUE TITLE
Feature Request: Traffic indicator enhancements

### ISSUE THREAD

**Issue by xxRaiyanxxYT** [siavash79/AOSPMods#159]
### What's on your mind?
Hello is it possible to implement
custom traffic indicator offsets rather than fixed one
and add more traffic indicator styles inspired from other custom roms?
(also a toggle to only show download or upload / both)
### Is this feature implemented on any other app/mod/rom? please specify
• Cherish OS (The traffic indicator style tho)
• Derpfest (Same as above)
• AospExtended (Same as above)

**Comment by EleoXDA** [comment]
You are in luck. @siavash79 is testing this mod in new build. Soon will be out 👍

**Comment by xxRaiyanxxYT** [comment]
i see i see thanks ✨
