### ISSUE TITLE
 There is a little space here. It is requested to add a status bar position indicator switch

### ISSUE THREAD

**Issue by zxw660404** [siavash79/AOSPMods#160]
![Screenshot_20220519-113046_AOSP Mods](https://user-images.githubusercontent.com/49113514/169215977-de96b23e-48b2-4ee2-83f0-44ef9328bdde.png)

**Comment by EleoXDA** [comment]
Could you explain a little more? Your request is not descriptive enough

**Comment by zxw660404** [comment]
Picture 1 shows that the gap between batteries with aospmods installed is too large

Picture 2 shows that aospmods is not installed
![Screenshot_20220519-113046_AOSP Mods](https://user-images.githubusercontent.com/49113514/169231359-43bcba30-5523-4dfe-9068-5183dd0e9fcf.png)
![1102D802-18C2-4EEF-AA41-5117583654F8](https://user-images.githubusercontent.com/49113514/169231407-cb6f407a-b833-4421-8998-ec5225499e52.jpeg)

**Comment by zxw660404** [comment]
Status bar GPS privacy indicator switch required

**Comment by EleoXDA** [comment]
![Screenshot_20220519-104944_1.png](https://user-images.githubusercontent.com/27622683/169253694-17a9978e-3067-4fc6-b80c-4421bad514c9.png)

Statusbar GPS Navigation Privacy icon is there. It has nothing to do with AOSPMods.
