### ISSUE TITLE
Cant load font module in schinese

### ISSUE THREAD

**Issue by Mr54233** [siavash79/AOSPMods#162]
**Describe the bug**
i cant  load some font module in magisk,i dont know why 

**To Reproduce**
flash the module and reboot then the font module not work anymore

**Expected behavior**
i want the font work

**Screenshots**
just normal font not my want 

 - Device: mi 9
 - OS: pep12.1

**LSPosed Log**
Please attach LSposed Module log if you are able to. (Open LSPosed, go to module logs, press save button and attach to this bug report)
[LSPosed_2022-05-19T21_23_06.239.zip](https://github.com/siavash79/AOSPMods/files/8729474/LSPosed_2022-05-19T21_23_06.239.zip)

**Comment by siavash79** [comment]
Go to theme section and disable customized fonts. Then reboot 2 times

**Comment by Mr54233** [comment]
dude,i reboot many times, it seems dont work too
[LSPosed_2022-05-20T08_53_27.933.zip](https://github.com/siavash79/AOSPMods/files/8734970/LSPosed_2022-05-20T08_53_27.933.zip)

**Comment by EleoXDA** [comment]
We need much more information from you:
1. Your device, android version, firmware number (or if custom ROM, then its name and date), magisk version
2. Modules in magisk and lsposed
3. Does the font module work without AOSPMods module?
4. What version of AOSPMods do you have?
5. When you disable custom fonts in theme section and reboot two times as @siavash79 mentioned above, then AOSPMods has no interaction with fonts. So this basically means either your firmware/custom ROM is incompatible or the magisk font module.

**Comment by siavash79** [comment]
If you did disable the custom fonts like @EleoXDA showed and reboot many times

Then the problem doesn't relate to AOSPMods anymore

**Comment by Mr54233** [comment]
1,xiaomi mi 9 12.1 pixel experience plus 20220415-0143-official

2,disable all another module include lsposed
Does the font module work without AOSPMods module?
What version of AOSPMods do you have?
When you disable custom fonts in theme section and reboot two times as @siavash79 mentioned above, then AOSPMods has no interaction with fonts. So this basically means either your firmware/custom ROM is incompatible or the magisk font module.

**Comment by Mr54233** [comment]
1,xiaomi mi 9 12.1 pixel experience plus 20220415-0143-official
2,disable all another module include lsposed
3,yes
4,lastest beta04

**Comment by Mr54233** [comment]
https://drive.google.com/drive/folders/1yLF7zd50NPxnLmJ-PtbzMLa-wogfgMr0?usp=sharing
i upload my font module to here ,and you can test in this website https://font.yukonga.top/
the smartizen work fine but the zen black not work at all
![photo_2022-05-20_20-20-49](https://user-images.githubusercontent.com/46802509/169528382-aa350efe-36df-4cdb-a889-db376b95698a.jpg)
![Screenshot_20220520-201606_Wdnmd](https://user-images.githubusercontent.com/46802509/169528389-6843cc69-c2d3-4f91-88b8-2a3f7e57750d.png)
![Screenshot_20220520-201615_Wdnmd](https://user-images.githubusercontent.com/46802509/169528398-dc732175-ae33-4234-81ce-e2b07db2ad17.png)

i really really want you guys fix this well  ,and thank you  guys notice my issue ，thank you very much

**Comment by EleoXDA** [comment]
> https://drive.google.com/drive/folders/1yLF7zd50NPxnLmJ-PtbzMLa-wogfgMr0?usp=sharing
> i upload my font module to here ,and you can test in this website https://font.yukonga.top/
> the smartizen work fine but the zen black not work at all
> ![photo_2022-05-20_20-20-49](https://user-images.githubusercontent.com/46802509/169528382-aa350efe-36df-4cdb-a889-db376b95698a.jpg)
> ![Screenshot_20220520-201606_Wdnmd](https://user-images.githubusercontent.com/46802509/169528389-6843cc69-c2d3-4f91-88b8-2a3f7e57750d.png)
> ![Screenshot_20220520-201615_Wdnmd](https://user-images.githubusercontent.com/46802509/169528398-dc732175-ae33-4234-81ce-e2b07db2ad17.png)
> 
> i really really want you guys fix this well  ,and thank you  guys notice my issue ，thank you very much

Could you send us the lsposed logs (from the app) while you have other modules disabled?

As far as I understand it could be PE+ incompatibility. Since as we wrote above, the module has no interaction with fonts once you disable the custom fonts menu and reboot twice.

As far as the attached fonts:
As we don't speak Chinese, it would be very hard for us to test or even understand the texts on the phone.

**Comment by siavash79** [comment]
Ok let's try something else:

Since you are rooted already, I'd suggest you try something:

Visit this path: /data/adb/modules/AOSPMods/system

Inside this, there should be font and product folders. Inside product there should be another font folder too

Also, inside product there's a folder called etc

Please see if there's any font file inside them
Or any xml file with name relating to font

Or....

adb shell
su
ls -r /data/adb/modules/AOSPMods/system > /sdcard/fontReport.txt

and then share /sdcard/fontReport.txt file here

**Comment by Mr54233** [comment]
> Ok let's try something else:
> 
> Since you are rooted already, I'd suggest you try something:
> 
> Visit this path: /data/adb/modules/AOSPMods/system
> 
> Inside this, there should be font and product folders. Inside product there should be another font folder too
> 
> Also, inside product there's a folder called etc
> 
> Please see if there's any font file inside them Or any xml file with name relating to font
> 
> Or....
> 
> adb shell su ls -r /data/adb/modules/AOSPMods/system > /sdcard/fontReport.txt
> 
> and then share /sdcard/fontReport.txt file here
[fontReport.txt](https://github.com/siavash79/AOSPMods/files/8745792/fontReport.txt)

**Comment by Mr54233** [comment]
> 

i dont know why the smartizen work fine but zen not ,and they are the some aurthor made,i not sure it relate aospmods ,but when i disable it the font worked.

**Comment by siavash79** [comment]
Oops sorry. Should be ls -R (capital r) in the command. Can you please run again

**Comment by Mr54233** [comment]
of crouse wait second

**Comment by Mr54233** [comment]
[fontReport (2).txt](https://github.com/siavash79/AOSPMods/files/8746896/fontReport.2.txt)
this is zen black 's log ,it not work

**Comment by siavash79** [comment]
Thank you

As I suspected:

At the situation you reported through the file, there's zero influence of AOSPMods on the fonts

The problem you're facing has another root

**Comment by Mr54233** [comment]
dude, I delete your font module all in data/adb/module/AOSPmod  and my fonts module worked ! I think you guys should look this
