### ISSUE TITLE
Showing the wrong tile when removing suggested app from app drawer

### ISSUE THREAD

**Issue by Arportal** [siavash79/AOSPMods#168]
Description:

When removing apps from the suggested row in Pixel Launcher, the "Don't suggest app" turns into "Uninstall", but in reality, it does the former.

1.Swipe up twice
2.Hold n drag the suggested app
3.See the bug.

 - Device: Pixel 3a (Sargo)
 - OS: Android 12.1 vanilla, May Security patch

**Comment by siavash79** [comment]
You probably confused this repo with Android AOSP. 

We're not google team here my dear
