### ISSUE TITLE
Proper Left and Right Positioning for Network Monitor

### ISSUE THREAD

**Issue by ZN0N15** [siavash79/AOSPMods#171]
**What's on your mind?**

I'm thinking that there should be an option to position the Network Monitor on either Left or Right side of the notification area without any large spaces, while also respecting spaces for other icons. 

As of now the only options are [Mid-Left, Mid-Right, and Far Left]. The problem with "Mid" positions is that they're too close to the center and can overlap with Notch/Punch Hole cameras on the center. I'm proposing that there should also be options for normal left and right positions.

Also, might I suggest adding extra options and themes to change the Arrows for the Network Monitor. Maybe add something like ↑↓

**Is this feature implemented on any other app/mod/rom? please specify**

Instead of:
![Screenshot_20220522-200656_Picsart~2](https://user-images.githubusercontent.com/57549197/169694886-6281474c-f672-4515-a70a-deb0532a4578.png)

It should look like:
![Picsart_22-05-22_20-14-52-950~2](https://user-images.githubusercontent.com/57549197/169694903-b51dbb29-a788-4c38-bea0-bcb55e954e9f.png)
![Picsart_22-05-22_20-19-39-962~2](https://user-images.githubusercontent.com/57549197/169694905-e8b79d9b-5952-42d9-b805-814b04557ce0.png)

**Comment by siavash79** [comment]
One thing that you can do to match network monitor with the center camera, is to fine-tune the center area of statusbar (under statusbar options, I guess second row)

One of the efforts that was done was "minimum meddling with system managed icon areas". Meaning not to enter the notification area or system icon area field and try not to change the behavior inside them.

Even the "Far Left" placement of network monitor is achieved by moving the notification area to the middle and opening an empty space for the network monitor to appear, not to play with the icons that are managed by Android system

Arrows may have a wider space for customization in the future. At the moment I tried to use the most minimalistic icons which also match with Android's default icons

**Comment by EleoXDA** [comment]
> I also ask you to consider the possibility of making speed in one line without transferring text in the case when only one direction (upload or download) is selected for display (with bigger text size) and ability hide direction icon
> ![Screenshot_20220524-213611](https://user-images.githubusercontent.com/1549909/170108000-08d58ebc-2301-42a9-9719-9d7cc316ae6b.png)
> Thank you

There are multiple customization possibilities for the internet speed meter. But we will first be fixing the stuff that is more important to release a stable build and only then consider adding more customizations in future versions ^^)

**Comment by siavash79** [comment]
We'll try to add such options as well

The reason behind current config is simple: use less statusbar space if possible. There are many things that go there and the space is valuable
