### ISSUE TITLE
Feature request: screenshot 

### ISSUE THREAD

**Issue by Damians0** [siavash79/AOSPMods#177]
I would like to take a screenshot with long press of the home or panorama button, is it possible to add this function?

**Comment by siavash79** [comment]
What's the panorama button?

**Comment by Damians0** [comment]
> What's the panorama button?

![Screenshot_20220528-084628_Trebuchet](https://user-images.githubusercontent.com/70938047/170814014-c61c574c-eec4-4d87-a381-93f1964efe6f.png)

**Comment by EleoXDA** [comment]
> > What's the panorama button?
> 
> ![Screenshot_20220528-084628_Trebuchet](https://user-images.githubusercontent.com/70938047/170814014-c61c574c-eec4-4d87-a381-93f1964efe6f.png)
> 

It is called recents. You can use Xposed Edge

**Comment by Damians0** [comment]
> > > Qual è il pulsante panorama?
> > 
> > 
> > ![Screenshot_20220528-084628_Trebuchet](https://user-images.githubusercontent.com/70938047/170814014-c61c574c-eec4-4d87-a381-93f1964efe6f.png)
> 
> Si chiama pulsante recenti. Puoi usare Xposed Edge

But I use Zygisk I cannot use Xposed Edge

**Comment by Damians0** [comment]
Either home button or recent button is the same. Maybe home button is better.

**Comment by EleoXDA** [comment]
> > > > What is the panorama button?
> > > 
> > > 
> > > ![Screenshot_20220528-084628_Trebuchet](https://user-images.githubusercontent.com/70938047/170814014-c61c574c-eec4-4d87-a381-93f1964efe6f.png)
> > 
> > It's called the recent button. You can use Xposed Edge
> 
> But I use Zygisk I cannot use Xposed Edge

Xposed edge works PERFECTLY fine with zygisk and AOSPMods together
![Screenshot_20220528-103855.png](https://user-images.githubusercontent.com/27622683/170817937-90a77806-8038-40c2-80d4-3695da4d7bbc.png)

Just tested and even long press volume button for screenshot works.

Please use Xposed edge for remapping button functions.

**Comment by Damians0** [comment]
But if I search for xposed edge in lsposed it is not there
![Screenshot_20220528-105944_Trebuchet](https://user-images.githubusercontent.com/70938047/170818965-c03e74b6-8d3d-4f8e-8c6e-1c27f9caead1.png)

**Comment by EleoXDA** [comment]
Google play store

**Comment by Damians0** [comment]
I tried the module doesn't work with lsposed and android 12.
 The screenshot function with long press of the home button does not work

**Comment by EleoXDA** [comment]
> I tried the module doesn't work with lsposed and android 12.
>  The screenshot function with long press of the home button does not work

Home button is used for google assistant. Google search to see why you can't easily implement with another function. Anyways this issue is closed
