### ISSUE TITLE
Brightness slider on bottom is misaligned after phone restart

### ISSUE THREAD

**Issue by f4ndor** [siavash79/AOSPMods#178]
**Describe the bug**
Brightness slider on bottom is misaligned after phone restart.

**To Reproduce**
1. Enable brightness slider in quicksettings
2. Enable Move brightness slider to the bottom
3. Restart UI ( everything looks fine at this point ) 
4. Restart phone -> Slider is misaligned

**Expected behavior**
I expect the slider to remain vertically centered

**Screenshots**
![Screenshot_20220527-123328](https://user-images.githubusercontent.com/3774057/170684680-c49a0313-95e6-49b1-a149-b6e23e6197e6.jpg)

 - Device: Pixel 5
 - OS: 12.1

**Comment by EleoXDA** [comment]
Perfectly aligned here. See screenshots. Please mention which app version are you on? Your screen dpi? Are you on custom dpi from developer options or stock dpi from settings/display?

Also mention all the magisk modules, lsposed modules and themer apps present on your setup. And lastly, share lsposed logs 
![Screenshot_20220527-133129](https://user-images.githubusercontent.com/27622683/170691703-a4b8d2e5-5464-47fb-a959-9a216cd350bc.png)
![Screenshot_20220527-133235](https://user-images.githubusercontent.com/27622683/170691744-d0ee6ed9-abbc-41de-9b56-79cd657735e0.png)
![Screenshot_20220527-133237](https://user-images.githubusercontent.com/27622683/170691761-f174c547-d27d-4344-a2a8-b60d4a56125f.png)

**Comment by f4ndor** [comment]
App version: 1.0.0 - not a new issue, had this on the prev version aswell

I did not change anything dpi related in the developer options.
The current settings/display size is default.

I have no other LSPosed modules or theming apps.

And as i mentioned, it only breaks after restarting the phone. If I do a UI restart with the button in the app, it fixes it until I restart. Not a mayor issue, just not sure what is causing it.

My settings:
[aospmods-settings.zip](https://github.com/siavash79/AOSPMods/files/8786441/aospmods-settings.zip)

Logs
[LSPosed_2022-05-27T13_42_56.927.zip](https://github.com/siavash79/AOSPMods/files/8786422/LSPosed_2022-05-27T13_42_56.927.zip)

Enabled modules
![Screenshot_20220527-134340](https://user-images.githubusercontent.com/3774057/170693712-1af04eed-53bc-4b56-a620-ff3bd2a013e5.jpg)

Magisk version
![Screenshot_20220527-134328](https://user-images.githubusercontent.com/3774057/170693714-a5d79bb0-6093-48db-b0fe-f3b5f9c5a29b.jpg)

**Comment by EleoXDA** [comment]
> App version: 1.0.0 - not a new issue, had this on the prev version aswell
> 
> I did not change anything dpi related in the developer options.
> The current settings/display size is default.
> 
> I have no other LSPosed modules or theming apps.
> 
> And as i mentioned, it only breaks after restarting the phone. If I do a UI restart with the button in the app, it fixes it until I restart. Not a mayor issue, just not sure what is causing it.
> 
> My settings:
> [aospmods-settings.zip](https://github.com/siavash79/AOSPMods/files/8786441/aospmods-settings.zip)
> 
> Logs
> [LSPosed_2022-05-27T13_42_56.927.zip](https://github.com/siavash79/AOSPMods/files/8786422/LSPosed_2022-05-27T13_42_56.927.zip)
> 
> Enabled modules
> ![Screenshot_20220527-134340](https://user-images.githubusercontent.com/3774057/170693712-1af04eed-53bc-4b56-a620-ff3bd2a013e5.jpg)
> 
> Magisk version
> ![Screenshot_20220527-134328](https://user-images.githubusercontent.com/3774057/170693714-a5d79bb0-6093-48db-b0fe-f3b5f9c5a29b.jpg)
> 
> 

Truth to be told I don't understand whether you mean vertical misalignment or horizontal.
But anyways, I retried with exactly your setup including display size (default) and font size (default), quick settings row/columns but still unable to replicate. We will wait for other users to report. If none, then we cant reproduce your issue.

![ZomboDroid 28052022094912.jpg](https://user-images.githubusercontent.com/27622683/170816141-b65135af-719d-45b4-9000-b2bc5eddad8a.jpg)

**Comment by f4ndor** [comment]
I meant vertically centered, between the toggles and the bottom row / pager.
The alignment is even different on the screenshots you posted. ( on the recent screenshots, the bar is more top aligned, while on the previous ones it is perfectly centered )

But the issue (where there is no gap between the slider and the bottom toggles) might be specific to me, I'll try to figure out what could cause it.

**Comment by EleoXDA** [comment]
That is because of different screen size, resolution and dpi. There is no way to make it perfect even in stock pixel firmware without any changes. If you experiment with display size and font size in your own phone you will find out that is the case.

As far as it goes it is much important for the function to work. And it works.

Afaik this issue is cleared out 😉
