### ISSUE TITLE
Text in Qs tiles theme

### ISSUE THREAD

**Issue by pythonpy1997** [siavash79/AOSPMods#180]
What's on your mind?
Ans. After changing Qs tiles tmeme in aosp mod text gone , so I want text after changing Qs tiles theme in aosp mod.

Is this feature implemented on any other app/mod/rom? please specify
Ans. It's implemented in Project blaze
https://github.com/ProjectBlaze/manifest

![IMG_20220527_164057_251](https://user-images.githubusercontent.com/89606297/170688920-4f8be489-2648-4ded-870f-854cb39a272c.jpg)
In this screen shot you can see text under qs tiles , I want this in all qs tiles themes.

**Comment by siavash79** [comment]
You've got a very good suggestion.
However the themes are a small collection of works done by other devs.
In AOSPMods the concentration is on system apps modifications.
I'm sure some other apps that specifically focus on themes offer much wilder choices
