### ISSUE TITLE
Enabling both dual tone QS light theme and accented navigation pill causes the pill to revert back to black and white after a systemUI restart

### ISSUE THREAD

**Issue by Jnss98b** [siavash79/AOSPMods#183]
**Describe the bug**
Just keeping track of the bug mentioned in #151 

**To Reproduce**
1. Enable light QS panel
2. Enable dual tone QS panel
3. Enable navigation pill accent
4. Force restart systemUI
5. See error

**Expected behavior**
Both settings shouldn't affect each other

**Screenshots**
![Screenshot_20220527-112023](https://user-images.githubusercontent.com/24306400/170730668-85d93970-1c48-47d9-8d37-4e5602c87b68.png)

 - Device: Pixel 5
 - OS: Android 12.1

**Comment by EleoXDA** [comment]
Have you checked with the latest build?

**Comment by Jnss98b** [comment]
If you meant v1.1.2 then yes I did, on the first day it came out too. The issue's still happening
