### ISSUE TITLE
the statubar icons has moved, not symmetrically

### ISSUE THREAD

**Issue by necrosskull** [siavash79/AOSPMods#185]
# the statubar icons has moved, not symmetrically
## before using module 
![image](https://user-images.githubusercontent.com/92830706/170772678-87e240a4-6b11-4e73-aef8-60f54384ae1c.png)
## after using module
![image](https://user-images.githubusercontent.com/92830706/170772768-442831bd-f7b0-4933-bba8-b6a41a193b2c.png)
the distance between the battery icon and the network indicator has increased significantly

**Comment by EleoXDA** [comment]
Dev already aware of the issue:
https://t.me/AOSPMods_Support/202

**Comment by siavash79** [comment]
Fixed
https://github.com/siavash79/AOSPMods/commit/9e8a7012542ffb7f49962f4b053ae8cdb979bc8f
