### ISSUE TITLE
Brightness control along statusbar

### ISSUE THREAD

**Issue by Gavin123-code** [siavash79/AOSPMods#186]
What's on your mind?

Is this feature implemented on any other app/mod/rom? please specify
So I'm coming from nameless to spark OS and this was a very useful feature and sparkles didn't have it or I can't find it because I'm an idiot but it would be nice to have it added it's very useful

**Comment by mingaldrichgan** [comment]
FYI this can be achieved with Xposed Edge:

![Screenshot_20220602-141035](https://user-images.githubusercontent.com/1753319/171729633-dff8b7b1-4ce9-462b-b136-3d1bd89f3868.png)
