### ISSUE TITLE
Allow more than 4 notification icons

### ISSUE THREAD

**Issue by brmcc** [siavash79/AOSPMods#187]
Would it be possible to remove the 4 icon notification limit?  I figured this would be a popular request but maybe not.   Gravitybox had this option and I really miss it!

**Comment by siavash79** [comment]
There's no limit to notification icons, as long as your screen size allows it.

Anyway, you can expand notification area (in cost of system icons area), using "fine tune center area" in statusbar mods

**Comment by brmcc** [comment]
Thanks for letting me know this normally isn't an issue.  It appears to be on some phones at least, as searching I did find this thread today about if affecting Google Pixels:
[](https://forum.xda-developers.com/t/statusbar-notification-icon-limit-increased-to-7-android-12.4023603/)
I'll figure out how the limit was overcome with GravityBox in Android 11, and see if it's something I can make a module for or could be easily enough added to AOSPMods.  Thanks for making an awesome mod!!
