### ISSUE TITLE
Please add potion, to get  (auto-brightness ) option in qs panel

### ISSUE THREAD

**Issue by Avikbarui** [siavash79/AOSPMods#189]
Please add potion, to get  (auto-brightness ) option in qs panel
![IMG_20220530_014637_526](https://user-images.githubusercontent.com/65493316/170889739-5d50fcc8-1338-4a11-b55b-23e1b62e2aa7.jpg)

**Comment by EleoXDA** [comment]
As it is in the request template, you need to mention from which open-source (not MIUI) custom ROM you request it

**Comment by Avikbarui** [comment]
> 

From evolutionx rom source code you can get this!

**Comment by Jnss98b** [comment]
Pretty sure it was in the mod by ElTifo that was the predecessor to this mod as well
