### ISSUE TITLE
Add option to see data usage in qs panel

### ISSUE THREAD

**Issue by Avikbarui** [siavash79/AOSPMods#190]
Add option to see data usage in qs panel
![IMG_20220530_015742_566](https://user-images.githubusercontent.com/65493316/170890217-c4c65105-306d-4738-abeb-2cfc73d3c435.jpg)

**Comment by siavash79** [comment]
Thanks

It's already added in the code and will be available in the next release

**Comment by siavash79** [comment]
Plus much more advanced options

**Comment by EleoXDA** [comment]
Added since canary build27
