### ISSUE TITLE
On latest sparkos 12.3, advance toogle to reboot will turn white when device set to darkmode and opposite on the other side when device is not in darkmode advance toogle will turn blavk

### ISSUE THREAD

**Issue by savagelmc** [siavash79/AOSPMods#195]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

 - Device: 
 - OS: 

**LSPosed Log**
Please attach LSposed Module log if you are able to. (Open LSPosed, go to module logs, press save button and attach to this bug report)

**Comment by EleoXDA** [comment]
Please put a concise description of event with in depth info about your device AND lsposed logs
