### ISSUE TITLE
Is it really necessary to show the combined icons on status bar

### ISSUE THREAD

**Issue by Kitsunejasutin** [siavash79/AOSPMods#196]
Like the title said, Before these combined icons is hidden on status bar and only appears on qs. Is it intentional or some kind of bug?
![Screenshot_20220531-070803_Pixel Launcher](https://user-images.githubusercontent.com/73803767/171067269-d066cfd9-5e48-4455-bb7e-910c66a365b5.png)

**Comment by siavash79** [comment]
What shows in the screenshot is not the result of this module.

It's either your ROM doing it or maybe some other modules. AOSPMods doesn't modify the signal icons (except asking system to replace LTE with 4g or use combined icons, but not doing so itself)

**Comment by Kitsunejasutin** [comment]
> What shows in the screenshot is not the result of this module.
> 
> It's either your ROM doing it or maybe some other modules. AOSPMods doesn't modify the signal icons (except asking system to replace LTE with 4g or use combined icons, but not doing so itself)

Hmmm I see, my rom doesn't have signal icon modifications but I'll check it further thanks
