### ISSUE TITLE
[Feature Request] Preview for icon styles

### ISSUE THREAD

**Issue by flame-0** [siavash79/AOSPMods#197]
**Description**
Preview for icon styles, such as signal, quick settings, and/or any related to icon styles.

**Is this feature implemented on any other Application or ROM?**
Yes, it is implemented on [CherishOS](https://github.com/CherishOS).

**Example**
> <img src="https://user-images.githubusercontent.com/40175769/171099213-325451b5-e839-49f0-8654-bfb13ba6e1b3.png" alt="drawing" height="512"/>
>
> _Image is from CherishOS user._

**Comment by siavash79** [comment]
Sorry. Not in the plans
