### ISSUE TITLE
BUGGED

### ISSUE THREAD

**Issue by savagelmc** [siavash79/AOSPMods#198]
On latest sparkos 12.3, advance toogle to reboot will turn white when device set to darkmode and opposite on the other side when device is not in darkmode advance toogle will turn black

 - Device: Realme 6/RM6785
 - OS: Android 12L

![Screenshot_20220531-204403_Settings.png](https://user-images.githubusercontent.com/103225133/171177221-76219cb3-9fe5-4227-b2d0-803d6ff67488.png)![Screenshot_20220531-204411_Settings.png](https://user-images.githubusercontent.com/103225133/171177238-8fa91923-3d62-435e-91e2-2a5f156ff1d9.png)
 

https://drive.google.com/drive/folders/1-z996YGcfwIfqX8VuJ31Rpd0ZaB1MDAE

Attached link/file are lsposed logs and screenshot

**Comment by EleoXDA** [comment]
What is "advance toggle to reboot"?
If you mean these, then they work perfectly fine in pixel stock firmware. It is problem of the custom ROM you are using. Please report to your custom
![Screenshot_20220531-150547](https://user-images.githubusercontent.com/27622683/171180430-400e021d-8964-4163-ad13-581479194498.png)
![Screenshot_20220531-150559](https://user-images.githubusercontent.com/27622683/171180460-05937883-6834-48a5-a7b5-152e9ec332db.png)
 ROM maintainer

**Comment by EleoXDA** [comment]
Ok, noted
