### ISSUE TITLE
Separate Wi-Fi/Mobile data QS toggle doesn't work, Pixel 6 stock

### ISSUE THREAD

**Issue by lonsagisawa** [siavash79/AOSPMods#20]
**Describe the bug**
Separate Wi-Fi/Mobile data QS toggle not working in Pixel 6 stock ROM.

**To Reproduce**
1. Turn on separate internet tile in AOSP Mods app
2. Reboot the device
3. Open quick settings and enter edit mode
4. Internet toggle is still unified

**Expected behavior**
Separate Wi-Fi/Mobile data QS toggle appears.

**Screenshots**
https://user-images.githubusercontent.com/5173607/161377196-db9102fd-c309-42c7-8bb5-a9af4ed760f0.mov

 - Device: Pixel 6
 - OS: Stock 12.1 March update(SP2A.220305.013.A3)

**LSPosed Log**
https://www.dropbox.com/s/2603nl0hjpo6w1k/LSPosed_2022-04-02T18_35_58.855.zip?dl=0

Thanks for effort, I'm quite happy with this mod and stock ROM!

**Comment by KuroHaze** [comment]
I can confirm the same behavior on the Pixel 6 Pro on stock ROM March security patch.  Same method of reproduction as  the initial post and have included the LSPosed log as well.  Thank you!

https://drive.google.com/file/d/11nUBFzID0WrHe9y1gQjqxrTpurNJsrsg/view?usp=sharing

**Comment by siavash79** [comment]
Thanks for your report.

The first thing is to make sure your app has root permissions. If so, it would be good if you can install the attached debug build, and send me the logs again: (you can install it normally)
- Install the apk
- reboot systemui (or phone)
- turn the internet switch off/on
- send the logs again, so that it can be studied further

**Comment by KuroHaze** [comment]
I have installed the debug apk and reproduced the issue via your instructions.  Here is the updated log.  Thanks!

https://drive.google.com/file/d/1MeQZWk1OsytAwAmh4IxeeFBN6Z-zyvKq/view?usp=sharing

**Comment by lonsagisawa** [comment]
Okay it was my bad, grant root access permission to SystemUI(not AOSP Mods though) and voila! It worked! Tried attached debug build first but also works with current beta build.

![Screenshot_20220403-175829](https://user-images.githubusercontent.com/5173607/161420366-5500e048-31cc-4a6a-9caa-0a7840ddd23b.png)

**Comment by siavash79** [comment]
> I have installed the debug apk and reproduced the issue via your instructions.  Here is the updated log.  Thanks!
> 
> https://drive.google.com/file/d/1MeQZWk1OsytAwAmh4IxeeFBN6Z-zyvKq/view?usp=sharing

Thanks. It seems like you're also having issues with root permission of systemUI. Please try it and let me know if you're okay or not

**Comment by KuroHaze** [comment]
That seemed to do the trick.  There was no initial prompt from Magisk to allow root access to SystemUI.  But the separate tiles are working now.  Thank you!

**Comment by lonsagisawa** [comment]
Maybe add instruction to grant root access to SystemUI in XDA post or somewhere helps people like me.
