### ISSUE TITLE
System UI Crashes/Reboots Pretty Often Throught The Day On Latest Module

### ISSUE THREAD

**Issue by parasgargexx20** [siavash79/AOSPMods#202]
**Describe the bug**
System UI Crashes/Reboots Automatically A Lot More Often Than Stock UI With No Mods Applied.

**To Reproduce**
1. Go to 'AOSP Mods App'
2. Click on 'Any Customization Option You See In The App And Test It For A While And You Will Likely See System UI Crash/Reset In A Few Hours'

**Expected behavior**
The Mod Should Be More Stable For Other Pixel Based Custom Roms And Shouldn't Crash/Reboot The SystemUI Pretty Often Throughout The Day.

**Screenshots**

 - Device: Redmi Note 9 Pro (curtana/miatoll)
 - OS: Android 12.1/Android 12L PixelExperience_Plus_miatoll-12.1-20220517-2311-OFFICIAL.zip

**LSPosed Log**
Please attach LSposed Module log if you are able to. (Open LSPosed, go to module logs, press save button and attach to this bug report)

I might have attached logs twice by mistake sorry.
[LSPosed_2022-06-01T19_41_02.413.zip](https://github.com/siavash79/AOSPMods/files/8815027/LSPosed_2022-06-01T19_41_02.413.zip)

**Comment by EleoXDA** [comment]
Pixel Experience Plus is much more away from stock pixel than other ROMs like Pixel Experience or Lineage OS. 

So, basically this mod is built on and tested on stock pixel firmware and we also have several other ROM users like Pixel Experience, LineageOS, ArrowOS, ProtonOS and etc that tell us they have most of the functions working even though these custom ROMs are not fully supported.

As far as the "systemUI restart", are you sure those are systemUI restarts or simply overlay refresh? I will check the logs to find whether there are any mentioning of systemUI crash or not

**Comment by EleoXDA** [comment]
Could you please update to stable 1.1.1 from inside the app and check how it is now?

**Comment by parasgargexx20** [comment]
> Could you please update to stable 1.1.1 from inside the app and check how it is now?

Ok

**Comment by parasgargexx20** [comment]
But On GitHub I Saw 1.0.0 Stable So I Thought It's Latest

**Comment by parasgargexx20** [comment]
It Geniunely Restarts System UI

**Comment by parasgargexx20** [comment]
I'll Try 1.1.1

**Comment by parasgargexx20** [comment]
> Could you please update to stable 1.1.1 from inside the app and check how it is now?

I Installed It And Am Doing Testing
But My Initial Testing Says It's Much More Stable Now On v1.1.1 But I'll See If There Are System UI Restarts Or Not After Using It For Atleast A Day Or Two

**Comment by parasgargexx20** [comment]
> I'll Try 1.1.1 (Clean Install)

I Have Clean Installed V1.1.1

**Comment by parasgargexx20** [comment]
![Screenshot_20220602-113600_Kiwi Browser](https://user-images.githubusercontent.com/102552831/171563892-4b17f852-f845-4141-a23d-5c07e9fdcc75.png)

**Comment by EleoXDA** [comment]
As far as I understand this build is more stable for you. If you run into a new system instability please make a new report. Also, please consider talking about your other app issues with your ROM maintainer as they worsen your experience with ROM :)

**Comment by parasgargexx20** [comment]
https://user-images.githubusercontent.com/102552831/171566572-2509bca4-f14a-496f-89ec-4571bb635c8d.mp4

One Thing Which Is Common With All AOSP Mods Build Is The FingerPrint Unlock Animation Is Slowed Down When The Mod Is Installed

**Comment by EleoXDA** [comment]
It could be because of device chipset optimization and so on. But as far as pixel devices are concerned we did not notice any changes. As I said this also could be because of poor compatibility of PE+ with our MOD.

**Comment by parasgargexx20** [comment]
> It could be because of device chipset optimization and so on. But as far as pixel devices are concerned we did not notice any changes. As I said this also could be because of poor compatibility of PE+ with our MOD.

Alright. Actually My Device Has Snapdragon 720G Chip
