### ISSUE TITLE
Keyboard arrows

### ISSUE THREAD

**Issue by k2helix** [siavash79/AOSPMods#203]
Hello, thank you for creating this module, it is very helpful.

One thing I miss from a previous Android version (11) was the option to toggle on keyboard arrows that would show on bottom left and right corners whenever the keyboard was opened. With gesture navigation, it was also possible with a GravityBox option.

I think it would be highly useful, as for now the only way to move throughout text is by using the volume keys.

**Comment by mingaldrichgan** [comment]
+1 to this. Here's the commit where GravityBox added them to the gesture navigation bar:
https://github.com/GravityBox/GravityBox/commit/cab192bc6828932ba4d023ac9b39c16cc94d0d50

**Comment by EleoXDA** [comment]
You can still get it with 3rd party keyboard apps though.

**Comment by EleoXDA** [comment]
> And Gboard hold-swipe on space key

Yes. I use that function all the time

**Comment by siavash79** [comment]
+ The more I think about it, the more certain I become: Not adding the old 3-button navbar mods: 3-button is extinct

**Comment by mingaldrichgan** [comment]
>> And Gboard hold-swipe on space key
> Yes. I use that function all the time
As do I, but it's really not the same thing.

> The more I think about it, the more certain I become: Not adding the old 3-button navbar mods: 3-button is extinct
I respectfully disagree with this being considered a 3-button navbar mod. GravityBox was able to get it to work with the gestural nav bar.

That said, this is one of the features I was hoping to take a stab at implementing myself when I had the time. Unfortunately, I've been busy.
