### ISSUE TITLE
Performance And Stability Issues With The White Quick Settings On V1.1.2 

### ISSUE THREAD

**Issue by parasgargexx20** [siavash79/AOSPMods#204]
**Describe the bug**

**To Reproduce**
1. Go to 'AOSP Mods App'
2. Click on 'Quick Settings Option And Turn On White Quick Settings Option And Lock Your Device And Turn On Screen (Do Not Unlock) Try Accessing Quick Settings'
4. See The Laggy Notification Pull Down That's Even Worse Than MIUI.

**Expected behavior**
The Mod Should Be More Stable For Other Pixel Based Custom Roms.

**Screenshots**

 - Device: Redmi Note 9 Pro (curtana/miatoll)
 - OS: Android 12.1/Android 12L PixelExperience_Plus_miatoll-12.1-20220517-2311-OFFICIAL.zip

**LSPosed Log**
Please attach LSposed Module log if you are able to. (Open LSPosed, go to module logs, press save button and attach to this bug report)
[LSPosed_2022-06-02T21_21_36.234.zip](https://github.com/siavash79/AOSPMods/files/8825508/LSPosed_2022-06-02T21_21_36.234.zip)

**Comment by parasgargexx20** [comment]
Also One More Thing I Always Clean Install The Updates Of AOSP Mods.

**Comment by siavash79** [comment]
- Can't produce the lag myself. I hope someone else can test it too @EleoXDA @ElTifo 
- You never need to "clean install" the module. Magisk modules (by default) clean-install themselves. You're only making your life difficult by having to set the settings again

**Comment by EleoXDA** [comment]
Please share a video cast. There is no slowdown on our side. It is still probably related to PE+ not being compatible with this MOD. You did mention you use PE+ on your previous report

Please switch to PE or ProtonOS and check the result. No other user has experienced in our 190 member test group.

**Comment by parasgargexx20** [comment]
https://user-images.githubusercontent.com/102552831/171772548-92dec0c1-6e1c-418b-9bf7-6399b8d0163e.mp4


https://user-images.githubusercontent.com/102552831/171772565-a8846e06-4717-47c7-938a-3676009e374e.mp4

**Comment by parasgargexx20** [comment]
> Please share a video cast. There is no slowdown on our side. It is still probably related to PE+ not being compatible with this MOD. You did mention you use PE+ on your previous report
> 
> Please switch to PE or ProtonOS and check the result. No other user has experienced any slowdown in our 190 member telegram test group.

The Thing Is Stock PE Has Older Security Patch And My Phone Obviously Is Not A Pixel So It Won't Have Official Proton Rom Build

**Comment by parasgargexx20** [comment]
> * Can't produce the lag myself. I hope someone else can test it too @EleoXDA @ElTifo
> * You never need to "clean install" the module. Magisk modules (by default) clean-install themselves. You're only making your life difficult by having to set the settings again

I Took Backup Of Previous Settings

**Comment by parasgargexx20** [comment]
![Screenshot_20220603-075507_Kiwi Browser](https://user-images.githubusercontent.com/102552831/171774622-fd823960-0aaf-45e7-a1fe-1de71ea12a96.png)

**Comment by EleoXDA** [comment]
As it mentions in text, there WILL be broken features. You can install but you need to know that it will not fully work.

And as I mentioned back in your previous bug report, your ROM is not completely supported since it is not fully compatible with this MOD.

Is it explanatory?

**Comment by EleoXDA** [comment]
No. As I already mentioned in my message in your previous report, this MOD is built on and tested on stock pixel firmware on Google Pixel devices.

You are free to use supported ROMs in the list. If you are not, then you need to be aware that it will not be fully compatible.
