### ISSUE TITLE
Left Shortcut On Lock screen Miss positioned 

### ISSUE THREAD

**Issue by topsy-turvy99** [siavash79/AOSPMods#21]
idk if this is the intended position

**Screenshots**
!
![Screenshot_20220403-035530_AOSP Mods](https://user-images.githubusercontent.com/96917972/161403563-2bf6b512-6bf3-4157-aa3e-30630ffe855d.png)

 - Device: 
 - Redmi Note 4
 - OS: 
 - Lineage OS 19.1  A12.1 (https://github.com/zeelog/OTA/releases)

**Comment by siavash79** [comment]
Hi

This actually is NOT the left shortcut. Lockscreen has 2 spots for 2 shortcuts on the screen, and 2 corner swipe shortcuts on the corner.

This option turns on the "corner swipe shortcut", which is by default google assistant.

In the future we will add more options to use 2 main shortcuts further

**Comment by topsy-turvy99** [comment]
> Hi
> 
> This actually is NOT the left shortcut. Lockscreen has 2 spots for 2 shortcuts on the screen, and 2 corner swipe shortcuts on the corner.
> 
> This option turns on the "corner swipe shortcut", which is by default google assistant.
> 
> In the future we will add more options to use 2 main shortcuts further

okay cool,

just to be clear even when shortcut is disabled, my current is able to call google assistant by swiping on both the edge but doesn't show any shortcurt on any of the side

and enabling the left shortcut in ASOP mods shows this google assistant icon which is not alligned, but the right side camera shortcut is perfectly placed 🙂,

i will keep the left shortcut off meanwhile, i was planning to add the dialer shorcut their 😅

**Comment by siavash79** [comment]
The latest commit will make next version have customization of both shortcuts. but it will be limited to camera and assistant. why? because from lockscreen, we have to make sure not to compromise user security while the device is locked. Camera and assistant already take care about this themselves. But not the phone app as far as I know
