### ISSUE TITLE
Power + volume gesture for vibrate

### ISSUE THREAD

**Issue by syyyr** [siavash79/AOSPMods#217]
Hi, on previous versions of Android, you were able to press power and volume buttons simultaneously to enable vibrate mode. I was wondering if AOSPMods could enable such functionality.

Thanks

**Comment by EleoXDA** [comment]
Currently on pixel,
Vol.up+power button is for power menu (whether you have assistant or not)
Vol.down+power button is for screenshot

**Comment by syyyr** [comment]
> Vol.up+power button is for power menu (whether you have assistant or not)

I can see how that's useful, but I don't use the long press power button assistant shortcut, so I'd still much rather have the vibrate shortcut.

**Comment by EleoXDA** [comment]
> > Vol.up+power button is for power menu (whether you have assistant or not)
> 
> I can see how that's useful, but I don't use the long press power button assistant shortcut, so I'd still much rather have the vibrate shortcut.

I don't think remapping the power button is ever any good idea. Even Xposed Edge warns you against it and blocks any remapping of the power button.

It is easier to press a volume button and adjust the ringer from the icon
😉
![Screenshot_20220605-124500.png](https://user-images.githubusercontent.com/27622683/172046861-6c1efa3d-47d2-4211-8b67-e941f4b85139.png)

**Comment by syyyr** [comment]
> I don't think remapping the power button is ever any good idea. Even Xposed Edge warns you against it and blocks any remapping of the power button.

I was thinking about remapping the power AND volume up button combo, not just pressing the power button. Are you suggesting that remapping the button combo is also a bad idea?

> It is easier to press a volume button and adjust the ringer from the icon

It's not, at least for me. With the button shortcut, I just pressed it and it was done. Now I have to press the volume button (that might even change my volume?), then click the icon and then click another icon.

**Comment by EleoXDA** [comment]
> Are you suggesting that remapping the button combo is also a bad idea?

I would say staying away from remapping the only key that lets you cold restart or boot to recovery is your best deal
☺️

**Comment by syyyr** [comment]
I would still be able to press (and hold) JUST the power button and that would let me open the power menu restart. Maybe I'm misunderstanding something, I don't know.

**Comment by EleoXDA** [comment]
Well, if you find an app that allows the power button or its combo to be remapped for android 12+ please notify us. But as far as I know it is warned against it.

**Comment by syyyr** [comment]
Did something change in Android 12+, that made it more dangerous?

**Comment by EleoXDA** [comment]
> Did something change in Android 12+, that made it more dangerous?

Security check got denser and less manual control over phone... Basically _iphone_ization

**Comment by syyyr** [comment]
I see. Well, I would still like this feature to be implemented if possible.

**Comment by siavash79** [comment]
I agree with @EleoXDA

In presence of gestures android already set for power+vol buttons, it's a very bad idea to make any changes to them.

It goes to the manager app and everyone wants to set their combination to it and they'll simply get confused for some very important actions, being power menu and screenshot
