### ISSUE TITLE
Canary Changelogs

### ISSUE THREAD

**Issue by ohmybahgosh** [siavash79/AOSPMods#219]
Is there any specific source where we can view Changelog for these canary releases? Went from 35-42 fairly quickly, but not seeing a Changelog

**Comment by EleoXDA** [comment]
Generally you can see canary changelogs from commits here. As canary builds are automated by dev's own personal code, there is no requirement for a separate GitHub post with changelog. 

Stable versions get a full list of changelogs but canary versions mainly include one attempt for improvement or a bug fix that is discussed in the telegram group. If you follow the discussions in the telegram group you can get its sense.

**Comment by siavash79** [comment]
I have to agree with both opinions

So far I've been so lazy to make a base for Canary change logs. Hopefully some day I'll work on it
