### ISSUE TITLE
Pulsing/dozing/bar checks are wrong

### ISSUE THREAD

**Issue by josephcsible** [siavash79/AOSPMods#22]
https://github.com/siavash79/AOSPMods/blob/6b7dffb51fd92684175413f41485e96c14066829/app/src/main/java/sh/siava/AOSPMods/systemui/DoubleTapSleepLS.java#L52-L61

This code doesn't work the way it's supposed to. It's always going to check what `mPulsing`, `mDozing`, and `mBarState` were when `createTouchHandler` first returned, not what they are when the touches actually happen.

**Comment by siavash79** [comment]
Hmmm! Seems about fair!

This was one of the first mods I made, and back then I had not much idea about what and why I was doing. I'll look into it soon.

So: you seem to have a good idea about what you're talking about. Why don't you join the party?

**Comment by josephcsible** [comment]
I made a standalone module without that problem and with a few other fixes as well: https://github.com/josephcsible/DoubleTaptoSleep/blob/master/app/src/main/java/io/github/josephcsible/doubletaptosleep/DoubleTaptoSleep.java

Want me to PR that version into here?

**Comment by siavash79** [comment]
I made the changes anyway...... will push to master after test. more or less seems like yours

That was not my point anyway. My point was if you're up to it, join the team and contribute to the project with more mods

**Comment by josephcsible** [comment]
Sure, I'll join. I don't know how active I'll be able to be though.
