### ISSUE TITLE
Notch Killer

### ISSUE THREAD

**Issue by DeadneM** [siavash79/AOSPMods#225]
Hi, with the new status bar height settings it cause conflicts with notch.

The status bar can't go lower than the dimension of the notch

Before when the status bar size was small of medium in AOSP mod it set the notch to 0(or something like this)

Which was good cause in AOSP you could still set the left padding on and off and the center offset.

And so many where using fullscreen where before they couldn't just by choosing small or medium size and enabling the left padding 

Now with the new status bar size setting it break this 

I doubt it was the goal before to kill the notch but in my case I'm always fullscreen and maybe other people just like having their landscape app taking fullscreen

**Comment by EleoXDA** [comment]
Hello.

Your report is missing quite a lot of points; like the device, installed app version, screenshots of setting page and results of choosing those settings. Please update your report so that it is easily comprehensible.

Regards,

**Comment by DeadneM** [comment]
Yeah sorry it's late for me, as it isn't an issue I thought my device info etc wasn't necessary.

I'm on a pixel 4a with June stock android.
But it will touch any phone with a notch

Before the new status bar height settings in AOSP mod you could choose between small and medium size.
When choosing one of those two setting it was killing the notch.
Which was a good thing (App in landscape can take 100% of the screen and you can have an immersive status bar anywhere)

Where we would all agree the new status bar height is a good thing would it be possible to add a notch Killer to AOSP mod ?

I hope it's better explained now. English is not native language

**Comment by EleoXDA** [comment]
İ am still struggling to understand your request. That is why I asked you to share some screenshots that would explain what you are trying to tell us in more details.

From what I remember, pixel 4a has a front camera at side of display. And thus there is a notch at side of your statusbar. When you go landscape, this part of screen is not used for 18:9 views (e.g. Youtube Videos) but it can be used if you extend the screen with gesture to enlarge the video.

What I didnt understand is where does this mod stand in killing the notch? Does it make the view (game, video and etc) go beyond the camera so that part of the view is being blocked by front cam?

I am sorry, as I said it is hard to understand what you mean. Maybe tomorrow morning you can specify your request with some screenshots or photos of your device if necessary

**Comment by DeadneM** [comment]
Lol I'm not sure taking pictures would explain this, it could be worse lol. 
Also I can't take picture of the notch
Imma try keeping it simple



FEATURE REQUEST
My feature request is to add notch Killer option in AOSP mod.

Why?
This will fix the status bar height percentage on notched phone and enable the possibly to use the status bar part of screen for apps



LONG STORY You shouldn't read ^^
You understood well that Pixel 4a have a notch and the screen part where the status bar is when an app is in landscape or in portrait immersive is blacked out if the system UI think there's a notch.( Youtube can if you pinch like you know but many other app just show a black bar even in portrait )


Before AOSP mod v49 you had a choice of two size for the status bar small and medium

Both choice lead to a side effect of killing the notch.


If you still don't understand please just add a notch Killer option 😉

**Comment by EleoXDA** [comment]
I do understand you know. The statusbar height percentage is not final. These versions that are being released are canary versions. There will also be improvements towards that setting. Maybe after it is finalized you could get what you wanted :)

**Comment by EleoXDA** [comment]
Did you check latest canary build?

**Comment by DeadneM** [comment]
Hello, yes I looked at each canary build until the problem was solved in v52 
Then dev revert the fix in v53 
And finally the change made in v52 were rereverted in v54 😁

In short, as it is now as soon as you choose a status bar size lower than 100% in AOSP mod. It kill the notch. 👌

I'm fine with it and it works like it was before.

Just that it only works if you choose a lower status bar. Which is totally fine for me. (I don't use status bar, only the qs panel and notification panel) 

We can mark this issue as resolved

**Comment by DeadneM** [comment]
Canary v59 readd this issue unfortunately

Issue in pictures

 On pictures you can see there's a little space which is not the same as status bar
This space is the same as when you set the status bar size to 50%

And as it doesn't kill the notch when in landscape most application doesn't take all the screen.


I don't know what it is supposed to fix it was working as intended before. 

Are people on telegram complaining about notch overlapping clock in notification panel ? 

If that's the case then you can't have both.


Just an option to kill the notch around the correct left side padding.

And keep the rest as it is 


I don't know why dev is commiting so much on this

**Comment by siavash79** [comment]
Canary 59 kills the notch ONLY as much as it needs. removing it completely makes larger statusbars to lose center balance.

Latest canary ensures that only the required amount will be reduced from the notch.
