### ISSUE TITLE
Allow quick tile have more rows

### ISSUE THREAD

**Issue by lublak** [siavash79/AOSPMods#226]
What's on your mind?

Currently i use the No34D stile.
It works nice! [Screenshot_20220612-101348_GitHub.png](https://user-images.githubusercontent.com/44057030/173223870-5c8309ce-af35-4649-a4ec-bb2e7cdface2.png)
But ir would be nice to have a second row in collapsed mode.
So you have 8 tiles avaible.

Is this feature implemented on any other app/mod/rom? please specify

I think no.

**Comment by EleoXDA** [comment]
Fixed in canary build 58

**Comment by EleoXDA** [comment]
Fixed in latest canary build (58)
