### ISSUE TITLE
Network traffic in icon

### ISSUE THREAD

**Issue by lublak** [siavash79/AOSPMods#227]
What's on your mind?

Before i used linageos 19.1 which is based on aosp i was on oxygen os android 10.
In the network icon there was some arrows to show if network is used (uploud: up arrow, download: down arrow)
Something like this:
![IMG_20220612_102535.jpg](https://user-images.githubusercontent.com/44057030/173224329-e9fb41b7-c35a-49fe-9d61-1fc211475065.jpg)

Is this feature implemented on any other app/mod/rom? please specify

Was it oxygen os or android 10.

**Comment by EleoXDA** [comment]
OOS is not open source and moving stuff from android 10 to 12L is barely possible.

You can use the network meter. Which shows not only whether there is an upload or download but also its speed.

**Comment by lublak** [comment]
That is a pity. Because I think this text-based view with the speed is really not nice. And I only find it interesting (especially with mobile data) whether it simply uses the internet or not.
