### ISSUE TITLE
IOS overscroll override request.  

### ISSUE THREAD

**Issue by Jal3223** [siavash79/AOSPMods#228]
Would it be possible to have this as a feature to override the Android 12 stock overscroll?

Is this feature implemented on any other app/mod/rom? please specify
I have not confirmed that it works, but it has recently been updated:

https://github.com/Valkriaine/bouncy

**Comment by EleoXDA** [comment]
Have you seen any custom ROM using it? Or any android device?

**Comment by Jal3223** [comment]
I haven't seen it implemented anywhere yet. I found it on GitHub, and was just hoping that it would work. The developer has made some recent changes, so it leads me to believe that it has been tested though. Does it look like it would be possible to implement?

**Comment by Jal3223** [comment]
It is made for Android devices however. The developer shows an example of it being implemented on another Android app that he has developed (Factor launcher).

**Comment by EleoXDA** [comment]
Truth to be told I don't see much difference with respect to what we already have (elastic overscroll effect). This effect may be liked by niche users who want to have iphones maybe. And there is even a toggle to turn off the elastic overscroll effect in AOSPMods. So let's wait and see what Siavash will decide.

**Comment by EleoXDA** [comment]
I couldn't find the conversation between you and Siavash about disabling elastic animation, but let me ask you:
- are you on pixel stock firmware?
- did you enable apps you want the animation to be disabled in the LSposed? Did you add the system framework as well?

**Comment by Jal3223** [comment]
I was talking with him through PM. He confirmed that many of the apps did not abide by the request to remove the overscroll. He tried a few things but could never get it to work. I figured this would be easier because he has the layout provided. Maybe it would unlock the secret to why the edits he did would not disable overscroll for system or many apps.

**Comment by siavash79** [comment]
Thanks for the suggestion

As a matter of fact, removing overscroll effect is a bit different than adding another one.

The "general" policy is to focus on functionality and clarity of phone's functions. Looks and themes go to the last priority for implementation.
