### ISSUE TITLE
Module causes lag in music streaming apps

### ISSUE THREAD

**Issue by draumaz** [siavash79/AOSPMods#231]
**Describe the bug**
When any setting is enabled, the module will redraw the app when media is playing or stopping.

**To Reproduce**
1. Install AOSPMods, enable any setting
2. Open a media player app (confirmed affected: **Spotify, Subtracks**)
3. Interact with item; play, pause, scroll around, expand to art view
4. Witness redraws and lag

**Expected behavior**
No repeated redraws

**Workaround**
Disable all settings in AOSPMods

**Screencasts**

https://user-images.githubusercontent.com/77967471/173465832-5162c23c-f944-4702-b192-10bdcebfb104.mp4

https://user-images.githubusercontent.com/77967471/173466355-805f0319-0b5b-4ab7-9b81-6ef9c591c402.mp4

 - Device: Google Pixel 3 (blueline)
 - OS: lineage-19.1-20220607-nightly-blueline-signed (Android 12.1)

**LSPosed Log**
[LSPosed_2022-06-13T16_49_02.255.zip](https://github.com/siavash79/AOSPMods/files/8895184/LSPosed_2022-06-13T16_49_02.255.zip)

**Comment by EleoXDA** [comment]
So when you disable all settings inside AOSPMods you get no issue. So it is some settings that causes your phone lag on custom ROM. Could you detect which setting exactly does it?

First things first, custom ROMs like Lineage OS are not fully supported. From your logs I couldn't find ANR for other than AOSPMods.

Secondly, you might want to switch to canary builds. New canary version is 15 versions newer than your current.

Thirdly, I couldn't yet throughly check your logs, but from what I see there are no unresponsiveness. Could you check with Youtube Music or Poweramp?

Lastly, your events were not able to be reproduced on our devices. There is a possibility that it is coming from custom ROM incompatibility. As you may know, this MOD is built on AOSP source code, which differs from LineageOS.

**Comment by draumaz** [comment]
As far as I could tell, the effect is independent of any specific setting - it happens when any setting is enabled. For instance, I got the lag when I enabled Pitch Black dark mode, or when I hid the navigation bar, etc.

I unfortunately think you might be right that this is a LineageOS issue. 

I'll give the latest Canary build a try and get back to you with the results.

**Comment by EleoXDA** [comment]
Well then definitely it is due to an incompatible custom ROM. I can use this module on my pixel 3aXL (stock firmware) with no issue at all. So it should work perfectly on a pixel 3 device as it is even better in CPU/GPU.

That means the culprit is the custom ROM

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
