### ISSUE TITLE
"No notifications" shows up briefly when turning off the screen

### ISSUE THREAD

**Issue by uvalenzuela** [siavash79/AOSPMods#232]
After installing AOSPmods, the text "No notifications" shows up when turning off the display. Weirdly enough, when turning off the display while the notification shade is down, everything is fine.

**Comment by EleoXDA** [comment]
Please fill up the information requested for bugreport:

- Your device manufacturer and model name
- Android version
- Security update date (if it's a custom ROM, then its name and date of release)
- Screenshots or photos explaining the issue
- Your magisk version
- List of your magisk modules and versions
- Your LSposed version
- List of your LSposed modules and versions
- LSposed logs (extracted from the app)

When taking LSposed logs, be sure to 
- disable all modules other than AOSPMods & LSposed in Magisk Manager
- disable all modules in LSposed other than AOSPMods
- Reboot once
before taking LSposed logs

**Comment by uvalenzuela** [comment]
- Google Pixel 5 ("redfin")
- Stock Android 12L (June security patch)
- fsociety tribute stable kernel #1.57
- Magisk 24.3 (24300)
- Modules: Pixel 5 NR Unlock, Zygisk - LSPosed, AOSP Mods
- LSPosed v. 1.8.3 (6574) Zygisk
- LSPosed Modules: AOSP Mods

[LSPosed_2022-06-14T09_03_59.536.zip](https://github.com/siavash79/AOSPMods/files/8900459/LSPosed_2022-06-14T09_03_59.536.zip)

**Comment by EleoXDA** [comment]
Please aslo show screenshots, screenrecords and/or photos of the bug you want to describe as your description is not self-explanatory.

**Comment by uvalenzuela** [comment]
I just flashed the stock kernel and the bug is still happening, so I don't think it is related to the custom kernel.

I'm afraid that, since the bug happens when turning off the screen, I can't do a screen record, or take a screenshot, nor do I have another device with which take a video. However, I'll try my best to explain the bug again.

Steps to reproduce:
1. Make sure no notifications are active and "Always show time and info" (aka Always On Display) is enabled.
2. Open any app, or swipe up to go home, either way is fine.
3. Press power button to turn the screen off.
4. As the screen is turning off, the message "No notifications" can be briefly seen as part of the Always On Display information, about halfway between the bottom of the screen, and the AOD weather information.
5. The "No notifications" message disappears as soon as the battery percentage (at the bottom of AOD) appears. 

Note: when turning off the screen while on the lockscreen, the bug does not appear. Also, when turning off the screen while the notification shade is down, the bug does not appear. 

All in all, this is really a cosmetic bug, nothing too serious.

**Comment by siavash79** [comment]
Can't reproduce

**Comment by EleoXDA** [comment]
I could reproduce it but not anymore
