### ISSUE TITLE
change link to lsposed in readme t to github

### ISSUE THREAD

**Issue by nutpantz** [siavash79/AOSPMods#233]
Change the link to lsposed to github https://github.com/LSPosed/LSPosed/releases over telegram link used now.
Everybody can access github, not everyone can access telegram

**Comment by EleoXDA** [comment]
Where is the link to LSposed in Github?

There is only text afaik:
![Screenshot_20220616-072523.png](https://user-images.githubusercontent.com/27622683/173997701-aae9f439-a9f6-4f55-bcd4-6bae4f19312b.png)

**Comment by nutpantz** [comment]
https://github.com/LSPosed/LSPosed/releases

That url gives me the releases page

**Comment by EleoXDA** [comment]
Your meesage says we need to change the link to lsposed in our github readme. Where do you think we need to change it?

**Comment by nutpantz** [comment]
https://github.com/siavash79/AOSPMods/releases

To install, you will need to:
Install LSPosed Zygisk (https://t.me/LSPosedArchives)
Install the zip file in Magisk (You will be able to install canary builds once the stable version is installed, through in-app updater)
Reboot

**Comment by siavash79** [comment]
Noted. Thanks
