### ISSUE TITLE
Quick pin unlock 

### ISSUE THREAD

**Issue by TravisShepherd** [siavash79/AOSPMods#243]
No need to press enter after lock screen pin input.

This feature has been implemented in gravity box.

**Comment by EleoXDA** [comment]
Gravitybox is not an android 12 mod

**Comment by TravisShepherd** [comment]
It's an unofficial release, but it's an option for the 12 release and
earlier releases.

**Comment by EleoXDA** [comment]
I don't know about that, but if you have link to the sources of the unofficial android 12 release, share here.

**Comment by siavash79** [comment]
Your timing couldn't be better. Added to the latest canary

**Comment by TravisShepherd** [comment]
https://forum.xda-developers.com/t/unofficial-gravitybox-s-version.4456047/

**Comment by EleoXDA** [comment]
> https://forum.xda-developers.com/t/unofficial-gravitybox-s-version.4456047/

It is already available in latest canary of module
