### ISSUE TITLE
number of qs columns 4 tiles fit the text down and icon up

### ISSUE THREAD

**Issue by elijahmurphy** [siavash79/AOSPMods#244]
Hi dev can request for inserting text in 4 tiles columns to fit without scrolling by putting icons in up and text in down without off or on

![IMG_20220530_192122_287](https://user-images.githubusercontent.com/54771764/174491984-fdccd1a6-ac7c-426e-8d7b-fb181d63fa41.jpg)

like this thank you so much dev

Is this feature implemented on any other app/mod/rom? please specify yes they implemented

**Comment by EleoXDA** [comment]
You didn't answer has it been done in any other custom ROM?

**Comment by siavash79** [comment]
> Hi dev can request for inserting text in 4 tiles columns to fit without scrolling by putting icons in up and text in down without off or on
> 
> ![IMG_20220530_192122_287](https://user-images.githubusercontent.com/54771764/174491984-fdccd1a6-ac7c-426e-8d7b-fb181d63fa41.jpg)
> 
> like this thank you so much dev
> 
> Is this feature implemented on any other app/mod/rom? please specify yes they implemented

I'd suggest using QS Tile themes which are available all over internet. Some of them have done this already
