### ISSUE TITLE
Signal Icon is changed to default after reboot or restart SystemUI

### ISSUE THREAD

**Issue by adrobyshewsky** [siavash79/AOSPMods#246]
How to reproduce:
1. Go to "Theming" - "Icon Style". Set icon style, e.g., "Sam";
2. Set signal icon theme, e.g., "Zig-Zag";
3. Everything is OK;
4. Reboot phone or simply restart SystemUI;
5. Signal icon theme will be "Sam".

Expected behavior:
Signal icons theme should be "Zig-Zag" not "Sam".

Device: POCO X3 Pro (vayu);
Magisk: 25.1 (Stable).

![Screenshot_20220621-131025_Settings](https://user-images.githubusercontent.com/107919205/174775752-6d28813b-8647-4c40-a296-43c87c0d4c60.png)
![Screenshot_20220621-131122_Magisk](https://user-images.githubusercontent.com/107919205/174775772-c1c84da5-6aca-4a02-b94c-d82d92382032.png)

**Comment by siavash79** [comment]
Can't reproduce
