### ISSUE TITLE
Quick Setting Tiles Overlapping and Notification Width Decrease 

### ISSUE THREAD

**Issue by Raul1198** [siavash79/AOSPMods#247]
**Describe the bug**
After changing the  number of columns and  maximum quick qs ,the quick tiles are overlapping when the device is rotated to landscape and a media is playing .  the width of the notification is also decreased

**To Reproduce**
1. Go to Quick Setting Panel 
2. Set Number of QS Columns to 3
3. Set Maximum Tiles in  Quick QS Settings to 6

**Expected behavior**
These settings would applied with above changes only in portrait mode and  in landscape mode the quick qs tiles would be 4 (default) which was in 1.1.2

**Screenshots**
![Screenshot_20220621-152508_AOSP Mods](https://user-images.githubusercontent.com/29801315/174777207-55faa172-6b7b-4031-9eef-4fe6866bbc04.png)
![Screenshot_20220621-153223_AOSP Mods](https://user-images.githubusercontent.com/29801315/174777518-7a1d9801-a5a8-4866-bcb9-d7fd47226887.png)

 - Device: Redmi K20 Pro
 - OS: Voltage OS 1.6 (Android 12L)

**Comment by siavash79** [comment]
Custom roms not supported for bug report

to avoid the issue on custom roms, make sure you set maximum number of QS, BASED ON MAXIMUM 2 ROWS: ie when you have 2 columns, 2x2 = 4. more than that is not supposed to be set (On pixel stock it doesn't matter as it simply ignores higher numbers)

**Comment by EleoXDA** [comment]
> @siavash79 @EleoXDA 

There is no way to program qs toggles to behave differently when there is a media player using xposed. You can only change the number of qs toggles per row. Depending on how many times you use QQS while playing media in landscape, you can adjust the numbers to be either different than default if you have no problems with QQS toggles in landscape while a media is plays, or choose default if you have to have no problems with QQS toggles in landscape while a media is played.

If you ask me, I just pull QQS to open extended QS in landscape mode while the media is played and you have no issue of the sort.

So, as I wrote above, you have to make a decision depending on whether you want to have a custom number of QS toggles or you have to have no issues on QQS & landscape & with media playing...

**Comment by siavash79** [comment]
Looks beautiful to me!

Kidding. I'll take a look

**Comment by siavash79** [comment]
I just don't remember when or how I closed this. Literally the first time I'm seeing it!
