### ISSUE TITLE
[Request] Slide on statusbar to change brightness

### ISSUE THREAD

**Issue by SoumyBhow** [siavash79/AOSPMods#248]
What's on your mind

Would it be possible to add the option to be able to change the brightness by sliding on the statusbar?

Is this feature implemented on any other app/mod/rom? please specify

It can be found in most custom roms like LineageOS, AOSP Extended, CRDroid, etc. I am unable to find any other mod (like Xposed modules) where this can be found.

**Comment by siavash79** [comment]
Thanks for the suggestion.

With ambient brightness adjustment, the need to touch brightness value is much less than before, which can also be set on the very accessible QS/QQS panel.

Therefore this feature is not planned
