### ISSUE TITLE
Firefox crash after intall V1.0.0-beta-01

### ISSUE THREAD

**Issue by DredgenRinz** [siavash79/AOSPMods#25]
**Describe the bug**
After install AOSP Mod V1.0.0-beta-01, Firefox start crashing from startup, remove aosp module or rollback to canary 007 fix the issue

**To Reproduce**
1. Install latest LSposed (1.8.0 (6488))
2. Reboot
3. Install AOSP Mod V1.0.0-beta-01
4. Reboot 2 times

**Expected behavior**
No app crash on start-up/while using device

**Screenshots**
No aplica/not needed

 - Device: Xiaomi Redmi Note 9 (merlinx)
 - OS: PixelExperience 12.1

**LSPosed Log**
[LSPosed_2022-04-04T13_22_34.847.zip](https://github.com/siavash79/AOSPMods/files/8412240/LSPosed_2022-04-04T13_22_34.847.zip)

**Comment by siavash79** [comment]
Please try turning off Google Sans font in themes section and reboot, and see if the problem persists or not

**Comment by DredgenRinz** [comment]
> Please try turning off Google Sans font in themes section and reboot, and see if the problem persists or not

yes, after a clean install, firefox still crash on boot/startup, even with no config applied

**Comment by DredgenRinz** [comment]
tracking a bit the logcat, i think find something, only happends with aospmod installed

04-08 21:56:36.252 20227 20227 I Gecko   : type=1400 audit(0.0:6021): avc: denied { read } for name="libpq_cust.so" dev="dm-1" ino=2042 scontext=u:r:untrusted_app:s0:c168,c256,c512,c768 tcontext=u:object_r:vendor_file:s0 tclass=file permissive=1 app=org.mozilla.firefox
04-08 21:56:36.257  9664 19411 I A       : The GellerConfig is not present, defaulting isUploadEnabled for corpus GDD_APA_BISTO to true.
04-08 21:56:36.252 20227 20227 I Gecko   : type=1400 audit(0.0:6022): avc: denied { open } for path="/vendor/lib64/libpq_cust.so" dev="dm-1" ino=2042 scontext=u:r:untrusted_app:s0:c168,c256,c512,c768 tcontext=u:object_r:vendor_file:s0 tclass=file permissive=1 app=org.mozilla.firefox
04-08 21:56:36.252 20227 20227 I Gecko   : type=1400 audit(0.0:6023): avc: denied { getattr } for path="/vendor/lib64/libpq_cust.so" dev="dm-1" ino=2042 scontext=u:r:untrusted_app:s0:c168,c256,c512,c768 tcontext=u:object_r:vendor_file:s0 tclass=file permissive=1 app=org.mozilla.firefox
04-08 21:56:36.252 20227 20227 I Gecko   : type=1400 audit(0.0:6024): avc: denied { map } for path="/vendor/lib64/libpq_cust.so" dev="dm-1" ino=2042 scontext=u:r:untrusted_app:s0:c168,c256,c512,c768 tcontext=u:object_r:vendor_file:s0 tclass=file permissive=1 app=org.mozilla.firefox

**Comment by DredgenRinz** [comment]
Problem solved partially, by some reason after install AOSPMods while firefox is on zygisk deny list, block access to some files needed.

remove firefox from deny list solve the problem.

Issue closed.

**Comment by DredgenRinz** [comment]
Problem solved partially, by some reason after install AOSPMods while firefox is on zygisk deny list, block access to some files needed.

remove firefox from deny list solve the problem.

Issue closed.
