### ISSUE TITLE
Module to change fonts does not work

### ISSUE THREAD

**Issue by GalaxyNight** [siavash79/AOSPMods#250]
The module to change fonts does not work.

1. Install AOSPMods
2. Install Fonts module (For example: [Mejiro font](https://github.com/AndroPlus-org/magisk-module-mejiro-font) )
3. reboot

Poco x3 Pro
Android 12L
crdroid 8.6
Security patch: june 2022
Magisk:25.1
LSPOSED:1.8.3

**Comment by EleoXDA** [comment]
There is an option in theming section which says "enable using custom fonts". This setting enables custom fonts ONLY of AOSPMods app. If you DISABLE that setting and reboot, you can use custom fonts OF ANOTHER module/app.

Most probably you enabled this option.

Or else, your custom ROM is not compatible.

**Comment by GalaxyNight** [comment]
Once I did a clean install, it fixed it.

**Comment by GalaxyNight** [comment]
I have the same problem with Nusantara rom and changing the font settings and Clean Install did not fix it.

Nusantara rom 4.6

**Comment by siavash79** [comment]
You have to disable custom fonts option in the module, and reboot twice. the mod itself deletes the xml for you...... enabling it, brings it back to life
