### ISSUE TITLE
Java script for status bar date

### ISSUE THREAD

**Issue by Allfixed** [siavash79/AOSPMods#253]
dEEE use to work. It appears JavaScript no longer works since last 2 updates. I reverted to 1.1.2 and it works again. Pixel 6, stock A12. Latest Magisk and LSPosed. No other modules which interact with status bar. Thanks

**Comment by EleoXDA** [comment]
![Screenshot_20220623-234342.png](https://user-images.githubusercontent.com/27622683/175407712-8894d9bb-4415-4d44-82c6-7d42bf100e79.png)

Please read the explanations **thoroughly(!!!)** and execute as written. There is NO dEEE anymore. You need to write $G before EVERY date number/text ($P for persian dates).

I think the explanations are **very loud and clear.**
