### ISSUE TITLE
Unlocking rotations and/or forcing reverse portrait mode

### ISSUE THREAD

**Issue by YKScoding** [siavash79/AOSPMods#268]
What's on your mind?
I would like to turn the forehead on my pixel 4 into a chin, it looks better and helps with accidental palm touches. If possible, can you make the lock screen and the AOD flipped as well?

Is this feature implemented on any other app/mod/rom? please specify
It seems to be implemented in gravitybox but that does not have an android 12 version.
The xposed module 'app settings reborn' can work but with individual apps only

**Comment by EleoXDA** [comment]
You realize that you won't be able to use the phone with its speaker and upside down front camera? You request to get your phone rotated and locked to 180 degrees?

**Comment by YKScoding** [comment]
Thanks for the reply. the speaker and front camera can still be used normally when the phone is flipped, including face unlock. 

I know that the feature requested is not related to the general improvements aimed at by this module, but I had been searching for ways to do this to no avail. Could you maybe point me towards some modules or she'll scripts

**Comment by siavash79** [comment]
Ref. Canary 69
