### ISSUE TITLE
SystemUI Crashes when browsing AOSPMods app

### ISSUE THREAD

**Issue by ItsLynix** [siavash79/AOSPMods#269]
**Describe the bug**
On PHH-Treble based roms, SystemUI crashes upon browsing around different categories in the AOSPMods app.

**To Reproduce**
1. Install on PHH-Treble AOSP Based ROM
2. Launch AOSPMods app
3. Browse to any categories
4. Screen will turn black

**Expected behavior**
SystemUI does not stop unexpectedly.

**Screenshots**
Cannot be properly captured

 - Device: Samsung Galaxy A51
 - OS: Phh-Treble 12.1 v414 (DescendantOS ROM) (Android 12L)

**LSPosed Log**
Provided in first comment for ease

**Comment by ItsLynix** [comment]
[Module Log](https://github.com/siavash79/AOSPMods/files/9041372/LSPosed_2022-07-04T19_36_07.334.zip)

**Comment by EleoXDA** [comment]
Custom ROMs like descendant are not supported. Only stock pixel firmware and near-stock AOSP ROMs like Pixel Experience normal version.

By checking your logs I noticed your ROM is very much incompatible with this MOD. And I also noticed that ROM itself isn't that much stable on your device, as it also has many errors. 

My suggestion: switch to pixel Experience normal or something that is more compatible.

This MOD is built on and tested on only stock pixel firmware, so we cannot guarantee support for vast amounts of custom ROMs that increase in number every day

**Comment by ItsLynix** [comment]
> Custom ROMs like descendant are not supported. Only stock pixel firmware and near-stock AOSP ROMs like Pixel Experience normal version.
> 
> By checking your logs I noticed your ROM is very much incompatible with this MOD. And I also noticed that ROM itself isn't that much stable on your device, as it also has many errors.
> 
> My suggestion: switch to pixel Experience normal or something that is more compatible.
> 
> This MOD is built on and tested on only stock pixel firmware, so we cannot guarantee support for vast amounts of custom ROMs that increase in number every day

I'm not sure whether or not the errors you saw were caused by the rom's own modification of SystemUI interfering with the mod's functionality, or if the rom is actually unstable? I'd appreciate if you could provide which logs in specific you were referring to when it comes to general rom instability.

Anyhow, It's always hard for me to switch ROMs as they don't always tend to behave well on dirty flashing, and if I do a clean flash, I will lose my BankID (Sweden's bank authorization system that EVERYONE uses for digital ID for bank apps and such), which can tell whether or not it has been reinstalled with a backup or similar (however the hell it does that), and I need to travel to an IRL bank to restore that properly. (God I'd be their top customer lmao)

Anyhow, I'll work some stuff out ig and try normal PE.

**Comment by EleoXDA** [comment]
As I said, if you need to have this MOD, then yes. But otherwise if you are ok with customizations that you have already in the ROM, leave it

**Comment by ItsLynix** [comment]
Alrighty

**Comment by rufus582** [comment]
Descendant os is least compatible with AOSP mods😂. I think they use a wierd overlay system that's not stock. So basically each and every interaction u make with AOSP mods will end up in a system ui crash. But other roms like pe+ and all work perfectly fine with AOSP mods.

**Comment by EleoXDA** [comment]
Possibly. I have not used custom ROMs since Evo X. And that was in 2018. Since then I am using only stock pixel firmware and never looked back. PE+ is also not fully compatible. PE normal edition is more compatible, but yet it is not as compatible as pixel stock firmware. So, this goes as it says in the description of the MOD for compatibility. Since LOS itself is not using clean AOSP code, it is also not fully compatible.

**Comment by rufus582** [comment]
Atleast the app experience is smooth on pe. Not as spikey as in descendant os😏
