### ISSUE TITLE
Feature Request: More options for volume steps

### ISSUE THREAD

**Issue by PalmDevs** [siavash79/AOSPMods#270]
## What's on your mind?
I'm thinking AOSPMods should have more options for volume steps. Currently we only have one for media volume. What if we have those ones for these: 
 - Alarm
 - System
 - In-call
 - And lastly, if possible: Ring & Notification

## Is this feature implemented on any other app/mod/ROM? please specify
Some ROMs do have this implemented, but I can't find much mods or apps that actually does its job.

**Comment by siavash79** [comment]
Please refer to: https://forum.xda-developers.com/t/mod-xposed-magisk-aosp-mods-system-modifications-for-aosp-based-android-12.4421743/post-87071859

**Comment by PalmDevs** [comment]
Ah, that's quite sad but it's understandable.

Closed as wontfix
