### ISSUE TITLE
About building and deployment

### ISSUE THREAD

**Issue by gibcheesepuffs** [siavash79/AOSPMods#271]
Hi, I would like to understand how the app is built and deployed as there are no docs explaining that part. I would like to extend functionality myself. So, I cloned the project with git (submodules as well recursively), compiled it and built an apk and later deployed the apk on my device already running AOSPMods. I had to use luckypatcher to disable package manager complaining for different signature. Another question I have is about APKs in the overlay folder inside the zip releases. I would to know if they are prebuilt APKs or are being built using some procedure. Thanks!

**Comment by siavash79** [comment]
Hi

It's very nice that you're interested in building.

Now that you've successfully built the APK, you've got to do few easy things:

- locate the folder Magisk Mod
- put the apk in system/priv-app/AOSPMods/yourAPK.apk
- zip the CONTENTS of Magisk mod, and flash it with magisk

alternatively, you can zip the folder without the apk, install it in magisk and install the apk separately

About signature mismatch: uninstall the magisk module and you'll be fine

**Comment by siavash79** [comment]
The overlay apks are mostly pre-built (except for light QS themes which we did them ourselves). But you can also build your own if you like: decompile one of them, change android manifest package name, change the resources in res folder, compile again, and you're done
