### ISSUE TITLE
Add in-app language selection

### ISSUE THREAD

**Issue by bzz11g** [siavash79/AOSPMods#272]
_What's on your mind?_

Hi Siavash and Elbay Malik!
Please add the ability to select the language of the application in the settings
The application has already been translated into many languages, but for me (and I think for many) it will be much easier and more convenient to use English in the application, without translating the entire OS into English.
The English language is in many ways more concise than the national ones, and also already contains all the definitions that are used in the OS and leaves no place for misunderstanding of the meaning of the described function/option.

Thank you!

**Comment by EleoXDA** [comment]
If you notice any misspell or wrong translation in the text of your language, you can just easily add your changes with pull request. Upon examinations they can be added to translation text.

**Comment by siavash79** [comment]
Added to latest canary
