### ISSUE TITLE
When activated "Ignore the camera cutout" after turning the screen to landscape, the text in the status bar is shifted to the top

### ISSUE THREAD

**Issue by bzz11g** [siavash79/AOSPMods#273]
**Describe the bug**
When you activate "Ignore the camera cutout" after rotating the phone to landscape position, the text in the status bar is shifted to the top

**To Reproduce**
1. Go to 'AOSP Mods > Miscellaneous'
2. Activate 'Ignore the camera cutout'
3. Rotate your phone 90 degrees (landscape)
4. Rotate back to portrait mode
5. See that the text alignment to the top of the statusbar

**Expected behavior**
The text should be aligned to the middle of the statusbar, as it was before the screen was rotated.

**Screenshots**
![bug](https://user-images.githubusercontent.com/1549909/177742596-7db0d2da-4c6f-4953-a2b5-c1db45c1994b.png)

 - Device: Pixel 6
 - OS: Stock 12.1.0 (SQ3A.220705.003, Jul 2022)
 - AOSPmods: canary-70

**LSPosed Log**
[LSPosed_2022-07-07T12_20_43.518.zip](https://github.com/siavash79/AOSPMods/files/9062268/LSPosed_2022-07-07T12_20_43.518.zip)
**My AOSPmods settings file**
[07-07-2022.txt](https://github.com/siavash79/AOSPMods/files/9062276/07-07-2022.txt)

**Comment by EleoXDA** [comment]
This should work until UI reboot. If it works, please report so that we can think of ways to make sure that statusbar height is not being misread when ignoring camera cutout rotation

**Comment by bzz11g** [comment]
Yes it works, but after reboot and unlock device alignment go to top and I need repeat all steps with changing statusbar size and rotating screen
