### ISSUE TITLE
White brightness icon in QQS

### ISSUE THREAD

**Issue by bzz11g** [siavash79/AOSPMods#275]
_Originally posted by @bzz11g in https://github.com/siavash79/AOSPMods/issues/192#issuecomment-1177341766_
This bug is comeback 
White Icon on Light theme
White Icon on Dark theme
AOSPMods: Canary-70
Device: Pixel 6
OS: Stock 12.1.0 (SQ3A.220705.003, Jul 2022)
![Screenshot_20220707-125553](https://user-images.githubusercontent.com/1549909/177747079-bfcc9edb-1032-4219-90d5-c19e6c5c9521.png)![Screenshot_20220707-125559](https://user-images.githubusercontent.com/1549909/177747085-cff13dab-e7f0-4539-a5b1-f5410bd430b9.png)

**Comment by EleoXDA** [comment]
https://github.com/siavash79/AOSPMods/issues/192#issuecomment-1177885480

**Comment by EleoXDA** [comment]
Cannot replicate. Please provide all the required data for bugreport

**Comment by EleoXDA** [comment]
I advise switching on the light qs on light theme option. The default one is buggy on AOSPMods. I dont know whether there will be any more fix on this.

**Comment by bzz11g** [comment]
ok, i understand

**Comment by EleoXDA** [comment]
I changed to "not planned" so that it is not fixed but also currently there is no intention of fixing it
