### ISSUE TITLE
No background under brightness slider in QQS

### ISSUE THREAD

**Issue by bzz11g** [siavash79/AOSPMods#276]
**Describe the bug**
No BG under brightness slider in QQS, regardless of whether a thick or thin indicator is selected

**To Reproduce**
1. Go to 'Quick Settings Panel'
2. Activate 'Show brightness slider on QQS Panel'
3. Open QQS
4. See the bug

**Expected behavior**
The background should be under the brightness slider

**Screenshots**
![Без имени-1](https://user-images.githubusercontent.com/1549909/177756713-01b182ae-7a2e-4083-86da-8c42ef464981.png)

 - Device: Pixel 6
 - OS: Stock 12.1.0 (SQ3A.220705.003, Jul 2022)
 - AOSPmods: canary-70

**LSPosed Log**
[LSPosed_2022-07-07T13_51_20.361.zip](https://github.com/siavash79/AOSPMods/files/9062852/LSPosed_2022-07-07T13_51_20.361.zip)

**Comment by EleoXDA** [comment]
Overlay of brightness bar on QQS acts like that. Unfortunately no other way to add it using overlays.

**Comment by EleoXDA** [comment]
Difference is that overlay doesn't get applied on dark theme background. And overlays are not easy to work with.

**Comment by bzz11g** [comment]
Sorry, I don't understand in application development and modifications (if I could, I'm try to help fix bugs, but I don't know how), but it seems to me that if the problem is in the system theme, and the problem does not occur when using a custom overlay, then why not apply  custom overlay (which looks exactly like the system overlay) on top of the system overlay in dark mode, wouldn't that solve this problem?

**Comment by EleoXDA** [comment]
Sorry. I mistook the issues.

Let me answer this one
