### ISSUE TITLE
Space between time and AM/PM indicator in the status bar

### ISSUE THREAD

**Issue by pranaya2005** [siavash79/AOSPMods#278]
Hi, can we have a space between the time and the AM/PM indicator (enabled using AOSPMods) please? Thanks in advance!
![Screenshot_20220710-221414~3](https://user-images.githubusercontent.com/61061454/178154049-5b952da3-abe0-4c94-962a-f370a8a29ec0.png)

**Comment by siavash79** [comment]
You can disable am/pm and add a custom text after clock like this: "  $Ga"

**Comment by pranaya2005** [comment]
> You can disable am/pm and add a custom text after clock like this: " $Ga"

Works great, thanks!
