### ISSUE TITLE
Disableable Settings

### ISSUE THREAD

**Issue by Eclipswf** [siavash79/AOSPMods#279]
I'm using project elixir 12L
It didn't have back gesture setting height so I used this module to get it but brightness bar options of this module conflicts with rom's in-built settings.
So can you make these disableable?

**Comment by siavash79** [comment]
If you don't enable brightness slider settings they don't do anything in that regard.
Most of the options are designed the same way

If you still think there's a conflict please share more details and screenshots

**Comment by Eclipswf** [comment]
But they did, after uninstalling this module those bugs disappeared

11 Tem 2022 Pzt 02:51 tarihinde Siavash ***@***.***> şunu
yazdı:

**Comment by EleoXDA** [comment]
Then you can discuss the compatibility of this MOD with your ROM dev or ask the ROM dev to include the back gesture height from this MOD to ROM.

But as Siavash wrote above, if you don't enable any settings it will not touch anything in your ROM.

**Comment by siavash79** [comment]
I'll review the code to  see if there's any change needed

**Comment by siavash79** [comment]
Try canary 76
