### ISSUE TITLE
Battery Bar slow to update

### ISSUE THREAD

**Issue by digger16309** [siavash79/AOSPMods#281]
**Describe the bug**
When disconnecting charger, Battery Bar stays as charging color, not normal non-charging color(s) and bar length doesn't update to reflect correct battery level. Happens intermittently but often. Fixed by toggling battery Bar switch in app, or darkening and locking screen and opening. 

**To Reproduce**
1) Set battery Bar to single color, separate charging color
2) Charge device
3) Remove Charger 

**Expected behavior**
Battery Bar returns to non-charging color and reflects new battery level

 - Device: pixel 5
 - OS: A12.1; July Update, also June Update

**Comment by siavash79** [comment]
Can't reproduce. Are you on stock pixel rom?

**Comment by digger16309** [comment]
[LSPosed_2022-07-12T12_33_05.596.zip](https://github.com/siavash79/AOSPMods/files/9095146/LSPosed_2022-07-12T12_33_05.596.zip)

Yes, stock Pixel ROM, stock kernel.  I attached my LSposed log and it's the only module I'm running in LSposed. The sisue occurred right before I pulled the log. As I said, the issue is intermittent, and I think potentially related to the device charging in deep sleep mode, but unsure what the exact triggers are.

**Comment by EleoXDA** [comment]
> [LSPosed_2022-07-12T12_33_05.596.zip](https://github.com/siavash79/AOSPMods/files/9095146/LSPosed_2022-07-12T12_33_05.596.zip)
> 
> Yes, stock Pixel ROM, stock kernel. I attached my LSposed log and it's the only module I'm running in LSposed. The sisue occurred right before I pulled the log. As I said, the issue is intermittent, and I think potentially related to the device charging in deep sleep mode, but unsure what the exact triggers are.

Please also share a screenrecord to show us. Is it same as my screenrecord above?

**Comment by digger16309** [comment]
Can't reproduce with evidence to Dev's requirements.
