### ISSUE TITLE
request: use a *thin* track on the brightness slider

### ISSUE THREAD

**Issue by Efreak** [siavash79/AOSPMods#283]
What's on your mind?
By default, my rom (crdroid 8.6/A12) has a super-heavy brightness slider (same height as the qs toggles themselves, which I'd also like to reduce the size of), and I'd like to reduce it down to normal thickness. The room itself actually has a setting to control brightness by swiping the status bar, so I don't actually need to even be able to control it from here, I just want it as a visual indicator.

Is this feature implemented on any other app/mod/rom? please specify
This is default functionality, I'm guessing? Just based on the slider description there, though--I don't have another A12 rom for my phone (moto G6) to test.

**Comment by EleoXDA** [comment]
The default of android 12+ is already thin track on brightness slider. So, making such a MOD will be useless on stock pixel firmware and PE. You should request this from your ROM dev and/or maintainer, as crdroid itself is a highly customizable ROM, and the overlay MODs of AOSPMods most probably will already not work on crdroid as per numerous reports from our users.

**Comment by siavash79** [comment]
Currently, we're focusing on modifications based on "original, android open source" source code. Your request is about reverting back a modification made by your rom to AOSP, which unfortunately doesn't fall under our current scope
