### ISSUE TITLE
Override custom rom's quick settings background colour and replace it with material you theming.

### ISSUE THREAD

**Issue by linusrg1** [siavash79/AOSPMods#288]
What's on your mind?
Most custom roms respect material you theming throughout the os, however the evox team decided to go for a black background in the quick settings instead. It would be great if there was a way to revert this change and give it a material you themed background instead like all other ROMs use.

Is this feature implemented on any other app/mod/rom? please specify
Technically?

**Comment by siavash79** [comment]
As mentioned before, customized modifications of custom roms is not in AOSPMods scope. 
Like the name suggests, this mod directly targets android the way Google has originally designed. And doesn't cover other developers' modifications on it
