### ISSUE TITLE
Ability to make any app a lock screen shortcut.

### ISSUE THREAD

**Issue by linusrg1** [siavash79/AOSPMods#289]
What's on your mind?
Right now you can only make a select few items lock screen shortcuts, it would be great if you could make any two apps you wanted lockscreen shortcuts.

Is this feature implemented on any other app/mod/rom? please specify
Yes this feature is available in other ROMs like derpfest.

**Comment by siavash79** [comment]
Making app or activity shortcut is easy. The reason why this feature doesn't exist on Android or our mod is easy: assuming the screen is locked (which is most of the time) the shortcut will have an unlock prerequisite, which makes it pointless (if you have to unlock your phone for your app to run, why don't you use your launcher to run it then?)
