### ISSUE TITLE
Lockscreen custom text replacing carrier text

### ISSUE THREAD

**Issue by rafagale** [siavash79/AOSPMods#3]
**Describe the bug**

Custom text replacing carrier text doesn't work

**To Reproduce**
Activate it and reboot the device

**Expected behavior**
Custom text should appear on the top left corner on the lockscreen

**Screenshots**

 - Device: pixel 6 pro
 - OS: android 12L beta 3

**Comment by rafagale** [comment]
Screenshots are missing. Please let me know if you have any telegram group for testing as i would be interested my tg is @rafareborn

**Comment by siavash79** [comment]
Hi
Please try canary 005 and let me know if you're problem is solved.

I'm also running 12L beta 3 and it's working for me on 005

**Comment by rafagale** [comment]
Hey, unfortunately it seems like it still does not work somehow. I also restarted SystemUI and the phone itself without success

I will provide more details:

Google Pixel 6 Pro Build S2B3.220205.007.A1
Magisk 24.3 (24300)
LSPosed version 1.7.2 (6476)

![20220321_101710](https://user-images.githubusercontent.com/32096750/159233444-03646fbb-54df-408c-9d6f-b0fffe25a41f.gif)

I dont see any exception on module or verbose logs

**Comment by rafagale** [comment]
Fixed in March build
