### ISSUE TITLE
Data and Wifi toggle are getting removed

### ISSUE THREAD

**Issue by bhaskar966** [siavash79/AOSPMods#30]
It's often happening , with a systemui restart or a reboot it hiding my device's data and Wifi toggles and I have to drag and drop everytime. Even I didn't enabled 'Internet Tile" in AOSP MODS . 

Device : Redmi Note 10 Pro (sweetin)
ROM : Nameless AOSP
Android Ver : 12.1/12L

Other than that this mod is working like a charm for me! Specially the Nav bar accent color feature is awesome. 
Thanks for making such tool .

**Comment by siavash79** [comment]
So to understand correctly: do you mean your rom already has wifi and data tiles, and you don't need internet tile option. As that the case?

**Comment by siavash79** [comment]
@ElTifo 
I think we have to change the QS prefs to a list pref, having a "none" option and 2 other options. None option to make zero actions.
OR we can disable startup action of internet tile method and limit it to user pref change act

What do you think?

**Comment by bhaskar966** [comment]
Yes , This ROM already have seperated data and Wifi tiles. And not only this almost all roms for my device(may be other devices also) have separated data and Wifi tile .
Hope you will get it now .
If have any questions you can ask

**Comment by bhaskar966** [comment]
![Screenshot_20220406-123113_Chrome](https://user-images.githubusercontent.com/86063625/161914892-7467c4a9-169f-4e9f-af09-8530020f526e.png)
![Screenshot_20220406-123126_Chrome](https://user-images.githubusercontent.com/86063625/161914904-09535778-3268-4265-a748-ad020b747faa.png)

**Comment by bhaskar966** [comment]
Like this 


![Screenshot_20220406-123213_Chrome](https://user-images.githubusercontent.com/86063625/161914979-36adc763-3b45-4550-b759-541c965a93e2.png)

**Comment by bhaskar966** [comment]
Found another thing !
Afternoon installing this module , System UI also asks for SuperUser permission. As i knew system UI is a system app , this should not ask for SuperUser right...

Anyways , if I don't grant the super user permission to system UI then the accent color reverting back to built-in color. 
Don't know about other things , i didn't tried.

**Comment by incmak** [comment]
> 

Yes i confirm this

**Comment by bhaskar966** [comment]
Thanks sir .
This is an amazing work what you are doing!
Love this mod
