### ISSUE TITLE
Add an option to disable lockscreen tint

### ISSUE THREAD

**Issue by Jnss98b** [siavash79/AOSPMods#312]
**What's on your mind?**
Stock Android has had a lock screen tint/scrim for a while and it appears even when a bright wallpaper is applied which changes the text color to dark. It would be nice to have an option to disable it to fully show your wallpaper on the lock screen as it is originally

**Is this feature implemented on any other app/mod/rom? please specify**
Not that I know of because I haven't really used custom ROMs in so long but I assume this would be a basic feature in many heavily customizable ROMs but I did see a guide [here](https://forum.xda-developers.com/t/guide-how-to-remove-the-lockscreen-wallpaper-and-notification-pulldown-dimming-tint.3819931/) and these possibly outdated modules [here](https://forum.xda-developers.com/t/lockscreen-wallpaper-tint-remover.3818980/) and [here](https://forum.xda-developers.com/t/xposed-lp-mm-cm12-13-bright-lockscreen-no-more-dark-overlay.3198020/)

**Comment by siavash79** [comment]
As carefully I looked at the screenshots, I couldn't see any difference between them. What's the exact case?

**Comment by EleoXDA** [comment]
No issue found
