### ISSUE TITLE
No Lightning icon inside Circle Battery while charging 

### ISSUE THREAD

**Issue by BrotherBoard** [siavash79/AOSPMods#314]
**Device:** Samsung Galaxy A10 (A105F)
**ROM:** CherishOS
**Android Version:** Android 12.1L
**Arch:** ARM64

**Magisk Verison:** 25.1 (25100)
**Zygisk:** Yes
**LsPosed:** Yes

**Module Version:** 1.3.2
**Module Status:** Enabled in LsPosed

**Bug Report:** Setting Circle battery type and trying to charge will result in hiding the "Lightning" icon inside the battery.

**Comment by siavash79** [comment]
Thanks for your report

As mentioned in the bug report notes, we currently only accept bugs reported from stock pixel and pixel experience roms.

Reports from other roms will not be considered unless similar reports from supported roms are received

**Comment by mingaldrichgan** [comment]
I have personally noticed this on stock Pixel (4 XL) ROM as well, though
not consistently.

**Comment by bdr99** [comment]
In case anyone comes across this issue, I'm having the same problem and have opened https://github.com/siavash79/AOSPMods/issues/448 for it.

**Comment by EleoXDA** [comment]
> In case anyone comes across this issue, I'm having the same problem and have opened https://github.com/siavash79/AOSPMods/issues/448 for it.

Issue fixed in latest canary
