### ISSUE TITLE
Add an option to disable lockscreen tint (sorry for dupe, I couldn't reopen the issue)

### ISSUE THREAD

**Issue by Jnss98b** [siavash79/AOSPMods#316]
**I'm sorry I had to create a duplicate issue to #312 because I couldn't reopen it. I also did not get email notifications for them so I completely forgot to follow up. Please give me a chance to expand my reasonings**

What's on your mind?
Stock Android has had a lock screen tint/scrim for a while and it appears even when a bright wallpaper is applied which changes the text color to dark. It would be nice to have an option to disable it to fully show your wallpaper on the lock screen as it is originally

Is this feature implemented on any other app/mod/rom? please specify
Not that I know of because I haven't really used custom ROMs in so long but I assume this would be a basic feature in many heavily customizable ROMs but I did see a guide [here](https://forum.xda-developers.com/t/guide-how-to-remove-the-lockscreen-wallpaper-and-notification-pulldown-dimming-tint.3819931/) and these possibly outdated modules [here](https://forum.xda-developers.com/t/lockscreen-wallpaper-tint-remover.3818980/) and [here](https://forum.xda-developers.com/t/xposed-lp-mm-cm12-13-bright-lockscreen-no-more-dark-overlay.3198020/)

The difference is more noticeable if you set the lock screen and home screen with the same wallpaper. You can clearly see the difference between these two screenshots below, the lock screen wallpaper is tinted with a scrim. Before people jump in and argue "but that's for better visibility". No, that's what the dark texts are for. I also used a darker wallpaper under the light one to demonstrate that the scrim is permanent and isn't just for lighter wallpapers. Note that I used the exact same wallpaper for each screenshot pair

**Light wallpaper that triggers dark texts**
![image](https://user-images.githubusercontent.com/24306400/184754074-75741514-a3ab-4925-b5f7-7c4797348783.png)
![image](https://user-images.githubusercontent.com/24306400/184754123-69c1f43a-7128-4f6d-9494-f1d4725b2b0c.png)

**Darker wallpaper with white texts**
![image](https://user-images.githubusercontent.com/24306400/184755504-b934ede5-dd58-49aa-ba34-54871e453b08.png)
![image](https://user-images.githubusercontent.com/24306400/184755517-52a85d97-6d81-4d80-82fb-a8eb714a9bdc.png)

**Comment by EleoXDA** [comment]
Not an issue in stock firmware
