### ISSUE TITLE
Network Monitor position: Right(before status icons)

### ISSUE THREAD

**Issue by lonsagisawa** [siavash79/AOSPMods#317]
## What's on your mind?
I'm trying AOSPMods canary(Xposed only version) on Pixel 6 stock Android 13 now, some feature works and some doesn't(don't blame me here, I know this is not compatible for A13 yet.)  
However, when I enabled network monitor and set position to Mid-Right, positioning is bit different from Android 12L and tbh I like it more. It was just right of display cutout in before, now left of statusbar icons.

![Screenshot_20220816-193745](https://user-images.githubusercontent.com/5173607/184862694-f3f8e5a0-9548-4005-9c1a-735d1c426dcb.png)

I don't know this gonna be "fixed", but if you consider fix this could you leave this position as an option?

## Is this feature implemented on any other app/mod/rom? please specify
A lot of Android 12L based custom ROMs places network monitor here.

**Comment by EleoXDA** [comment]
Nice find. I also like it there. But there are still works to be done in statusbar. Let's see whether it holds up
