### ISSUE TITLE
[Feature requst] Option to remove lock screen scrim/wallpaper dimming

### ISSUE THREAD

**Issue by Jnss98b** [siavash79/AOSPMods#318]
I'm sorry I had to create a duplicate issue to https://github.com/siavash79/AOSPMods/issues/312 because I couldn't reopen it. I also did not get email notifications for them so I completely forgot to follow up. Please give me a chance to expand my reasonings. **THIS IS DEFINITELY A STOCK ISSUE SINCE I'M ON A PIXEL 5 RUNNING STOCK GOOGLE ROM. Can you please stop locking follow ups and discuss this issue like grown ups.**

Even google knows this is a thing. Look at their android 12 presentation slide
![image](https://user-images.githubusercontent.com/24306400/184909630-aaf37eab-1115-42be-ab5c-6d72d1c6b1a0.png)

What's on your mind?
Stock Android has had a lock screen tint/scrim for a while and it appears even when a bright wallpaper is applied which changes the text color to dark. It would be nice to have an option to disable it to fully show your wallpaper on the lock screen as it is originally

Is this feature implemented on any other app/mod/rom? please specify
Not that I know of because I haven't really used custom ROMs in so long but I assume this would be a basic feature in many heavily customizable ROMs but I did see a guide [here](https://forum.xda-developers.com/t/guide-how-to-remove-the-lockscreen-wallpaper-and-notification-pulldown-dimming-tint.3819931/) and these possibly outdated modules [here](https://forum.xda-developers.com/t/lockscreen-wallpaper-tint-remover.3818980/) and [here](https://forum.xda-developers.com/t/xposed-lp-mm-cm12-13-bright-lockscreen-no-more-dark-overlay.3198020/)

The difference is more noticeable if you set the lock screen and home screen with the same wallpaper. You can clearly see the difference between these two screenshots below, the lock screen wallpaper is tinted with a scrim. Before people jump in and argue "but that's for better visibility". No, that's what the dark texts are for. I also used a darker wallpaper under the light one to demonstrate that the scrim is permanent and isn't just for lighter wallpapers. Note that I used the exact same wallpaper for each screenshot pair

Light wallpaper that triggers dark texts
![image](https://user-images.githubusercontent.com/24306400/184909156-03872136-3656-4e22-866e-7fd69326f074.png)
![image](https://user-images.githubusercontent.com/24306400/184909185-39273b0f-c91b-46e7-b512-ae8f893d9571.png)

Darker wallpaper with white texts
![image](https://user-images.githubusercontent.com/24306400/184909226-cb959013-0515-48a0-98f3-a28135fe1a1b.png)
![image](https://user-images.githubusercontent.com/24306400/184909250-7ddfff72-31d0-4c4b-a8aa-99953ad32d14.png)

**Comment by Jnss98b** [comment]
@siavash79 Please let me explain and discuss this instead of closing my issue and locking follow-up every single time.

**Comment by Jnss98b** [comment]
Yes pretty much so. I honestly wouldn't mind a toggle either. I don't think people would want to darken the scrim anyway

**Comment by Jnss98b** [comment]
To reiterate, this is definitely a stock thing. I'm using a pixel 5 running the default ROM google provided. It doesn't get more stock than that other than running straight up aosp

**Comment by EleoXDA** [comment]
Personally it doesn't bother me. But we can think of it after we get the functions that are used by many users from android 12 to 13.

**Comment by Jnss98b** [comment]
I'm not too pressed about it either. A lot of AOSP mods features are more "nice to have" anyway so if there is a way to mod it, it'd definitely be a nice addition

**Comment by Jnss98b** [comment]
Thank you so much for implementing it!
