### ISSUE TITLE
Brightness slider options - not working on latest canary (107)- P6 Pro

### ISSUE THREAD

**Issue by nangelovv** [siavash79/AOSPMods#319]
**Describe the bug:**
None of the options in Quick Settings Panel -> Brightness slider options work in A13 stable, instead when any of them is toggled, restarts the system ui, but does not change anything in the quick settings

**To Reproduce / Steps to reproduce the behavior:**
Update to stable Android 13
Open AOSP Mods
Open Quick Settings Panel -> Brightness slider options 
Enable any of the brightness slider options
SystemUI restarts itself, but nothing is changed

**Expected behavior:**
The SystemUI should not restart itself automatically (maybe it’s crashing) and the brightness slider should either be hidden/showing in QQS panel/be moved to the bottom of QS

**Device: Pixel 6 Pro**
**OS: Android 13 stable, August security patch**

**Comment by EleoXDA** [comment]
Please wait patiently. A13 was announced less than week ago. We are doing updates nearly every day.
