### ISSUE TITLE
Missing feature of separation Wifi/Mobile Data QS toggle

### ISSUE THREAD

**Issue by zyh941** [siavash79/AOSPMods#322]
**Describe the bug**
Hello, I used to use this module for a few months and it worked well before my system updated to Android 13 stable version. After I update my system, the tile settings is no longer appear.

**To Reproduce**
1. Scroll down the QS panel, there is only a 'internet' tile.
2. Go to AOSP mods settings\Quick Settings Panel\ , there is no separation toggle at all.

**Expected behavior**
Separate Wifi/Mobile data QS toggle appears.

**Screenshots**
two pics.
![Screenshot_20220823-225820](https://user-images.githubusercontent.com/95530307/186193195-a8bb9603-acc2-494a-90e0-a367dda85458.png)
![Screenshot_20220823-225844](https://user-images.githubusercontent.com/95530307/186193353-300f75fc-d329-45a2-b969-7ba9474ea708.png)

 - Device: Google Pixel 5
 - OS: stable stock Android 13 (TP1A.220624.014)

**LSPosed Log**
[LSPosed_2022-08-23T23_02_14.220641.zip](https://github.com/siavash79/AOSPMods/files/9403739/LSPosed_2022-08-23T23_02_14.220641.zip)

**Comment by siavash79** [comment]
On Android 13 source code Google has put special attention to remove any hint of separated tiles in the tile drawer.

Reverting that effort is just too much work, while there are 3rd party apps to bring them back to you easily.

So: no more separate tiles on 13
