### ISSUE TITLE
[Feature request]3 button nav swap option

### ISSUE THREAD

**Issue by H3ll-Fir3** [siavash79/AOSPMods#323]
What's on your mind?
please add 3 button nav swap..
its back-home-recent now..
i want to do it like this,recent-home-back..

Is this feature implemented on any other app/mod/rom? please specify
this is available in majority of custom rom,
but absent my favourite rom that I'm using...

**Comment by digger16309** [comment]
Would like this as well if possible. There was a separate mod for it but a little risky using it with AOSP Mods at the same time and also not compatible with A13

**Comment by H3ll-Fir3** [comment]
> Would like this as well if possible. There was a separate mod for it but a little risky using it with AOSP Mods at the same time and also not compatible with A13

what was the separate mod??
does it work with a12L??

**Comment by digger16309** [comment]
It's called NavBar Swap. It is only for Pixel devices, and I think the Dev pushed it out ONLY for specific Pixel devices.  The Dev last pushed out an update for the July build of A12.1 on Pixel 5, but I can't vouch for any other device. 
https://forum.xda-developers.com/t/clock-mods-remove-navbar-or-battery-etc-mods.4177829/

**Comment by siavash79** [comment]
Unfortunately 3 button navigation mods are not planned to be done

**Comment by H3ll-Fir3** [comment]
> Unfortunately 3 button navigation mods are not planned to be done

sir,is it too complex to be done,
or you are working with other feature so its on hold??

**Comment by siavash79** [comment]
Actually, none! I don't believe 3-button navbar worth the time/effort spent for modification. It's old, extinct and has a very low userbase among rooters
