### ISSUE TITLE
Disappearing Wifi, Data, & Battery indicator 

### ISSUE THREAD

**Issue by Zilla0617** [siavash79/AOSPMods#332]
*Please note: At the time being, only bug reports from Pixel Stock firmware, or Pixel Experience (normal edition) will be considered. Bug reports from other firmwares will only be taken into account if also reported from one of the supported roms.*

**Describe the bug**
Description of bug that can be replicated: wifi, data, and battery indicator goes missing once screen timeout. Reappears once the notification screen is brought down.

**To Reproduce**
1. Wait for screen to timeout or manually turn off screen
2. Enter back to home screen
3. See error of missing indicators

**Expected behavior**
Aforementioned indicators should be present at all times 

**Screenshots**

 - Device: Pixel 6 Pro
 - OS: A13 August update 

**LSPosed Log**
N/A, bug reproducible

**Comment by siavash79** [comment]
Couldn't reproduce

Can you please tell me if your multi row system icons is enabled or not

**Comment by Zilla0617** [comment]
No I did not have multi row system icons enabled. I had the network monitoring enabled (mid right) and the wifi and mobile data indicators were themed with Kai. The battery indicator was themed as well, dashed circle multicolored with the battery percentage in the center. The status bar was shrunk to about 85%.

**Comment by Zilla0617** [comment]
I have a GIF depicting the issue, its about 11.35MB. Its too big to attach here, do have you somewhere I can send it to?

**Comment by siavash79** [comment]
Instead, please export your settings to file and attach it here

**Comment by Zilla0617** [comment]
ASOP Mod Settings attached

Aug 27, 2022 12:44:34 AM Siavash ***@***.***>:

**Comment by siavash79** [comment]
I guess you've got to attach it through the website

**Comment by EleoXDA** [comment]
> *Please note: At the time being, only bug reports from Pixel Stock firmware, or Pixel Experience (normal edition) will be considered. Bug reports from other firmwares will only be taken into account if also reported from one of the supported roms.*
> 
> **Describe the bug**
> Description of bug that can be replicated: wifi, data, and battery indicator goes missing once screen timeout. Reappears once the notification screen is brought down.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Wait for screen to timeout or manually turn off screen
> 2. Enter back to home screen
> 3. See error of missing indicators
> 
> 
> **Expected behavior**
> Aforementioned indicators should be present at all times 
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
>  - Device: Pixel 6 Pro
>  - OS: A13 August update 
> 
> **LSPosed Log**
> N/A, bug reproducible 
> 

Not reproducible on my end as well.
Does it work ok without any options? Or it stops working ONLY after you enable your options? if that is the case, please reply this message from GitHub website rather than from email. There your attachments will be visible. Currently your attachments are not visible

**Comment by Zilla0617** [comment]
The Mod settings is not recognized by the website, so I cannot attach it.

**Comment by Zilla0617** [comment]
Im not sure if you received this, but i will add it here:  I did not have multi row system icons enabled. I had the network monitoring enabled (mid right) and the wifi and mobile data indicators were themed with Kai. The battery indicator was themed as well, dashed circle multicolored with the battery percentage in the center. The status bar was shrunk to about 85%.

**Comment by EleoXDA** [comment]
> The Mod settings is not recognized by the website, so I cannot attach it.

Just zip it and send the zipped folder.

**Comment by Zilla0617** [comment]
ASOP Settings attached

**Comment by Zilla0617** [comment]
[AOSP Mod Settings 8-15-22(1).zip](https://github.com/siavash79/AOSPMods/files/9438056/AOSP.Mod.Settings.8-15-22.1.zip)

**Comment by siavash79** [comment]
Still couldn't reproduce. Maybe eleo can try your file too

**Comment by EleoXDA** [comment]
Just tried it myself. Not able to reproduce the issue.

It could be related to all the other magisk modules, lsposed modules and possibly other root apps that user has. He mentioned only magisk modules in his previous post.

**Comment by EleoXDA** [comment]
- A user also tested the custom kernel that Zilla0617 uses on pixel stock firmware android 13. And he also cannot reproduce the bug.

**Comment by EleoXDA** [comment]
It turns out the user had a face unlock LSPosed module that caused this issue

**Comment by EleoXDA** [comment]
That is why I always urge users to remove all the other modules BEFORE replicating the issue and reporting here

**Comment by Zilla0617** [comment]
I did disabled all modules in Magisk & LSPosed but because the issue was so intermittent it was not noticeable in that state for an hour or two. The only reason I noticed was because I had to factory reset my phone and I waited a few days before setting it up face unlock. That's when I realized it was the app causing the issue.

Oct 15, 2022 5:06:39 PM Elbay Malik ***@***.***>:

**Comment by EleoXDA** [comment]
The question was to reproduce the event after disabling modules. And if you find out the issue, you should update your bugreport even if it is closed. This is not only for you. This is for a future user who will also have same issue like you - so that we can help him/her faster
