### ISSUE TITLE
Black Screen Bug

### ISSUE THREAD

**Issue by ZhuSunDev** [siavash79/AOSPMods#333]
*Please note: At the time being, only bug reports from Pixel Stock firmware, or Pixel Experience (normal edition) will be considered. Bug reports from other firmwares will only be taken into account if also reported from one of the supported roms.*

**Describe the bug**
When device bootup,should input password before unlock(PIN,password,fingerprint etc,I just tested PIN+fingerprint two methods).
If don't input after a few time,screen will off,wait a moment press power button,screen will turn on but blackscreen.
you can't see that lockscreen ui and anything,in this case, long press power button,it will display diffrent with Android 12 boot menu(like early Android version).
In this case,you only can select reboot device and next time quickly unlock until screen off.
If unlocked the first time since bootup,everything is ok,only never unlock and screen off will lead to this bug.

**To Reproduce**
1. Open Setting -> Security -> Screen lock
2. Be sure selected any password(swipe no bugs)
3. Restart
4. Don't input password,wait to screen off,after 5 second,press power button on screen,see the error.(as the picture shows,screen already light up but blackscreen,it's obvious on LCD screen)
![IMG_7037](https://user-images.githubusercontent.com/112301592/187059766-7d90a9d5-6300-44ee-ac3c-6c251598291d.JPG)

5.Long press power button,show boot menu,select restart.(as the picture shows,you can see the menu is different to Android12)
![IMG_7038](https://user-images.githubusercontent.com/112301592/187059772-33760081-12ab-4ac9-9e32-eecd5ae815d8.JPG)

6.After restart quickly input password unlock phone until screen off,no bugs until next restart.

**Expected behavior**

**Screenshots**

 - Device: gauguinpro
 - OS: Pixel Experience 12(https://forum.xda-developers.com/t/rom-12-gauguin-official-pixel-experience-12-mi-10t-lite-mi-10i-redmi-note-9-pro-5g.4352869/)

**LSPosed Log**

[LSPosed_2022-08-28T13_42_48.676.zip](https://github.com/siavash79/AOSPMods/files/9439153/LSPosed_2022-08-28T13_42_48.676.zip)

**Comment by EleoXDA** [comment]
First things first, did you retry this event after disabling other magisk modules and lsposed modules? You need to restart after disabling other magisk modules for them to take effect

**Comment by ZhuSunDev** [comment]
Sorry,I was installed a strange magisk module,checked two afternoon still not notice it...
uninstall it all is done straightly,sorry again for my mistake and thank your reply.
