### ISSUE TITLE
Function addition of main menu to enable selection

### ISSUE THREAD

**Issue by LQ2002** [siavash79/AOSPMods#334]
What's on your mind?

Using Aosp mod only requires it to achieve some functions, not all the main menu functions in the mod. Included I only need to modify the lock screen, but I do not need to modify the status bar and other parts. Request to develop this feature

Is this feature implemented on any other app/mod/rom? please specify

I can't realize the lock screen modification function in aosp mod with rom. So I requested to develop this feature and only enable the required main menu features.

**Comment by EleoXDA** [comment]
Hello,

If you don't touch other parts of the MOD and enable only lockscreen mods you will get only lockscreen mods.
