### ISSUE TITLE
Expanded notification shade colors are wrong on stock white theme

### ISSUE THREAD

**Issue by dazewell** [siavash79/AOSPMods#336]
**Describe the bug**
Color of the additional segments at the bottom of the expanded notification shade in white theme is turned white once the module gets enabled. Even with no other options turned on. Tested on the stable as well as on canary 125.

**To Reproduce**
1. Install and activate the module.
1. Restart SystemUI / reboot.

**Expected behavior**
Segments are black as they are by default.

**Screenshots**
![Picsart_22-08-28_21-08-47-105](https://user-images.githubusercontent.com/12871617/187121237-ff079305-b30f-424d-b1d8-a9ca76476de9.jpg)

 - Device: Google Pixel 6
 - OS: Stock Android 13 (TP1A.220624.021)

**LSPosed Log**
[LSPosed_2022-08-28T21_10_16.509168.zip](https://github.com/siavash79/AOSPMods/files/9441496/LSPosed_2022-08-28T21_10_16.509168.zip)

**Comment by siavash79** [comment]
Are you using Full package or Xposed only? They look perfectly fine on my device.

Please also send me your exported settings

**Comment by dazewell** [comment]
Ouch, how could I forget to mention that. I'm using Full version. Here are the settings and clean LSPosed logs after enabling the module. So once I've restarted the system UI through the app, this happened again.

[LSPosed_2022-08-29T09_21_59.802937.zip](https://github.com/siavash79/AOSPMods/files/9446224/LSPosed_2022-08-29T09_21_59.802937.zip)
[aospmods.txt](https://github.com/siavash79/AOSPMods/files/9446239/aospmods.txt)

**Comment by EleoXDA** [comment]
> Ouch, how could I forget to mention that. I'm using Full version. Here are the settings and clean LSPosed logs after enabling the module. So once I've restarted the system UI through the app, this happened again.
> 
> [LSPosed_2022-08-29T09_21_59.802937.zip](https://github.com/siavash79/AOSPMods/files/9446224/LSPosed_2022-08-29T09_21_59.802937.zip)
> [aospmods.txt](https://github.com/siavash79/AOSPMods/files/9446239/aospmods.txt)
> 
> And the same for the Xposed canary 126 actually:
> [LSPosed_2022-08-29T09_33_26.047764.zip](https://github.com/siavash79/AOSPMods/files/9446305/LSPosed_2022-08-29T09_33_26.047764.zip)
> [aospmods-x-c126.txt](https://github.com/siavash79/AOSPMods/files/9446308/aospmods-x-c126.txt)
> 

What Siavash was asking you to do is to take a backup of your AOSPMods app settings from "3dot menu/import-export/export to" option. Then add that file in a zip folder and attach it here.

I also own pixel 6 and also use this MOD and it never is white on black as yours. So there has to be some kind of incompatible theme app/module/function that you use that triggers this
![Screenshot_20220901-152827.png](https://user-images.githubusercontent.com/27622683/187925788-ed3bfd1c-1aa3-4749-8583-6575a6d90c97.png)
![Screenshot_20220901-152834.png](https://user-images.githubusercontent.com/27622683/187925820-6ab85e34-b926-4c6f-b1c2-23cfef6eeaca.png)

**Comment by Jnss98b** [comment]
> I also own pixel 6 and also use this MOD and it never is white on black as yours. So there has to be some kind of incompatible theme app/module/function that you use that triggers this

I can reproduce this behavior on my pixel 5 if I toggle dark/light mode and then choose a different color palette in wallpaper & style once or twice. It gets temporarily fixed if I reboot my phone

**Comment by Jnss98b** [comment]
Here's my settings https://file.io/y56SoQhpg9NE

**Comment by EleoXDA** [comment]
> > I also own pixel 6 and also use this MOD and it never is white on black as yours. So there has to be some kind of incompatible theme app/module/function that you use that triggers this
> 
> I can reproduce this behavior on my pixel 5 if I toggle dark/light mode and then choose a different color palette in wallpaper & style once or twice. It gets temporarily fixed if I reboot my phone
> 
> Edit: Screenshot
> ![image](https://user-images.githubusercontent.com/24306400/188062947-8b548db1-a7e2-472b-a009-77ae4c76da09.png)
> 

Tried with a repainter, and then with wallpaper&style but cannot reproduce with your exported settings any of that on my device. It is still showing the same as I shared my screenshots above

**Comment by InsyncIntros** [comment]
I'm also having this problem with my pixel software, a temporary fix is to switch to dark theme, restart system UI, and then switch back to light theme. I do not know why this is happening, but it does. 
![Screenshot_20220907-183217](https://user-images.githubusercontent.com/84303659/188995204-65cbcb83-dda8-4cd5-8a8a-49f4fe3a2d03.png)
![Screenshot_20220907-183352](https://user-images.githubusercontent.com/84303659/188995287-c7f748b5-fa1f-4f74-95e9-615e44bf2bef.png)
I have also attached my magisk modules list, in case you guys know which module could cause this.

**Comment by InsyncIntros** [comment]
> I'm also having this problem with my pixel software, a temporary fix is to switch to dark theme, restart system UI, and then switch back to light theme. I do not know why this is happening, but it does. ![Screenshot_20220907-183217](https://user-images.githubusercontent.com/84303659/188995204-65cbcb83-dda8-4cd5-8a8a-49f4fe3a2d03.png) ![Screenshot_20220907-183352](https://user-images.githubusercontent.com/84303659/188995287-c7f748b5-fa1f-4f74-95e9-615e44bf2bef.png) I have also attached my magisk modules list, in case you guys know which module could cause this.

and here's my exported settings. https://file.io/JTgqpLhp6pjX

**Comment by EleoXDA** [comment]
> > I'm also having this problem with my pixel software, a temporary fix is to switch to dark theme, restart system UI, and then switch back to light theme. I do not know why this is happening, but it does. ![Screenshot_20220907-183217](https://user-images.githubusercontent.com/84303659/188995204-65cbcb83-dda8-4cd5-8a8a-49f4fe3a2d03.png) ![Screenshot_20220907-183352](https://user-images.githubusercontent.com/84303659/188995287-c7f748b5-fa1f-4f74-95e9-615e44bf2bef.png) I have also attached my magisk modules list, in case you guys know which module could cause this.
> 
> and here's my exported settings. https://file.io/JTgqpLhp6pjX

theming agents? substratum? repainter?

**Comment by InsyncIntros** [comment]
> > > I'm also having this problem with my pixel software, a temporary fix is to switch to dark theme, restart system UI, and then switch back to light theme. I do not know why this is happening, but it does. ![Screenshot_20220907-183217](https://user-images.githubusercontent.com/84303659/188995204-65cbcb83-dda8-4cd5-8a8a-49f4fe3a2d03.png) ![Screenshot_20220907-183352](https://user-images.githubusercontent.com/84303659/188995287-c7f748b5-fa1f-4f74-95e9-615e44bf2bef.png) I have also attached my magisk modules list, in case you guys know which module could cause this.
> > 
> > 
> > and here's my exported settings. https://file.io/JTgqpLhp6pjX
> 
> theming agents? substratum? repainter?

no I have not used any theming engines yet
