### ISSUE TITLE
Brightness slider issue  

### ISSUE THREAD

**Issue by Arafatulislamantor** [siavash79/AOSPMods#339]
## Brightness Slider Issues😐
   
Brightness slider have some issues.The problem is brightness bar does not do this(watch provided video)  when I single touch brightness up-down.when i active AOSP Mods then brightness slider not working like this

https://user-images.githubusercontent.com/47410095/188008404-c8556b2b-8e82-42c8-931b-120fa7cce9e4.mp4

## AOSP Mods : Latest

**Comment by EleoXDA** [comment]
Please **RE READ notes in the group and submit a bug report with requested information.**

What you show **works perfectly fine on my device**. To find **what is wrong on your device** we need BUG report information that **was requested in the notes of the group**.

**Comment by siavash79** [comment]
He's right: brightness slider mod on Android 12 doesn't do the animation correctly.
Luckily on Android 13 it doesn't happen anymore

**Comment by EleoXDA** [comment]
> He's right: brightness slider mod on Android 12 doesn't do the animation correctly. Luckily on Android 13 it doesn't happen anymore

I didnt see anything related to Android 12 on his report. Neither did he report properly when asked two times in telegram chat. I shouldnt assume what user has. I only can say what I observe on mine with respect to his bugreport: 
- LSPosed Version : 1.8.3
- Magisk : 25.2
- AOSP Mods : Latest

**Comment by Arafatulislamantor** [comment]
> He's right: brightness slider mod on Android 12 doesn't do the animation correctly. Luckily on Android 13 it doesn't happen anymore

Yes my brightness slider animation is not working properly. I have tried aosp mods in many roms but same. How does the animation get stuck when increasing or decreasing the brightness of the phone. If you fixed it for A12L it would be great help.

**Comment by EleoXDA** [comment]
It is fixed for A13 as noted by Siavash above. So, no need to work on upgrading lower android version. Upgrade to A13

**Comment by Arafatulislamantor** [comment]
> It is fixed for A13 as noted by Siavash above. So, no need to work on upgrading lower android version. Upgrade to A13

A13 is not fully stable yet.So mostly Android 12 users. So we are having a lot of trouble with this

**Comment by EleoXDA** [comment]
> > It is fixed for A13 as noted by Siavash above. So, no need to work on upgrading lower android version. Upgrade to A13
> 
> A13 is not fully stable yet.So mostly Android 12 users. So we are having a lot of trouble with this

A13 was fully stable weeks ago. And you can just update to A13
