### ISSUE TITLE
Brightness slider animation not working

### ISSUE THREAD

**Issue by woeijiunn88** [siavash79/AOSPMods#342]
*Please note: At the time being, only bug reports from Pixel Stock firmware, or Pixel Experience (normal edition) will be considered. Bug reports from other firmwares will only be taken into account if also reported from one of the supported roms.*

**Describe the bug**
#339 , log will provide in this issue.

**To Reproduce**
1. Drag the brightness slider.
2. The slider will remains at the initial state while dragging, after release the slider position will change.

**Expected behavior**
Brightness adjustment will work but the slider animation doesn't.

**Screenshots**

https://user-images.githubusercontent.com/20749427/188788656-558159ac-30a9-4be9-8f7d-c1165a93d3bd.mp4

 - Device: Xiaomi POCO F1 (beryllium)
 - OS: PixelExperience_Plus_beryllium-12.1-20220817-0755-OFFICIAL (SQ3A.220705.004)
 - Magisk: 25.2
 - LSPosed: 1.8.3 (6552)
 - App Version: canary-130 (Xposed only)

**LSPosed Log**
[LSPosed_2022-09-07T12_12_40.056.zip](https://github.com/siavash79/AOSPMods/files/9502656/LSPosed_2022-09-07T12_12_40.056.zip)

**Additional Notes**
- Magisk and Xposed Modules except AOSP Mods are disabled.
- ROM is clean flashed few hours ago, the bug is already existed while no additional modification and applications installed.

**Comment by EleoXDA** [comment]
Switch to Android 13 and it will ne fixed! ALWAYS check previous reports (completed too) before reporting
