### ISSUE TITLE
Sim indicators retained on status bar

### ISSUE THREAD

**Issue by Swilla66** [siavash79/AOSPMods#349]
![Screenshot_20220912-190757](https://user-images.githubusercontent.com/94477128/189725848-bf6aa6fb-8724-4855-9776-a8e5f78d9f79.png)
Sim cards indicators still show on status bar even after applying the combined signal icons option.
This is Pixel OS Android 13 initial build

**Comment by siavash79** [comment]
Pixel OS not supported, thus not expected to work normally
