### ISSUE TITLE
Option to disable location and camera/mic indicators

### ISSUE THREAD

**Issue by 1RandomDev** [siavash79/AOSPMods#350]
What's on your mind?
Pls add option to disable this annoying location indicator and other option to disable the camera/mic indicator. I didn't find any mod that can disable them on all ROMs. Would really appreciate if this is possible.

Is this feature implemented on any other app/mod/rom? please specify
The crDroid ROM can do this

**Comment by siavash79** [comment]
Hopefully in the next canary

**Comment by 1RandomDev** [comment]
Thx, thats one of the most useful features of this whole mod :D Me and many other people are looking for a module that can do this for almost 1 year now.
