### ISSUE TITLE
Status Bar Compressed When Out Of Full Screen

### ISSUE THREAD

**Issue by drkui** [siavash79/AOSPMods#353]
I'm having an issue with the status bar compressing to the left when I exit out of the horizontal orientation. I first noticed this behavior after exiting from a full screen YouTube video, then on Netflix, and and so forth. 
Before:
![Screenshot_20220914-164021~2](https://user-images.githubusercontent.com/11448650/190281717-13a46708-db4d-4267-8fd4-b9b10ea332aa.png)
After:
![Screenshot_20220914-164033~2](https://user-images.githubusercontent.com/11448650/190281727-fe547e3d-aa86-486d-bcbb-3e70930fc117.png)

I have an Xperia 1 Mark III, running Android 12.

**Comment by siavash79** [comment]
This issue comes directly from Android. When you change the orientation it announces the available area to the statusbar items. Apparently it reports them wrong for a brief moment. But after a few seconds they return to their normal position
