### ISSUE TITLE
[Bug]  doesn't work on any ROM I installed

### ISSUE THREAD

**Issue by Dimitrysaf** [siavash79/AOSPMods#355]
### Describe the issue

Yeah, that seems weird, but for now I have ArrowOS version 13 android 13 UNOFFICIAL and may AOSP doesn't work, the app seems to open fine I GRANTED root and every setting I toggle doesn't seem to work 

### Steps to reproduce

Doesn't fixed yet

### Your device setup (Please take some time to give correct information here)

Poco F1 
Android 13  | ArrowOS UNOFFICIAL
Beryllium
AOSP Version canary-135 (135)

**Comment by EleoXDA** [comment]
Fully supported ROMs are pixel stock firmware and pixel experience normal and plus editions.

Unless you provide the required information, this bugreport cannot be proceeded.

**Comment by EleoXDA** [comment]
> ### Describe the issue
> 
> Yeah, that seems weird, but for now I have ArrowOS version 13 android 13 UNOFFICIAL and may AOSP doesn't work, the app seems to open fine I GRANTED root and every setting I toggle doesn't seem to work 
> 
> ### Steps to reproduce
> 
> Doesn't fixed yet
> 
> ### Expected bahavior
> 
> _No response_
> 
> ### Your device setup (Please take some time to give correct information here)
> 
> Poco F1 
> Android 13  | ArrowOS UNOFFICIAL
> Beryllium
> AOSP Version canary-135 (135)
> 
> ### Logs
> 
> _No response_

Fully supported ROMs are pixel stock firmware and pixel experience normal and plus editions. And many more ROMs can still use even though one-two options may not work as requested.

It seems you haven't provided required information. You may not have important services like LSposed Zygisk/Riru.
Unless you provide the required information, this bugreport cannot be proceeded.

**Comment by EleoXDA** [comment]
Please fill out the bugreport so that we can access your information. Until then, there is nothing to debug
