### ISSUE TITLE
Battery icon problem 

### ISSUE THREAD

**Issue by xerel89** [siavash79/AOSPMods#357]
### Describe the issue

Battery icon problem 

### Steps to reproduce

Hey! 
I have installed the AOSPMods module with follow steps
1. Downloading from the xda forum and installing in the magisk apk app and reboot
2. Settings made that I need as needed
3. Well I have chosen stroked battery and here lies my problem when I have turned on automatic screen idle and it changes back to the standard 

![Screenshot_20220919-075810_Shell](https://user-images.githubusercontent.com/33770412/190959327-47b185d3-4957-48a5-8d59-40e1b0222ed4.png)
![Screenshot_20220919-080001_Shell](https://user-images.githubusercontent.com/33770412/190959339-d1cf71bc-e4ff-4907-aa5f-30d30845c863.png)
Here the lsposed report for more information 
[LSPosed_2022-09-19T08_00_37.488.zip](https://github.com/siavash79/AOSPMods/files/9596487/LSPosed_2022-09-19T08_00_37.488.zip)

[Bug Video ](https://mega.nz/file/Xe411AJB#QEJLE2GiH6tNVv3Tto7K70hj0dtRY6WLSRXc6m5D49Y )

[Bug Report](https://mega.nz/file/OTwGnLAZ#NTrZKsaeIiZvGSOB7DdL1sthe70xUVaEvEZj2Jwp1bA)

I hope I was able to explain my problem sufficiently. 

### Your device setup (Please take some time to give correct information here)

Xiaomi Redmi Note 9 Pro
Pixel Exprience Plus
Android 12
Version August 8/28

### Logs
- - [x] ## > `~~ ~~`
``` _No response

**Comment by EleoXDA** [comment]
Could you do this:
Revoke root access to all other theming apps
Disable all magisk modules and lsposed modules (other than lsposed magisk module and AOSPMods magisk+lsposed module), then try to replicate the bug. If you are successful please fill out the bugreport checklist with exported settings from AOSPMods (put it in a zipped folder so that GitHub can allow sharing it)

**Comment by xerel89** [comment]
Here the bug report, I have not found out how I can uploaded the file here...

**Comment by EleoXDA** [comment]
Could you reopen with requested info?

**Comment by xerel89** [comment]
What to you mean?  I am using now again lineage same problem no different, when the automatic ration is off I have no problems but I when is on and I turn the phone change the battery icon... No hurry it is not a big problem for me :)

**Comment by EleoXDA** [comment]
> What to you mean? I am using now again lineage same problem no different, when the automatic ration is off I have no problems but I when is on and I turn the phone change the battery icon... No hurry it is not a big problem for me :)

I mean this message: https://github.com/siavash79/AOSPMods/issues/357#issuecomment-1250886546

And lineage is not even supported - so only pixel stock firmware and official pixel experience ROMs are accepted.

**Comment by siavash79** [comment]
Reading the bug report, I couldn't understand this: are you now on PE plus or LOS? It does make a difference which one you're on right now

**Comment by xerel89** [comment]
When I created the bug report, I had Pixel plus installed, now I used Lineage again because I like this rom better. I'm waiting until the new miatoll update comes, will there be an Android 13 update in this regard?

**Comment by EleoXDA** [comment]
android 13 is already supported by AOSPMods since start of September. And there is no support for LOS

**Comment by xerel89** [comment]
Sorry, I expressed myself incorrectly, I actually meant the new pixel plus update. I read on xda that Android 13 is available for miui and therefore I wonder if it will be included in the next Pixel plus update.

**Comment by EleoXDA** [comment]
This is off-topic question here. You have a bugreport with unknown OS, with a log link that doesnt lead to any files and still no response to https://github.com/siavash79/AOSPMods/issues/357#issuecomment-1250886546

**Comment by EleoXDA** [comment]
Once you make up your mind, please collect all necessary logs with proper answers to question, and then we can discuss what can be the remedy to your issue. For know I am closing this issue as I would rather talk in a clean page with all the information in first post.
