### ISSUE TITLE
[A12] Double lock screen after applying lock screen setting in AOSPMods

### ISSUE THREAD

**Issue by padiyes** [siavash79/AOSPMods#358]
### Describe the issue

Double lock screen after applying lock screen setting in AOSPMods

### Steps to reproduce

After fresh install, the first time to do for me is to install magisk and AOSPMods. Just after change the settings related to lock screen, after some times I realize that double lock screen appears in my device. In this case, I should unlock the device twice.

Note:

1. Already using the latest AOSPMods (2.1.0)
2. Only occur when lock screen activated
3. Already try to "Reset all settings" and reboot but the issue still occur
4. On Android 12 (ArrowOS 12.1 and PixelOS 12)
5. Only able to fix this issue by factory reset

Setting os AOSPMods has been exported as below (please note that I need to rename it as .txt so it can be uploaded):
[aospsetting22aug22a12.1.txt](https://github.com/siavash79/AOSPMods/files/9546919/aospsetting22aug22a12.1.txt)

Video of the issue could be reviewed below:
https://user-images.githubusercontent.com/11946436/189626317-5690c2df-37bc-40b0-a014-abe034cbda03.mp4

If there's another details needed, don't hesitate to contact me. And thanks for the attention :)

### Expected bahavior

The lock setting of AospMods should not obstruct the lock screen of Android OS.

### Your device setup (Please take some time to give correct information here)

- ArrowOS 12.1 and PixelOS 12
- Latest magisk (25.2)
- Latest AOPSMods (2.1.0)

### Logs

Lsposed log available here:
[LSPosed_2022-09-19T15_13_44.353.zip](https://github.com/siavash79/AOSPMods/files/9597183/LSPosed_2022-09-19T15_13_44.353.zip)

**Comment by EleoXDA** [comment]
> ### Describe the issue
> 
> Double lock screen after applying lock screen setting in AOSPMods
> 
> ### Steps to reproduce
> 
> After fresh install, the first time to do for me is to install magisk and AOSPMods. Just after change the settings related to lock screen, after some times I realize that double lock screen appears in my device. In this case, I should unlock the device twice.
> 
> Note:
> 
> 1. Already using the latest AOSPMods (2.1.0)
> 2. Only occur when lock screen activated
> 3. Already try to "Reset all settings" and reboot but the issue still occur
> 4. On Android 12 (ArrowOS 12.1 and PixelOS 12)
> 5. Only able to fix this issue by factory reset
> 
> Setting os AOSPMods has been exported as below (please note that I need to rename it as .txt so it can be uploaded):
> [aospsetting22aug22a12.1.txt](https://github.com/siavash79/AOSPMods/files/9546919/aospsetting22aug22a12.1.txt)
> 
> Video of the issue could be reviewed below:
> https://user-images.githubusercontent.com/11946436/189626317-5690c2df-37bc-40b0-a014-abe034cbda03.mp4
> 
> If there's another details needed, don't hesitate to contact me. And thanks for the attention :)
> 
> ### Expected bahavior
> 
> The lock setting of AospMods should not obstruct the lock screen of Android OS.
> 
> ### Your device setup (Please take some time to give correct information here)
> 
> - ArrowOS 12.1 and PixelOS 12
> - Latest magisk (25.2)
> - Latest AOPSMods (2.1.0)
> 
> 
> 
> ### Logs
> 
> Lsposed log available here:
> [LSPosed_2022-09-19T15_13_44.353.zip](https://github.com/siavash79/AOSPMods/files/9597183/LSPosed_2022-09-19T15_13_44.353.zip)

Neither arrowOS nor PixelOS are compatible ROMs. Bug reports are welcome from pixel stock firmware and Pixel Experience ROM.
