### ISSUE TITLE
Brighten Neon Light Tile theme

### ISSUE THREAD

**Issue by nickelnine** [siavash79/AOSPMods#360]
What's on your mind?
I like using the Neon QS style but I find the tiles are too dark. Perhaps the neon glow around the tile could be used as the base color of the tile itself plus a little brighter?

Is this feature implemented on any other app/mod/rom? please specify
The closest I've used is Neon tile style from crDroid A11 which has a bright blue tile color which I'd like to see implemented here.

Thanks for the efforts.

**Comment by EleoXDA** [comment]
If you find an android 13 custom ROM with open source, please add it

**Comment by EleoXDA** [comment]
Write back to reopen the issue
