### ISSUE TITLE
[Bug] OxygenOS  Icons Theme

### ISSUE THREAD

**Issue by gloeyisk** [siavash79/AOSPMods#362]
### Describe the issue

Unable to apply OxygenOS icons theme in Theming > Icon style section starting from version 2.1.0. The icons stayed default (no change) even after a reboot or two.

### Steps to reproduce

1. Open AOSP Mods app
2. Click Theming
3. Click Open Style
4. Select OxygenOS

### Your device setup (Please take some time to give correct information here)

- Xiaomi Redmi Note 10 Pro running PixelOS
- Android 12.1
- SQ3A.220705.004
  PixelOS_sweet-12.1-20220812-0031
- Magisk 25.2 Stable
- AOSP Mods 2.2.0
- LSposed 1.8.4

**Comment by EleoXDA** [comment]
Works fine with pixel stock firmware. Please use a supported ROM/firmware
