### ISSUE TITLE
Option To Answer Incoming calls with Volume Buttons

### ISSUE THREAD

**Issue by DEVDD960** [siavash79/AOSPMods#368]
This feature is useful while gaming as it prevents the phone app from minimizing the game,  And after all game can be played simultaneously after recieving the call..which is again a plus point of it... 

This feature is available in LineageOS and Roms based on it.

If possible please add this feature.  
![photo_2022-09-24_15-28-48](https://user-images.githubusercontent.com/69689986/192092033-0bae425b-5c3c-4de5-9d04-59f753772deb.jpg)

**Comment by EleoXDA** [comment]
What is the difference here? When this feature is enabled do you not see the caller id and answer/reject buttons?

**Comment by DEVDD960** [comment]
> 



> What is the difference here? When this feature is enabled do you not see the caller id and answer/reject buttons?

I see those buttons but when I accept the call through those buttons the game will be minimized completely and the phone app will be opened, but if this feature is added if the call is accepted by pressing the volume buttons the game will not be minimised thats the difference.

**Comment by siavash79** [comment]
Thanks

This option doesn't look useful enough from my point of view
- you don't get enough controls over the call as you're supposed to
- there's a risk of mistake specially when the phone is in the pocket
- volume buttons during phone ringing are already mapped for a much useful feature: silencing the call
