### ISSUE TITLE
realme GT 5G(realme UI 3.0) not working

### ISSUE THREAD

**Issue by willie666687** [siavash79/AOSPMods#369]
Almost every settings not working on realme GT 5G(android 12)
![Screenshot_2022-09-25-21-42-42-47_72e51cb3a52fdee2708cbc77b8e0ce65](https://user-images.githubusercontent.com/89621369/192146738-06c14eb6-d37b-4fcb-912b-4ef935504c85.jpg)
![Screenshot_2022-09-25-21-42-39-90_72e51cb3a52fdee2708cbc77b8e0ce65](https://user-images.githubusercontent.com/89621369/192146740-0b99b62e-e553-4159-96b6-0902713a784e.jpg)
![Screenshot_2022-09-25-21-42-08-74_72e51cb3a52fdee2708cbc77b8e0ce65](https://user-images.githubusercontent.com/89621369/192146741-5cac27dc-81d8-43a9-a8d4-a1acb7fbc544.jpg)
original
![Screenshot_2022-09-25-21-45-50-91_72e51cb3a52fdee2708cbc77b8e0ce65](https://user-images.githubusercontent.com/89621369/192146913-f729e50d-c4f4-4131-b616-df77c3f47f4e.jpg)

**Comment by EleoXDA** [comment]
This was already answered!
https://github.com/siavash79/AOSPMods/issues/371#issuecomment-1257235627
