### ISSUE TITLE
Long press missing on A13

### ISSUE THREAD

**Issue by MachoMan1988** [siavash79/AOSPMods#370]
On Android 13 (I have Pixel Experience rom) is missing on AOSP Mods the option for killing app on back long press. I have 2.2.0 version

**Comment by EleoXDA** [comment]
> On Android 13 (I have Pixel Experience rom) is missing on AOSP Mods the option for killing app on back long press. I have 2.2.0 version

The option to kill app is present in gesture navbar. 3button navbar is obsolete and will no longer be supported

**Comment by Retardium** [comment]
Hi, could you please reconsider the support for the 3 button navigation? I especially miss the kill app function.

I use it on A13 and I don't think it will be removed in the future either. At least on A14 it will still be available according to various sources.

**Comment by EleoXDA** [comment]
> @EleoXDA 
> Hi, could you please reconsider the support for the 3 button navigation? I especially miss the kill app function.
> 
> I use it on A13 and I don't think it will be removed in the future either. At least on A14 it will still be available according to various sources.

No. We advise users to focus instead on gesture navigation. 3button navigation is obsolete
