### ISSUE TITLE
[Bug] Realme GT 5G not working

### ISSUE THREAD

**Issue by willie666687** [siavash79/AOSPMods#371]
### Describe the issue

Almost every settings not working on realme GT 5g (realme UI 3.0)

### Steps to reproduce

Original QS title
![Screenshot_2022-09-25-21-45-50-91_72e51cb3a52fdee2708cbc77b8e0ce65](https://user-images.githubusercontent.com/89621369/192150417-680ad8d4-be84-4d0a-bfed-8395f6c109c6.jpg)
used AOSP Mods
![Screenshot_2022-09-25-21-42-42-47_72e51cb3a52fdee2708cbc77b8e0ce65](https://user-images.githubusercontent.com/89621369/192150382-30d39014-088c-4053-8697-4c1dff6351e0.jpg)
![Screenshot_2022-09-25-21-42-39-90_72e51cb3a52fdee2708cbc77b8e0ce65](https://user-images.githubusercontent.com/89621369/192150384-ec366d34-7211-4f0a-9c90-64c63fe1f846.jpg)
ASOP settings
![Screenshot_2022-09-25-21-42-08-74_72e51cb3a52fdee2708cbc77b8e0ce65](https://user-images.githubusercontent.com/89621369/192150385-a8f1806b-8ae5-436c-9b48-092cc7a74e5f.jpg)

### Your device setup (Please take some time to give correct information here)

-Realme GT 5G
-realme UI 3.0
-Android 12
-XMX2022_11_C.20
-magisk 25.2
-Lsposed 1.8.4
-AOSP mods 2.2.0

**Comment by EleoXDA** [comment]
You should read the compatibility table of this MOD. It is only for AOSP and full support is only for pixel stock firmware AND pixel experience ROMs. No other ROM is supported
