### ISSUE TITLE
Can you add the “Carrier Label” feature?

### ISSUE THREAD

**Issue by odmfl** [siavash79/AOSPMods#372]
I would like to get back this function that has gradually disappeared in the custom roms

commits that might help 

https://github.com/DerpFest-12/frameworks_base/commit/8465908ebe2c64f3a7ead799c33ceb401d0f3d6e

https://github.com/DerpFest-12/packages_apps_DerpSpace/commit/38a72ad74fd6b569e8deaedfdbee4dfaee4665ff

**Comment by EleoXDA** [comment]
Where do you want to see Carrier Label? Any A13 ROMs that currently have it?

**Comment by odmfl** [comment]
yes i like to see carrier labels in “lookscreen and status bar” at the same time.  Currently no A13 Rom have this option, some A12 Rom have it but they are very few

**Comment by EleoXDA** [comment]
> yes i like to see carrier labels in “lookscreen and status bar” at the same time. Currently no A13 Rom have this option, some A12 Rom have it but they are very few

In stock pixel firmware you already have carrier label in statusbar of lockscreen. Where else do you want to have it?

**Comment by odmfl** [comment]
In stock pixel firmware, carrier label is only visible on the lockscreen.
it's my personal taste, but I'd like it to be visible in the statusbar as well.

With this modification that I ask you have 4 choices.  The user can choose where to view it. I send you a screenshot from RR10 with the 4 available choices.
![C1E178C3-E393-4806-9D33-1FE77FBEF33B](https://user-images.githubusercontent.com/77236251/192974473-87d088de-7a2e-4a33-867a-bfdf694c5343.jpeg)

**Comment by EleoXDA** [comment]
> In stock pixel firmware, carrier label is only visible on the lockscreen. it's my personal taste, but I'd like it to be visible in the statusbar as well.
> 
> With this modification that I ask you have 4 choices. The user can choose where to view it. I send you a screenshot from RR10 with the 4 available choices. ![C1E178C3-E393-4806-9D33-1FE77FBEF33B](https://user-images.githubusercontent.com/77236251/192974473-87d088de-7a2e-4a33-867a-bfdf694c5343.jpeg)

You did not understand my question. I am saying if you can see it in QS and lockscreen statusbar already, what is the use of seeing it anywhere else?

**Comment by odmfl** [comment]
I just like it that way and some ROMs have this option.  But this option as you can see also allows you not to view it anywhere or only in the status bar. So there could also be a sense, some users may prefer viewing only in the statusbar, others would not want to view it at all, others like me like to see it always. In custom ROMs there are many options that may not make sense, I'll give you an example: Percentage of the battery visible to the right or left of the icon of the battery, in this option what is the sense?  There is no sense so in the end the percentage I see on the right or on the left may seem indifferent, yet in many custom ROMs this option is present.  Sometimes mods have meaning, functionality and usefulness, other times mods have only an aesthetic purpose.  This is precisely the beauty of custom ROMs, and of the mods present in them.

**Comment by mingaldrichgan** [comment]
As a compromise, would it make sense to add "carrier label" as a placeholder variable that can be used in the custom clock string if desired?

**Comment by EleoXDA** [comment]
> 



> I just like it that way and some ROMs have this option. But this option as you can see also allows you not to view it anywhere or only in the status bar. So there could also be a sense, some users may prefer viewing only in the statusbar, others would not want to view it at all, others like me like to see it always. In custom ROMs there are many options that may not make sense, I'll give you an example: Percentage of the battery visible to the right or left of the icon of the battery, in this option what is the sense? There is no sense so in the end the percentage I see on the right or on the left may seem indifferent, yet in many custom ROMs this option is present. Sometimes mods have meaning, functionality and usefulness, other times mods have only an aesthetic purpose. This is precisely the beauty of custom ROMs, and of the mods present in them.

I understand your concern, and though this MOD is not a custom ROM with lots of customizations, we try to give modifications that prove to be useful in function rather than aesthetics or making your phone look cool. Unless you want to ask this feature from your custom ROM, I dont think this feature will be in our to-do list (unless we have nothing else to add)

**Comment by EleoXDA** [comment]
> As a compromise, would it make sense to add "carrier label" as a placeholder variable that can be used in the custom clock string if desired?
That will require some time to test to see whether we have direct access to string of mobile carrier.

**Comment by odmfl** [comment]
Ok, I understand what you mean, I think it is better that this is implemented in a Custom Rom, I hope that some developer will implement it in some Rom with A13.  Thanks anyway. I close the issue

**Comment by siavash79** [comment]
May I ask a more basic question: what is a carrier label and what is it used for?

**Comment by EleoXDA** [comment]
It is the text that we can change in Lockscreen to a custom one. It is also visible under the internet icon in quick settings AND top of the quick settings (near battery) when you are connected to mobile data. So basically it is already everywhere 😁
![Screenshot_20220930-105857](https://user-images.githubusercontent.com/27622683/193234398-b6464026-9419-4e27-b6fd-9c9466471763.png)
![Screenshot_20220930-110057](https://user-images.githubusercontent.com/27622683/193234420-14308849-7a95-4297-892c-965d047b3d7e.png)

**Comment by siavash79** [comment]
Thanks

Can't understand how it can be useful though

**Comment by EleoXDA** [comment]
> Thanks
> 
> Can't understand how it can be useful though

Exactly. That was my comment. I dont see a use of it. E.g. WiFi SSID can be useful if you have a "routine" set up in google assistant or a Tasker action that gets executed with you connecting to a specific WiFi (e.g. work, home, cafe) but I find no use of showing mobile carrier name especially if you know what carrier you have. This can only be used to show your friends what your phone is capable to do...which is not a useful function
