### ISSUE TITLE
[Pixel 5a A12] Back Button Force Close App Not Working if Unlocked Via Fingerprint, Only Power Button > Pin

### ISSUE THREAD

**Issue by ohmybahgosh** [siavash79/AOSPMods#376]
### _Force Close Foreground Application by Long Pressing Back Button Doesn't Work if Phone is Opened via Fingerprint Unlock, Only Works via Power Button Unlock_

**Device:**
_Pixel 5a_
_Android 12 (12 (SQ3A.220605.009.A1))_

**AOSPMod Version:**
_Canary 143 (Xposed Only)_

**AOSPMod Settings Export:**
_https://anonfiles.com/D1Df05A9yf/PIXEL-5A-ANDROID12_AOSPMOD-SETTINGS_

**LSPosed Version:**
_1.8.4 (6609) - Zygisk_

**Reproducing Bug:**

1.  Either Press Power Button to Turn off Screen, or Let the Screen turn off automatically
2.  Place finger on fingerprint scanner to unlock the phone
3.  Attempt to force close any app by long pressing back button, and the function to force close fails 
4. Repeate Step One
5. Unlock With Power Button, Enter Pin if Smart Lock prompt is displayed 
6. Repeat Step 3, and the function will now work properly and force close the application

**Comment by EleoXDA** [comment]
3button navbar is deprecated. And so is android 12. Please use navigation bar and update to android 13 for support.

Why android 12? Pixel 5 can update to android 13 that is currently supported. Are you using developer edition of android 12 that Google released or old version of standard android 12?

And lastly we don't see logs. We at least need logs from you for the step 3. If no logs (or no proofs in logs) we cannot help as we no longer have android 12 devices

**Comment by ohmybahgosh** [comment]
> 3button navbar is deprecated. And so is android 12. Please use navigation bar and update to android 13 for support.
> 
> Why android 12? Pixel 5 can update to android 13 that is currently supported. Are you using developer edition of android 12 that Google released or old version of standard android 12?
> 
> And lastly we don't see logs. We at least need logs from you for the step 3. If no logs (or no proofs in logs) we cannot help as we no longer have android 12 devices

I've upgraded to Android 13 (T1B1.220819.006)..

Could you clarify where the 3button replacement navigation bar setting is that allows for force closing foreground app?
