### ISSUE TITLE
Direct unlock

### ISSUE THREAD

**Issue by kfriedberg** [siavash79/AOSPMods#378]
What's on your mind?
Hoping to get direct unlock (skip swipe up to unlock when turning on screen, and go directly to pattern/PIN entry) including see through style

Is this feature implemented on any other app/mod/rom? please specify
GravityBox

**Comment by EleoXDA** [comment]
That is not useful as you won't see notifications/quick settings and so on on your lockscreen. That is the reason why the lockscreen is there.

**Comment by kfriedberg** [comment]
For my uses, I don't really need the lockscreen?  Out and about, I'd rather all those things be locked behind my pattern/PIN.  At home with Smart Unlock active to skip pattern/PIN, I'd prefer to get to full phone functions as soon as possible.

Just upgraded past Android 11 and missing this GB feature, and hoping it can be added here so I could get it back.

**Comment by EleoXDA** [comment]
That is a very niche usage, I think you should just find a way to disable your lockscreen overall.

**Comment by siavash79** [comment]
Added to latest canary
