### ISSUE TITLE
[Bug] Privacy indicators Hiding not working on Android 13 October Update

### ISSUE THREAD

**Issue by zyh941** [siavash79/AOSPMods#382]
### Describe the issue

Privacy indicators always show

### Steps to reproduce

After I upgrade my Pixel 5 (running Google stock ROM) to Android 13, TP1A.221005.002. I find the hiding switch not working. Whatever I turn it on or off, the privacy indicators always show. Please fix it.

### Your device setup (Please take some time to give correct information here)

-Google Pixel 5 stock firmware October Security Patch
-Android 13 Stable version
-Magisk v25.2 Stable
-AOSPMods 2.2.0
-LSPosed 1.8.4
Root access apps:
![root access](https://user-images.githubusercontent.com/95530307/193729193-d86a1020-bed1-44bc-bf7e-eb443595acdb.png)

Magisk modules:
![MG modules](https://user-images.githubusercontent.com/95530307/193729234-7cb82b48-5604-4be8-ab68-69eb9456e3e8.png)

LSPosed modules:
![LSP modules](https://user-images.githubusercontent.com/95530307/193729263-eb2f8846-1aba-4135-b0ac-49f4df41110d.png)

### Logs

LSP logs.
[LSPosed_2022-10-04T11_30_10.519417.zip](https://github.com/siavash79/AOSPMods/files/9702582/LSPosed_2022-10-04T11_30_10.519417.zip)

**Comment by EleoXDA** [comment]
We cannot reproduce it. To check it, please follow steps as described. Disable all other modules and retry. In our devices, indicators can be turned off. Please retry it and open a new report if unsuccessful

**Comment by siavash79** [comment]
I confirm the issue. Apparently wallpaper dim is also broken

**Comment by EleoXDA** [comment]
Could it be about latest version 144? Users with 143 on october cant replicate the issue

**Comment by siavash79** [comment]
Apparently it was 144. 145 is okay

**Comment by EleoXDA** [comment]
But @zyh941 is on stable version of AOSPMods which has no such bug. So, zyh941 needs to figure out why his/her device has issues whereas others are fine. That is why I was intended to close this report until I hear more in depth report with all the other modules shut down
