### ISSUE TITLE
[Bug] Camera Shortcut on Lockscreen doesn't work 

### ISSUE THREAD

**Issue by Turbocharger** [siavash79/AOSPMods#384]
### Describe the issue

Setting Lockscreen Shortcut for Camera doesn't opens up camera app instead it ends up on homescreen

### Steps to reproduce

- Setup Lockscreen Shortcut for Camera Left/Right
- Tap on Camera App, it asks for security code or Fingerprint and ends up landing on homescreen 

### Expected bahavior

It should be opening camera app without asking for Fingerprint or passcodes

### Your device setup (Please take some time to give correct information here)

- OnePlus 7 pro, PixelExperiance Rom
- Android 13 Beta version - September 5 Security Patch
- Magisk V25.2 Stable - A0SPMods Canary 148 enabled with Lockscreen Shortcut, Miscellaneous Phonecall Vibration activated 
- Root access to AOSPMods, FKM, [SharedUID]Island, PixelLauncher, PixelLauncher Mods, [SharedUID] SystemUI, SolidExplorer, TeMeFi
- AOSPMods Canary 148 and Zygisk LSposed 1.8.4
- GCam_8.1.101_Wichaya_V1.6_Snapcam as System App using TeMeFi v1.1.19, no other camera apps installed. 

### Logs

[LSPosed_2022-10-10T00_15_25.142667.zip](https://github.com/siavash79/AOSPMods/files/9742350/LSPosed_2022-10-10T00_15_25.142667.zip)
[LSPosed_2022-10-10T00_11_06.797271.zip](https://github.com/siavash79/AOSPMods/files/9742351/LSPosed_2022-10-10T00_11_06.797271.zip)
![Screenshot_20221010-000903](https://user-images.githubusercontent.com/9499593/194774190-265dcdc5-1b2e-43e5-9924-7841813cba5d.png)
![Screenshot_20221010-000320](https://user-images.githubusercontent.com/9499593/194774194-5907b239-8208-4cb9-a100-8332fb0a9857.png)

**Comment by EleoXDA** [comment]
Are you able to open GCam_8.1.101_Wichaya_V1.6_Snapcam using double power button click?

**Comment by siavash79** [comment]
Camera shortcut on the lockscreen uses the "secure intent" for camera usage. Meaning it signals the camera app to open the camera without access to the gallery.
This essentially works on stock camera app, and not third party cameras. You can even test this by double pressing the power button, and observing that it won't launch Gcam unless the phone is fully unlocked and not on lockscreen
