### ISSUE TITLE
Add recents and back button to navbar gestures

### ISSUE THREAD

**Issue by NilsSchoovaerts** [siavash79/AOSPMods#392]
Would it be possible to add "back and recents" to the extra navigation gestures -> swipe up action from left/right of navbar. 

This way we can swipe left, right on navbar to go back or open recents menu.

**Comment by NilsSchoovaerts** [comment]
![Screenshot_20221016-130732](https://user-images.githubusercontent.com/15262599/196031874-f139dfc0-4339-45a2-952b-d9deef233c40.png)

**Comment by EleoXDA** [comment]
> Would it be possible to add "back and recents" to the extra navigation gestures -> swipe up action from left/right of navbar. 
> 
> This way we can swipe left, right on navbar to go back or open recents menu. 

These gestures are not for swiping left or right from navbar. Those are gestures upwards. From left bottom to left center and right bottom to right center.

I think you misunderstood the gestures here

**Comment by NilsSchoovaerts** [comment]
> > Would it be possible to add "back and recents" to the extra navigation gestures -> swipe up action from left/right of navbar. 
> > 
> > This way we can swipe left, right on navbar to go back or open recents menu. 
> 
> These gestures are not for swiping left or right from navbar. Those are gestures upwards. From left bottom to left center and right bottom to right center.
> 
> I think you misunderstood the gestures here

I know how the gestures work. I mean that instead of swiping left / right of the screen to go back (how it works on aosp). I would like to swipe up from right bottom of navbar to go back. And swipe up from left bottom of navbar to go into recents. To give you an idea, I think it's how the gestures work on a samsung phone.

**Comment by siavash79** [comment]
I understood his point. As a matter of fact, I'm almost certain he's coming from a Samsung phone, where gesture navigation is like that

**Comment by pritster5** [comment]
I would also love it if you could add the ability to go back via swipe up from left or right part of the bottom side. This would allow for OnePlus style gesture based navigation.

**Comment by xdanvitox** [comment]
Can you also please add an action to turn the screen off? I would love to have the right side swipe up sleep the device.

**Comment by EleoXDA** [comment]
> Can you also please add an action to turn the screen off? I would love to have the right side swipe up sleep the device.

One feature per post please. Open another issue for new suggestion

**Comment by xdanvitox** [comment]
> > Can you also please add an action to turn the screen off? I would love to have the right side swipe up sleep the device.
> 
> One feature per post please. Open another issue for new suggestion

Got it!

**Comment by EleoXDA** [comment]
> > > Can you also please add an action to turn the screen off? I would love to have the right side swipe up sleep the device.
> > 
> > One feature per post please. Open another issue for new suggestion
> 
> Got it!

Already added to latest canary 😄

**Comment by xxz3** [comment]
I'd love it. Basically it's just how OnePlus originally implemented navigation. Back from bottom is so useful, you can use all application's side gestures like browser navigation from sides without gestures overlapping.

https://user-images.githubusercontent.com/16058143/200957074-aad386f0-688c-4972-9adf-1f309b13d954.mp4


https://user-images.githubusercontent.com/16058143/200957918-391b6e6c-fdd5-4668-9a7b-8650a382fa3a.mp4

**Comment by EleoXDA** [comment]
After several trials - seems not possible
