### ISSUE TITLE
Option to un-hide navbar when keyboard is active

### ISSUE THREAD

**Issue by NilsSchoovaerts** [siavash79/AOSPMods#393]
When the hide navbar feature is enabled, the keyboard selection tool and close keyboard button are also hidden when the keyboard is active. The keyboard also appears lower on the screen. Unhiding navbar when the keyboard is active would be a solution. 
![Screenshot_20221016-130531](https://user-images.githubusercontent.com/15262599/196031813-30e08b2b-72be-4069-88ed-f8bae0ee1fe3.png)
![Screenshot_20221016-130622](https://user-images.githubusercontent.com/15262599/196031836-a45e5536-89ad-40d2-9fe4-c0987d4b2016.png)

**Comment by EleoXDA** [comment]
> When the hide navbar feature is enabled, the keyboard selection tool and close keyboard button are also hidden when the keyboard is active. The keyboard also appears lower on the screen. Unhiding navbar when the keyboard is active would be a solution. ![Screenshot_20221016-130531](https://user-images.githubusercontent.com/15262599/196031813-30e08b2b-72be-4069-88ed-f8bae0ee1fe3.png) ![Screenshot_20221016-130622](https://user-images.githubusercontent.com/15262599/196031836-a45e5536-89ad-40d2-9fe4-c0987d4b2016.png)
If hiding navbar is due to protecting screen burn, I would suggest NOT hiding navbar, but decreasing its width to 0%. This way, you will not get screen burn and also will get keyboard and hide button when typing

**Comment by NilsSchoovaerts** [comment]
> > When the hide navbar feature is enabled, the keyboard selection tool and close keyboard button are also hidden when the keyboard is active. The keyboard also appears lower on the screen. Unhiding navbar when the keyboard is active would be a solution.
> 
> If hiding navbar is due to protecting screen burn, I would suggest NOT hiding navbar, but decreasing its width to 0%. This way, you will not get screen burn and also will get keyboard and hide button when typing

The reason to hide the navbar is to maximize screen real estate. Without hiding the navbar and setting width to 0%, makes it technically invisible, but leaves a small grey bar at the bottom of the screen.

**Comment by NilsSchoovaerts** [comment]
> Can you not use this MOD with AOSPMods together?

That's what I did now. Seems to run fine so far.

**Comment by EleoXDA** [comment]
Great then. You can use them together 👍
