### ISSUE TITLE
don't touch qs at all when no option related to it are enabled

### ISSUE THREAD

**Issue by soredake** [siavash79/AOSPMods#395]
What's on your mind? 
It would be nice if aospmods by default would not touch qs at all when no options related to it.

Even when no option related to qs are enabled aospmods adds transition animation to brightness bar, makes it's position wrong and brightness bar doesn't animated correctly.

wrong brightness bar position:
![bug](https://user-images.githubusercontent.com/5204968/196485246-8eb5e1dd-0bf0-46c4-ad40-d76a27431c91.jpg)

Is this feature implemented on any other app/mod/rom? please specify

**Comment by EleoXDA** [comment]
You should not use it on unsupported custom ROMs
