### ISSUE TITLE
[Bug] Keyguard wallpaper dim no longer works

### ISSUE THREAD

**Issue by Jnss98b** [siavash79/AOSPMods#396]
### Describe the issue

I'm not sure if this is an Android 13 thing or the pixel 7 pro being new but the keyguard wallpaper dim slider does not work at all. In the screenshot below I only changed the dim amount once but I've tried many different values, including 0 and 100 and they lockscreen looked the same, even after a systemUI restart or even a reboot.

### Steps to reproduce

1. Open AOSP Mods
2. Tap on Lock Screen
3. Change the keyguard wallpaper dim to any amount other than Default
4. Lock the screen and then turn it back on
5. See no difference in the dimness of the wallpaper at all

https://user-images.githubusercontent.com/24306400/196586026-c3f926a9-c333-462a-8d07-e0a1ba6a5dad.mp4

### Expected bahavior

Keyguard dim slider should either dim the chosen amount or remove wallpaper dimming at 0

### Your device setup (Please take some time to give correct information here)

- Google Pixel 7 Pro
- Stock Android 13 Stable
- October update
- Magisk 25.2 Stable
- LSposed 1.8.4 Zygisk

![image](https://user-images.githubusercontent.com/24306400/196585473-5c24420d-c398-46ed-95c9-869fef41370e.png)
![image](https://user-images.githubusercontent.com/24306400/196585547-8027ee3c-1f14-4024-8d58-0d52f3867b30.png)
![image](https://user-images.githubusercontent.com/24306400/196585585-dd46097f-e59d-4aba-87e7-114d622ac2b7.png)

### Logs

[LSPosed_2022-10-18T22_41_25.141933.zip](https://github.com/siavash79/AOSPMods/files/9816390/LSPosed_2022-10-18T22_41_25.141933.zip)

**Comment by Jnss98b** [comment]
I installed canary to see if it'd fix it but got the same results as before

**Comment by Jnss98b** [comment]
> Works fine here. Stock android 13 pixel 6 latest canary

I want to test a theory. Would you mind setting the keyguard wallpaper dim slider to default and then going to Settings > Digital Wellbeing & parental controls >Bedtime mode > Customize > Screen options at bedtime and enable the Dim the wallpaper option then enable bedtime mode, lock the screen and check to see if the lock screen wallpaper is dim alongside the home screen wallpaper too or just the home screen wallpaper was dimmed?

**Comment by Jnss98b** [comment]
Is this really fixed or you just closed it because you don't wanna deal with it

**Comment by gzyguo** [comment]
> Is this really fixed or you just closed it because you don't wanna deal with it

Can you adjust now?

**Comment by Jnss98b** [comment]
I can but it takes awhile to apply after being adjusted and I still haven't figured out what the deals is

**Comment by gzyguo** [comment]
I have 4 Android devices. 
2 of them are can take effect.
They are all on official LOS21, basically same environment.
1 of them took effect after system OTA, I assumed.

**Comment by EleoXDA** [comment]
> I have 4 Android devices. 2 of them are can take effect. They are all on official LOS21, the 4, basically same environment. 1 of them took effect after system OTA, I assumed.
> 
> Sometimes I see the adjusted effect on Lock screen on regular use but immediately changed back to default status . Like there is another event taken control. Sometimes the security prevent it to apply user settings on lockscreen. just like Windows. After login, the personal user settings like color inversion, night light take effect, that make sense somewhat. But not always behaved the same over long term.
> 
> IMO the toggle of System Settings Multiple User should be the key problem in logic. It let system know that the whole device environment is belong to 1 person, and the only existed user settings should be constant. And perhaps the show sensitive in formation on lock screen should be the 2nd key. It decide how much constant there should be.

we only support pixel stock firmware. no any other ROM/custom ROMs
