### ISSUE TITLE
[Bug] White Clock and Battery

### ISSUE THREAD

**Issue by other909** [siavash79/AOSPMods#400]
### Describe the issue

After some time using white quick panel clock and battery become white. To fix it need to reboot UI.

### Steps to reproduce

![Screenshot_20221019-090800~2](https://user-images.githubusercontent.com/115772733/196812049-53571e05-10c3-40cb-97e2-b617db606279.png)
![Screenshot_20221019-090817~2](https://user-images.githubusercontent.com/115772733/196812053-7338250c-c733-4176-b5b5-15188f94aba0.png)

### Your device setup (Please take some time to give correct information here)

Google Pixel 7 Pro
Stock Firware Android 13
October Security Patch
Magisk 25.2
AOSP Mods stable 2.3.0

**Comment by other909** [comment]
OK, i also will test it.

**Comment by Jnss98b** [comment]
The patch note only said [potential] which means it was just an attempt

**Comment by Jnss98b** [comment]
I just got the bug again this morning lol great timing

![image](https://user-images.githubusercontent.com/24306400/197034017-aefa8f3c-e47d-4873-9ed8-40aa83e364f8.png)

**Comment by other909** [comment]
Yes, i also have this bug after changet to canary.

**Comment by Jnss98b** [comment]
I will say tho now a forced systemUI restart in the app fixes it (temporarily) while before the update I had to reboot my phone to do that
