### ISSUE TITLE
[Feat-Req] Possibility to change vol panel position 

### ISSUE THREAD

**Issue by tanishqmanuja** [siavash79/AOSPMods#401]
Is it possible to add a toggle for volume panel position, because many aosp roms by default have it on right side but some phones have the actual hardware button on left side.

The rom developer builds pure aosp without adding device overlay for "config_audioPanelOnLeftSide".
So this feature will be highly useful for left side volume button phones.

**Comment by siavash79** [comment]
Thanks for the post and derailed explanation.

As of now, our focus is on stock pixel rom and pixel experience official rom.

I'd suggest requesting your custom rom devs to correct the panel position for your device
