### ISSUE TITLE
[Bug] Brightness-leveled flashlight tile has no haptic feedback when the "Vibrate on QS tile tap" option is enabled

### ISSUE THREAD

**Issue by Jnss98b** [siavash79/AOSPMods#402]
### Describe the issue

Like the title said

### Steps to reproduce

1. Open AOSP Mods settings
2. Go to Quick Settings Panel
3. Enable "Vibrate on QS tile tap"
4. Enable Brightness-leveled Flashlight tile
5. Swipe open QS
6. Tap on the flashlight tile and feel no haptic feedback

### Expected bahavior

The flashlight tile should vibrate every time it's tapped

### Your device setup (Please take some time to give correct information here)

- Google Pixel 7 Pro
- Android 13 stable
- October 2022 update
- Magisk 25.2 stable
- LSposed 1.8.4 Zygisk

**Comment by EleoXDA** [comment]
It is by design

**Comment by Jnss98b** [comment]
Well that sucks
