### ISSUE TITLE
[Feat] Remove chevrons from Network Monitor / Reduce clear all apps button size/add text

### ISSUE THREAD

**Issue by xdanvitox** [siavash79/AOSPMods#403]
### What's on your mind?

![Screenshot_20221021-190315](https://user-images.githubusercontent.com/7152711/197312952-26a28b18-4511-41a8-9da3-4e7b137bfe5f.png)

Option to toggle the chevrons on/off in the status bar Network Monitor.

I only use download so I don't need the indicator and like the tidiness of just the text.

Also, the "Clear all" button at the bottom of recents is a little too large. Is it possible to force it to scale to the same size as the other icons? This is on Android 13 Pixel.

It would also be cool if you could add the text "Clear all" to the right to match the other options.

### Is this feature implemented on any other app/mod/rom? please specify

I believe GravityBox used to have the option to toggle the up/down icons and do not believe I've seen the "Clear all" button like this before.

Thank you either way! This module is great.

**Comment by EleoXDA** [comment]
Actually the clear all button is on scale with others. It is the same standard icon that was used for a long time. Afaik clear all text messed up the button layout but we can check if it can be implemented anyway

**Comment by EleoXDA** [comment]
This how it looks on stock pixel firmware. What ROM are you on?

![Screenshot_20221022-090154.png](https://user-images.githubusercontent.com/27622683/197325549-6e0a31f6-d54a-427e-abc0-3cb4a4e5f3b6.png)

**Comment by NilsSchoovaerts** [comment]
It might look more uniform with the rest of the icons if there would be text next to it saying clear?

**Comment by NilsSchoovaerts** [comment]
> can

"Clear" text would defenitely make it look more uniform with the other two icons. Maybe it would be possible to replace the screenshot button with the clear all button? Or something like that?

**Comment by NilsSchoovaerts** [comment]
> Check latest canary
> 
> Since not all languages are as concise as English and for some of them the words "Screenshot" and "Select" can fill whole width of page, the clear all button (with no text) has been moved to middle and right-most position (in addition to clear all button at the middle but left-most position) of recents

![Screenshot_20221025-154308.png](https://user-images.githubusercontent.com/15262599/197790187-3a7c20aa-3864-4c61-9bf7-333aee0948d9.png)

I like the implementation. Would it be possible to have a toggle to disable the left button when the new right one is selected? Two buttons at the end of the recents page looks a bit silly.

**Comment by EleoXDA** [comment]
This how it looks on stock pixel firmware. What ROM are you on?

![Screenshot_20221022-090154.png](https://user-images.githubusercontent.com/27622683/197325549-6e0a31f6-d54a-427e-abc0-3cb4a4e5f3b6.png)

I am not sure what you use, but on stable android 13 for pixel 6 has it on the same height. If you use any theme or whatnot it can interfere.

![Screenshot_20221026-061123.png](https://user-images.githubusercontent.com/27622683/197932754-93564852-2224-4ec8-86ca-2ddfcd084e6e.png)

**Comment by EleoXDA** [comment]
> > Check latest canary
> > 
> > Since not all languages are as concise as English and for some of them the words "Screenshot" and "Select" can fill whole width of page, the clear all button (with no text) has been moved to middle and right-most position (in addition to clear all button at the middle but left-most position) of recents
> 
> ![Screenshot_20221025-154308.png](https://user-images.githubusercontent.com/15262599/197790187-3a7c20aa-3864-4c61-9bf7-333aee0948d9.png)
> 
> I like the implementation. Would it be possible to have a toggle to disable the left button when the new right one is selected? Two buttons at the end of the recents page looks a bit silly. 
> 
> Edit: looking at the screenshot it also seems both buttons are aligned differently

I am not sure what you use, but on stable android 13 for pixel 6 has it on the same height. If you use any theme or whatnot it can interfere.

![Screenshot_20221026-061123.png](https://user-images.githubusercontent.com/27622683/197932754-93564852-2224-4ec8-86ca-2ddfcd084e6e.png)

**Comment by NilsSchoovaerts** [comment]
> > > Check latest canary
> > > 
> > > Since not all languages are as concise as English and for some of them the words "Screenshot" and "Select" can fill whole width of page, the clear all button (with no text) has been moved to middle and right-most position (in addition to clear all button at the middle but left-most position) of recents
> > 
> > ![Screenshot_20221025-154308.png](https://user-images.githubusercontent.com/15262599/197790187-3a7c20aa-3864-4c61-9bf7-333aee0948d9.png)
> > 
> > I like the implementation. Would it be possible to have a toggle to disable the left button when the new right one is selected? Two buttons at the end of the recents page looks a bit silly. 
> > 
> > Edit: looking at the screenshot it also seems both buttons are aligned differently
> 
> I am not sure what you use, but on stable android 13 for pixel 6 has it on the same height. If you use any theme or whatnot it can interfere.
> 
> ![Screenshot_20221026-061123.png](https://user-images.githubusercontent.com/27622683/197932754-93564852-2224-4ec8-86ca-2ddfcd084e6e.png)

Using stable android 13 on pixel 7

**Comment by EleoXDA** [comment]
> Using stable android 13 on pixel 7, without themes

Hi again. Google just released a firmware that we think could be pixel 7 stable firmware. If you can join to our Telegram group (linked in ReadMe of our GitHub page) we are testing fixes for that. Maybe this can also be targeted with other bugs mentioned (as lockscreen dimness) not working on pixel 7.

If you have time we would like to test those fixes with you to release a fix for pixel7 users

**Comment by NilsSchoovaerts** [comment]
> 
> > Using stable android 13 on pixel 7, without themes
> 
> Hi again. Google just released a firmware that we think could be pixel 7 stable firmware. If you can join to our Telegram group (linked in ReadMe of our GitHub page) we are testing fixes for that. Maybe this can also be targeted with other bugs mentioned (as lockscreen dimness) not working on pixel 7.
> 
> If you have time we would like to test those fixes with you to release a fix for pixel7 users

I don't have a telegram account but I can look into it tomorrow. I do use xda though. Happy to help testing where I can.

**Comment by dwarren-upngo** [comment]
I'm on stock Android 13 on Pixel 7 Pro. The icon may have been affected by my display scaling but doesn't even matter now with the new button 🤓

**Comment by xdanvitox** [comment]
I am on stock Android 13 on Pixel 7 Pro. I believe it may have been getting thrown off by my display scaling or something but it doesn't matter now anyway with the new button 🤓

**Comment by xdanvitox** [comment]
Thanks, guys!
