### ISSUE TITLE
[Bug] $Nssid variable isn't working 

### ISSUE THREAD

**Issue by itsboo07** [siavash79/AOSPMods#405]
### Describe the issue

$Nssid variable isn't working and any variable with prefix $N is not working . I use xiaomi pad 5 A13 offical arrow stable (wifi model )

### Steps to reproduce

![Screenshot_20221023-003007_1](https://user-images.githubusercontent.com/87331871/197358094-b4091a60-35da-47d2-8f17-7f2a8bd81d75.png)

### Expected bahavior

I would lile to see it working 

### Your device setup (Please take some time to give correct information here)

- xiaomi pad 5 (Wi-Fi)
- Android 13
- Arrow stable custom rom

**Comment by EleoXDA** [comment]
Please read Wiki for more info:
https://github.com/EleoXDA/AOSPMods/wiki/WikiMODs

It is written what you need to do

**Comment by itsboo07** [comment]
@EleoXDA  Really not sure how the wiki helps in my case ..variable like $Gd works but not $Nssid

**Comment by EleoXDA** [comment]
I see you are on stable afaik. In latest canary we provided the description. So it was removed from wiki. Here is the updated description:
Basically go to Miscellaneous menu and enable network statistics. Done.

![Screenshot_20221022-221258.png](https://user-images.githubusercontent.com/27622683/197360675-2fc5556e-1faa-4e87-96f7-2ba10956f85b.png)

**Comment by itsboo07** [comment]
Thanks ...it worka now ( im in stable)...i have few questions
1) does collecting network statistics with refresh interval of 10 mins consume more battery ?
2) is it possible to you if commands say..if wifi is connected show `Ssid` or else show `No wifi connected`
3) whats the difference between stable and canary?
Sorry for all this questions..just curious

**Comment by EleoXDA** [comment]
Join our telegram group linked in our repo. Questions are answered there. They will be added to Wiki soon as well. But no ETA
