### ISSUE TITLE
Text Battery Options

### ISSUE THREAD

**Issue by AngryManMLS** [siavash79/AOSPMods#406]
The one thing AOSP Mods needs is options for text only battery with extra features available on say circle battery. On my Pixel 7 Pro I can at least have an text only battery in the status bar on the device options itself. However that lacks the extra stuff AOSP Mods like fast charging indicator for instance. So perhaps adding an option for text battery with options such as fast charging indicator would be very helpful. Fast charging indicator for instance can be done either with a graphic to the side of the text battery or having the battery text percentage in a user selected color. Thanks for a great mod this really helps add a number of great features to the stock experience of the Pixel 7 Pro.

**Comment by EleoXDA** [comment]
> The one thing AOSP Mods needs is options for text only battery with extra features available on say circle battery.

How would you imagine it? Please draw a picture. Or even better, show us a custom ROM with open source that already contains that (even more better - show us the commit that did it ;) )

> On my Pixel 7 Pro I can at least have an text only battery in the status bar on the device options itself.

Is it something exclusive to pixel 7? As I dont have it on neither pixel 6 stock pixel firmware android 13 nor pixel 3aXL stock pixel firmware android 12.

> However that lacks the extra stuff AOSP Mods like fast charging indicator for instance. So perhaps adding an option for text battery with options such as fast charging indicator would be very helpful. 

Everything aside, such a text battery would have no battery percentage indication if there is no icon. In circle battery you get a filled/unfilled part in circle which indicates that. If you want to have only text, then it means you will not know how much battery you actually have without checking the QS. This is a very bad user experience. Equivalent to owning an iPhone 😄 

> Fast charging indicator for instance can be done either with a graphic to the side of the text battery or having the battery text percentage in a user selected color. Thanks for a great mod this really helps add a number of great features to the stock experience of the Pixel 7 Pro.

That would mean that you want to have dynamic battery indicator which would get either one or two spots on statusbar depending on charge level and charging/discharging. This would mean that statusbar icons would have to dance around every time depending on that. This is also not very good.

I instead advise you to choose standard battery icon (I do so too). The only difference with your variant is that I get a battery icon near text always. What can be done is, we can try to add a separate battery icon (exactly like stock battery icon+text) but with different color of battery icon when there is fast charging. That could be fun thing to add - add also would provide good user experience.
