### ISSUE TITLE
[Bug] Clock doesn't stay on the right side

### ISSUE THREAD

**Issue by simplepinoi177** [siavash79/AOSPMods#407]
### Describe the issue

I have moved the clock position to the right side, but when I pull down the notification bar, it goes back to the left (only while the notification bar is being pulled down and the tiles can be seen). Here are screenshots: https://imgur.com/Y03BGuY ; https://imgur.com/BZV8TED  

### Steps to reproduce

1. The clock is set to the right side of the screen
2. I pull down the notification bar
3. The clock is now on the left side (as it is stock experience).
-  It stays on the left side while notification bar is down and the tiles are being shown 
4. When I pull the notification bar back up and/or go to the homescreen or enter into an app, it returns back to the modification of the clock placed on the right

### Expected bahavior

The clock should stay on the right side and should not move or switch sides.

### Your device setup (Please take some time to give correct information here)

- Google Pixel 7 Pro Stock Firmware October Security Patch (TD1A.220804.031)

- Android 13 stable version

- October Security Patch; first OTA day-one update

- Magisk 25.2 Stable

- 3G Battery Manager, AOSP Mods, Bring Back NFC Quick Settings, BusyBox, BusyBox, BusyBox Pro, GSam Battery Manager, Lucky Patcher, MacroDroid, Pixel Launcher, Swift Backup, [ShareUID] System UI -- 
![Screenshot_20221022-124407](https://user-images.githubusercontent.com/32727914/197360471-f954cfbb-a5ed-4016-a2eb-ff7fcde26bc2.png) --------------------------------------------------

![Screenshot_20221022-124416](https://user-images.githubusercontent.com/32727914/197360492-02a097e1-6a7f-4358-816e-5447cfc5b807.png)

- AOSP Mods (Full version) 2.3.0, Patches to Android (Lucky Patcher Module) 1.0, Systemless Hosts 1.0, Universal Safetynet Fix 2.3.1, Youtube ReVanced 17.36.37, Zygisk - LSPosed 1.8.4 (6609) -- 
![Screenshot_20221022-125053](https://user-images.githubusercontent.com/32727914/197360547-ef5995de-6e39-48f4-974a-5b68099a7a6c.png) ------------------------------------------------------

![Screenshot_20221022-125113](https://user-images.githubusercontent.com/32727914/197360558-0413f96a-846e-41de-b0c4-f156ee8961c6.png)

- LSPosed 1.8.4 (6609)

- AOSP Mods 2.3.0, Lucky Patcher 10.2.9 -- 
![Screenshot_20221022-125617](https://user-images.githubusercontent.com/32727914/197360566-bf1fab6c-39c9-4700-96c5-1573f86a1994.png)

### Logs

[LSPosed_2022-10-22T13_02_10.980578.zip](https://github.com/siavash79/AOSPMods/files/9845182/LSPosed_2022-10-22T13_02_10.980578.zip)

**Comment by EleoXDA** [comment]
Just checked on pixel 6 with stock 13 firmware, works fine.

**Comment by siavash79** [comment]
That's intended. Moving the clock refers to "status bar", where there's a very limited area available for many elements.

When pulling down the notification shade, you're watching the "quick settings header", and not the status bar anymore. Over there, there's a generous amount of space available, and we really don't need to change the design

**Comment by EleoXDA** [comment]
> That's intended. Moving the clock refers to "status bar", where there's a very limited area available for many elements.
> 
> When pulling down the notification shade, you're watching the "quick settings header", and not the status bar anymore. Over there, there's a generous amount of space available, and we really don't need to change the design

As far as I understood, he says the clock on statusbar moves from right side to left side after you pull down QS and then pull it up. So, he doesnt mean the clock in QS but actually the clock in statusbar before and after pulling down QS and pulling up

**Comment by siavash79** [comment]
`(only while the notification bar is being pulled down and the tiles can be seen)`

This is his exact wording

**Comment by simplepinoi177** [comment]
I apologize...I may be getting confused as to what is referred to as "status bar", "notification bar", "notification shade", or "quick settings header" and may have thought they are all the same...

In any case, I had thought that the mod to place the clock to the right side would be persistently remain on the right side, regardless of whether it is simply on the notification bar or any other situation; which is why I may have mistakenly believed this to be a bug situation.
If possible and not too much trouble, I would request it to do just that, or to have an additional option to keep it persistently on the right side under any/all situations.

I appreciate the attention on this.

**Comment by simplepinoi177** [comment]
> `(only while the notification bar is being pulled down and the tiles can be seen)`
> 
> This is his exact wording

I apologize...I may be getting confused as to what is referred to as "status bar", "notification bar", "notification shade", or "quick settings header" and may have thought they are all the same...

In any case, I had thought that the mod to place the clock to the right side would be persistently remain on the right side, regardless of whether it is simply on the notification bar or any other situation; which is why I may have mistakenly believed this to be a bug situation.
If possible and not too much trouble, I would request it to do just that, or to have an additional option to keep it persistently on the right side under any/all situations.

I appreciate the attention on this.
