### ISSUE TITLE
[Bug] Brightness animation laggy

### ISSUE THREAD

**Issue by itsboo07** [siavash79/AOSPMods#408]
### Describe the issue

Brightness animation slider is laggy like the one i shared below but system settings animation is smooth . Also without asop mod flashed animation was perfect.

### Steps to reproduce

1. Open notification panel
2. Adjust brightness by sliding right or left

### Expected bahavior

I would like to see the animation smooth 

### Your device setup (Please take some time to give correct information here)

- Xiaomi pad 5 Arrow stable Android 13 custom rom( release 22-10-2022)
- Magisk verison:  25.2-delta(25200)
- List of magisk modules: ASOP mods, Universal safety net fix(zygisk), Zygisk-LSPosed
- LSPosed version: 1.8.4(6609)

### Logs

Animation bug:
![ezgif-5-06d0cda45d](https://user-images.githubusercontent.com/87331871/197362661-750da2b1-27a1-43ea-9a5b-14302ab15c3d.gif)

Animation in system settings:(to prove it's not a rom bug)
![ezgif-5-bab60677d2](https://user-images.githubusercontent.com/87331871/197362780-8c34612f-ab64-4840-83c4-3b929cd4e63d.gif)

**Comment by EleoXDA** [comment]
Arrow OS is buggy and not supported since day 1

**Comment by itsboo07** [comment]
I dont use any of the brightness features ...is it possible to have a stock brightness toolbar instead of asop mod?
Because stock slider works fine ...

**Comment by EleoXDA** [comment]
Switch to a supported ROM. We cannot support ROMs that have changed AOSP source code that much. We can only support stock pixel firmware and pixel experience ROMs.
