### ISSUE TITLE
[Bug] Dynamic Build number in QS Panel footer

### ISSUE THREAD

**Issue by SachinKarinki** [siavash79/AOSPMods#409]
### Describe the issue

Dynamic Build number in QS Panel footer is not working, instead of value its showing the words which I entered. Please check attachments

### Steps to reproduce

1. Open AOSP Mods.
2. Open "Quick Settings Panel" section.
3. Enable "Modify build text number in QS panel" option from "Build number in QS Panel footer" section.
4. Open "Enter custom text"
5. Enter this "Usage : $Ncall | $Nall" and press ok.
6. Now turn off the screen and turn on the screen.
7. Instead of getting the output as "Usage : Wifi_Usage_GB | Mobile_data_GB" , The actual output i got is "Usage: Ncall | Nall".

![Screenshot_20221025-064918_AOSP Mods_1](https://user-images.githubusercontent.com/48996479/197665624-19abe5ce-ae83-4342-b833-edc9bbc49fcf.png)
![Screenshot_20221025-064910_AOSP Mods_1](https://user-images.githubusercontent.com/48996479/197665631-2d42a0eb-c053-45ce-9d62-89d5bc733c0f.png)

### Expected bahavior

The output should be like : "Usage: 30GB | 1GB

### Your device setup (Please take some time to give correct information here)

• Poco X3 Pro (Code Name : Vayu)
• Android 12L
• Pixel Experience Plus
• Build Date : 13 August 2022
• 5 August 2022
• SQ3A.220705.004 PixelExperience_Plus_vayu-12.1-20220813-2256-OFFICIAL
• Magisk 25.2

• List of Root granted apps : 

![Screenshot_20221025-071323_Andy](https://user-images.githubusercontent.com/48996479/197665282-7f962377-5d5e-4f3f-8746-1a6978d6520a.png)

• Magisk version screenshot : 

![Screenshot_20221025-071602_Andy](https://user-images.githubusercontent.com/48996479/197665342-ed9b4ade-09ef-44ae-99d0-44333781fe85.png)

• Magisk modules list screenshot: 

![Screenshot_20221025-071632_Andy](https://user-images.githubusercontent.com/48996479/197665370-b6cfa09f-b843-48c3-928d-0434cfd00596.png)

• Lsposed version screenshot : 

![Screenshot_20221025-071427_Shell](https://user-images.githubusercontent.com/48996479/197665409-1baff4a9-fd6d-4b99-a86e-4568e7dc39bf.png)

• Lsposed Modules screenshot: 

![Screenshot_20221025-071332_Shell](https://user-images.githubusercontent.com/48996479/197665471-c822edfb-e8bd-4dce-90c7-b2cabac4f4c5.png)

### Logs

Lsposed Logs :

[LSPosed_2022-10-25T07_30_50.348.zip](https://github.com/siavash79/AOSPMods/files/9856553/LSPosed_2022-10-25T07_30_50.348.zip)

**Comment by siavash79** [comment]
Please read the manual again

You've got to enable network statistics in misc settings for N variables to work
