### ISSUE TITLE
[Bug] Taskbar settings non functional

### ISSUE THREAD

**Issue by 1RandomDev** [siavash79/AOSPMods#411]
### Describe the issue

Apparently non of the taskbar settings work. Setting it to forced enabled doesn't do anything and if I enable it in the system settings the rest of the customisations doesn't do anything.

### Steps to reproduce

Change any of the taskbar related options in "Navigation bar", restart and see that everything stayed the same.

### Expected bahavior

Be able to enable/disable the navbar, show recent apps and change the height and curve radius.

### Your device setup (Please take some time to give correct information here)

- Galaxy Tab S6 Lite with LineageOS 19.1
- AOSP Mods 2.3.0 Full

**Comment by EleoXDA** [comment]
LOS is not supported BECAUSE it does NOT have pixel launcher which is CRUCIAL for taskbar

**Comment by 1RandomDev** [comment]
Ok didn't knew that the taskbar is provided by the launcher. But why can't it be implemented to the LineageOS launcher. I can't imagine that the taskbar from LOS is that different from the Google one.

**Comment by EleoXDA** [comment]
It is. You can check the source codes and even see how we make taskbar to appear - thereby you will see why trebuchet (or whatever the LOS launcher name is) is incompatible

**Comment by 1RandomDev** [comment]
Ok thats really unfortunate. And there's really no chance of Trebuchet being supported oo in ner future?

**Comment by EleoXDA** [comment]
> Ok thats really unfortunate. And there's really no chance of Trebuchet being supported too in near future?

There is no chance for Trebuchet to be supported...

BUT, there is a chance that you can replace the inbuild launcher with Pixel Launcher MOD (by TeamFiles developers - you can reach to them through their website and Telegram support group of TeamFiles). That is a magisk module that changes the inbuilt launcher with Pixel Launcher and this way you can use LOS with AOSPMods and still have taskbar (and other pixel launcher MODs of AOSPMods).

For more information, please google it.

**Comment by EleoXDA** [comment]
> Ok but the pixel launcher is proprietary and probably sends data to Google :/

Android is proprietary. You should use microG if you are afraid of it - and then the microG people can access your data. Choose wisely. Anyways, topic closed
