### ISSUE TITLE
Bootlooping on Zenfone 8

### ISSUE THREAD

**Issue by Stefano-Panzeri** [siavash79/AOSPMods#412]
Hi,
first of all, thanks for making AOSPMods!
I've attempted to install AOSPMods on my ASUS Zenfone 8 with Android 12.
I have Magisk installed, with LSposed for Zygisk. As ZenUI is not much different from AOSP, I've tried to install AOSPMods on my phone as explained in the guide, but unfortunately it caused a bootloop. 
I recovered the phone using TWRP, deleting the AOSPMods module folder.
Even tough the developers may not want to spend time supporting roms different from pure AOSP, I think it would be a good idea to have a list of devices that are known to bootloop with AOSPMods, just for people to know that if they want to try to install it they should have TWRP ready to recover the phone because it will very likely bootloop.

**Comment by EleoXDA** [comment]
Zenfone IS much different than AOSP and was never supported

Same is MotoUI, OneUI, or ANY other "AOSP" from manufacturer. None of them is supported.
