### ISSUE TITLE
[Bug] Hiding Gesture Navigation Bar also hides Keyboard Space

### ISSUE THREAD

**Issue by UltraHQ** [siavash79/AOSPMods#414]
### Describe the issue

When the navigation bar is hidden, it also hides the keyboard space at the bottom with the option to hide the keyboard
### Steps to reproduce

1. Enable Hide Navigation bar

(Not my picture, taken from Google) This space gets hidden, which is bad, especially if you're used to the keyboard position. Optionally add the setting to decide, whether you want to remove it too
![Unbenannt](https://user-images.githubusercontent.com/35925402/198851766-ff2eb77c-6933-4a2a-aead-883d61957a01.png)

### Expected bahavior

Only hide bottom pill

### Your device setup (Please take some time to give correct information here)

- Google Pixel 7
- Android 13

**Comment by EleoXDA** [comment]
Use this:
https://github.com/siavash79/AOSPMods/issues/393#issuecomment-1280377412

**Comment by EleoXDA** [comment]
Also, this is not a bug report. What you want to do is a feature request.

**Comment by UltraHQ** [comment]
> Use this: [#393 (comment)](https://github.com/siavash79/AOSPMods/issues/393#issuecomment-1280377412)

Problem with this is, it shows a small white space in some apps like WhatsApp. Author said in an issue Ticket, that it's not fixable, as it's the gcam lag fix which is necessary.

So AOSPmods is the only module, which can hide the bottom pill without any issues.

I did see it as a bug, because I think the keyboard space doesn't count under gesture.

**Comment by EleoXDA** [comment]
If we include it in AOSPMods it will have same gcam lag and will have same white space in whatsapp.

You have two choices: either DONT hide navbar but decrease the navbar width to 0% so that it is not visible
OR
hide navbar and get no "button to hide keyboard"

You can hide keyboard with back gesture as well.

Suit yourself

**Comment by UltraHQ** [comment]
> If we include it in AOSPMods it will have same gcam lag and will have same white space in whatsapp.
> 
> You have two choices: either DONT hide navbar but decrease the navbar width to 0% so that it is not visible OR hide navbar and get no "button to hide keyboard"
> 
> You can hide keyboard with back gesture as well.
> 
> Suit yourself

Makes sense, thanks for the explanation.
But can't you change the transparency of the black bottom bar to 0%? When decreasing the navbar width.
This could also maybe fix the problem

> You can hide keyboard with back gesture as well.
For me, it's not about the hide button. It's the position of the keyboard, because it's normally a bit higher, and I'm used to it.

**Comment by EleoXDA** [comment]
> Makes sense, thanks for the explanation.
> But can't you change the transparency of the black bottom bar to 0%? When decreasing the navbar width.
> This could also maybe fix the problem
It is not black all the time. It depends on the current app's theme color. If you are using keyboard, it depends on keyboard color theme. Making it transparent will remove the theme abilities. E.g. I am writing with white theme and navbar region is white. If I write with black theme on keyboard, it becomes black.

Same for the app themes. If I use an app with dark theme, navbar is dark. If I use app with light theme, it is light colored.

So it doesn't make sense to make it transparent. It is already optimized for several theme options and colors xml of the app bar colors

**Comment by UltraHQ** [comment]
> > Makes sense, thanks for the explanation.
> > But can't you change the transparency of the black bottom bar to 0%? When decreasing the navbar width.
> > This could also maybe fix the problem
> 
> It is not black all the time. It depends on the current app's theme color. If you are using keyboard, it depends on keyboard color theme. Making it transparent will remove the theme abilities. E.g. I am writing with white theme and navbar region is white. If I write with black theme on keyboard, it becomes black.
> 
> Same for the app themes. If I use an app with dark theme, navbar is dark. If I use app with light theme, it is light colored.
> 
> So it doesn't make sense to make it transparent. It is already optimized for several theme options and colors xml of the app bar colors

I understand, but what I'm trying to achieve is hiding it completely. Right now, with decreasing the navbar width to 0% I have a bar at the bottom, which may changes it color depending on the app. But I don't want it at all, because there's no pill anymore

**Comment by mingaldrichgan** [comment]
OP, as an alternative, use
https://github.com/Magisk-Modules-Alt-Repo/HideNavBar instead and select
Immersive mode. That's what I've been using (in conjunction with AOSPMods)
and I think it's exactly what you're looking for.

**Comment by EleoXDA** [comment]
@mingaldrichgan I have already have [advised it to him](https://github.com/siavash79/AOSPMods/issues/414#issuecomment-1296102064) but for some reason [it does not work for him well](https://github.com/siavash79/AOSPMods/issues/414#issuecomment-1296138465)

**Comment by mingaldrichgan** [comment]
Sorry I missed that part of the conversation! Thank you for your hard work on this project by the way. Much appreciated.

**Comment by boehs** [comment]
Same issue. I use the linked module which I like because of the customization, gcam lags. I reinstalled with gcam fix, and noticed that the keyboard had no space, so I ran `sudo -c hn` to adjust, which fixed it but gcam is back to lagging. So then I try this mod which is nice because it works without reboot, no gcam lag, but keyboard is so low!

I don't understand why this issue occurs. What is wrong with gcam? Is there absolutely no workaround?

**Comment by EleoXDA** [comment]
> Same issue. I use the linked module which I like because of the customization, gcam lags. I reinstalled with gcam fix, and noticed that the keyboard had no space, so I ran `sudo -c hn` to adjust, which fixed it but gcam is back to lagging. So then I try this mod which is nice because it works without reboot, no gcam lag, but keyboard is so low!
> 
> I don't understand why this issue occurs. What is wrong with gcam? Is there absolutely no workaround?

https://github.com/siavash79/AOSPMods/issues/414#issuecomment-1296150518

**Comment by humanplayer2** [comment]
I apologize that this is off topic, but could you tell me where the Hide Navigation bar option is? I can't find it in 2.3.0.

**Comment by mingaldrichgan** [comment]
> I apologize that this is off topic, but could you tell me where the Hide Navigation bar option is? I can't find it in 2.3.0.

Which version are you using? This option is only available in the "Full" version. (I think it's under "Navigation bar" -> "Gesture navigation" but I'm using the "Lite" version so I can't confirm that.)

**Comment by humanplayer2** [comment]
I'm on Full, and Android 13, Pixel 7. For the love of me, I can't find it..

**Comment by humanplayer2** [comment]
> > I apologize that this is off topic, but could you tell me where the Hide Navigation bar option is? I can't find it in 2.3.0.
> 
> Which version are you using? This option is only available in the "Full" version. (I think it's under "Navigation bar" -> "Gesture navigation" but I'm using the "Lite" version so I can't confirm that.)

I'm on Full, and Android 13 on a Pixel 7. For the love of me, I can't find it.

**Comment by EleoXDA** [comment]
> > Which version are you using? This option is only available in the "Full" version. (I think it's under "Navigation bar" -> "Gesture navigation" but I'm using the "Lite" version so I can't confirm that.)
> 
> I'm on Full, and Android 13 on a Pixel 7. For the love of me, I can't find it.
> 
> Edit: I'm guessing it's a bug. [This is not what I see](https://github.com/siavash79/AOSPMods/issues/367#issue-1384459080): Both toggles are missing for me.

Share screenshots of main AOSP page, then Navigation bar menu as shown in my screenshots below:
![Screenshot_20221106-100722](https://user-images.githubusercontent.com/27622683/200162721-b89c9ad3-d59f-435b-8b60-6ccc52e8ab5e.png)
![Screenshot_20221106-100724](https://user-images.githubusercontent.com/27622683/200162724-b176b8f7-c4fa-40fe-9dea-174777c75b0e.png)
