### ISSUE TITLE
System Ui crashing

### ISSUE THREAD

**Issue by wowkazmir** [siavash79/AOSPMods#415]
Upon successfully unlocking my device with the correct pin the system ui crashes, the screen goes black and takes me back to the lock screen in turn locking the phone again. Using a pixel 7 here with the easy unlock option enabled.

**Comment by EleoXDA** [comment]
Answer all the questions in the bugreport. Obviously whatever you wrote is not reproducible in other pixel7 users. Create a new bugreport issue and answer all the questions as asked

![Screenshot_20221030-052343.png](https://user-images.githubusercontent.com/27622683/198862491-142bee6d-28e8-45be-977a-22b8e738ad09.png)
![Screenshot_20221030-052244.png](https://user-images.githubusercontent.com/27622683/198862500-43d7ebbb-b69c-47d2-8a25-295f45479b39.png)

**Comment by EleoXDA** [comment]
I am guessing that you no longer want to report this issue

**Comment by wowkazmir** [comment]
Hi there,

While the issue still exists, I realized I was running the latest Android 13 QPR1 Beta 3 build when reporting about it.

Fortunately, when reverting to the latest stable build everything seems to work well.

Thanks for all your support and effort!

**Comment by EleoXDA** [comment]
Perfekt 😍
