### ISSUE TITLE
[Bug] hold power for flash gesture turns on the screen 

### ISSUE THREAD

**Issue by Vlout** [siavash79/AOSPMods#416]
### Describe the issue

title, minor inconvenience 

### Steps to reproduce

1. hold power
2. look at the screen turn on along with flash

### Expected bahavior

screen not turning on

### Your device setup (Please take some time to give correct information here)

![Screenshot_20221030-225506_Shell](https://user-images.githubusercontent.com/115418854/198892437-1ff3678a-7cb2-458b-b5aa-8df5f629e8e2.png)
![Screenshot_20221030-225501_Shell](https://user-images.githubusercontent.com/115418854/198892440-cecf2629-920e-4a2d-b660-26e6186f7e3c.png)
![Screenshot_20221030-225437_Shell](https://user-images.githubusercontent.com/115418854/198892441-cf0ea1d8-88e5-4b22-92a5-a9614439af8a.png)
![Screenshot_20221030-225411_Magisk](https://user-images.githubusercontent.com/115418854/198892442-f7eee0fa-35cf-456b-897f-c5c34c9b9ae3.png)
![Screenshot_20221030-225345_Magisk](https://user-images.githubusercontent.com/115418854/198892443-c7310e71-6868-417c-ba10-93751cc6e1fd.png)
![Screenshot_20221030-225325_Settings](https://user-images.githubusercontent.com/115418854/198892444-e4d26676-627a-45b9-b409-19e45c2b3b5a.png)

### Logs

 Nothing in log
[LSPosed_2022-10-30T22_57_34.786181.zip](https://github.com/siavash79/AOSPMods/files/9896410/LSPosed_2022-10-30T22_57_34.786181.zip)

**Comment by EleoXDA** [comment]
Please check out previous issues before opening new one. This was already discussed and explained why it behaves like that.
