### ISSUE TITLE
[Bug] Volume buttons don't change volume with screen off and long press to skip music

### ISSUE THREAD

**Issue by xdanvitox** [siavash79/AOSPMods#422]
### Describe the issue

While media is playing and the "Long press Volume buttons to skip music" option in on, the buttons no longer function on normal presses to turn the volume up or down.

### Steps to reproduce

1. Enable "Long press Volume buttons to skip music" in AOSP Mods
2. Starting playing music
3. Turn off the screen
4. Press volume up and/or down and the volume will not change
5. !! Volume buttons do function as intended when the option in turned off in AOSP Mods !!

### Expected bahavior

Volume keys should function as normal on short presses and turn the volume up and down and skip music on long presses.

### Your device setup (Please take some time to give correct information here)

- Google Pixel 7 Pro
- Android 13
- October 5, 2022 security update, TD1A.220804.031 build
- Magisk 25.2
![Screenshot_20221104-142039](https://user-images.githubusercontent.com/7152711/200077262-a9ef9959-61a0-401f-b0ff-103503f79e3b.png)
![Screenshot_20221104-142152](https://user-images.githubusercontent.com/7152711/200077271-fcae5ecb-54c0-4f81-8307-922daabb824e.png)

- LSposed 1.8.4
![Screenshot_20221104-142251](https://user-images.githubusercontent.com/7152711/200077363-86486b6b-c4ca-48c0-a854-f5083a43658d.png)

### Logs

Can't seem to get clean logs. When I clear and try to reproduce, they are blank.

**Comment by siavash79** [comment]
That's intended to avoid unwanted volume change while changing tracks. You can change volume when the screen is on

**Comment by xdanvitox** [comment]
Ahh, I see. That makes sense. Thank you!
