### ISSUE TITLE
[Feat] Add screen off/lock action to gesture bar left/right swipe up

### ISSUE THREAD

**Issue by xdanvitox** [siavash79/AOSPMods#423]
### What's on your mind?
Please add an action to the gesture bar left/right swipe up options to sleep the device

### Is this feature implemented on any other app/mod/rom? please specify
A number of third-party gesture apps, some kernels, older system-wide xposed modules such as GravityBox, etc. offer a screen-off action via a gesture and I'm missing it a lot now that I don't have it again :) (without having to run a separate app or flash a kernel)

**Comment by siavash79** [comment]
Navbar swipe to the side is reserved for app switch. It's not logical to disable the original behavior.

I'd suggest using third party apps like FNG which is able to trigger actions on side vertical gestures. Currently I'm also using it to turn off my screen

**Comment by siavash79** [comment]
However, we do have navbar swipe up actions (without side swipe), which can include screen off action as well

**Comment by xdanvitox** [comment]
Oh, no this is what I meant and thank you so much for adding it and the volume change!
