### ISSUE TITLE
[Bug] "Hide Navigation Bar" and "Convert Taskbar to Recents" missing on Android 13, Pixel 7.

### ISSUE THREAD

**Issue by humanplayer2** [siavash79/AOSPMods#424]
### Describe the issue

The "Hide Navigation Bar" and "Convert Taskbar to Recents" toggles are missing from "Navigation Bar" menu

### Steps to reproduce

1. On stock Pixel 7 Android 13, install LSPosed 1.8.4 and AOSP Mods Full 2.3.0
2. See that e.g. brightness on QQS works.
3. On main menu, click "Navigation bar"
4. See that only "Gesture navigation", "3-Button navigation" and "Android taskbar" are shown.
5. Compare to [this screenshot](https://github.com/siavash79/AOSPMods/issues/367#issue-1384459080) and conclude that "Hide navigation bar" and "Convert Taskbar to recents bar" are missing.

### Expected bahavior

That "Hide navigation bar" and "Convert Taskbar to recents bar" show.

### Your device setup (Please take some time to give correct information here)

- Google Pixel 7 Stock Firmware October Security Patch
- Magisk v25.2 stable
- AOSPMods 2.3.0 Full, LSPosed 1.8.4, InitiRcHider, Systemless hosts, Universal SecurityNet Fix (v.2.3.1, modded by Displax)

**Comment by EleoXDA** [comment]
https://github.com/siavash79/AOSPMods/issues/414#issuecomment-1304752674

**Comment by EleoXDA** [comment]
Also, always fill in all information requested from bugreports, where logs are one of the vital stuff to be shared

**Comment by siavash79** [comment]
To hide the navbar you need to install the full version

For the recents bar you must Force enable taskbar first

**Comment by humanplayer2** [comment]
> Also, always fill in all information requested from bugreports, where logs are one of the vital stuff to be shared. If you open a new bugreport, you will see how easy it is to share logs

Ok, will do. It said "If possible", and as I was on my PC with nothing but Magisk installed on that phone, I took optionality at face value.

**Comment by humanplayer2** [comment]
> To hide the navbar you need to install the full version
> 
> For the recents bar you must Force enable taskbar first 

Thank you for the reply.

I did install the full version.

**Comment by humanplayer2** [comment]
I don't know what went wrong the first time, but now I factory reset the phone and re-installed the same files: First Magisk, then rebooted, then LSPosed, rebooted, then AOSP Mods, rebooted.  Now AOSP Mods loads quickly where before it loaded for 30+ sec., and "Hide navigation bar" shows. I apologize for wasting your time.

**Comment by EleoXDA** [comment]
Just for fun, I wonder what is "initirchider" in your modules list

**Comment by humanplayer2** [comment]
> Just for fun, I wonder what is "initirchider" in your modules list 

Without the typo I introduced (sorry), it's [InitRcHider, see here](https://forum.xda-developers.com/t/module-initrchider.4369285/).
