### ISSUE TITLE
Add circular to icon shapes

### ISSUE THREAD

**Issue by AdeeGaming01** [siavash79/AOSPMods#425]
This would be a great QoL addition to those running OOS 12, COS 12 or other heavily modified OSs that might not have circular icons by default

**Comment by EleoXDA** [comment]
Themes and icon packs included in AOSPMods are not maintained anymore. They are presented "AS IS", and will not be updated to add new icon packs/themes

**Comment by EleoXDA** [comment]
And BTW, oos is not even supported and testers had huge issues on oos and other heavily modified OSs. 

This is only supported on:
- Pixel Experience ROMs (normal and plus)
- Stock pixel firmware
