### ISSUE TITLE
[Bug] Signal Icons Theme (non-default) causes .gms.persistent logcat spam

### ISSUE THREAD

**Issue by hyproman** [siavash79/AOSPMods#427]
### Describe the issue

Enabling a non-default Themes->Signal Icons Theme setting causes .gms.persistent logcat error spam; I/O error reading the APK(s) of the enabled theme. For example, with Xperia theme enabled, the log messages are:

`E .gms.persistent: Failed to open APK '/product/overlay/AOSPMods_XperiaSignal/XperiaSignalOverlay.apk': I/O error`
`E .gms.persistent: Failed to open APK '/product/overlay/AOSPMods_XperiaWiFi/XperiaWiFiOverlay.apk': I/O error.`

These messages repeat many many times per "event", where each "event" depends on user interaction with the phone (presumably related to status bar icon updates? Unclear). Selecting the default icon theme mutes these errors.

### Steps to reproduce

1. Start tailing the log for errors: `adb logcat '*:S .gms.persistent'`
2. Open AOSPMods, navigate to Themes -> Signal Icons Theme, and choose a theme (I have tried Xperia and Sneaky so far; both have reproduced the issue)
3. Close AOSPMods and navigate around the phone a little (if all else fails, load Google Maps, but this is not required)
4. Observe logcat output, spamming many error messages regarding "I/O error" trying to read from "/product/overlay/AOSPMods_<theme>/<the apk file>"

### Expected bahavior

Expected no logcat error messages, as is such when running with no Signal Icons Theme enabled.

### Your device setup (Please take some time to give correct information here)

- Google Pixel 6 Stock Firmware Build TPA.221005.002
- Android 13
- AOSPMod (Full) canary-162
- LSPosed 1.8.4
- Magisk 25.2 stable
- Zygist enabled; enforcing DenyList (to pass SafetyNet, Play Protect, etc)

Other Magisk Modules Enabled:
- Advanced Charging Controller
- Busybox for Android NDK
- CloudflareDNS4Magisk
- Magiskhide Props Config
- NoStorageRestrict
- Systemless Hosts
- Universal SafetyNet fix
- Zygist - LSPosed

**Comment by hyproman** [comment]
Curious observation: without theming enabled, at least when Location Services is being used (e.g. Google Maps open), there exists a Location status bar icon. However, with theming enabled, no themed Location status bar icon is visible. Could it be that the theme apks do not contain a Location icon, and that is what Google's location services is complaining about? Unclear to me.

**Comment by EleoXDA** [comment]
> ### Describe the issue
> 
> Enabling a non-default Themes->Signal Icons Theme setting causes .gms.persistent logcat error spam; I/O error reading the APK(s) of the enabled theme. For example, with Xperia theme enabled, the log messages are:
> 
> `E .gms.persistent: Failed to open APK '/product/overlay/AOSPMods_XperiaSignal/XperiaSignalOverlay.apk': I/O error`
> `E .gms.persistent: Failed to open APK '/product/overlay/AOSPMods_XperiaWiFi/XperiaWiFiOverlay.apk': I/O error.`
> 
> These messages repeat many many times per "event", where each "event" depends on user interaction with the phone (presumably related to status bar icon updates? Unclear). Selecting the default icon theme mutes these errors.
> 
> ### Steps to reproduce
> 
> 1. Start tailing the log for errors: `adb logcat '*:S .gms.persistent'`
> 2. Open AOSPMods, navigate to Themes -> Signal Icons Theme, and choose a theme (I have tried Xperia and Sneaky so far; both have reproduced the issue)
> 3. Close AOSPMods and navigate around the phone a little (if all else fails, load Google Maps, but this is not required)
> 4. Observe logcat output, spamming many error messages regarding "I/O error" trying to read from "/product/overlay/AOSPMods_<theme>/<the apk file>"
> 
> ### Expected bahavior
> 
> Expected no logcat error messages, as is such when running with no Signal Icons Theme enabled.
> 
> ### Your device setup (Please take some time to give correct information here)
> 
> - Google Pixel 6 Stock Firmware Build TPA.221005.002
> - Android 13
> - AOSPMod (Full) canary-162
> - LSPosed 1.8.4
> - Magisk 25.2 stable
> - Zygist enabled; enforcing DenyList (to pass SafetyNet, Play Protect, etc)
> 
> Other Magisk Modules Enabled:
> - Advanced Charging Controller
> - Busybox for Android NDK
> - CloudflareDNS4Magisk
> - Magiskhide Props Config
> - NoStorageRestrict
> - Systemless Hosts
> - Universal SafetyNet fix
> - Zygist - LSPosed
> 
> 
> ### Logs
> 
> _No response_

You report log spam without sharing logs. Please share logs. Those are vital especially when we cannot replicate your issue

**Comment by EleoXDA** [comment]
> Curious observation: without theming enabled, at least when Location Services is being used (e.g. Google Maps open), there exists a Location status bar icon. However, with theming enabled, no themed Location status bar icon is visible. Could it be that the theme apks do not contain a Location icon, and that is what Google's location services is complaining about? Unclear to me.


Themes and icon packs included in AOSPMods are not maintained anymore. They are presented "AS IS", and will not be updated to add new icon packs/themes

If you like it, use it. But there will be no support regarding them

**Comment by hyproman** [comment]
@EleoXDA So can you reproduce it or not?

I looked at the LSPosed logs, and they don't say anything interesting. I listed the magisk modules I'm running; I hope you'd agree that none of them have anything to do with UI theming or anything remotely related. Also literally the only reason I have LSPosed is for AOSPMods.

Given your comment and the fact that you've already closed this bug (which is fine by me; I'm very happy with AOSPMods otherwise) then there's certainly no point in me jumping through hoops to provide more information, correct?

Anyway, thanks for your time and effort. This module makes A12+ manageable.
