### ISSUE TITLE
Add a volume bar

### ISSUE THREAD

**Issue by nullllfire** [siavash79/AOSPMods#429]
Add a volume bar in the quick settings panel as the brightness bar.
It is a feature that I liked in iOS but in Android I have not seen that they implement it.

![Screenshot_20221108-010343.png](https://user-images.githubusercontent.com/115514963/200500124-794f9f70-3032-4042-826b-af7a029e1db8.png)
![Picsart_22-11-08_01-22-41-184.jpg](https://user-images.githubusercontent.com/115514963/200500148-207945dd-dcdb-4181-a3b5-8fde33db645a.jpg)

Something like that.

**Comment by EleoXDA** [comment]
Not useful. Use volume buttons instead. You have them at sides of your phone

**Comment by ProtoSharkk** [comment]
This could be useful for people who have their volume buttons mapped to do other things or whose volume buttons are broken/don't work.

**Comment by EleoXDA** [comment]
> This could be useful for people who have their volume buttons mapped to do other things or whose volume buttons are broken/don't work.

they can find lots of 3rd party apps.
