### ISSUE TITLE
Hide arrow

### ISSUE THREAD

**Issue by nullllfire** [siavash79/AOSPMods#430]
Customize back gesture.

Don't show back gesture arrow.

It's visually annoying.

![Screenshot_20221108-025717~2.png](https://user-images.githubusercontent.com/115514963/200522392-dd16a357-a3b0-4a9b-8b23-c299710d96c5.png)

**Comment by EleoXDA** [comment]
It is intended to give you point that you are moving back now. It is SUPER useful especially when using gestures inside an app so that you can revert the back gesture if you don't want to exit app.

This is UX 101
