### ISSUE TITLE
I don't see this option

### ISSUE THREAD

**Issue by nullllfire** [siavash79/AOSPMods#431]
### Describe the issue

I don't see this option in the aplication. Forgot to add it?  o Where is that option?

### Steps to reproduce

![Picsart_22-11-08_03-39-51-576](https://user-images.githubusercontent.com/115514963/200531172-d9b28b02-566c-4b7b-ad34-6d21f47ca59a.png)

### Your device setup (Please take some time to give correct information here)

Moto G60 - Android 13 - Custom Rom PixelExperience Unofficial -  TP1A.220905.004
PixelExperience_hanoip-13.0-BETA-20220930-1231-UNOFFICIAL - Magisk 25.2 - LSposed 1.8.4

![Screenshot_20221108-035201](https://user-images.githubusercontent.com/115514963/200534058-e04cebf2-0d93-47d4-bc01-db1aefcfad58.png)
![Screenshot_20221108-035126](https://user-images.githubusercontent.com/115514963/200534061-052a2669-cfed-4084-8940-d4c8e0d6a920.png)

**Comment by EleoXDA** [comment]
This is not an option, but feature. For more information, head to our support group in telegram. It is linked in ReadMe file
