### ISSUE TITLE
[Feature request] Option to disable QS panel when the device is locked

### ISSUE THREAD

**Issue by xxz3** [siavash79/AOSPMods#433]
I think this is a mayor lack in stock Pixel Rom and a security issue. Do you think is it possible to add this feature?

**Comment by EleoXDA** [comment]
It is not security issue because toggles are not clickable without secure sign in

**Comment by xxz3** [comment]
This is not completely true, as airplane mode and Bluetooth for example, are working without unlocking. Anyway if it's not planned is ok.

**Comment by EleoXDA** [comment]
> This is not completely true, as airplane mode and Bluetooth for example, are working without unlocking. Anyway if it's not planned is ok.

Your phone can be forced shut down with a long press power button. So enabling bluetooth is nothing compared to it
