### ISSUE TITLE
[Bug] brightness slider

### ISSUE THREAD

**Issue by dr3mro** [siavash79/AOSPMods#435]
### Describe the issue

Brightness bar won't move with gesture but brightness works 

### Steps to reproduce

Install android 12 and Magisk and Lposed 
Install aosp mods 
Try to move the brightness slider it won't actively move with gesture but brightness will change and when you retreat your finger the brightness bar will fill 

No modifed settings at all 

### Expected bahavior

Brightness bar should move like the sound bar not after removing finger 

### Your device setup (Please take some time to give correct information here)

Xiaomi mi11 lite 
Pixel experience rom 
Android 12

**Comment by EleoXDA** [comment]
Android 12 known issue. Update to A13 for fix
