### ISSUE TITLE
Add app icon to toast msg

### ISSUE THREAD

**Issue by nickelnine** [siavash79/AOSPMods#438]
What's on your mind?
Be nice to know which app is generating the toast message by having the app icon alongside the message. 

Is this feature implemented on any other app/mod/rom? please specify
Spark and Cherish OS

**Comment by EleoXDA** [comment]
> What's on your mind?
> Be nice to know which app is generating the toast message by having the app icon alongside the message. 
> 
> Is this feature implemented on any other app/mod/rom? please specify
> Spark and Cherish OS

Could you show an example? A screenshot or two probably

**Comment by nickelnine** [comment]
![Screenshot_20221112-151506_Sushi Launcher](https://user-images.githubusercontent.com/28116390/201497693-fa4990c7-c809-4f86-a301-90791c6fea3e.png)

**Comment by EleoXDA** [comment]
It already is like that.
![Screenshot_20221113-093056.png](https://user-images.githubusercontent.com/27622683/201512949-440490fd-5ad1-4a08-ac47-a2a6a3579daa.png)

**Comment by nickelnine** [comment]
That was a bad example on my part. Yes, Magisk puts the app icon for messages Magisk itself generates like in both of our screenshots. Also Ex Kernel Manager does the same thing (screenshot provided). Similarly, what I'm requesting is for app icon to appear next to the toast message that the app creates. 
![Screenshot_20221113-071438_Nova7](https://user-images.githubusercontent.com/28116390/201521579-e2861aa2-38f4-430b-bf4e-7c8b674049c9.png)
Ex Kernel Manager toast
![Screenshot_20221113-071456_Nova7](https://user-images.githubusercontent.com/28116390/201521597-b5fcbd46-aee3-4902-a85b-63a78d56b84d.png)
Toast without the app icon (Would have AutoLocation icon if implemented)
Hope you reconsider.

**Comment by EleoXDA** [comment]
> That was a bad example on my part. Yes, Magisk puts the app icon for messages Magisk itself generates like in both of our screenshots. Also Ex Kernel Manager does the same thing (screenshot provided). Similarly, what I'm requesting is for app icon to appear next to the toast message that the app creates. ![Screenshot_20221113-071438_Nova7](https://user-images.githubusercontent.com/28116390/201521579-e2861aa2-38f4-430b-bf4e-7c8b674049c9.png) Ex Kernel Manager toast ![Screenshot_20221113-071456_Nova7](https://user-images.githubusercontent.com/28116390/201521597-b5fcbd46-aee3-4902-a85b-63a78d56b84d.png) Toast without the app icon (Would have AutoLocation icon if implemented) Hope you reconsider.

I will need to check myself with an app that gives toast message. Afaik just need to read metadata of toast message but will need to see whether it is possible generate the icon of the app nearby. I haven't got toast message from other than magisk.
