### ISSUE TITLE
Fully disable left side navigation gesture to access slide menus in apps. 

### ISSUE THREAD

**Issue by NilsSchoovaerts** [siavash79/AOSPMods#440]
We are able to disable side navigation (left side) but this doesn't give us access to slide menu's in apps suchs as Gmail, discord, etc. Could this function be added?

**Comment by EleoXDA** [comment]
> We are able to disable side navigation (left side) but this doesn't give us access to slide menu's in apps suchs as Gmail, discord, etc. Could this function be added?
> 

Wait, in Gmail you have a 3dot icon to open the menu. Same on discord. Those sidebar navigations as I said are obsolete but yet haven't yet been removed from apps. I guess you can decrease the sensitivity of the back gesture... 
![Screenshot_20221113-162410.png](https://user-images.githubusercontent.com/27622683/201529827-1c9f6a20-6550-493a-b9d6-52e51d30deb0.png)
![Screenshot_20221113-162458.png](https://user-images.githubusercontent.com/27622683/201529836-6a6014fe-fa89-4ca1-a5bb-ced41924a26e.png)
![Screenshot_20221113-162617.png](https://user-images.githubusercontent.com/27622683/201529838-c6f11d59-30b8-437d-878d-c41796565a76.png)

**Comment by EleoXDA** [comment]
In case you still need it,  https://github.com/Magisk-Modules-Repo/HideNavBar allows disabling left or right side for back gestures.
