### ISSUE TITLE
[Bug] Flashlight on quick settings panel not working

### ISSUE THREAD

**Issue by CDR-ShizutoKJWR** [siavash79/AOSPMods#441]
### Describe the issue

After updating to PE+ A13 Nov patch, flashlight on qs panel doesn't work (says camera in use). Disabling aosp mods for the time being fixes the issue

### Steps to reproduce

1. Update/flash PE nov build (on any phone)
2. Flash magisk and aosp mods
3. Open QS and flashlight should be indicated as not working

### Expected bahavior

As mentioned

### Your device setup (Please take some time to give correct information here)

- Xiaomi Redmi Note 11 (Pixel Experience Plus)
- 13
- november 5, 2022
- 25.2
- (refer to attached screenshot)
- 1.8.4 and 1.8,5 (updated hoping it would fix it)
- (refer to attached screenshot)
![Screenshot_20221113-164218_Magisk](https://user-images.githubusercontent.com/118101174/201513420-03e587ce-7097-4c91-a404-eb76ea872b9c.png)
![Screenshot_20221113-164221_Magisk](https://user-images.githubusercontent.com/118101174/201513423-9af908a4-9ead-4c29-ad02-09ad5560c7cf.png)

**Comment by EleoXDA** [comment]
AOSPMods only registers itself for flashlight events, with no access to the camera.
If your ROM disables flashlight access, this means your ROM confuses flashlight access with the camera access. This has to be fixed from ROM side. Talk this with your ROM dev
