### ISSUE TITLE
Hide Next Alarm on Lockscreen

### ISSUE THREAD

**Issue by creeve4** [siavash79/AOSPMods#443]
Please implement the option to hide the next alarm icon and time on the lockscreen.

This is currently implemented in the [DarkTricks Xposed module](https://github.com/darkeyes84/dark_tricks) (and works with A13).
[This commit](https://github.com/darkeyes84/dark_tricks/commit/64463d4c83e8bfee8cd1546836ed61f77cc735a7) may be helpful.

**Comment by EleoXDA** [comment]
https://github.com/siavash79/AOSPMods/issues/71

**Comment by creeve4** [comment]
Why do you keep closing these requests?!?! 
It is possible to hide the next alarm on the lockscreen, I even shared code for a method that was implemented using Xposed.
