### ISSUE TITLE
Toggle to remove the "!" Sign in signal icons in status bar when not connected to mobile data

### ISSUE THREAD

**Issue by 1Kilany** [siavash79/AOSPMods#447]
What's on your mind?
Toggle to remove the "!" Sign in signal icons in status bar when not connected to mobile data in pixel based roms

Is this feature implemented on any other app/mod/rom? please specify
Yes it's in custom roms under the name of " show data disabled icon " but not pixel based ones

**Comment by EleoXDA** [comment]
Use a magisk module called "signal cross fix" by cool_modules team
