### ISSUE TITLE
typo in the installation script

### ISSUE THREAD

**Issue by saifhakem** [siavash79/AOSPMods#449]
yeah so i was so fast to re-flash AOSPmods and i noticed that Lsposed was wrote as "Lspsed", it doesn't really affect anything i was just keen eyed and decided to report it
![Screenshot_20221118-202521](https://user-images.githubusercontent.com/83399502/202765474-4640b317-287f-49ed-9560-37cc73748088.png)
thanks for this module by the way, it really helped me alot

**Comment by EleoXDA** [comment]
I did PR for you ;) https://github.com/siavash79/AOSPMods/pulls

**Comment by saifhakem** [comment]
thanks sweetie :3
