### ISSUE TITLE
Dark Theme Style doesn't Apply Correctly after a System Refresh

### ISSUE THREAD

**Issue by ZN0N15** [siavash79/AOSPMods#45]
I have a bug where setting up the Dark Theme to Pitch Black or any other dark theme style doesn't apply correctly to the UI after a Restart/Reboot.

The only way to fix it is to open AOSP Mods after the Reboot and reselecting the desired theme manually again to apply the theme correctly.

Edit: I just found out that this also happens when Changing Wallpapers or when the system tries to change the Color Palette to match the wallpaper, and because of this the Dark Theme is also affected.

Basically every time I have to Reboot my device, I would have to re-apply the theme again manually.

**To Reproduce**
1. Go to AOSP Mods > Theming 
2. Select a desired Dark Theme Style 
3. Remember what it looks like after applying
4. Restart or Reboot the Device

**Expected behavior**

The theme should stay permanent to what was applied from AOSP Mods after making a Restart/Reboot of the device, and it should not revert back to the old Dark theme style.

**Screenshots**

After Applying "Pitch Black" Theme

![Screenshot_20220409-173149_Settings Services](https://user-images.githubusercontent.com/57549197/162566421-26e7781e-2f03-4c18-866a-72a8f3b55d76.png)
![Screenshot_20220409-173144_AOSP Mods](https://user-images.githubusercontent.com/57549197/162566424-59bdf8a1-642a-4cb9-b627-d12997730224.png)

After a Restart/Reboot of the Device

![Screenshot_20220409-173121_Settings Services](https://user-images.githubusercontent.com/57549197/162566445-ebc5957d-6770-4186-8b09-90a5644e80b0.png)
![Screenshot_20220409-173109_crDroid Home](https://user-images.githubusercontent.com/57549197/162566447-55afed49-068e-4178-8c86-4e990619cf5b.png)

 - Device: Poco X3 NFC
 - OS: Android 12.1 CrDroid 8.4

**Comment by bhaskar966** [comment]
crDroid has their own implementation of Monet/"Material You" ; maybe it's the cause of your issue. And don't reboot everytime, you can just restart or reboot your system UI.
To fix this crDroid issue ,
1. try to use the system setting to trun on pinch black mode 
2. Or use Repainter (available on Play Store [@kdrag0n](https://github.com/kdrag0n)  
3. Lastly their is 1 way ..
 But I'm not sure it will work to fix this issue or not-
Download [https://github.com/termux/termux-app/releases/tag/v0.118.0](Termux) and give Superuser permission. 

Now Type:

settings delete secure theme_customization_overlay_packages

& press enter. After finishing this process, reboot device once.

Last trick(no.3) might bring some issues , do it in your own risk

**Comment by ZN0N15** [comment]
Well, I guess it only works on AOSP Roms without Monet Theming engine. I'll close this just now since it's basically just a Rom/Systemwide issue. Thanks anyways!
