### ISSUE TITLE
[Bug] Bottom QS area black (and clipped) in dark mode

### ISSUE THREAD

**Issue by diegonogaretti** [siavash79/AOSPMods#452]
### Describe the issue

Bottom QS area has no background in light mode (white if there're notifications like active apps or network may be monitored) while it's black and clipped in dark mode

### Steps to reproduce

1. Enable light QS background and two-tone option
2. Expand QS, bottom area has no background or white background (with notifications)
3. Switch do dark mode, max brightness, expand and check bottom area. It's black and clipped. 

### Expected bahavior

No background for the area in dark mode without notifications and dark area with notifications

### Your device setup (Please take some time to give correct information here)

- Google Pixel 6
- Android 13 stable, stock, last available factory image
- Nov security update
- Magisk 25.2
- Adaway, AOSP Mods, Pixel Launcher, De-Bloater, Lawnchair, ReVanced Manager, Solid Explorer, [SharedUID] System UI
- AOSP Mods (Full version) 2.4.0, De-Bloater 1.0, mindetach 2.3, Move Certificates 1.9, Systemless Hosts 1.0, Universal SafetyNet Fix 2.3.1, Zygisk - LSPosed 1.8.5
- LSPosed 1.8.5
- AOSP Mods (Full version) 2.4.0

**Comment by EleoXDA** [comment]
No such issue here.

![Screenshot_20221121-161745.png](https://user-images.githubusercontent.com/27622683/203091149-8b653c12-a86a-4d1d-b9ea-123f778f4013.png)

**Comment by diegonogaretti** [comment]
> No such issue here.
> 
> ![Screenshot_20221121-161745.png](https://user-images.githubusercontent.com/27622683/203091149-8b653c12-a86a-4d1d-b9ea-123f778f4013.png)

You can see that the bottom area is clipped and black. I think it should be dark (not black) and not clipped as it's not in light mode

**Comment by EleoXDA** [comment]
It is as it is. This is the implementation of dual tone QS functions. You can turn it off though. We will not work on fine tuning the colors and etc. As long as it functions and texts are readable.

**Comment by diegonogaretti** [comment]
> It is as it is. This is the implementation of dual tone QS functions. You can turn it off though. We will not work on fine tuning the colors and etc. As long as it functions and texts are readable.

Thanks anyway
