### ISSUE TITLE
Option to have same QS toggles color for dark and light mode

### ISSUE THREAD

**Issue by diegonogaretti** [siavash79/AOSPMods#453]
What's on your mind?

> Please add an option to keep the same QS toggles color between dark and light mode. Currently dark mode has a lighter
and bland color while light has a more vibrant one.

Is this feature implemented on any other app/mod/rom? please specify

> Don't know

**Comment by EleoXDA** [comment]
Use repainter or use pitch black theme style

**Comment by diegonogaretti** [comment]
> That is from Google side. You can use substratum themes to adjust colors for your liking

Thanks!
