### ISSUE TITLE
Feature Request: Option to keep power menu's emergency button color to red

### ISSUE THREAD

**Issue by diegonogaretti** [siavash79/AOSPMods#454]
What's on your mind?

> Please add an option to keep power menu's emergency button color to red like in stock power menu while keeping the dark/light theme option

Is this feature implemented on any other app/mod/rom? please specify

> Don't know

**Comment by EleoXDA** [comment]
> What's on your mind?
> 
> > Please add an option to keep power menu's emergency button color to red like in stock power menu while keeping the dark/light theme option
> 
> Is this feature implemented on any other app/mod/rom? please specify
> 
> > Don't know
> 

Low priority...

**Comment by diegonogaretti** [comment]
> > What's on your mind?
> > > Please add an option to keep power menu's emergency button color to red like in stock power menu while keeping the dark/light theme option
> > 
> > 
> > Is this feature implemented on any other app/mod/rom? please specify
> > > Don't know
> 
> Low priority...

Thanks! Will wait :)

**Comment by siavash79** [comment]
@ElTifo

**Comment by EleoXDA** [comment]
Added on latest canary
