### ISSUE TITLE
[Bug] White clock QS panel

### ISSUE THREAD

**Issue by diegonogaretti** [siavash79/AOSPMods#455]
### Describe the issue

Clock in QS panel is white in light mode sometimes. Switching do dark mode and back to light fixes it.

### Steps to reproduce

1. Enable light QS background and two-tone option
2. Doesn't happen always so no steps to reproduce

### Expected bahavior

Clock should be the same color as the rest of the text in QS panel

### Your device setup (Please take some time to give correct information here)

- Google Pixel 6
- Android 13 stable, stock, last available factory image
- Nov security update
- Magisk 25.2
- Adaway, AOSP Mods, Pixel Launcher, De-Bloater, Lawnchair, ReVanced Manager, Solid Explorer, [SharedUID] System UI
- AOSP Mods (Full version) 2.4.0, De-Bloater 1.0, mindetach 2.3, Move Certificates 1.9, Systemless Hosts 1.0, Universal SafetyNet Fix 2.3.1, Zygisk - LSPosed 1.8.5
- LSPosed 1.8.5
- AOSP Mods (Full version) 2.4.0

**Comment by EleoXDA** [comment]
That behavior is observed in 1-2 users too but very rarely happens and we cannot figure out what is the culprit. If you can find it please share. Otherwise it was already fixed from our side

**Comment by diegonogaretti** [comment]
> That behavior is observed in 1-2 users too but very rarely happens and we cannot figure out what is the culprit. If you can find it please share. Otherwise it was already fixed from our side

Think I found it!
If an app sets the status bar to a dark color or black, clock is white and not reverted back to its color when you exit app

**Comment by EleoXDA** [comment]
> > That behavior is observed in 1-2 users too but very rarely happens and we cannot figure out what is the culprit. If you can find it please share. Otherwise it was already fixed from our side
> 
> Think I found it! If an app sets the status bar to a dark color or black, clock is white and not reverted back to its color when you exit app

let me test it

**Comment by EleoXDA** [comment]
cannot reproduce

> > That behavior is observed in 1-2 users too but very rarely happens and we cannot figure out what is the culprit. If you can find it please share. Otherwise it was already fixed from our side
> 
> Think I found it! If an app sets the status bar to a dark color or black, clock is white and not reverted back to its color when you exit app

cannot repoduce

**Comment by diegonogaretti** [comment]
> cannot reproduce
> 
> > > That behavior is observed in 1-2 users too but very rarely happens and we cannot figure out what is the culprit. If you can find it please share. Otherwise it was already fixed from our side
> > 
> > 
> > Think I found it! If an app sets the status bar to a dark color or black, clock is white and not reverted back to its color when you exit app
> 
> cannot reproduce

Not happening for me too now. Thanks anyway
