### ISSUE TITLE
Re-implement prevent ringing on Pixel 6/Pro

### ISSUE THREAD

**Issue by f8lxninja** [siavash79/AOSPMods#459]
Google in their infinite wisdom removed the Power + Volume Up shortcut that lets you turn vibrate mode on or off, even if you turn off the assistant on power button hold for the pixel 6 (and 7?) series.

From what I can tell, there is not a solution for this problem out in the wild. My Google-fu could be pretty bad so if there is an option out there please let me know.

**Comment by EleoXDA** [comment]
What about using the volume button and changing it from its menu? I have used it since forever and have never needed anything else

**Comment by f8lxninja** [comment]
While that is an option, it requires too many inputs from the user to accomplish that task. I have a smart watch, and I normally keep my phone on silent because notifications that are important come through to the watch. When I need to charge it, I flip vibrate on with the shortcut on my phone so I still get notified. This used to be an option in the settings app and it still shows up for other pixel phones, so I was hoping this mod could restore it in some way shape or form.

Sincerely,

Ben Townsend
________________________________

**Comment by EleoXDA** [comment]
> While that is an option, it requires too many inputs from the user to accomplish that task. I have a smart watch, and I normally keep my phone on silent because notifications that are important come through to the watch. When I need to charge it, I flip vibrate on with the shortcut on my phone so I still get notified. This used to be an option in the settings app and it still shows up for other pixel phones, so I was hoping this mod could restore it in some way shape or form.
> 
> Sincerely,
> 
> Ben Townsend


I see. Let's see if they haven't removed the action altogether, then it could be possible.

**Comment by siavash79** [comment]
Well..... I don't think this is an impossible request...... but....... what about the power menu?

**Comment by f8lxninja** [comment]
In your opinion, how much more difficult would it be to restore the button shortcut versus adding it to the power menu? I would prefer it to be as it was on previous pixel phones, but if it is significantly more challenging I'll compromise.

________________________________
