### ISSUE TITLE
Easy Unlock doesn't work on ArrowOS 13.

### ISSUE THREAD

**Issue by Adiker** [siavash79/AOSPMods#460]
### Describe the issue

After enabling the Easy Unlock option, it doesn't work. You still need to tap enter button.

### Steps to reproduce

1. Check option to enable Easy Unlock
2. You still need to tap enter button, which means it doesn't work at all.

### Expected bahavior

It should work.

### Your device setup (Please take some time to give correct information here)

- POCO F4
- ArrowOS 13 latest build
- November security patch
- Magisk 25.2 latest
- AOSP Mods, AdAway, Network Signal Guru, Simple Reboot, Root Checker, Viper4AndroidFX
- Builtin BusyBox, Viper4AndroidFX, Systemless hosts, miui camera port, universal safetynet fix, lsposed (zygisk), Audio Modification Library. And of course AOSP Mods.
- LSposed 1.8.5 zygisk
- AOSP Mods, Call Recording, SetAppFull

**Comment by EleoXDA** [comment]
Arrow was never supported. Read readme file
