### ISSUE TITLE
[Bug] Force unlocking screen rotations actually breaks the rotations!

### ISSUE THREAD

**Issue by saifhakem** [siavash79/AOSPMods#461]
### Describe the issue

unable to maximize videos with the option enabled (tested on chrome and youtube) and unable to use that little screen rotation button that pops up on the bottom

### Steps to reproduce

1.1. go to any app that supports screen rotation
1.2. turn your phone into landscape and click that little button that pops up on the bottom >it doesn't work

2.1 open any app with an maximizing button whatever it is >it doesn't work
(everything works fine when auto rotation is enabled expect the maximizing button)

### Expected bahavior

said above in the steps to reproduce box

### Your device setup (Please take some time to give correct information here)

xiomai poco x3 nfc (surya)
android 13
November 2022 PixelOS_surya-13.0-20221116-1037 (TD1A.221105.003)
magisk 25.2 
root access apps:
![Screenshot_20221126-184304_kjnkiop](https://user-images.githubusercontent.com/83399502/204097020-191b86a2-e24d-47af-81f1-e5d5f5e7246a.png)
magisk modules:
![Screenshot_20221126-184353_kjnkiop](https://user-images.githubusercontent.com/83399502/204097060-351ef4a9-7b04-4c2b-85c6-1ea95959281b.png)
lsposed 1.8.5 (zygisk of course)
lsposed modules: aosp mods 2.4.0, update locker 1.2.2 

### Logs

catlog (just in case): 
[logcat_11-26-2022_18-31-38.txt](https://github.com/siavash79/AOSPMods/files/10096555/logcat_11-26-2022_18-31-38.txt)
lsposed logs: 
[LSPosed_2022-11-26T18_47_04.290823.zip](https://github.com/siavash79/AOSPMods/files/10096557/LSPosed_2022-11-26T18_47_04.290823.zip)

**Comment by EleoXDA** [comment]
It is expected behavior. It is only meant to be enabled in situations you have to rotate screen when it is impossible

**Comment by GoodnessGraciousImUsingGithub** [comment]
alrighty that makes sense, i guess it'll be a great idea to put that as a warning under the option so you won't be spammed with bug reports by people that actually care?

**Comment by EleoXDA** [comment]
> alrighty that makes sense, i guess it'll be a great idea to put that as a warning under the option so you won't be spammed with bug reports by people that actually care?
> 

There are lots of Mods that users may misunderstand. We cannot put a "Disclaimer" below each of them. If user feels a mod should act otherwise, he can choose to bugreport (as you did), or a faster way would be using our Telegram support chat and get immediate response to the questions (mostly not requiring to fill up full bug report).
