### ISSUE TITLE
Split wifi QS icon stays on the "on" state when connection is lost 

### ISSUE THREAD

**Issue by Redeorhcs** [siavash79/AOSPMods#462]
I have the option enabled to break the data and wifi quick setting tiles apart. The buttons work, but if I lose connection to a particular wifi network the QS tile for wifi will stay on and show I am connected to the network that I lost connection to. If I hold down the wifi QS tile to open the internet setting menu correct states will be shown. Wifi will be off and available networks will be shown.  I've tried attaching my settings here to aid in the troubleshooting process, but I cant figure out how to attach anything other than a picture.  If more information is required please reach out to me and forgive me if I haven't done this correctly. I frequently download stuff from GitHub, but I've never posted here.

**Comment by EleoXDA** [comment]
Google's problem. Report to Google

**Comment by Redeorhcs** [comment]
This happened after I split the QS tile via AOSP mods. *Google's* problem?

**Comment by EleoXDA** [comment]
> Really!? This can't be gathered with root and exposed to boot?! So tasker
> and everything else will no longer be able to use wifi state for
> various reasons?

As written above. Internet toggle is not seperable anymore in a13. It is hardcoded and backdoor for expose is locked

**Comment by bdr99** [comment]
IMHO, if this feature does not work correctly on Android 13, then it should be hidden on devices running Android 13, until a workaround or some other solution is found.

**Comment by Redeorhcs** [comment]
I understand. I will deal with it and hope that it is fixed someday soon. I
appreciate the kind reply. Are you guys working on a new update for AOSP
mods to be compatible with the December update for the pixel series?

**Comment by EleoXDA** [comment]
Yes. For more news about updates please join Telegram support group. As you can see the latest patches were towards fixing incompatibilities on dec patch
