### ISSUE TITLE
Feature Request: Remove user icon on lockscreen

### ISSUE THREAD

**Issue by kxxt** [siavash79/AOSPMods#470]
What's on your mind?

Hi, thanks for your nice work. 

I'm using android multiple user feature, which added a user icon on lock screen. 

![lockscreen](https://user-images.githubusercontent.com/18085551/204936121-4f366d18-3136-4125-b6ae-f1069f39db4e.png)

 It's annoying to see this icon. I would really appreciate it if you could add an option to remove the user icon.

Is this feature implemented on any other app/mod/rom? please specify

https://forum.xda-developers.com/t/how-to-hide-the-user-icon.3361200/

https://github.com/half-duplex/CleanLockscreen implements this feature, but it haven't been updated for 6 years.

**Comment by siavash79** [comment]
Removing the user icon is fairly easy. but the question I want ask is this: how does the user select the "other" users if they icon/button is gone?

**Comment by kxxt** [comment]
> Removing the user icon is fairly easy. but the question I want ask is this: how does the user select the "other" users if they icon/button is gone?

That icon doesn't function as a button. It's just an indicator of the current user. 

We can switch  the user using the button here:

![](https://user-images.githubusercontent.com/18085551/205437632-0d71d5d5-8be6-42f3-9dcc-184143730209.png)
