### ISSUE TITLE
Unexpected font change

### ISSUE THREAD

**Issue by ChanceGPM** [siavash79/AOSPMods#48]
When enabling the module, it changes the font even though I have default Headline/body font on. Also lock screen clock has a thicker font than usual.

**Comment by siavash79** [comment]
In the themes  section, try disabling google sans font option (first item) and reboot. See if it solves your problem or not

**Comment by accayman7** [comment]
Same!
I'm wondering what would happen if I removed the fonts folder from the module zip
![Screenshot_20220411-193841](https://user-images.githubusercontent.com/46288671/162798347-210098f8-7ab4-475a-9eae-1907038f554a.png)

**Comment by ChanceGPM** [comment]
@accayman7 Did you try it?

**Comment by accayman7** [comment]
@ChanceGPM yes, no luck 😕

**Comment by fuzeless** [comment]
Same problem here! I managed to circumvent by extracting the modules, replacing both modified Roboto fonts (in /data/fontz and /system/fonts) with their originals, re-zip and reinstall.
You can get the original RobotoStatic and Roboto font from [here](https://drive.google.com/drive/folders/10hxJByS0Bis38zEc5ElRl_rTqfBgeQfc) or get it by yourself from /system/fonts (with the aospmod module disabled).

Hope that @siavash79 would fix the problem! And thanks for this amazing modules btw!

**Comment by siavash79** [comment]
Fixed in canary 010. The fonts are not activated by default anymore

**Comment by fuzeless** [comment]
Confirmed, font is behaving normally now!

**Comment by Mr54233** [comment]
not fix in chinese font it still will be overwrite
