### ISSUE TITLE
[Bug] Network Speed indicator

### ISSUE THREAD

**Issue by killerlearner** [siavash79/AOSPMods#481]
### Describe the issue

Network speed is showing blank when make it colourful is disabled only arrow is showing while if i combined download and upload speed nothing is shown

### Steps to reproduce

1:  Go to status bar setting and then slide down to network settings
2: Enable it and you will not show anything (if anything is not using background data) 
3: Set auto hide to 0 to enable it auto display and see only arrow is showing 

### Expected bahavior

Show download and upload speed

### Your device setup (Please take some time to give correct information here)

Device: Resmi note 8 pro
Android 13 
Custom rom: Proton plus November 5 security patch
Magisk modules: Screenshot 
Lsposed Version: 1.8.5 Zygisk Latest
Lsposed Module : Aosp mods, disable secure flasg

### Logs

![Screenshot_20221207-133734_Manager](https://user-images.githubusercontent.com/67904798/206123542-bd999022-d149-4136-9754-d59d4095238a.png)
![IMG_20221207_134012_727](https://user-images.githubusercontent.com/67904798/206123669-aeb7f866-34a4-4aa0-b03b-9a819ecba9b9.jpg)
![IMG_20221207_134012_406](https://user-images.githubusercontent.com/67904798/206123672-0db8db50-b0b2-436a-8c26-b2f7845933f6.jpg)
![IMG_20221207_134012_925](https://user-images.githubusercontent.com/67904798/206123675-4b87e6b9-207c-4d67-95da-1a41086360bc.jpg)

I tried uninstalling module and reinstalling reset all settings and trying both all and only lxposed module.

**Comment by EleoXDA** [comment]
Proton Plus is not in supported ROMs list
