### ISSUE TITLE
[Bug] some stuff isn't working after December update

### ISSUE THREAD

**Issue by kax17** [siavash79/AOSPMods#482]
### Describe the issue

Some stuff like volte icon, double tap to lock isn't working after the December update

### Steps to reproduce

Just don't work

### Expected bahavior

Expected to work as before the update

### Your device setup (Please take some time to give correct information here)

- pixel 7
- android 13
- December security patch
- Magisk 25.2
- 
![Screenshot_20221208-000236](https://user-images.githubusercontent.com/91348835/206392375-7f7d9b1e-2b94-4581-8640-3e039030d389.png)

- 
![Screenshot_20221208-000201](https://user-images.githubusercontent.com/91348835/206392509-faed02de-fd11-4856-b210-9e8b0c5a9524.png)

- lsposed 1.85
- 
![Screenshot_20221208-000604](https://user-images.githubusercontent.com/91348835/206392709-c5186be9-c660-4984-8a4b-04d6750c7081.png)

**Comment by EleoXDA** [comment]
Already being worked on. Please check out telegram support group to learn more information

**Comment by diegonogaretti** [comment]
**Describe the issue**
Status bar clock not showing after boot up. Need to enable one of the status bar clock mods to make it visible again

**Steps to reproduce**
- Boot
- Staus bar clock not showing
- Toggle one of the status bar clock mods to make it visible again
- Expected bahavior
- Status bar clock should be visible by default

**Your device setup (Please take some time to give correct information here)**
- Google Pixel 6
- Android 13 stable, stock, last available factory image
- Dec security update
- Magisk 25.2
- Adaway, AOSP Mods, Pixel Launcher, De-Bloater, Lawnchair, ReVanced Manager, Solid Explorer, [SharedUID] System UI
- AOSP Mods (Full version) last canary version, De-Bloater 1.0, mindetach 2.3, Systemless Hosts 1.0, Universal SafetyNet Fix 2.3.1, Zygisk - LSPosed 1.8.5
- LSPosed 1.8.5
- AOSP Mods (Full version) last canary version

**Comment by Subarupan** [comment]
**Describe the issue**
Icon bg for locked/unlocked not showing

**Steps to reproduce**
1. Install AOSPMods without changing any settings
2. Lockscreen icon bg won't work for lock/unlock icons

**Expected bahavior**
Showing unlock/locked icon bg

**Your device setup (Please take some time to give correct information here)**

- Pixel 6&7 Dec update
- Magisk 25.2
- LSPosed 1.8.5 AOSPMods canary-186

**Comment by akmsk1999** [comment]
in Light theme QS tiles become pale,brightness slider and tiles should have same color....but tiles colors are pale than brightness sliders....
![Screenshot_20221218-162056_Messenger](https://user-images.githubusercontent.com/16622098/208294743-6f810ee0-ffb6-4b32-9663-eb14a84a05fe.png)

**Comment by EleoXDA** [comment]
> ### Describe the issue
> 
> Some stuff like volte icon, double tap to lock isn't working after the December update
> 
> ### Steps to reproduce
> 
> Just don't work
> 
> ### Expected bahavior
> 
> Expected to work as before the update
> 
> ### Your device setup (Please take some time to give correct information here)
> 
> - pixel 7
> - android 13
> - December security patch
> - Magisk 25.2
> - 
> ![Screenshot_20221208-000236](https://user-images.githubusercontent.com/91348835/206392375-7f7d9b1e-2b94-4581-8640-3e039030d389.png)
> 
> - 
> ![Screenshot_20221208-000201](https://user-images.githubusercontent.com/91348835/206392509-faed02de-fd11-4856-b210-9e8b0c5a9524.png)
> 
> - lsposed 1.85
> - 
> ![Screenshot_20221208-000604](https://user-images.githubusercontent.com/91348835/206392709-c5186be9-c660-4984-8a4b-04d6750c7081.png)
> 
> 
> 
> ### Logs
> 
> _No response_

Fixed in latest canary updates

**Comment by EleoXDA** [comment]
> **Describe the issue**
> Status bar clock not showing after boot up. Need to enable one of the status bar clock mods to make it visible again
> 
> **Steps to reproduce**
> - Boot
> - Staus bar clock not showing
> - Toggle one of the status bar clock mods to make it visible again
> 
> **Expected bahavior**
>  Status bar clock should be visible by default
> 
> **Your device setup (Please take some time to give correct information here)**
> - Google Pixel 6
> - Android 13 stable, stock, last available factory image
> - Dec security update
> - Magisk 25.2
> - Adaway, AOSP Mods, Pixel Launcher, De-Bloater, Lawnchair, ReVanced Manager, Solid Explorer, [SharedUID] System UI
> - AOSP Mods (Full version) last canary version, De-Bloater 1.0, mindetach 2.3, Systemless Hosts 1.0, Universal SafetyNet Fix 2.3.1, Zygisk - LSPosed 1.8.5
> - LSPosed 1.8.5
> - AOSP Mods (Full version) last canary version

Fixed in latest canary updates

**Comment by EleoXDA** [comment]
> **Describe the issue**
> Icon bg for locked/unlocked not showing
> 
> **Steps to reproduce**
> 1. Install AOSPMods without changing any settings
> 2. Lockscreen icon bg won't work for lock/unlock icons
> 
> **Expected bahavior**
> Showing unlock/locked icon bg
> 
> **Your device setup (Please take some time to give correct information here)**
> 
> - Pixel 6&7 Dec update
> - Magisk 25.2
> - LSPosed 1.8.5 AOSPMods canary-186

Fixed in latest canary updates

**Comment by EleoXDA** [comment]
> **Describe the issue**
> Icon bg for locked/unlocked not showing
> 
> **Steps to reproduce**
> 1. Install AOSPMods without changing any settings
> 2. Lockscreen icon bg won't work for lock/unlock icons
> 
> **Expected bahavior**
> Showing unlock/locked icon bg
> 
> **Your device setup (Please take some time to give correct information here)**
> 
> - Pixel 6&7 Dec update
> - Magisk 25.2
> - LSPosed 1.8.5 AOSPMods canary-186

Reopened your issue as this ticket is done
