### ISSUE TITLE
Stuck at "Pixel is Starting"

### ISSUE THREAD

**Issue by cfxxpeace** [siavash79/AOSPMods#485]
Phone : Xiaomi Poco F3
Android version : 13
Rom : Pixel Experience 13
Security patch: November 5 2022
Magisk : 25.2
Lsposed : 1.8.5

Phone is unable to boot, stuck at "pixel is starting" after flashing the module, probably caused by the AOSP Mod apk, tried removing the apk from the zip file, and the phone boots up just fine, also tried uninstalled the module and only install the AOSPMOD.apk, stuck in "pixel is starting" again.

ps : the issue is not caused by any of the magisk or lsposed module i used ( including project themer ), I'm able to use everything including AOSP Mod before A13 November Security Patch.

[LSPosed_2022-12-09T15_53_39.230764.zip](https://github.com/siavash79/AOSPMods/files/10192875/LSPosed_2022-12-09T15_53_39.230764.zip)

![Screenshot_20221209-160242_LSPosed](https://user-images.githubusercontent.com/105487423/206654079-f4e97707-4acd-4bdb-8ffa-55c68842bd9e.png)
![Screenshot_20221209-160231_Settings](https://user-images.githubusercontent.com/105487423/206654086-6cee3ac6-c2a5-4da5-be48-51f607587be8.png)

**Comment by EleoXDA** [comment]
You submit report to AOSPMods repo without AOSPMods module and logs in group also don't have AOSPMods in it
