### ISSUE TITLE
[Bug] Stuck at "Pixel is Starting"

### ISSUE THREAD

**Issue by cfxxpeace** [siavash79/AOSPMods#486]
Phone : Xiaomi Poco F3
Android version : 13
Rom : Pixel Experience 13
Security patch: November 5 2022
Magisk : 25.2
Lsposed : 1.8.5

Phone is unable to boot, stuck at "pixel is starting" after flashing the module, probably caused by the AOSP Mod apk, tried removing the apk from the zip file, and the phone boots up just fine, also tried uninstalled the module and only install the AOSPMOD.apk, stuck in "pixel is starting" again.

ps : the issue is not caused by any of the magisk or lsposed module i used ( including project themer ), I'm able to use everything including AOSP Mod before A13 November Security Patch.

[log.txt](https://github.com/siavash79/AOSPMods/files/10193515/log.txt)

![Screenshot_20221209-160242_LSPosed](https://user-images.githubusercontent.com/105487423/206671578-2be7a869-3613-45ae-94d3-e340b5e3d94c.png)
![Screenshot_20221209-160231_Settings](https://user-images.githubusercontent.com/105487423/206671590-c004bd28-84bc-4841-be71-3ec62e49380c.png)

**Comment by zhujunsan** [comment]
Same here.

`v3.0.0 Full` is fine, after that will all cause stuck at 'Pixel is Starting'.

Although during this stuck, it is still responsible through shell. So I can use tools like `PixelFlasher` to disable/remove the module to recover the phone. 

Wondering how to completely remove and clean all the config files and do a clean install of the module
