### ISSUE TITLE
Re-implement lock screen album art blur

### ISSUE THREAD

**Issue by Drazini** [siavash79/AOSPMods#487]
What's on your mind?

If it is possible, I would love to see the option to blur the album art as the wallpaper for the lock screen be re-implemented in Android 13 as it was before Android 13 as I think it would look very nice with the new music player and just in general. Hopefully such a thing is possible in Android 13.

**Comment by EleoXDA** [comment]
Not yet possible on a13.

**Comment by draumaz** [comment]
Would truly love to see this implemented at some point. Custom ROMs have been able to reenable it, perhaps there's something of use there?

**Comment by EleoXDA** [comment]
Not via xposed
