### ISSUE TITLE
Feature Request: Pie Controls similar to GravityBox version

### ISSUE THREAD

**Issue by GUUser91** [siavash79/AOSPMods#490]
Can you implement Pie Controls similar to the GravityBox version? GravityBox version triggers quickly with no animation
![pie](https://user-images.githubusercontent.com/77461922/207842486-25961380-afc0-4eb5-abc6-6ff58e7c37d2.png)

https://user-images.githubusercontent.com/77461922/207844697-11056569-faf5-47ff-a33b-dbef0c7168f5.mp4

**Comment by EleoXDA** [comment]
Why not use apps on playstore? Already many available
