### ISSUE TITLE
Change QS panel page order, with default page.

### ISSUE THREAD

**Issue by gzyguo** [siavash79/AOSPMods#496]
What's on your mind?
Like I have 3 QS pages, I'd like to move the 1st, which is the default page to the page 2, in the center of the 3 pages, then the first expand will show me the center, the 2nd page, which is the default ideally, then I can access page1 or 2 with in 1 swipe, otherwise, if like now, the 1st page is the default, I have to swipe 2 times to access the page 3.

Is this feature implemented on any other app/mod/rom? please specify
Just in my mind.

**Comment by EleoXDA** [comment]
Just edit qs and sort accordingly
