### ISSUE TITLE
Feature request - allow additional QS columns

### ISSUE THREAD

**Issue by burntoc** [siavash79/AOSPMods#499]
It would be great to get to 5 or 6 QS columns (vs the current max of 4).  On a 1440 screen (P7P) with smaller text and icon above text it would be great to go to 5 or 6 columns.  I had another phone with similar resolution on A11 and had no issues with 6 columns.

Pixel Shade can do it, but it has other issues with pinhole notification apps such as dynamicSpot.

**Comment by EleoXDA** [comment]
It is practically possible but visibly disturbing.
