### ISSUE TITLE
[Bug] No such field runtime 

### ISSUE THREAD

**Issue by Archanial** [siavash79/AOSPMods#502]
### Describe the issue

There's the runtime that happens every 2 to 3 hours. 

### Steps to reproduce

No idea. My best guess it's related to double tap screen wake, since it's not always working when double tapping quickly.

### Your device setup (Please take some time to give correct information here)

Pixel 7 pro, stock, rooted with magisk 25.2, security update September 5th.
Lsposed 1.8.5, aosp 2.4.0, no other modules

### Logs

I'll attach them in a minute

**Comment by Archanial** [comment]
[trace_05.txt](https://github.com/siavash79/AOSPMods/files/10303985/trace_05.txt)
![Screenshot_20221226-160937](https://user-images.githubusercontent.com/37456678/209563524-35fe5ff4-6aa1-42e6-890f-9c5f37760aee.png)

**Comment by siavash79** [comment]
Nice catch

**Comment by EleoXDA** [comment]
One question though, why September sec patch with pixel 7 pro?

**Comment by Archanial** [comment]
No reason on particular, just never updated.

**Comment by EleoXDA** [comment]
> No reason in particular, just never updated.

Well, November sec patch and below is no longer updated. That is why I am asking. If you can reproduce it on Dec+ security patch we can discuss it

**Comment by Archanial** [comment]
I'll update in a bit and try to reproduce the bug.

**Comment by EleoXDA** [comment]
Ok. Please do and create an issue

**Comment by siavash79** [comment]
It MAY be still present in new versions. Let's keep it around to check it

**Comment by EleoXDA** [comment]
> It MAY be still present in new versions. Let's keep it around to check it

that is what I said to him. to open an issue after updating to Dec. But I no longer see it on Dec. It was present in Nov though

**Comment by Archanial** [comment]
Updated to 2.5.0, December 5th security update and the runtime is still there.

**Comment by EleoXDA** [comment]
> Updated to 2.5.0, December 5th security update and the runtime is still there.

Please share LSposed logs zip here

**Comment by Archanial** [comment]
[LSPosed_2022-12-30T17_55_41.198597.zip](https://github.com/siavash79/AOSPMods/files/10325582/LSPosed_2022-12-30T17_55_41.198597.zip)
Here are full lsposed logs.

**Comment by EleoXDA** [comment]
> [trace_05.txt](https://github.com/siavash79/AOSPMods/files/10303985/trace_05.txt)
> ![Screenshot_20221226-160937](https://user-images.githubusercontent.com/37456678/209563524-35fe5ff4-6aa1-42e6-890f-9c5f37760aee.png)
> 

I cannot find the logs you shared in this traces file you attached 🤔

> [LSPosed_2022-12-30T17_55_41.198597.zip](https://github.com/siavash79/AOSPMods/files/10325582/LSPosed_2022-12-30T17_55_41.198597.zip)
> Here are full lsposed logs.

Could you also share your AOSPMods settings?

To get AOSPMods settings, go to 3dot menu->import/export->export settings to a file and save it to a file. If you cannot upload the file to GitHub, try to add it in a zipped folder before uploading.

I checked but I cannot see the same error you have. It has to do something with your settings so we will need to reproduce with your options as this is probably not something that happens while installing AOSPMods but rather happens when some option is enabled. On our device there is no such error in full.log:

![Screenshot_20221230-224606.png](https://user-images.githubusercontent.com/27622683/210113909-52faa04f-dfdf-4592-9f4c-cb34914280d6.png)

**Comment by Archanial** [comment]
[aospsettings.zip](https://github.com/siavash79/AOSPMods/files/10326454/aospsettings.zip)
here are my settings

here's the screenshot from runtime happening on version 2.5.0
![Screenshot_20221230-233859](https://user-images.githubusercontent.com/37456678/210116159-cee48864-61b9-4449-9b33-57148119f471.png)

Reading the runtime and considering the screen doesn't always wake up when double tapped I can only assume the runtime happens when this setting is enabled:
![Screenshot_20221230-233932](https://user-images.githubusercontent.com/37456678/210116189-353d658e-6b27-40ea-9e55-b4cb7d993911.png)
Also the runtime always gets logged when I double tap the screen quickly two times in order to wake the phone up.

**Comment by EleoXDA** [comment]
> [aospsettings.zip](https://github.com/siavash79/AOSPMods/files/10326454/aospsettings.zip)
> here are my settings
> 
> here's the screenshot from runtime happening on version 2.5.0
> ![Screenshot_20221230-233859](https://user-images.githubusercontent.com/37456678/210116159-cee48864-61b9-4449-9b33-57148119f471.png)
> 
> Reading the runtime and considering the screen doesn't always wake up when double tapped I can only assume the runtime happens when this setting is enabled:
> ![Screenshot_20221230-233932](https://user-images.githubusercontent.com/37456678/210116189-353d658e-6b27-40ea-9e55-b4cb7d993911.png)
> Also the runtime always gets logged when I double tap the screen quickly two times in order to wake the phone up.

Now it is reproducible. It doesn't react when you tap too fast or tap too slow. That is expected behavior. 

But the error may need more attention:

```
E LSPosed-Bridge: java.lang.NoSuchFieldError: com.android.keyguard.KeyguardUpdateMonitor#mBouncer
E LSPosed-Bridge: 	at de.robv.android.xposed.XposedHelpers.lambda$findField$1(Unknown Source:6)
E LSPosed-Bridge: 	at de.robv.android.xposed.XposedHelpers.j(Unknown Source:0)
E LSPosed-Bridge: 	at de.robv.android.xposed.c.get(Unknown Source:28)
E LSPosed-Bridge: 	at java.util.Optional.orElseThrow(Optional.java:404)
E LSPosed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findField(Unknown Source:25)
E LSPosed-Bridge: 	at de.robv.android.xposed.XposedHelpers.getBooleanField(Unknown Source:4)
E LSPosed-Bridge: 	at sh.siava.AOSPMods.systemui.FingerprintWhileDozing$1.afterHookedMethod(FingerprintWhileDozing.java:54)
E LSPosed-Bridge: 	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
E LSPosed-Bridge: 	at LSPHooker_.shouldListenForFingerprint(Unknown Source:15)
E LSPosed-Bridge: 	at com.android.keyguard.KeyguardUpdateMonitor.updateFingerprintListeningState(KeyguardUpdateMonitor.java:22)
E LSPosed-Bridge: 	at com.android.keyguard.KeyguardUpdateMonitor.updateBiometricListeningState(KeyguardUpdateMonitor.java:0)
E LSPosed-Bridge: 	at com.android.keyguard.KeyguardUpdateMonitor$14.handleMessage(KeyguardUpdateMonitor.java:156)
E LSPosed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:106)
E LSPosed-Bridge: 	at android.os.Looper.loopOnce(Looper.java:201)
E LSPosed-Bridge: 	at android.os.Looper.loop(Looper.java:288)
E LSPosed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E LSPosed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
E LSPosed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E LSPosed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E KeyguardUpdateMonitorLog: Ignoring startListeningForFingerprint()]
```

**Comment by Archanial** [comment]
I have upgraded to 2.6.0, the exact runtime is gone, but a similar stack trace now keeps popping up. Lsposed 1.8.6, Jan sec update.
![Screenshot_20230125-140746](https://user-images.githubusercontent.com/37456678/214571746-12adc6d1-3fb5-49f1-ab30-5fc5fdf55360.png)
