### ISSUE TITLE
Swipe to Screenshot

### ISSUE THREAD

**Issue by AK2H** [siavash79/AOSPMods#506]
What's on your mind?
Swipe three fingers to take screenshot.

Is this feature implemented on any other app/mod/rom?
Yes (Evolution X)
![Screenshot_20221228-162115_Settings](https://user-images.githubusercontent.com/70269485/209834282-b8dcd4ac-704e-49d3-8acd-ecbd163b6a6e.png)

**Comment by EleoXDA** [comment]
No need. There is already many screenshots available in AOSPMods through gesture navigation
