### ISSUE TITLE
Power menu customization

### ISSUE THREAD

**Issue by AK2H** [siavash79/AOSPMods#507]
What's on your mind?
Custom power menu buttons.

Is this feature implemented on any other app/mod/rom?
Yes (Evolution X)
![Screenshot_20221228-161710_Settings](https://user-images.githubusercontent.com/70269485/209834596-760ce022-fe86-4a2b-a568-8a564f328fd7.png)

**Comment by EleoXDA** [comment]
You don't need so many options in power menu. Rather install evo x
