### ISSUE TITLE
[Bug]  not available

### ISSUE THREAD

**Issue by kuind** [siavash79/AOSPMods#511]
### Describe the issue

 not available

### Steps to reproduce

not available 
[LSPosed_2022-12-31T08_19_06.185953.zip](https://github.com/siavash79/AOSPMods/files/10326596/LSPosed_2022-12-31T08_19_06.185953.zip)

### Your device setup (Please take some time to give correct information here)

![Screenshot_20221231-082726_设置](https://user-images.githubusercontent.com/74531773/210119631-beaf491c-984f-4486-ae26-28e6d00432db.png)

### Logs

[LSPosed_2022-12-31T08_19_06.185953.zip](https://github.com/siavash79/AOSPMods/files/10326601/LSPosed_2022-12-31T08_19_06.185953.zip)

**Comment by EleoXDA** [comment]
Read readMe file before flashing. Your custom firmware not supported
