### ISSUE TITLE
[Feature request] prevent Magisk/Magisk Manager from updating to incompatible versions

### ISSUE THREAD

**Issue by Switch123456789** [siavash79/AOSPMods#515]
Fox's Magisk Manager recently updated AOSPMods to a version that is only compatible with A13, which lead to a lot of wasted time in troubleshooting why it is not working on my A12 based OS. Is it possible to implement something that prevents the user/the manager from updating to incompatible versions?

**Comment by EleoXDA** [comment]
We discussed this, and it is possible that we create a 2.4.2 version with the updater removed so that it no longer gets an update. But then, once you update over the December security patch, you will need to manually update to the latest stable (currently 2.5)

**Comment by Switch123456789** [comment]
Gotcha! Is it possible to let the v2.5+ installer detect if the Android-version is compatible? So if I try to install v2.5 on A12 it will terminate the installation-process?

**Comment by EleoXDA** [comment]
> Gotcha! Is it possible to let the v2.5+ installer detect if the Android-version is compatible? So if I try to install v2.5 on A12 it will terminate the installation-process?

This MOD is made for power users truth to be told. We wouldn't expect a power user to flash without reading. But we will check for that possibility

**Comment by Switch123456789** [comment]
Personally I don't read the description of every single update for every single module I use (might be bad practice but never had trouble with that the past 7 years). I often saw that there are separate entries in the repository for separate modules (like for A11, A12, A13 and so on) rather than having them in the same entry and giving them different version numbers. I thought this is common practice. But I guess that could be annoying since there might be no easy way to migrate the settings from one module to the other.

However, thanks for looking into it. Appreciate it!
