### ISSUE TITLE
[Bug] Homescreen does not take the full height, when tasklist is enabled

### ISSUE THREAD

**Issue by aronyi** [siavash79/AOSPMods#518]
### Describe the issue

Homescreen does not take the full height

### Steps to reproduce

Enable the tasklist in the navigationlist settings.
Also after reboot the homescreen does not take the full height of the portrait screen.
In landscape mode this issue does not appear.

### Expected bahavior

Homescreen takes the full height

### Your device setup (Please take some time to give correct information here)

Google Pixel 7 and Android 13. 
Aosp mods v. 2.5.0

### Logs

![Screenshot_20230105-135445](https://user-images.githubusercontent.com/122026365/210785514-04164928-c9b5-43fb-a544-c57af94d9428.png)
![Screenshot_20230105-135427](https://user-images.githubusercontent.com/122026365/210785527-290466e0-951b-45be-ac39-efb630a4596b.png)
![Screenshot_20230105-135419](https://user-images.githubusercontent.com/122026365/210785544-14735c5d-a2e6-4131-a070-16da016571fc.png)

**Comment by EleoXDA** [comment]
Taskbar has to take some space in bottom. What is the bug here could you be more accurate with definition of bug?

**Comment by aronyi** [comment]
The issue lies in the amount of free space around the homescreen widgets (marked yellow)

![Screenshot_20230105-144408](https://user-images.githubusercontent.com/122026365/210794253-ceb7e4f6-2650-4975-9149-9a7098395972.png)

**Comment by EleoXDA** [comment]
> The issue lies in the amount of free space around the homescreen widgets (marked yellow)
> 
> ![Screenshot_20230105-144408](https://user-images.githubusercontent.com/122026365/210794253-ceb7e4f6-2650-4975-9149-9a7098395972.png)
> 

The grids do not change numbers. They get smaller in size

**Comment by EleoXDA** [comment]
> > The issue lies in the amount of free space around the homescreen widgets (marked yellow)
> > 
> > ![Screenshot_20230105-144408](https://user-images.githubusercontent.com/122026365/210794253-ceb7e4f6-2650-4975-9149-9a7098395972.png)
> > 
> 
> The grids do not change numbers. They get smaller in size

Is this stock pixel launcher?

**Comment by EleoXDA** [comment]
> The issue lies in the amount of free space around the homescreen widgets (marked yellow)
> 
> ![Screenshot_20230105-144408](https://user-images.githubusercontent.com/122026365/210794253-ceb7e4f6-2650-4975-9149-9a7098395972.png)
> 

Is this stock pixel launcher?

**Comment by aronyi** [comment]
Yes, this is the stock pixel launcher

**Comment by EleoXDA** [comment]
> Yes, this is the stock pixel launcher

That looks like bug of Android 13 pixel launcher. As you know, taskbar is still not optimized for phones. Only tablets. There is nothing we can do for Google's launcher. Try to use some other launcher magisk modules like lawnchair, pixel launcher extended or a 3rd party launcher from playstore like Nova, Microsoft Launcher and etc
