### ISSUE TITLE
additional QS Tile themes

### ISSUE THREAD

**Issue by nickelnine** [siavash79/AOSPMods#523]
What's on your mind?
Add some new quick setting tile themes to this mod.
Here are some samples:
![qs color pop](https://user-images.githubusercontent.com/28116390/212522669-69960f30-e8b8-4a9c-afaa-c7fef29097cc.png)
QS Color Pop
![Qs two tone accent](https://user-images.githubusercontent.com/28116390/212522672-3185bba8-50b5-4bac-a9a9-968f2fa39ae7.png)
QS Two Tone Accent
![qs outline style](https://user-images.githubusercontent.com/28116390/212522677-1eee431c-7d40-4d86-8679-d7f387290052.png)
QS Outline Style

Seeing all of these added would be wonderful.

Is this feature implemented on any other app/mod/rom? please specify
SparkOS, CherishOS, RiceDroid all A13 ROMs

**Comment by EleoXDA** [comment]
No new themes, no new icons, no new signal icons theme. All the theming in AOSPMods is provided AS IS and will not be upgraded, fixed or updated. Those are no longer maintained
