### ISSUE TITLE
Brightness Slider is no longer animated correct upon changing some settings in AOSP Mods.

### ISSUE THREAD

**Issue by dongltron** [siavash79/AOSPMods#525]
### Describe the issue

I am unsure what settings exactly, but it appears random. Resetting all settings does not work, disabling and re-enabling the app doesn't work. The only way to fix this is to remove the module from Magisk and LSPosed entirely. The issue does not impede the function of the brightness slider itself  it simply seems to completely disable the sliding animation entirely. Changing the brightness works fine, however the icon simply snaps to my finger when it leaves the screen, instead of following my finger as expected.

### Steps to reproduce

1. Change settings (occurs at random?)
2. Restart SystemUI (or Reboot, same effect)
3. Brightness Slider is broken

### Expected bahavior

Brightness Slider functions normally

### Your device setup (Please take some time to give correct information here)

- Google Pixel 7 Pro
- Android 13
- 5 January 2023
- Version 25.2
- AOSP Mods, Fox's Magisk Module Manager, Pixel Launcher, ReVanced Manager, Shizuku, Swift Backup, System UI, Termux
- AOSP Mods (.2.5.0), Font Manager (5.7.6), Shamiko (0.6), Universal SafetyNet Fix (2.3.1), LSPosed (1.8.6)
- Version 1.8.6
- AOSP Mods (.2.5.0)

### Logs

Logs

[LSPosed_2023-01-18T04_55_44.810383.zip](https://github.com/siavash79/AOSPMods/files/10438442/LSPosed_2023-01-18T04_55_44.810383.zip)

Screen Recording (apologies for Drive link, file is too large)

https://drive.google.com/file/d/1CcDqS4ydNmaslaLudZoiXaq6zTfeduZh/view?usp=drivesdk

**Comment by EleoXDA** [comment]
It is known and dismissed. Read previous issues please. It was already answered
