### ISSUE TITLE
Systemui crash when accessing notification bar in full screen 

### ISSUE THREAD

**Issue by vidarwindir** [siavash79/AOSPMods#528]
### Describe the issue

Whenever I'm using a full screen game and recieve message or pull down the notification bar, my system UI restarts causing me to getting to lock screen. Has happened since canary-206 and now with stable 2.6.0 as well. Canary-205 / stable 2.5.0 work fine

### Steps to reproduce

1. Open full screen game (e.g. Command and Conquer Rivals, Brawl Stars
2. Receive message with pop-up or pull down notification bar twice to access quick toggles
3. Systemui restarts

### Expected bahavior

No crash when there's a pop-up or I want to change quick settings

### Your device setup (Please take some time to give correct information here)

- Google Pixel 7 Pro
- Android 13
- January 2023 Update
- Magisk 25.2
- Superuser:
![Screenshot_20230126-074926](https://user-images.githubusercontent.com/50791194/214774505-5a2e9cd4-764e-4d37-bf63-c02f20ceb21b.png)
- Modules: 
![Screenshot_20230126-075052](https://user-images.githubusercontent.com/50791194/214774676-4cc7b340-2c75-4df7-9019-056431f3fd01.png)
- Lsposed 1.8.6
- Lsposed Modules: 
![Screenshot_20230126-075346](https://user-images.githubusercontent.com/50791194/214774886-a3755593-17a9-44ec-a5c9-823e708d2cd7.png)

### Logs

Sorry it's my first ever report, when I copy the log in here it's too long. I tried pasting it here:
[Pastebin Link](https://pastebin.com/GSRmzUb9) 
Password: g4j8RH9T0N

I forgot to disable the other modules prior to writing this report, if needed I can provide a clean log.

**Comment by siavash79** [comment]
Can't produce the bug you reported.

What I can find from the log you shared is a lot of errors from project themer (com.drsants.eggproject), but nothing from AOSPMods

You may want to disable other Xposed modules, reboot and test again

**Comment by vidarwindir** [comment]
> What I can find from the log you shared is a lot of errors from project themer (com.drsants.eggproject), but nothing from AOSPMods
> 

Hello, thanks for the information.
After some testing i believe I ruled out all other possible reasons and believe that AOSPMods recent addition of "Added option to set different QS Tile numbers in portrait/landscape" is most likely the reason for my problems.
Project themer had the same feature already present and I believe now their compatibility to each is broken.

**Comment by siavash79** [comment]
The two modules have proven not so much compatible with each other. It's better if you choose which one to use
