### ISSUE TITLE
Batter indicator tweaks

### ISSUE THREAD

**Issue by EkriirkE** [siavash79/AOSPMods#529]
What's on your mind?
I love the colourful battery indicator (I use dashed w/ percent).  It would be nice if the option to transition colour was available while in colourful mode e.g. be all green when good then transition to yellow, then red.  Not white (dark mode) to yellow to red.  Basically "Make it  Colourful" starts at green instead of white (dark mode) with the transition toggle on.

I enjoyed the animated circle spinning as it closed while charging as seen in GravityBox (11)

Also, an option to replace/mimic the icon behaviour while the quicksettings/notifications are open-  Currently the modified and stock icons are here.  -- Related, the clock mods are also dropped from within the QS screen

Is this feature implemented on any other app/mod/rom? please specify
Animated is in GraviyBox(11)

This is an excellent mod, thank you!

**Comment by EleoXDA** [comment]
All theming coloring and icons are provided AS IS and not to be maintained
