### ISSUE TITLE
FP icon replacement

### ISSUE THREAD

**Issue by allday5850** [siavash79/AOSPMods#531]
What's on your mind?
I didn't know if it would be possible to change/customize the under-display fingerprint icon on the lockscreen? 

Is this feature implemented on any other app/mod/rom? please specify
I'm sure it is implemented in another rom, but not that I know of off the top of my head. But this app here I know does it for One Plus.
https://github.com/zacharee/OPFPControl

**Comment by EleoXDA** [comment]
No
