### ISSUE TITLE
Always show estimated Battery time

### ISSUE THREAD

**Issue by UltraHQ** [siavash79/AOSPMods#537]
![c98873dbc57bb670118eda7a4bbba684-w300](https://user-images.githubusercontent.com/35925402/221440004-aae2f64a-7237-4f40-aca6-0d8ffb878e11.jpg)
(Not my picture, taken from google)

You see it, when your battery is low and probably won't hold until your next charge. (never worked for me)
Or always, when you're in landscape mode.

According to some of my research, it was always shown back then. And I also prefer seeing it always.

Would love to see a toggle that enables it to always show.

**Comment by EleoXDA** [comment]
As far as I know, Iit is not programmable. It shows battery percentage when you have enough battery and estimated time when you have low battery. It can't show estimated battery when it is still not low - estimation needs to be calculated from your current use. So, when it has not enough information, it cannot "estimate" in a clever manner. And the reason it switches in low battery, so that you know approximately how much time you are left before you need to find a charger.

A very useful User Experience model.

**Comment by UltraHQ** [comment]
> A very useful User Experience model.

Indeed. But it does not work.

Maybe it's a Pixel 7 issue or something, I don't know. But overriding this and showing it always would be a quick way to fix it.
I personally don't mind seeing unrealistic estimations.

**Comment by EleoXDA** [comment]
> Indeed. But it doesn't work.
> 
> Maybe it's a Pixel 7 issue or something, I don't know. But overriding this and showing it always would be a quick way to fix it.
> I personally don't mind seeing unrealistic estimations.
> 

Works very well here, on my pixel 6. Maybe some other module is breaking in your device. But that is outside AOSPMods. In that case, follow these steps:

-  disable (better yet, delete) all modules other than AOSPMods & LSposed in Magisk Manager 
- disable all modules in LSposed other than A0SPMods
- Reboot
- Try to replicate the bug. If not successful, then it means some other module is causing the issue. Find the culprit module and stop using it.
- If successful, then extract LSposed logs. And after that, open a new issue and select bugreport. Answer all the questions and share LSposed logs zip there

**Comment by UltraHQ** [comment]
> > Indeed. But it doesn't work.
> > Maybe it's a Pixel 7 issue or something, I don't know. But overriding this and showing it always would be a quick way to fix it.
> > I personally don't mind seeing unrealistic estimations.
> 
> Works very well here, on my pixel 6. Maybe some other module is breaking in your device. But that is outside AOSPMods. In that case, follow these steps:
> 
> * disable (better yet, delete) all modules other than AOSPMods & LSposed in Magisk Manager
> * disable all modules in LSposed other than A0SPMods
> * Reboot
> * Try to replicate the bug. If not successful, then it means some other module is causing the issue. Find the culprit module and stop using it.
> * If successful, then extract LSposed logs. And after that, open a new issue and select bugreport. Answer all the questions and share LSposed logs zip there

I did some more research, and apparently Google decided to disable it on the Pixel 7.
One guy ( https://www.reddit.com/r/GooglePixel/comments/ytbcrd/i_like_how_the_pixel_7_puts_the_battery/ ) also reported this behavior.

So this is not a bug, but a feature from Google, which again makes my argument valid again.

**Comment by EleoXDA** [comment]
> > > Indeed. But it doesn't work.
> > > Maybe it's a Pixel 7 issue or something, I don't know. But overriding this and showing it always would be a quick way to fix it.
> > > I personally don't mind seeing unrealistic estimations.
> > 
> > 
> > Works very well here, on my pixel 6. Maybe some other module is breaking in your device. But that is outside AOSPMods. In that case, follow these steps:
> > 
> > * disable (better yet, delete) all modules other than AOSPMods & LSposed in Magisk Manager
> > * disable all modules in LSposed other than A0SPMods
> > * Reboot
> > * Try to replicate the bug. If not successful, then it means some other module is causing the issue. Find the culprit module and stop using it.
> > * If successful, then extract LSposed logs. And after that, open a new issue and select bugreport. Answer all the questions and share LSposed logs zip there
> 
> I did some more research, and apparently Google decided to disable it on the Pixel 7. One guy ( https://www.reddit.com/r/GooglePixel/comments/ytbcrd/i_like_how_the_pixel_7_puts_the_battery/ ) also reported this behavior.
> 
> So this is not a bug, but a feature from Google, which makes my point valid again.

We will need to ask it from all testers in group that own pixel 7. And as I said, if pixel 7 does not have estimation, probably whole function was removed. And frankly, I am guessing if it really was removed ONLY from pixel 7 (which is very unlikely), then it will continue on other devices as well once it passes test phase. If it does not pass test phase, it will be eliminated.
