### ISSUE TITLE
Add option for using your own fonts

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [siavash79/AOSPMods#539]
Is it possible to add an option to use your font instead of the built-in ones?

**Comment by EleoXDA** [comment]
No

**Comment by EleoXDA** [comment]
> Why? Security issue, or not wanting to deal with support requests?

No. Simply because the part related to icon themes, signal icons and fonts is to be used AS IS and will not be supported since 2022. And thus there would be no addition or update to that part.

**Comment by EleoXDA** [comment]
Also, the font change in AOSPMods is not throughout the system but only at systemUI regions. Thus, it is not considered as whole font change. There are magisk modules that can replace up to 95-99% of the fonts in the phone. And we dont have any such promise
