### ISSUE TITLE
Screenshots gesture

### ISSUE THREAD

**Issue by accayman7** [siavash79/AOSPMods#54]
3-fingers gesture for screenshots

**Comment by siavash79** [comment]
This will not be on top of the list because it needs hacking system framework (which we're super reluctant to do at this stage because of high risk of bootloops)

**Comment by accayman7** [comment]
I absolutely understand that, take your time. 
Quality before quantity ;-)

**Comment by drishal** [comment]
Tbh I would also love that for roms like lineageos 
I wonder how does xposed edge manage to use these gestures tho 🤔
