### ISSUE TITLE
[Feature Request] Zygisk Version of AOSPMods

### ISSUE THREAD

**Issue by git-Hmmm** [siavash79/AOSPMods#540]
## What's on your mind?
Please provide a version of the module that uses zygisk and doesn't require the lsposed or xposed.

## Is this feature implemented on any other app/mod/rom? please specify
Multiple magisk modules use Zygisk for modifications.

**Comment by EleoXDA** [comment]
Not possible. Please read what is xposed and what do you we use in module.

Thanks
