### ISSUE TITLE
Alternative Method of Enabling Taskbar

### ISSUE THREAD

**Issue by AndrewCPU** [siavash79/AOSPMods#543]
_I had made this post under the Discussions board, but as @siavash79 pointed out, this is a better place for it_
_Original text:_
There's a better way to enable the taskbar for phones.. Currently the method that everyone seems to use is ripping off the isTablet flag of the Taskbar. This works, however it modifies Pixel Launcher's scaling to a stupid small size for a phone. 

There's a few different flags that can be set to enable the taskbar without screwing with Pixel Launcher's scaling.. I don't have the time to build a PR at the moment, but I can provide you with what I have from my personal module. 

The AOSPMods way of disabling the base gesture pill:
_Removed old code. See linked repo_
And then for the hook into PixelLauncher:
_Removed old code. See linked repo_
Instead of an incredibly overscaled launcher, we get:
![image](https://user-images.githubusercontent.com/4711859/223146785-e8e72bbe-2d38-426c-80f4-a53d5d97edb1.png)
![image](https://user-images.githubusercontent.com/4711859/223146840-89787467-12b3-4dfb-a490-387555c66bfa.png)

**I pushed my demo project to the following repo if you need to use it for reference: https://github.com/AndrewCPU/EnableTaskbar/**

There are some hardcoded intricacies that I haven't gotten to figure out yet, but I'll mention it here:
-  The default size of the taskbar handle is HUGE! I've reduced it to at least by default 413px, however this value really should change based on screen DPI. I'm not sure how to handle that properly, my last attempt ended with me bootlooping haha.
- If the device profile padding isn't **perfect** there will be an animation jump at the end of the exit app to home animation (with the taskbar open).
At the moment, I have it hard coded to taskbarStashedHeight * 1.5, which seems to line up properly on my Pixel 7 Pro with display size 4 of 5 in Settings.
This hard coded 1.5 is probably a reflection of my display size..
This function may also not be 100% correct. However if it's incorrect, it's currently perfectly incorrect lol. See the [official implementation](https://cs.android.com/android/platform/superproject/+/master:packages/apps/Launcher3/src/com/android/launcher3/DeviceProfile.java;bpv=1;bpt=1;l=1148?q=DeviceProfile&gsn=getHotseatLayoutPadding&gs=kythe%3A%2F%2Fandroid.googlesource.com%2Fplatform%2Fsuperproject%3Flang%3Djava%3Fpath%3Dcom.android.launcher3.DeviceProfile%23f5304e98ac3a07c4029fc5acad88d9c9de18513d97e814a6160b6375c6a2e192) for more info... 
- The default corner radius for the taskbar is ever so slightly wrong for Pixel 7 Pro. By default, I scale it down 0.9f, however there's most definitely a proper way to get this info from the OS, I didn't get a chance to find it.

**Comment by siavash79** [comment]
Thanks for your post. reflected in the latest canary https://github.com/siavash79/AOSPMods/commit/b5ad2c825ec59fe64dbecab5c8391a9727f72e48
