### ISSUE TITLE
[Bug] Can someone fix my device

### ISSUE THREAD

**Issue by phucvn2002vn** [siavash79/AOSPMods#544]
### Describe the issue

when i set up some things my system keeps crashing

### Steps to reproduce

1. open AOSPMods
2. tweak some settings like battery icon or status bar
3. my system started crashing after tweaking
4. after i disabled all modules in Magisk or LSPosed, the problem persisted

### Your device setup (Please take some time to give correct information here)

![Screenshot_20230307-144748](https://user-images.githubusercontent.com/96324562/223358602-effd27b3-a4b3-4a31-8b39-e57956f85fb0.png)
![Screenshot_20230307-144809](https://user-images.githubusercontent.com/96324562/223358609-d20b798b-68af-45f8-8f57-58cbfe2279cf.png)
![Screenshot_20230307-144635](https://user-images.githubusercontent.com/96324562/223358615-ba198177-cf3d-447a-b22f-683882145502.png)
![Screenshot_20230307-144744](https://user-images.githubusercontent.com/96324562/223358618-841b1b0b-aacd-4341-b940-206aaf05c62d.png)
![Screenshot_20230307-151718](https://user-images.githubusercontent.com/96324562/223364436-ea148bf5-3288-4e32-9b55-9f89f8bbce95.png)
![Screenshot_20230307-151721](https://user-images.githubusercontent.com/96324562/223364442-e58f8e04-fdf8-4248-bbd2-a09a9221325c.png)
![Screenshot_20230307-151730](https://user-images.githubusercontent.com/96324562/223364447-eee9e3a8-0df6-41f2-9a3b-5f4772af01aa.png)

### Logs

[AOSPMod1.txt](https://github.com/siavash79/AOSPMods/files/10906808/AOSPMod1.txt)

**Comment by EleoXDA** [comment]
It is answered in telegram group. Please read replies in the telegram group
