### ISSUE TITLE
Feature request: stable v2.7.0 (255)- double tap status bar area to instantly scroll to top 

### ISSUE THREAD

**Issue by Redeorhcs** [siavash79/AOSPMods#550]
What's on your mind?
Is it possible to add functionality so that a double tap on the status bar clock area could scroll instantly to the top of the screen in whatever app the user is currently in? For example, if a user scrolls to the bottom of a long settings menu or to the bottom of a long web page we have to manually scroll and swipe many times a long the side of the screen to get back to the top of the screen. This functionality would be much faster and easier to nearly instantly scroll to the top of the screen/ page.

This is a native iOS feature. It's outlined and shown in this video. Given that some launchers like nova can hide the status bar it would be best for the tap action be monitored in an area of the screen where the status bar resides as opposed to actually having to be ON the status bar (because it might not be displayed when this scroll action is needed). 

https://youtu.be/pvJDXTNblbQ

Here is a 3rd party app that provides the functionality. It's another app that users using AOSP mods have to download. With AOSP mods already having swipe gesture options in it I thought this might be a possibility to add.

Thanks.

Is this feature implemented on any other app/mod/rom? please specify

The feature is available on stock iOS. It is shown in the video link above ( https://youtu.be/pvJDXTNblbQ ). There are third party apps on the playstore that do this. Here is one of them with the highest rating:

https://play.google.com/store/apps/details?id=com.scroll.scrolltop.backtotop

As a bonus feature, is it possible to add a double tap somewhere in a lower corner that allows automatic scroll to the bottom?

**Comment by EleoXDA** [comment]
Our basic rule is -> if there is an app that can do the function, you don't need it in Xposed.

So, if there is already such an app, use it :)
