### ISSUE TITLE
March Update Taskbar

### ISSUE THREAD

**Issue by AndrewCPU** [siavash79/AOSPMods#551]
Hi folks!

With the March update, there's an issue with the taskbar, and I have a suggestion for a feature :) 

Issue:
Google increased the spacing of the Taskbar, the touch areas to collapse the taskbar cannot be hit anymore since touch between app icons is disabled, and the icons go edge to edge now so you cant touch between the last icon and the side of the screen. I think an easy way to fix this would be to just adjust how much padding is inbetween the icons, but I'm not sure where they've moved that to (if at all).

Suggestion:
With the March update, Google added the Transient Taskbar to launcher3. Mishaal had nice coverage on this during the beta cycle.
By default, the transient taskbar is disabled (just as the taskbar is), but can be enabled if you hook into the DisplayController class.

```java
Class<?> displayController = findClass("com.android.launcher3.util.DisplayController", loadPackageParam.classLoader);

hookAllMethods(displayController, "isTransientTaskbar", new XC_MethodHook() {
                @Override
                protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                    param.setResult(true);
                }
});
```

**Comment by siavash79** [comment]
Thanks!!

I actually tested the transient taskbar when qpr2b3 was released. My findings was that Google had a reason to disable it for now: to my eyes it was not ready. I believe it has consistency issues and user can't rely on its presence when it's needed.

I'll give it another shot soon anyway

**Comment by siavash79** [comment]
I gave it another try just now: The transient taskbar doesn't look reliable to me yet: it gets stashed and inflated very randomly, and the shortcuts aren't reliable to tap on.

Let's keep this in mind and check again after some updates
