### ISSUE TITLE
Remove date from clock widget

### ISSUE THREAD

**Issue by UltraHQ** [siavash79/AOSPMods#554]
![Screenshot_20230319-104335](https://user-images.githubusercontent.com/35925402/226166808-48faee4a-92ea-48be-a197-ce801002aafa.png)

Talking about this. The stock android clock widget.

It doesn't make sense to have it there, because the "At a glance" also shows the date.
With both widgets showing the date, it just looks odd.

**Comment by EleoXDA** [comment]
Use another custom widget clock
