### ISSUE TITLE
Android 12 Leaked Screenshots

### ISSUE THREAD

**Issue by AndrewCPU** [siavash79/AOSPMods#558]
What's on your mind?
Hi folks. I'm wondering if anyone could put together a new QS tile option to match the leaked versions of Android 12s QS menu?

Is this feature implemented on any other app/mod/rom? please specify
It was Android 12s leaked design..

![Early-Android-12-Mockup-2.jpg](https://user-images.githubusercontent.com/4711859/227988406-d46c5547-12bd-404a-baf8-7c4c005e50f6.jpg)

**Comment by EleoXDA** [comment]
What is the functional benefit?

**Comment by AndrewCPU** [comment]
Well, AOSPMods is based around customization, so, if the question is "What functional benefit?" the answer is "It's inherently the objective of the entire app"..
