### ISSUE TITLE
Brightness icon color

### ISSUE THREAD

**Issue by jojobozo** [siavash79/AOSPMods#56]
**Describe the bug**
The icon color is gray.

**To Reproduce**
1. Go to AOSP Mods app
2. Click on Theming
3. Select OxigenOS icons style

**Expected behavior**
I expected the icon color to be black as it should be.

**Screenshots**
![Screenshot_20220412-152247_Quickstep_1](https://user-images.githubusercontent.com/98482700/162972961-b3cd9dfd-696d-42c3-81bc-c451b7946ff8.png)

 - Device: POCO X3 NFC
 - OS: Android 12L

**Comment by jojobozo** [comment]
I checked and not only OxigenOS have this bug

**Comment by EleoXDA** [comment]
Which ROM are you on @jojobozo ? And have you checked the latest stable update 1.1.1?

**Comment by EleoXDA** [comment]
As far as I know there is no auto brightness icon on pixel firmware. And the brightness icon issue is better explained in https://github.com/siavash79/AOSPMods/issues/192 which is more up to date and can be replicated on pixel devices as well. I think we should close this issue and continue work on that one. If @siavash79 and @ElTifo also agree, we can close this and shift discussion there.

The brightness icon issue is solely dependent on disabling "light QS panel on light theme" whilst using light theme. No other option or setting is creating this behavior.
