### ISSUE TITLE
Text Battery

### ISSUE THREAD

**Issue by AngryManMLS** [siavash79/AOSPMods#565]
Months ago I wrote on an idea of adding text battery with a lightning icon. However after my initial message I was unable to get back to you on this suggestion due to multiple issues that came up in my life. Thankfully with things slowing down I can return to Android testing and all that fun stuff. Anyways...

The battery text/lightning icon for instance is a feature found in some ROMs such as Ancient ROM. I am not overly familiar with where things lie in their Github sadly but here is their Github.

https://github.com/Ancient-Roms

I have included a picture of what the feature looks like on my end. When the device such as my Pixel 7 Pro is charging the lightning bolt appears indicating the device is charging which to me is super useful. Anyways thanks for the amazing AOSP Mods!

![Screenshot_20230326-114306_Pokémon_GO](https://user-images.githubusercontent.com/5227592/229383871-6f4d5687-68c7-46bf-9c07-4ceeadf098ac.png)

**Comment by AngryManMLS** [comment]
Yes it is. For whatever reason I couldn't find that. Still getting used to GitHub.

**Comment by siavash79** [comment]
If we forget about the lightning icon, you can permanently add percentage via systemUI tuner, and then hide the icon in the mod.

And if you need to know if you're charging, there's always the battery bar to show only while charging
