### ISSUE TITLE
App crashes [Bug] 

### ISSUE THREAD

**Issue by RashadGasimly** [siavash79/AOSPMods#566]
### Describe the issue

After updating AOSP Mods app is crashing

### Steps to reproduce

1.I downloaded zip file from official github reporsity
2.I flashed zip file via Fox's mmm
3.I restarted device
4.I saw app crashed and name is changed itself
![Screenshot_20230405-220604_Settings](https://user-images.githubusercontent.com/129990317/230173269-647032a1-3ec6-4954-b5f4-45f26e9b39f1.png)
![Screenshot_20230405-221120_Pixel Launcher](https://user-images.githubusercontent.com/129990317/230173278-9be564eb-6cb9-4ee4-bcd6-d8ae5ec076b6.png)

### Expected bahavior

Hello,i updated AOSP Mods app to 2.7.2 from 2.4.1 but it crashes and name is changed itself.

### Your device setup (Please take some time to give correct information here)

Samsung Galaxy A70 (SM-A705FN)
Android 13
Custom ROM (Pixel Experience (Plus Edition),March 03 2023)
Magisk Delta (fdac22ba-delta) (Canary version)
![Screenshot_20230405-222726_Magisk Delta](https://user-images.githubusercontent.com/129990317/230171474-6c1b6ff5-a06a-4b5c-8cef-b9b0fd2c09c9.png)
![Screenshot_20230405-222736_Shell](https://user-images.githubusercontent.com/129990317/230171601-b3bba4fd-6051-4edb-a90a-cf5fcbe3e7bd.png)
LSPosed version: v1.8.6 (6842)
![Screenshot_20230405-222923_Shell](https://user-images.githubusercontent.com/129990317/230172075-3481d7db-36b6-43af-8253-d764a179d80c.png)

### Logs

[LSPosed_2023-04-05T22_30_20.296967.zip](https://github.com/siavash79/AOSPMods/files/11161968/LSPosed_2023-04-05T22_30_20.296967.zip)

**Comment by EleoXDA** [comment]
Magisk delta is not supported as far as I know

**Comment by RashadGasimly** [comment]
> Magisk delta is not supported as far as I know. Also, try clean install: uninstall module, reboot, install again after downloading from GitHub, reboot

I tried but didn't work

**Comment by EleoXDA** [comment]
> > Magisk delta is not supported as far as I know. Also, try clean install: uninstall module, reboot, install again after downloading from GitHub, reboot
> 
> I tried but didn't work

Tried switching to magisk stable from magisk delta?

**Comment by RashadGasimly** [comment]
> > > Magisk delta is not supported as far as I know. Also, try clean install: uninstall module, reboot, install again after downloading from GitHub, reboot
> > 
> > 
> > I tried but didn't work
> 
> Tried switching to magisk stable from magisk delta?
> 
> Also if you installed through FoxMMM, it was reported some fails (if you read notes in telegram group).

I tried to flash via magisj delta but still error

**Comment by EleoXDA** [comment]
> > > > Magisk delta is not supported as far as I know. Also, try clean install: uninstall module, reboot, install again after downloading from GitHub, reboot
> > > 
> > > 
> > > I tried but didn't work
> > 
> > Tried switching to magisk stable from magisk delta?
> > 
> > Also if you installed through FoxMMM, it was reported some fails (if you read notes in telegram group).
> 
> I tried to flash via magisj delta but still error

NOT via magisk delta
Use STABLE magisk manager apk with stable magisk 25.2 or 26 and check

**Comment by RashadGasimly** [comment]
> > > > > Magisk delta is not supported as far as I know. Also, try clean install: uninstall module, reboot, install again after downloading from GitHub, reboot
> > > > 
> > > > 
> > > > I tried but didn't work
> > > 
> > > 
> > > Tried switching to magisk stable from magisk delta?
> > > Also if you installed through FoxMMM, it was reported some fails (if you read notes in telegram group).
> > 
> > 
> > I tried to flash via magisj delta but still error
> 
> NOT via magisk delta Use STABLE magisk manager apk with stable magisk 25.2 or 26 and check

I fixed thx for help

**Comment by RashadGasimly** [comment]
I fixed thx for help

**Comment by RashadGasimly** [comment]
I fixed.thx for help
