### ISSUE TITLE
Recent apps feature request

### ISSUE THREAD

**Issue by Kiroolos** [siavash79/AOSPMods#57]
What's on your mind?
Is there a way to put the "Clear all" button before the first item in recent apps instead of being the last item ?

![Screenshot_20220412-194202.png](https://user-images.githubusercontent.com/43939903/163022538-5a219bcb-eb6a-463a-8efc-e2cd9512c33a.png)

**Comment by nickelnine** [comment]
Or better yet, at the bottom middle?
![Screenshot_20220413-155122313](https://user-images.githubusercontent.com/28116390/163276383-c7d74c0e-f734-49f5-b1ba-e2e31a200a87.jpg)

**Comment by lonsagisawa** [comment]
I don't think this is possible since it handled by launcher actually, any opinions?

**Comment by siavash79** [comment]
That's correct it's handled by the launcher
It is technically possible, but we have to implement it on pixel launcher, which would only work on pixel phones and maybe pixel experience

**Comment by EleoXDA** [comment]
I suggest you ask from the launcher of your choice. If you use a pixel device, then Pixel Launcher Mod shared in TeamFiles telegram group is testing the "clear all button at the bottom of recents" in its canary build for testers (not yet available for everyone).

For android 12.1 there is one more launcher (Lawnchair 12.1) that has clear all button at the bottom of recents. But you will need to let go of the "select" option of the pixel launcher.

I agree with @siavash79 that to have it enabled we either need to make sure all the users have exactly same version of exactly same launcher or make a "warning" that this will work on one launcher of our choice.

That is why it would be wiser to let this be done by the launcher of choice afaik

**Comment by siavash79** [comment]
On a second thought, doing this modification through Xposed means a whole rearrangement of all the layouts and make a decent space for the button.
Frankly speaking, while it's a nice change, it's not that useful to move it up and front, comparing to the effort it takes for implementation
