### ISSUE TITLE
Fix system back gesture not working when GBoard is open

### ISSUE THREAD

**Issue by devnoname120** [siavash79/AOSPMods#574]
# What's on your mind?

Global back system gesture doesn't work on the lower side of the screen when GBoard is open. There used to be an Android 12 setting to enable back gesture even when keyboard is open, but it's not available in Android 13.

See video below for an illustration.

https://user-images.githubusercontent.com/2824100/232225035-4e6d1545-098f-46b1-b427-b7c1124530d0.mp4

**System information:**
- Android 13
- LineageOS 20-20230115
- GBoard 12.6.02.491625702-release-arm64-v8a

# Is this feature implemented on any other app/mod/rom? please specify

I didn't have this issue on MIUI (Android 12).

**Comment by EleoXDA** [comment]
LOS is not supported. Please report from supported ROMs

**Comment by devnoname120** [comment]
@EleoXDA As far as I know this isn't a LOS-specific issue but is present on AOSP as well.
