### ISSUE TITLE
[Bug] Chrome slow at launch

### ISSUE THREAD

**Issue by bunnypig** [siavash79/AOSPMods#576]
### Describe the issue

At first launch with chrome, it takes 3-5 seconds before chrome does any actual loading. This happens everytime when you've killed chrome. As soon as it has done the initial delayed launch, it works flawlessly. 

I'd also like to add that I've disabled all other modules and everything to see what was causing the issue, and only when AOSPmods is on, this happens. 
### Steps to reproduce

1. Kill chrome entirely
2. Open chrome
3. Wait 3-5 seconds
4. Website loads

### Expected bahavior

Instantaneous load

### Your device setup (Please take some time to give correct information here)

Google pixel 7 pro

Android 13

TQ2A (march update) 

Magisk 26.0

Adaway, CX File explorer, repainter

Fullscreen/immersive gestures v21, System-less hosts v1,  universal safetynet fix v2.4, Zygisk - Lsposed v1.8.6

AOSPmods is the only Lsposed module

**Comment by bunnypig** [comment]
I figured out what my issue was, apparently I had chrome on DenyList in magisk. I have no idea how that could cause this but after I removed it, the issue disappeared.

**Comment by EleoXDA** [comment]
> I figured out what my issue was, apparently I had chrome on DenyList in magisk. I have no idea how that could cause this but after I removed it, the issue disappeared.

Yes, when in magisk denylist (especially when all processes instead of a separate process you want to hide from root is chosen) then apps get delayed. That is an expected response
