### ISSUE TITLE
Gesture indicator sometimes visible after disabling

### ISSUE THREAD

**Issue by whitewallman** [siavash79/AOSPMods#577]
Gesture indicator (pill) occasionally becomes visible even after disabling via "Hide Navbar".

**Comment by EleoXDA** [comment]
> Gesture indicator (pill) occasionally becomes visible even after disabling via "Hide Navbar".

Use other magisk modules like
https://github.com/Magisk-Modules-Repo/HideNavBar

**Comment by whitewallman** [comment]
Could this not just some bits in Aospmods that could possibly be tweaked rather than installing a different Magisk module? The Aospmods toggle works 98% of the time.

**Comment by EleoXDA** [comment]
> Could this not just some bits in Aospmods that could possibly be tweaked rather than installing a different Magisk module? The Aospmods toggle works 98% of the time.

No
