### ISSUE TITLE
Portable hotspot — Add configuration option for auto turn off timeout

### ISSUE THREAD

**Issue by devnoname120** [siavash79/AOSPMods#578]
Would you be open to accept a pull request that would add a feature to change the hotspot auto shutdown timeout value ?

Implementation details : https://github.com/PixelOS-AOSP/packages_modules_Wifi/issues/1#issue-1432196957

**Comment by siavash79** [comment]
Good idea. Yes we're open to PRs of course.

**Comment by devnoname120** [comment]
@siavash79 Thank a lot for implementing it. 🙏

https://github.com/siavash79/AOSPMods/commit/5a9d6fef1ae77954acbf7c68b3e6d7ed0ce88caa
