### ISSUE TITLE
option to enable/disable custom font on lock screen clock 

### ISSUE THREAD

**Issue by yalexxandre** [siavash79/AOSPMods#582]
What's on your mind?

I like the font that is on the clock on the lock screen from my pixel, but I would like to enable google sans on the system. But then, the font on the clock is changed as well. Could have two options in custom fonts: system and and clock on the lock screen. Even choose different fonts for the two options. 

Is this feature implemented on any other app/mod/rom? please specify

I don't think so

**Comment by EleoXDA** [comment]
Fonts/themes/icons are to be used AS IS, i.e. there will be no updates, fixes or upgrades on those.

You can find other magisk modules for that. But the font you want to change and font you want to preserve are controlled from one point, so not possible
