### ISSUE TITLE
[Bug] Kill foreground app not working in canary build

### ISSUE THREAD

**Issue by chuck4100** [siavash79/AOSPMods#587]
### Describe the issue

While using canary builds, tested with 233 to 238, kill foreground app navigation gesture displays toat but does not kill app. Stable 2.7.2(233) works as intended. Canary-232 was fast known to work. 

### Steps to reproduce

Install canary build.
Set gesture to kill foreground app
Open any app
Swipe to kill app
Today is displayed, app remains

### Expected bahavior

App closed upon gesture

### Your device setup (Please take some time to give correct information here)

Pixel 7 pro march update (also tested with February update) 
Android 13 Stable version
Magisk v26.1 canary
LSposed 1.8.7

**Comment by siavash79** [comment]
It can't be true: 1. I can't reproduce the issue 2. kill function is not based on xposed: it's based of a shell command

The only thing remaining is that you might have reverted root permission from pixel launcher. Please don't
