### ISSUE TITLE
Disable camera sound

### ISSUE THREAD

**Issue by stinglama** [siavash79/AOSPMods#593]
I really enjoy you app, thanks for all the efforts. 

A request though, can you please add an option to disable the frustrating camera sound that we get when we click pictures.
A pixel 7 user. I don't have any option to disable the camera sound when a pic is clicked

**Comment by EleoXDA** [comment]
> Yes, I have already tried all the possible magisk modules that I can find related to it. But none worked
Well, find the one that works and send us the code. For devices in countries where camera sound disabling is prohibited (e.g. Japan) we can't fix it without having the device in said country.

When you find a commit from an app/magisk module/custom ROM that works, copy the link of the said service and re-open the issue
