### ISSUE TITLE
[May be it's a BUG] About hide navigation bar

### ISSUE THREAD

**Issue by milkdog114514** [siavash79/AOSPMods#595]
I think when I check the "hide the navigation bar" it should not hide soft-keyboard's hide bottom. which Pixel Experience Plus did it great, it can hide navigation bar with out hide soft-keyboard's hide bottom.
And here's images to show what Pixel Experience did between AOSP Mods did
![Screenshot_20230504-170157_Pixel Launcher Extende](https://user-images.githubusercontent.com/123655015/236160719-f418495b-9218-4388-80ef-54033c4d7dca.png)
![Screenshot_20230504-170056_AOSP Mods](https://user-images.githubusercontent.com/123655015/236160733-0c9946c6-2bf8-4e69-a862-db1adb33fae7.png)
![Screenshot_20230504-170239_Pixel Launcher Extende](https://user-images.githubusercontent.com/123655015/236160743-18f75253-e260-4e16-a14a-2fbd2ed6a314.png)

**Comment by EleoXDA** [comment]
It is not a bug. It is intended. If you want a different experience, use hide navbar module:
https://github.com/Magisk-Modules-Repo/HideNavBar

**Comment by milkdog114514** [comment]
> It is not a bug. It is intended. If you want a different experience, use hide navbar module:
> https://github.com/Magisk-Modules-Repo/HideNavBar

at least you can give us some option like it

**Comment by EleoXDA** [comment]
> > It is not a bug. It is intended. If you want a different experience, use hide navbar module:
> > https://github.com/Magisk-Modules-Repo/HideNavBar
> 
> at least you can give us some option like it

why do you want to add something that is already in another magisk module? The hide navbar in AOSPMods is simple and straightforward, that applies to 95% of the users. If users want more, they have option to disable it from AOSPMods and use another module that I linked

**Comment by milkdog114514** [comment]
> > > It is not a bug. It is intended. If you want a different experience, use hide navbar module:
> > > https://github.com/Magisk-Modules-Repo/HideNavBar
> > 
> > at least you can give us some option like it
> 
> why do you want to add something that is already in another magisk module? The hide navbar in AOSPMods is simple and straightforward, that applies to 95% of the users. If users want more, they have option to disable it from AOSPMods and use another module that I linked

I'm sorry if I caused you trouble. Because I think more modules will make less stability, if something can do in one module, I think I shouldn't install more modules.
