### ISSUE TITLE
[Bug] Unable to launch dashboard 

### ISSUE THREAD

**Issue by zyh941** [siavash79/AOSPMods#596]
### Describe the issue

App shortcut or launcher

### Steps to reproduce

1. When I flash AOSPMods 2.8.0.zip in Magisk, restart my phone successfully.
2. Try to launch AOSPMods app in app launcher or drawer, it keep crashing and cannot open anything.
3. Uninstall the 2.8.0 version totally and reinstall the last version 2.7.2, it works normally.
4. Try to upgrade to 2.8.0 version from 2.7.2 by flashing zip in Magisk, it happens as step 2.

### Expected bahavior

Normal app icon and launch normally

### Your device setup (Please take some time to give correct information here)

-Google Pixel 5 stock firmware May 2023 Security Patch
-Android 13 stable version
-Magisk v26.1 stable
-AOSPMods 2.8.0
-LSPosed 1.8.6 (6712)

### Logs

Screenshots and logs.

[LSPosed_2023-05-05T14_52_54.938731.zip
![Screenshot_20230505-143803](https://user
![Screenshot_20230505-143737](https://user-images.githubusercontent.com/95530307/236395374-9d788897-8533-49a1-b64a-d599238059df.png)
-images.githubusercontent.com/95530307/236395260-039710b0-6fe9-4424-bbd8-f03eb6378e32.png)
](https://github.com/siavash79/AOSPMods/files/11403963/LSPosed_2023-05-05T14_52_54.938731.zip)

**Comment by EleoXDA** [comment]
Install the apk from insdide download zip
