### ISSUE TITLE
Please Bring back Qs tile customisations

### ISSUE THREAD

**Issue by bhaskar966** [siavash79/AOSPMods#60]
In recent update you removed some of the qs tile styles. Don't know why , there might be some issues , you know better than me.

I just want to tell please bring back those styles especially those rectangular styles.
Thanks 😄

**Comment by siavash79** [comment]
Those themes were owned by someone else and they did not want them in our mod.

There's nothing we can do about it

**Comment by bhaskar966** [comment]
Okey . No issues 👍
I'm closing this issue.
