### ISSUE TITLE
Rescale icons while changing taskbar height.

### ISSUE THREAD

**Issue by pota2dev** [siavash79/AOSPMods#601]
While adjusting the taskbar height, it doesn't rescale the icons accordingly. If its height is too short then the icons pop out of the taskbar which looks bad.

Also, when the taskbar is set to recent bar it would be more useful to the users if it shows less items with bigger icons on tall taskbar and more items with small icons on short taskbar.

**Comment by EleoXDA** [comment]
Taskbar icons are adjusted by your system launcher and dpi of your screen. Taskbar icon sizes are not manually adjusted. If you want smaller icons, adjust dpi of your screen accordingly
