### ISSUE TITLE
[Bug] Installing a lower version doesn't work

### ISSUE THREAD

**Issue by drkui** [siavash79/AOSPMods#604]
### Describe the issue

I installed the Xposed version of 2.8.0 first, but that didn't work on my Xperia 1 III that's on Android 13 (March 2023 security patch), so I figured I would try on version 2.7.2. however I am not able to get 2.7.2 to install correctly.

### Steps to reproduce

Note: when on 2.8.0 the app icon looks fine and i can go into the app and tap on items, its just that none of the options works.

1. I first tried to uninstall the 2.8.0 module in LSPosed but got the message "Uninstall Unsuccessful". 
2. The next thing I did was go to Magisk and click the "Remove" button.
3. Rebooted the device
4. Went back into Magisk after the reboot
5. Confirmed that the 2.8.0 Magisk module is gone from the list
6. Installed the 2.7.2 Xposed zip
7. After rebooting the device, I see that the AOSPMods app's icon changed as well as the icon name to "sh.siava.AOSPMods.Setti.", when I tap the icon, my screen blinks and I go back to the app launcher.
8. When I check the app info, it says the app version is 2.8.0.

### Expected bahavior

When I install version 2.7.2, I expect the app to be version 2.7.2.

### Your device setup (Please take some time to give correct information here)

Sony Xperia 1 III
Android 13 Stock
March 2023 Security Patch
Magisk v26.1 Stable
AOSPMods 2.8.0 and 2.7.2
LSposed 1.8.6
AOSPMods 2.8.0 and 2.7.2

**Comment by drkui** [comment]
Small update on this, I flashed my device from scratch, rooted, and installed LSposed again. This time i was able to install 2.7.2, however the options didn't work for my device either, so I wanted to try 2.6.0. The same issue occurred, this time with 2.6.0.

**Comment by EleoXDA** [comment]
Read the readme file in GitHub to understand that Xperia firmware was never supported
