### ISSUE TITLE
The battery icon will not change on the new A14 Beta 2

### ISSUE THREAD

**Issue by abun880007** [siavash79/AOSPMods#605]
### Describe the issue

unable to change battery icon since updating to A14 Beta 2

### Steps to reproduce

open aosp mods

### Expected bahavior

icon would change to selected option 

### Your device setup (Please take some time to give correct information here)

Google Pixel 7 Pro
Android 14 Beta 2
May Security Patch
Magisk Delta 25210
LSposed 1.8.6 canary 6891
AOSP Mods Canary 243
Classic Power Menu1.6.2
DarQ 2.2.1
Themer 1.2.4

I have tried with all modules off except AOSP Mods and still have the same issue

**Comment by abun880007** [comment]
Hi thanks for the quick response I will grab them for you.



Kind Regards,




Adam Bunting
________________________________

**Comment by EleoXDA** [comment]
Please update the issue with logs from LSPosed. It takes 10 seconds to capture logs and upload it
