### ISSUE TITLE
2.8

### ISSUE THREAD

**Issue by zolyyy** [siavash79/AOSPMods#607]
### Describe the issue

Pixel Experience 13 Cannot open AOSP app after install new module for magisk

### Steps to reproduce

1. Install 2.8 Aosp mods for magisk
2. Cannot open Aosp app

### Your device setup (Please take some time to give correct information here)

Redmi Note 7
Pixel Experience 13
Latest magisk and lposed

**Comment by EleoXDA** [comment]
Install apk that is present inside of the zip
