### ISSUE TITLE
[Bug]  When you enter the Portable Hotspot menu the title shows Package Manager

### ISSUE THREAD

**Issue by abun880007** [siavash79/AOSPMods#609]
### Describe the issue

When you enter the Portable Hotspot menu the title shows Package Manager

### Steps to reproduce

go to Portable Hotspot menu

### Expected bahavior

menu should show Portable Hotspot

### Your device setup (Please take some time to give correct information here)

Google Pixel 7 Pro
Android 14 beta  2
May Sec Patch
Magisk Delta canary

**Comment by EleoXDA** [comment]
Will be fixed in future version
