### ISSUE TITLE
[Bug] "You need to use a Theme.AppCompat theme"

### ISSUE THREAD

**Issue by kthlh** [siavash79/AOSPMods#613]
### Describe the issue

The 2.8.0 version refuses to run with this error messages.

### Steps to reproduce

Install 2.8.0 release and try to run it.

Please note that I know no ROMs but Pixel are supported, but it seems to be related to the app/manifest. I've seen it before with some version on crDroid and another later version worked like a charm.

### Expected bahavior

Expected to at least run normally, like the previous versions.

### Your device setup (Please take some time to give correct information here)

Xiaomi Redmi Note 11, SuperiorOS 13, May security patch.
Magisk 26.1, LSPosed 1.8.6.

### Logs

  | time: 1684227351498
-- | --
  | device fp:Redmi/spes/spes:12/SKQ1.211103.001/V13.0.5.0.SGCMIXM:user/release-keys
  | product board:bengal
  | superior vers:SuperiorOS-Thirteen-spes-RELEASE-20230509-1128
  | msg: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
  | stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{sh.siava.AOSPMods/sh.siava.AOSPMods.SettingsActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
  | at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3642)
  | at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3779)
  | at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
  | at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
  | at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
  | at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
  | at android.os.Handler.dispatchMessage(Handler.java:106)
  | at android.os.Looper.loopOnce(Looper.java:201)
  | at android.os.Looper.loop(Looper.java:288)
  | at android.app.ActivityThread.main(ActivityThread.java:7925)
  | at java.lang.reflect.Method.invoke(Native Method)
  | at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  | at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
  | Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
  | at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:926)
  | at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:889)
  | at androidx.appcompat.app.AppCompatDelegateImpl.initWindowDecorActionBar(AppCompatDelegateImpl.java:605)
  | at androidx.appcompat.app.AppCompatDelegateImpl.getSupportActionBar(AppCompatDelegateImpl.java:592)
  | at androidx.appcompat.app.AppCompatActivity.getSupportActionBar(AppCompatActivity.java:165)
  | at sh.siava.AOSPMods.SettingsActivity.backButtonDisabled(SettingsActivity.java:76)
  | at sh.siava.AOSPMods.SettingsActivity.onCreate(SettingsActivity.java:95)
  | at android.app.Activity.performCreate(Activity.java:8341)
  | at android.app.Activity.performCreate(Activity.java:8320)
  | at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1426)
  | at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3623)
  | ... 12 more

**Comment by EleoXDA** [comment]
What does it cause? App FC? Services stop? Themes don't apply? Functions do not work? You didn't specify what you mean by the following sentence: "Expected to at least run normally, like the previous versions."

**Comment by EleoXDA** [comment]
> ### Expected bahavior
> 
> Expected to at least run normally, like the previous versions.

Please explain this

**Comment by EleoXDA** [comment]
> ### Logs
> 
> 
> 
>   | time: 1684227351498
> -- | --
>   | device fp:Redmi/spes/spes:12/SKQ1.211103.001/V13.0.5.0.SGCMIXM:user/release-keys
>   | product board:bengal
>   | superior vers:SuperiorOS-Thirteen-spes-RELEASE-20230509-1128
>   | msg: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
>   | stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{sh.siava.AOSPMods/sh.siava.AOSPMods.SettingsActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
>   | at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3642)
>   | at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3779)
>   | at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
>   | at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
>   | at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>   | at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
>   | at android.os.Handler.dispatchMessage(Handler.java:106)
>   | at android.os.Looper.loopOnce(Looper.java:201)
>   | at android.os.Looper.loop(Looper.java:288)
>   | at android.app.ActivityThread.main(ActivityThread.java:7925)
>   | at java.lang.reflect.Method.invoke(Native Method)
>   | at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
>   | at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
>   | Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
>   | at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:926)
>   | at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:889)
>   | at androidx.appcompat.app.AppCompatDelegateImpl.initWindowDecorActionBar(AppCompatDelegateImpl.java:605)
>   | at androidx.appcompat.app.AppCompatDelegateImpl.getSupportActionBar(AppCompatDelegateImpl.java:592)
>   | at androidx.appcompat.app.AppCompatActivity.getSupportActionBar(AppCompatActivity.java:165)
>   | at sh.siava.AOSPMods.SettingsActivity.backButtonDisabled(SettingsActivity.java:76)
>   | at sh.siava.AOSPMods.SettingsActivity.onCreate(SettingsActivity.java:95)
>   | at android.app.Activity.performCreate(Activity.java:8341)
>   | at android.app.Activity.performCreate(Activity.java:8320)
>   | at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1426)
>   | at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3623)
>   | ... 12 more
> 
> 

These are not the logs that we request

**Comment by kthlh** [comment]
> > ### Expected bahavior
> > Expected to at least run normally, like the previous versions.
> 
> Please explain this

The app won't run. I can't tell if the themes apply or if something works because I can't launch the app to configure it :) That's why I included the APP crash log and not the LSPosed one. Am I still wrong?

Thanks.

**Comment by EleoXDA** [comment]
> > > ### Expected bahavior
> > > Expected to at least run normally, like the previous versions.
> > 
> > Please explain this
> 
> The app won't run. I can't tell if the themes apply or if something works because I can't launch the app to configure it :) That's why I included the APP crash log and not the LSPosed one. Am I still wrong?
> 
> Thanks.

Install the apk file in zip. That is all you need to do

**Comment by kthlh** [comment]
> Install the apk

If I say it crashes/fails to run, it means I have it installed :) Thus the log. it was installed during the full zip installation in Magisk.
Well thanks anyway.

**Comment by EleoXDA** [comment]
> > Install the apk
> 
> If I say it crashes/fails to run, it means I have it installed :) Thus the log. it was installed during the full zip installation in Magisk. Well thanks anyway.

I told you to extract the apk file from zip and install it as a 3rd party app. Am I writing it clearly?
