### ISSUE TITLE
Option to Hide the "Data Disabled Icon" on the Signal Icon

### ISSUE THREAD

**Issue by ZN0N15** [siavash79/AOSPMods#614]
It would be nice to have the option to hide the "Data Disabled Icon" on the signal icon, which is basically the "!" Exclamation Point found on the Signal Bars when Mobile Data is turned off. To me they are just not pleasing to look at, and I think it's a bit redundant to have that indicator when the 4g/LTE icons are already present to indicate that Mobile Data is turned on.

Most custom roms that are highly customizable like CrDroid, EvoX, Ancient etc. all have a built in toggle to disable the "Data Disabled" icon. However there are still roms out there like Pixel Experience, which is the one I'm currently using, that don't have that toggle to disable it.

**Comment by EleoXDA** [comment]
This is not a priority and to be honest it is better to know that data is disabled. So, disabling that will lead to a person accidentally thinking he/she can still be connected to the internet without WiFi.

That is why, no. We do not advise or condone that behavior for the app. But, you still can find magisk modules that can do it. Locate the "cool_modules" channel in telegram and search for "signal data cross remover". That is one module that is advised for that function.

**Comment by ZN0N15** [comment]
> This is not a priority and to be honest it is better to know that data is disabled. So, disabling that will lead to a person accidentally thinking he/she can still be connected to the internet without WiFi.

This was never really an issue since Android 11 and prior versions. The only relevant Indicator that Mobile Data or Internet is turned on or connected was the presence of the LTE/4G Icon, which still currently exists today in Android 13. Whenever the 4G/LTE icon is present it is always assumed Data or Internet is turned on, and when it's not, Data is disabled. Which is why I thought (and I assume to be a majority opinion) that the Data Disabled icon was just a Redundant solution to a problem that never existed.

Sorry for the rant. Anyways, thank you for pointing out a module that can do what I requested. Although I don't necessarily agree, I respect the decision to Not prioritize or implement the feature.
