### ISSUE TITLE
Enable support for SBC HD XQ — aka BT SBC `Dual Channel` mode

### ISSUE THREAD

**Issue by devnoname120** [siavash79/AOSPMods#620]
# What's on your mind?

For unclear reasons the SBC Bluetooth implementation on Android only uses the `Joint Stereo` mode which limits the bitrate to a meager 328 kbps. Due to this, SBC garnered the reputation of having terrible audio quality.

But this isn't deserved, SBC can actually match the sound quality of AAC and even aptX HD! Simply switching the mode to `Dual Channel` already multiplies the bitrate by 2 — and without any downsides as far as I know.

In fact supporting the `Dual Channel` mode at high bitrates is not even optional: the already-old A2DP specification v1.2 explicitly requires SBC receivers to support this mode at 512 kbps. And the bitrate only goes higher with newer versions.

And it's not only theoretical. User tests on around a hundred different headphone models showed that an overwhelming majority of them indeed comply with the specification and support this mode.

# Is this feature implemented on any other app/mod/rom? please specify

Yes!

It's implemented in LineageOS (see [blog post](https://lineageos.org/engineering/Bluetooth-SBC-XQ/)) up to version 18. Unfortunately these patches never made it to LOS 19 / LOS 20. They didn't garner any attention from LOS developers (they are overworked already), so they were [never reviewed or merged](https://review.lineageos.org/q/topic:twelve-bt-sbc-hd-dualchannel).

See also [these patches](https://android-review.googlesource.com/q/topic:%22bt-sbc-hd-dualchannel%22) submitted to the AOSP repo. Likewise in spite of their best efforts the community never managed to get any attention from Android maintainers. The patches were eventually abandoned after 4 years.

# How can we implement this new feature?

I haven't yet come up with a strategy to implement these changes through hooks. I hope I'll be able to budget some time in the coming weeks to do a pull request though.

The OS patches are already available & working. This should make it a lot easier to implement this feature. I don't know whether they still work on the latest versions of Android or not though. Barely any changes were needed to port them from Android 10 to Android 12. It may or may not be harder to port them to Android 13/14.

**Comment by EleoXDA** [comment]
Could you give references to the studies you mention about user tests?

**Comment by devnoname120** [comment]
My estimate is a guess based on the forum posts/comments I've read so far
Unfortunately, I'm not aware of any consolidated headphone compatibility list.

Here are two forum posts with user reports that come to my mind

https://forum.xda-developers.com/android/software-hacking/improve-bluetooth-audio-quality-t3832615 (22 pages of comments)

http://4pda.ru/forum/index.php?showtopic=914135 (49 pages of comments)

**Comment by EleoXDA** [comment]
> My estimate is a guess based on the forum posts/comments I've read so far
> Unfortunately, I'm not aware of any consolidated headphone compatibility list.
> 
> Here are two forum posts with user reports that come to my mind
> 
> https://forum.xda-developers.com/android/software-hacking/improve-bluetooth-audio-quality-t3832615 (22 pages of comments)
> 
> http://4pda.ru/forum/index.php?showtopic=914135 (49 pages of comments)
> 
> -----------
> 
> **Edit**: Found a list with [around 50-60 devices](https://4pda.to/forum/index.php?showtopic=914135&view=findpost&p=76170413).

Ok. We will wait for your PR and investigate it afterwards

**Comment by siavash79** [comment]
Adding such patches need the code to be hooked at native level. At this point, native hooks are not planned on the mod.
