### ISSUE TITLE
[BUG] As i decrease the status bar height is creating a blank space

### ISSUE THREAD

**Issue by JeeChan6** [siavash79/AOSPMods#621]
### Describe the issue

It's creating a blank space of between app and status bar

### Steps to reproduce

Decrease status bar height to 50%
Open any app

### Expected bahavior

Blank space should not exist

### Your device setup (Please take some time to give correct information here)

![Screenshot_20230522-140228_AOSP Mods](https://github.com/siavash79/AOSPMods/assets/95633962/b4d48eb9-6abb-47d3-ba77-f37ee93d2f80)
Pixel 5
Android 13
Magisk 25.1

**Comment by EleoXDA** [comment]
Cannot reproduce

![Screenshot_20230522-140648.png](https://github.com/siavash79/AOSPMods/assets/27622683/104a47be-a027-473b-ba64-53ba1707c164)

![Screenshot_20230522-140636.png](https://github.com/siavash79/AOSPMods/assets/27622683/51f00798-883f-46a3-8eab-2987ff0705fb)

**Comment by EleoXDA** [comment]
You are missing lots of information that was requested. Please provide answers to them
![Screenshot_20230522-140826.png](https://github.com/siavash79/AOSPMods/assets/27622683/b7c6589f-2da1-4365-9239-6d60876c673c)

**Comment by EleoXDA** [comment]
We also need LSPosed logs in addition to debug info

**Comment by EleoXDA** [comment]
> ### Describe the issue
> 
> It's creating a blank space of between app and status bar
> 

Any update?
