### ISSUE TITLE
Hide QS in secure Lockscreen 

### ISSUE THREAD

**Issue by drazox** [siavash79/AOSPMods#631]
What's on your mind?

Available in evox,cr

**Comment by blackwind** [comment]
I feel like this is a legitimate request, particularly in Android 13 where "Active Apps" exists and divulges at least a handful of the apps you're running and offers unauthenticated users the ability to stop them for some reason. Although most "sensitive" QS actions require authentication, I, for example, don't want anyone who picks up my phone toggling DND, as this would alter the behavior of some of my Tasker macros. One could also imagine a scenario in which the user has QS tiles enabled for sensitive apps they don't want unauthenticated users knowing about.

Definitely a mod I'd use if it were added.

**Comment by drazox** [comment]
Yeah bro,mobile data/wifi, hotspot, Bluetooth can be manage from
Lockscreen,i really miss this feature

**Comment by EleoXDA** [comment]
> I feel like this is a legitimate request, particularly in Android 13 where "Active Apps" exists and divulges at least a handful of the apps you're running and offers unauthenticated users the ability to stop them for some reason. Although most "sensitive" QS actions require authentication, I, for example, don't want anyone who picks up my phone toggling DND, as this would alter the behavior of some of my Tasker macros. One could also imagine a scenario in which the user has QS tiles enabled for sensitive apps they don't want unauthenticated users knowing about.
> 
> Definitely a mod I'd use if it were added.

Some functions are deliberately left possible to be toggled for EASE of access. Otherwise you can forget about all shortcuts in lockscreen. E.g. for camera, flashlight, DND and etc.

You can request this from Google for the next android version. If they think it is valid request they will add it

**Comment by blackwind** [comment]
> Some functions are deliberately left possible to be toggled for EASE of access. Otherwise you can forget about all shortcuts in lockscreen. E.g. for camera, flashlight, DND and etc.

I hear ya, but that's exactly what I want. Given that the entire purpose of this module is to provide tweaks of questionable usefulness that Google will never, ever add, this feels in-scope, and there are at least two people here who want it and at least a thread's worth at XDA bemoaning lack of updates for another module that did exactly this before Android updates broke it.

This isn't a true security feature, granted, but is something that might be useful to some people for, among other reasons, the ones I mentioned. Hope it gets a spot on the issue tracker, at least, if not the module.

**Comment by EleoXDA** [comment]
> > Some functions are deliberately left possible to be toggled for EASE of access. Otherwise you can forget about all shortcuts in lockscreen. E.g. for camera, flashlight, DND and etc.
> 
> I hear ya, but that's exactly what I want. Given that the entire purpose of this module is to provide tweaks of questionable usefulness that Google will never, ever add, this feels in-scope, and there are at least two people here who want it and at least a thread's worth at XDA bemoaning lack of updates for another module that did exactly this before Android updates broke it.
> 
> This isn't a true security feature, granted, but is something that might be useful to some people for, among other reasons, the ones I mentioned. Hope it gets a spot on the issue tracker, at least, if not the module.

Entire purpose of this module is "what developer(s) want to see in their device and take acceptable requests".

**Comment by EleoXDA** [comment]
> This isn't a true security feature, granted, but is something that might be useful to some people for, among other reasons, the ones I mentioned. Hope it gets a spot on the issue tracker, at least, if not the module.

Yes. Do submit it to Google and hope for the best

**Comment by EleoXDA** [comment]
> ... this feels in-scope, and there are at least two people here who want it ...

Currently our scope is to get A14 compatible.
