### ISSUE TITLE
5G/4G switching tile in QS 

### ISSUE THREAD

**Issue by drazox** [siavash79/AOSPMods#632]
What's on your mind?

Is this feature implemented on any other app/mod/rom? please specify
Available in Derp
![Screenshot_20230602-211836](https://github.com/siavash79/AOSPMods/assets/80334164/f0253770-f28d-48f7-87c8-a8bb653b136d)

**Comment by EleoXDA** [comment]
Use settings. You don't switch that very often anyways. Instead you can use a shortcut in homescreen. You wouldnt want to use an xposed module for that
