### ISSUE TITLE
[Bug] Settings UI crashes on OnePlus 9 with LineageOS 20.

### ISSUE THREAD

**Issue by TimmyP777** [siavash79/AOSPMods#634]
### Describe the issue

It works, now it doesnt. The tweaks carried over.

### Steps to reproduce

Settings

### Expected bahavior

It opens like all the other versions

### Your device setup (Please take some time to give correct information here)

Android 13 LineageOS 20 OnePlus 9
Magisk 26.1
Lsposed 1.8.6

**Comment by EleoXDA** [comment]
lineageos was never supported.

Anyways, open the downloaded zip and install apk that is inside the zip file

**Comment by TimmyP777** [comment]
Thanks. I know it wasn't supported.

**Comment by devnoname120** [comment]
I can confirm that manually installing the APK from this path stopped the crashes for me on LOS 20: `AOSPMods_full.zip` > `system` > `priv-app` > `AOSPMods` > `AOSPMods.apk`.

**Comment by EleoXDA** [comment]
> lineageos was never supported.
> 
> Anyways, open the downloaded zip and install apk that is inside the zip file

^^^^^^^^^
Yes, I did wrote that above
