### ISSUE TITLE
Expandable Bluetooth Qs tile.

### ISSUE THREAD

**Issue by krrishkap** [siavash79/AOSPMods#635]
I've seen this on Evox it has Bluetooth tile with an arrow just like the combined internet tile when you tap on it expands like the internet tile and lets you choose from already paired devices. i dont have a full screenshot of it coz now I'm on pe+ but the tile looks like this and expands just like the combined internet tile.
![Screenshot_20230611-193259_Photos~2](https://github.com/siavash79/AOSPMods/assets/86251706/e4670b54-a3b8-4cb2-8f1b-ee5d27435c0c)

**Comment by siavash79** [comment]
Thanks!
But we will need to pass. After discussion, we didn't find the feature useful enough
