### ISSUE TITLE
Add Adaptive Brightness Quicksettings Toggle

### ISSUE THREAD

**Issue by lollilol** [siavash79/AOSPMods#638]
Add an available toggle in the quicksettings menu, that toggles adaptive brightness. There is already [an app](https://play.google.com/store/apps/details?id=p4nd4.autobrightness&hl=en&gl=US) that does it, but the toggle somehow is a bit inconsistent. It works but when you press it, it doesn't instantly toggle.

Thank you in advance!

**Comment by EleoXDA** [comment]
It is not available in pixel stock firmware. But you can find lots of other apps that can create you a autobrightness tile. 

The app you use is quite obsolete and may not work on latest firmware. Instead, use this app: https://play.google.com/store/apps/details?id=it.simonesestito.ntiles

It should work fine (also, you can join the beta channel for the app in case it doesnt work on stable - I tried from beta channel)

**Comment by EleoXDA** [comment]
For further discussions, you can join our support group:
https://t.me/AOSPMods_Support
