### ISSUE TITLE
Add Location to Privacy Indicators

### ISSUE THREAD

**Issue by kaljade** [siavash79/AOSPMods#639]
Currently you can only show or hide both camera & microphone privacy indicators but location is still displayed even if Hide privacy indicators is selected.

Ideally, a submenu allowing you to toggle which privacy indicators you'd like to display would provide the greatest granularity.

**Comment by EleoXDA** [comment]
You already see location icon on statusbar when an app uses your location

**Comment by kaljade** [comment]
Yeah, but selecting Hide privacy indicators only suppresses camera and mic, not location so the privacy indicator is not hidden as intended. Makes that feature superfluous if you have apps that require location on in the background.

**Comment by kaljade** [comment]
![Screenshot_20230619-154600_Nova7](https://github.com/siavash79/AOSPMods/assets/4401117/f415947f-1dd7-498e-87b5-6762ff948194)
So if I could suppress Mic and Location but still show Privacy indicators for camera by being able to toggle the required indicators, is what I meant

**Comment by kaljade** [comment]
This was resolved for me in v2.9.0 as location is now also being suppressed. Thank you for your continued development on this great software.

Kind regards,

Kal

**Comment by EleoXDA** [comment]
> This was resolved for me in v2.9.0 as location is now also being suppressed. Thank you for your continued development on this great software.
> 
> Kind regards,
> 
> Kal

It isn't actually. But whatever floats your boat 😃

**Comment by kaljade** [comment]
It's now working as intended with location indicators so even if you had nothing to do with it my boat is still floating, haha. Thanks for all the work you have done on a great mod. Cheers, Kal
