### ISSUE TITLE
[Bug] Flashlight unavailable on Surface Duo (AOSPMods Xposed)

### ISSUE THREAD

**Issue by Phyan** [siavash79/AOSPMods#641]
### Describe the issue

Flashlight is unavailable when AOSP Mods enabled 

### Steps to reproduce

1. Be on a Surface Duo
2. Enable AOSP Mods module in LSposed
3. Restart System UI
4. Flashlight option does not work

![Screenshot_20230620-151712](https://github.com/siavash79/AOSPMods/assets/66014175/8522772c-947b-4fde-80ce-5da832fccdc9)
![Screenshot_20230620-144512](https://github.com/siavash79/AOSPMods/assets/66014175/b0908d17-3e0d-49da-81c1-e152b25794e3)

### Expected bahavior

Flashlight should work by default

### Your device setup (Please take some time to give correct information here)

- Surface Duo (6/128)
- Android 12L Stable (Build number 2022.829.13/Security update May 1, 2023)
- Magisk 26.1
- LSposed 1.8.6 (Zygisk)
- AOSP Mods 2.4.1 (Xposed)

### Logs

[LSPosed_2023-06-20T15_17_31.528246.zip](https://github.com/siavash79/AOSPMods/files/11800271/LSPosed_2023-06-20T15_17_31.528246.zip)

**Comment by EleoXDA** [comment]
Old versions are already not supported. Latest variant was 2.4.1 for android 12L. 

Also, to fix flashlight toggle in your ROM/firmware, your ROM/firmware developer needs to read the following and fix what is broken in the ROM/firmware:

```
AOSPMods, - like the way systemUI flashlight tile does - registers itself to receive flashlight events to understand when the flashlight is turned on/off, but it never 'uses' the camera.

On a pixel phone, it's never a problem (as it technically shouldn't be of course). But on some custom ROMs, ROM incorrectly thinks that the camera is in use

The procedure happening is this: a camera manager service is acquired from context, and a flashlight status listener is registered. The listener has a single boolean variable which is turned true/false upon flashlight toggle change.

Source code:
https://github.com/siavash79/AOSPMods/blob/canary/app/src/main/java/sh/siava/AOSPMods/utils/SystemUtils.java

Line 194
```

As this does not require any fix from our side, I will end this issue. For future support please update to Android 13/14 (to "after December 2022" security patch). Android 12/12L  (including android 13 until November security patch) is no longer supported

**Comment by Phyan** [comment]
@EleoXDA Thanks for the reply! Yes, technically, as far as I understood on SDuo uses 12L in my case, at least that all news sources and videos on YouTube, but in the parameters of the system something is written about 12, which does not seem to be true. And yes, I have the latest version installed

As for a fix from Microsoft vendor, given how many problems this device has so far at the software level, I doubt that Microsoft is in any way interested in solving this problem (anyway, I will write them about this).
In any case, I would like to know if it is possible to solve this problem in any way on my part, perhaps by removing/deactivating some strings to fix the flashlight. In fact, I only need to tweak a few parameters using AOSPMods - nothing more

(Also, the provided link does not work, but I found a needed file [here](https://github.com/siavash79/AOSPMods/blob/canary/app/src/main/java/sh/siava/AOSPMods/modpacks/utils/SystemUtils.java), but it seems that the line provided is not correct in the current variant)
![image](https://github.com/siavash79/AOSPMods/assets/66014175/643ee209-dc18-4b80-8a84-f40066762cc4)

**Comment by Phyan** [comment]
Okay, thank you for the instruction! I'll see if I can solve the problem this way 👍
