### ISSUE TITLE
[Bug] Keyboard not auto-activate when entering App drawer search with hidden gesture bar

### ISSUE THREAD

**Issue by Nikostito** [siavash79/AOSPMods#643]
### Describe the issue

When enabling the option to hide gesture bar, keyboard stops auto coming up when activating app drawer search see attached video below

### Steps to reproduce

1. Enable hide navigation bar option
2. Try entering app drawer search from homescreen 
3. Keyboard foes not auto activate
4. Disable the hide option
5. Keyboard gets back to normal

Video of the bug:
https://drive.google.com/file/d/1yH4WaPpl_s-dHg0noeUy6v8CIwrUZzKU/view?usp=drivesdk

### Expected bahavior

Keyboard before the June update, was coming up as sson as you entered the quick search without any issue

### Your device setup (Please take some time to give correct information here)

- Google Pixel 7 Pro
- Android 13 (TQ3A.230605.012)
- Security Update:June 5, 2023
- Magisk v26.1
- 
![Screenshot_20230623-005626](https://github.com/siavash79/AOSPMods/assets/25390905/be6a71a1-dd59-436a-af1a-2add636245cc)
- 
![Screenshot_20230623-005806](https://github.com/siavash79/AOSPMods/assets/25390905/8509a045-b8be-4f71-b8fa-4ec78a6c244b)
- Zygisk - LSposed v1.8.6(6712)
- 
![Screenshot_20230623-005926](https://github.com/siavash79/AOSPMods/assets/25390905/ac92acee-8575-4b68-904b-192c745f5d7e)

### Logs

https://drive.google.com/file/d/1z-nReCgES-cGzSsR3rdrUv1UG_BrFVX2/view?usp=drivesdk

**Comment by EleoXDA** [comment]
Don't share logs as text. Open LSposed, go to the logs tab, click on the save icon and share the generated file.

From what I see your report is inconclusive, as for the first 2-3 attempts after hiding navbar, the keyboard showed up. Try restarting UI after hiding and showing navbar

**Comment by Nikostito** [comment]
> Don't share logs as text. Open LSposed, go to the logs tab, click on the save icon and share the generated file.
> 
> From what I see your report is inconclusive, as for the first 2-3 attempts after hiding navbar, the keyboard showed up. Try restarting UI after hiding and showing navbar

What?
How can I share a screen recording if the ui restarts?
My test is not inconclusive, if I wait like 5 seconds for all the changes to take affect, keyboard stops showing up immediately.

**Comment by Nikostito** [comment]
Added logs as zip to original post.

**Comment by EleoXDA** [comment]
> What? How can I share a screen recording if the ui restarts? My test is not inconclusive, if I wait like 5 seconds for all the changes to take affect, keyboard stops showing up immediately.

Try this:
- Turn off that feature in AOSPMods
- Install [hidenavbar module](https://github.com/Magisk-Modules-Repo/HideNavBar)
- Check whether it works with that module

If not, then it is Pixel launcher bug, if works, then use that module and we will add a paragraph in FAQ for this case.

All in all, for the module this issue is of low importance
