### ISSUE TITLE
[Bug] Volume panel is completely modified

### ISSUE THREAD

**Issue by fillwithjoy1** [siavash79/AOSPMods#644]
### Describe the issue

Volume Panel

### Steps to reproduce

1. Install AOSPMods and reboot
2. Volume rocker is different

### Expected bahavior

Volume rocker to be the same

### Your device setup (Please take some time to give correct information here)

- Google Pixel 6 Pro (TQ2A.230305.008.E1)
- Android 13
- Magisk 26.1
- BCR, MagiskHideProps, Universal SafetyNet Fix, LSPosed (Zygisk)
- LSPosed version 1.8.6
- Pixelify GPhotos, DarQ
- 
![Screenshot_20230624-174306](https://github.com/siavash79/AOSPMods/assets/29514446/9fa5ff4b-d438-4fc6-9882-05e1b38e392d)
![Screenshot_20230624-174311](https://github.com/siavash79/AOSPMods/assets/29514446/a6bfa791-4369-4d1f-ac17-2ad451d6d4f4)

**Comment by EleoXDA** [comment]
At least share screenshots showing volume rocker "BEFORE AOSPMODS" and "AFTER AOSPMODS"

AOSPMods has ZERO changes in volume rocker. So, also try to disable some modules like DarQ to see whether it has any effect.

**Comment by fillwithjoy1** [comment]
> AOSPMods has ZERO changes in volume rocker.
Explain this then (and I only disabled the AOSP module by itself
![Screenshot_20230625-180738](https://github.com/siavash79/AOSPMods/assets/29514446/806cc6ba-6412-4b45-bf26-c2baef5bd809)

![Screenshot_20230625-180534](https://github.com/siavash79/AOSPMods/assets/29514446/346f8ec2-99e2-40f0-aa3c-2820961d5966)

**Comment by EleoXDA** [comment]
Go to AOSPMods - Theming menu - select different icon style and check again.

**Comment by fillwithjoy1** [comment]
[LSPosed_2023-06-28T05_08_55.230771.zip](https://github.com/siavash79/AOSPMods/files/11886339/LSPosed_2023-06-28T05_08_55.230771.zip)

**Comment by EleoXDA** [comment]
![Screenshot_20230703-175306.png](https://github.com/siavash79/AOSPMods/assets/27622683/8970fa54-6f6e-45d0-834a-ad3e8b7a6519)

My volume panel is still like this. I have no idea why or how your volume panel has been changed. But it is not from AOSPMods. That is for sure

**Comment by fillwithjoy1** [comment]
> My volume panel is still like this. I have no idea why or how your volume panel has been changed. But it is not from AOSPMods. That is for sure

What do you mean by that? I provided a before and after image of the volume rocker changing when I install this mod, and it happens **everytime** I enable this module. If I disable AOSPMods module then the volume rocker is back to normal, with the default settings AOSPMods modifies the looks of the volume rocker that I do not like

**Comment by EleoXDA** [comment]
We cannot replicate the issue. Try switching to xposed version from full version and tell us whether you still observe this. There seems to be some issues with overlays on your setup in that case

**Comment by fillwithjoy1** [comment]
> We cannot replicate the issue. Try switching to xposed version from full version and tell us whether you still observe this. There seems to be some issues with overlays on your setup in that case

Seems to have fixed it. What do you mean by "overlays"

**Comment by EleoXDA** [comment]
> > We cannot replicate the issue. Try switching to xposed version from full version and tell us whether you still observe this. There seems to be some issues with overlays on your setup in that case
> 
> Seems to have fixed it. What do you mean by "overlays"

I meant whatever you had was never related to AOSPMods anyways

**Comment by fillwithjoy1** [comment]
> > > We cannot replicate the issue. Try switching to xposed version from full version and tell us whether you still observe this. There seems to be some issues with overlays on your setup in that case
> > 
> > 
> > Seems to have fixed it. What do you mean by "overlays"
> 
> I meant whatever you had was never related to AOSPMods anyways

I can however replicate it on my device, as using the full version of AOSPMods modifies the volume panel compared to the Xposed Version. I've attached the logs for both the full and the xposed version
[aosp_full_logs.zip](https://github.com/siavash79/AOSPMods/files/11972217/aosp_full_logs.zip)
[aosp_xposed_logs.zip](https://github.com/siavash79/AOSPMods/files/11972219/aosp_xposed_logs.zip)

**Comment by EleoXDA** [comment]
As I said, I am also on full version and my screenshot is shared above. And again, as I pointed out, check out the overlays. They are located in AOSPMods/Theming option. Check out Icon Style menu. You have probably changed it in past and forgot about it. Reset it and it will be fixed.
