### ISSUE TITLE
Auto brightness on/off in brightness bar

### ISSUE THREAD

**Issue by drazox** [siavash79/AOSPMods#646]
In pixel,i need to go to display settings and need to enable Auto Brightness.In evox or other custom roms,we have an option to turn on/off auto brightness in brightness bar.I request this feature because during gaming i need to disable auto brightness, because brightness will fluctuate if we cover the sensor with hand. So i hope u guys will add it

**Comment by EleoXDA** [comment]
You can only have a quick settings toggle for that. Use quick settings app from playstore
