### ISSUE TITLE
[Bug] Split Network WiFi QS Tile freezes if WiFi network becomes out of range

### ISSUE THREAD

**Issue by EdwardApollo** [siavash79/AOSPMods#647]
### Describe the issue

Using the split Network Quick Settings tile Internet -> WiFi + Bluetooth, if the Wireless network you are connected to becomes out of range, the tile freezes and becomes unresponsive.

### Steps to reproduce

Using separate internet tile QS option:
Connect to a WiFi network
Walk out of range of said network
Tile Freezes and cannot be toggled

### Expected bahavior

the tile should update, displaying that it is not connected to a network 

### Your device setup (Please take some time to give correct information here)

Google Pixel 6 Pro Stock ROM, rooted, May Update
Magisk 26.1
Magisk Modules:
![Screenshot_20230629-185017](https://github.com/siavash79/AOSPMods/assets/51210836/bff10282-7aa5-4739-80f7-9d7016fc5992)

Superuser Permissions:
![Screenshot_20230629-185106](https://github.com/siavash79/AOSPMods/assets/51210836/61550273-e15c-4947-9020-ec4f052ab6d1)

Lsposed Version 1.8.6 (6712) - Zygisk
Lsposed modules:
![Screenshot_20230629-185228](https://github.com/siavash79/AOSPMods/assets/51210836/dbb96da8-3d51-415f-96ea-78300e5fa6f1)

Aospmods lsposed perms:
![Screenshot_20230629-185316](https://github.com/siavash79/AOSPMods/assets/51210836/305c75cb-c74b-4ae1-9866-fb3d17079a72)

### Logs

To be generated

**Comment by EdwardApollo** [comment]
Additional Screenshots
QS Tile:
![Screenshot_20230629-185643](https://github.com/siavash79/AOSPMods/assets/51210836/c29cfa7a-744c-4778-9f66-873057599d7c)

WiFi Settings Page:
![Uploading Screenshot_20230629-185636.png…]()

**Comment by EdwardApollo** [comment]
WiFi QS Tile:
![Screenshot_20230629-185643](https://github.com/siavash79/AOSPMods/assets/51210836/7c4abff3-1cae-4bc3-86e8-21c0b7377368)

WiFi Settings Page:
![Screenshot_20230629-185636](https://github.com/siavash79/AOSPMods/assets/51210836/f8364fac-deb0-47bc-95d6-58b327db7903)

WiFi needed to be disabled from that page as the QS Tile is unresponsive

**Comment by EleoXDA** [comment]
Support was already dropped for splitting wifi/mobile icon. Use betterinternettiles instead.

**Comment by EleoXDA** [comment]
If you check latest versions you will see the mod is already not present in the app
