### ISSUE TITLE
[Bug] Lock screen charging information not working properly 

### ISSUE THREAD

**Issue by K-plus69** [siavash79/AOSPMods#648]
(Sorry for not using the "Bug" template for this issue. I don't have a PC at the moment and the GitHub app exits the app and opens the browser when I want to click it)

In the AOSPMods settings, when going to the lock screen section, there's an option to give detailed information about the charging speed. But it shows 0,0V, 0,0A and 0,0w charging speed. Maybe some roms need to select the charger location. 

I have a Huawei p20 lite with an AOSP custom Rom (LeaOS (AOSP with Huawei patches)). I'm running android 13 February patch.

**Comment by EleoXDA** [comment]
Not compatible ROM
