### ISSUE TITLE
[Bug] Power menu colour scheme changed unexpectedly

### ISSUE THREAD

**Issue by etnperlong** [siavash79/AOSPMods#650]
### Describe the issue

Color pattern of power menu changed without any mod enabled

### Steps to reproduce

1. Install AOSPMods and reboot
2. Color pattern of the power menu changed without any mod enabled

The original power menu:
![image](https://github.com/siavash79/AOSPMods/assets/4851274/b6d9ed41-a745-4754-be55-840a1a3ed3f3)
![image](https://github.com/siavash79/AOSPMods/assets/4851274/ed2bd6fa-9874-4b07-933d-e07865a9ad7f)

The power menu after enabling the full version of AOSPMods
![image](https://github.com/siavash79/AOSPMods/assets/4851274/9214716a-f306-4121-9af7-bbf2238c4d04)
![image](https://github.com/siavash79/AOSPMods/assets/4851274/af123e11-cba3-481f-a764-9f9332efb8f6)

### Expected bahavior

Color pattern of the power menu should not be changed

### Your device setup (Please take some time to give correct information here)

- Device: Google Pixel 7a
- System: Android 14 Beta 3 from the official beta program
- Security Update: 5 June 2023
- Root & Module System: [KernelSU](https://kernelsu.org/) v0.6.1(11041) with 5.10.157 kernel
Note: root permission was granted for all the packages from AOSPMod, and disabled "Umount modules" functions for SystemUI, Settings, and Dialer apps.
- List of apps that have been granted root access:
![image](https://github.com/siavash79/AOSPMods/assets/4851274/510a648b-abc7-4523-b967-428e6fefea50)

**_sh.siava.*_**
- List of apps that mounted to modules systems:
_**com.google.android.dialer
com.android.phone
com.google.android.apps.nexuslauncher
com.android.settings
com.android.systemui**_
- LSPosed Version: 1.8.6 (6896)

### Logs

[modules_2023-07-01T14_41_34.939297.log](https://github.com/siavash79/AOSPMods/files/11926136/modules_2023-07-01T14_41_34.939297.log)

**Comment by EleoXDA** [comment]
This is not the logs that we require. Please create zip using the method below and share here:

![IMG_20230701_194722_997.jpg](https://github.com/siavash79/AOSPMods/assets/27622683/d22c5e74-020e-484b-9f36-14624630216b)

**Comment by EleoXDA** [comment]
Also, kernelSU is not officially supported method. So, please use the method explained in readme file

**Comment by etnperlong** [comment]
I think this problem still exists and is not related to KernelSU.

I think the development team should at least maybe look at the Log, rather than having the preconception that "I don't look at it if it's not officially supported"

**Comment by EleoXDA** [comment]
We cannot reproduce on our devices. And literally anybody else in support group

**Comment by EleoXDA** [comment]
> I think this problem still exists and is not related to KernelSU.
> 
> I think the development team should at least maybe look at the Log, rather than having the preconception that "I don't look at it if it's not officially supported"

It is expected as the root method is not the one we advise. But the code is open-source. Feel free to check out what may have gone wrong
