### ISSUE TITLE
Edit Always on display

### ISSUE THREAD

**Issue by Anto426** [siavash79/AOSPMods#653]
if it's possible it would be nice to add an option to change Always on display maybe adding an image or change the font

Is this feature implemented on any other app/mod/rom? please specify
Not aosp roms have this option

anyway beautiful work!!

**Comment by EleoXDA** [comment]
What functional advantage does it bring? We accept features that bring functional advantages rather than adding beauty/aesthetics. For those, you can request feature from Iconify app.
