### ISSUE TITLE
Request - More features/options

### ISSUE THREAD

**Issue by droidmate** [siavash79/AOSPMods#66]
This is a request for more features/options on 3-button navbar. Already posted with screenshot on xda shall. Links:

https://forum.xda-developers.com/t/mod-xposed-magisk-pre-release-aosp-mods-system-modifications-for-aosp-based-android-12.4421743/post-86692363

https://forum.xda-developers.com/t/mod-xposed-magisk-pre-release-aosp-mods-system-modifications-for-aosp-based-android-12.4421743/post-86692489

More screenshots will be added at this link. You may check later. https://forum.xda-developers.com/t/mod-xposed-magisk-pre-release-aosp-mods-system-modifications-for-aosp-based-android-12.4421743/post-86750745

**Comment by hairyfred** [comment]
+ 1 for a invert swap + recents
