### ISSUE TITLE
[Bug] double tap to sleep on lock screen interferes with music widget

### ISSUE THREAD

**Issue by FurhadTheNerd** [siavash79/AOSPMods#665]
### Describe the issue

when you click twice on that music player widget or whatever it's called (video below) it will lock the phone, i believe that's not supposed to happen?

### Steps to reproduce

steps to reproduce:
(enable double tap to sleep on lock screen inside aospmods)
1. go to lock screen
2. click anywhere inside the music widget twice
3. then screen goes to sleep

https://github.com/siavash79/AOSPMods/assets/83399502/b52b77fc-a973-4776-b4c4-79fe076c12d6

### Your device setup (Please take some time to give correct information here)

- pixel 6 (orilo) stock firmware/rom
- android 13
- July 5, 2023
- magisk 26.1 (26100)
- apps with root access list: 
![Screenshot_20230728-113346](https://github.com/siavash79/AOSPMods/assets/83399502/8378a422-20b5-429d-a2ae-dbaf08653581)
- magisk modules list: 
![Screenshot_20230728-113449](https://github.com/siavash79/AOSPMods/assets/83399502/94aca0d5-ba3a-4639-b852-23b0daf87e9e)
- lsposed 1.8.6 (6712) - Zygisk
- lsposed modules: 
![Screenshot_20230728-113549](https://github.com/siavash79/AOSPMods/assets/83399502/3ec64e0c-dbe9-4e60-8ecc-0ec32b125cd7)

**Comment by EleoXDA** [comment]
> ### Describe the issue
> when you click twice on that music player widget or whatever it's called (video below) it will lock the phone, i believe that's not supposed to happen?

It is supposed to happen. Lockscreen is one. It doesn't separate widget from rest of the screen. And why double clicking on a widget instead of clicking once, **which is supposed to be done**?

**Comment by EleoXDA** [comment]
It is supposed to happen if you enabled double tap to sleep on lockscreen in AOSPMods. It doesnt separate lockscreen from widget. 

Also, you never need to double tap on the widget. One tap is the only one that is required.

And lastly, you can evade re-locking screen if you give one second between your touches
