### ISSUE TITLE
Disable access quick settings/notification center and power options in lockscreen.

### ISSUE THREAD

**Issue by NescauQuente** [siavash79/AOSPMods#667]
### What's on your mind?
Add an option in quick settings tab (or lock screen tab) to disable access to quick settings/notification center and power options menu.

### Is this feature implemented on any other app/mod/rom? please specify
Yes.

This option is available in official ROMs from manufacturers, such as Samsung for example, but if you are going to use LineageOS this option is not directly present in the settings.

The option is also available on GravityBox, but it only has an official version up to android 11.

**Comment by EleoXDA** [comment]
The security measurements are already applied by AOSP code. Toggles that need secure measurements require unlock by owner to proceed

**Comment by EleoXDA** [comment]
Also, there are at least 4-5 similar requests that were denied. Next time please browse previously denied requests before opening a new one
