### ISSUE TITLE
[Bug] Brightness Slider in QQS not visible after device restart/reboot, option in AOSPmods isn’t even visible, needs manual "restart SystemUI"

### ISSUE THREAD

**Issue by arghfrank** [siavash79/AOSPMods#670]
### Describe the issue

After restarting my device, the brightness slider is only visible in QS, not in QQS, although the option is activated in AOSP. I need to "Restart SystemUI" through AOSPmods, then it’s working.

### Steps to reproduce

Restart device, unlock, swipe to see QQS, no brightness slider. Also, the option in AOSPmods ("show brightness slider on QQS Panel" isn’t there, at this point.

AOSPmods -> Restart SystemUI -> swipe to see QQS, there it is. Instead of restarting SystemUI I could also turn off/on some of the other brigtness slider options in AOSPmods, like "move slider to bottom", afterwards the "Show brightness slider on QQS" option appears (and so does the brightness slider itself in QQS).

Attached LSPosed logs are from one of those cycles, i.e. reboot/look at qqs/restart systemui/look at qqs.
(Though I guess "look at QQS" isn’t shown in the log ..) :-)
Also a screencast is attached - QQS without brightness slider, then turning another option off/on in AOSPmods, "show brightness slider" option appears, brightness slider appears, exit.

I think it worked in the past, at least I would have noticed if it didn’t -- though sadly I can’t pinpoint what caused it to break (i.e. if it has been the AOSPmods-update or some other module or app in the last few days or anything else that I did).

Thanks for checking this in advance, let me know if you need more info/details on anything.

### Expected bahavior

Expected to see the brightness slider on top in QQS (and the option in AOSPmod) alwayshtness slider on top in QQS (and the option in AOSPmod) always

### Your device setup (Please take some time to give correct information here)

Pixel 7a, Stock firmware, 13.0.0 (TQ3A.230705.001, Jul 2023)
Magisk 26.1 stable
LSPosed 1.8.6, Zygisk
AOSPmods canary-270

### Logs

[LSPosed_2023-07-31T07_57_00.221180.zip](https://github.com/siavash79/AOSPMods/files/12211999/LSPosed_2023-07-31T07_57_00.221180.zip)
[LSPosed_2023-07-31T07_57_07.050721.zip](https://github.com/siavash79/AOSPMods/files/12212000/LSPosed_2023-07-31T07_57_07.050721.zip)

https://github.com/siavash79/AOSPMods/assets/13719504/fe231cf7-67cc-41eb-8177-0ffd6801d8ab

**Comment by arghfrank** [comment]
will do. thank you.

**Comment by EleoXDA** [comment]
Cannot reproduce. Sorry
