### ISSUE TITLE
Change quick tile text

### ISSUE THREAD

**Issue by chaoscreater** [siavash79/AOSPMods#671]
I miss the old Android 10 classic quick tile icons. I've managed to use this mod to make my quick tiles show extra rows and columns and now I can see a lot more quick tiles in one go. However, the text on them aren't very visible. I've tried to make the quick tile size tiny and restarted systemUI, but the text is still hard to read. Here's an example of what I mean:

![image](https://github.com/siavash79/AOSPMods/assets/18227319/b7045864-f93f-4ebf-ac7e-d33283d64e54)

Is it possible to make the text small, or the quick tile size even smaller? Ideally, they should be a round shape about the size of the old quick tile size. Like this:

![image](https://github.com/siavash79/AOSPMods/assets/18227319/4ae61137-1155-477a-a27f-720e6340bd4c)

**Comment by EleoXDA** [comment]
No

**Comment by EleoXDA** [comment]
This is what you can do with AOSPMods:

![Screenshot_20230731-164628.png](https://github.com/siavash79/AOSPMods/assets/27622683/17cc80f3-4444-4325-b943-6919bbb2eaba)



This is what you can do with AOSPMods + Iconify

![Screenshot_20230731-164540.png](https://github.com/siavash79/AOSPMods/assets/27622683/fdb97c08-a254-4078-ab3f-f0eed721dfaf)

**Comment by chaoscreater** [comment]
Thanks.

For those trying to find "vertical icons", it's actually called "Move tile icons to the top". Make sure to refresh system UI.

**Comment by EleoXDA** [comment]
Text size is available in AOSPMods too. Anyways, you found what you need

**Comment by EleoXDA** [comment]
For more info, read wiki page of AOSPMods. Everything is explained there already

**Comment by EleoXDA** [comment]
https://github.com/siavash79/AOSPMods/wiki/AOSPMods-Wiki

**Comment by chaoscreater** [comment]
Yes, the tile label size is there and I've dialed it all the way down to the lowest setting at 50%. But Iconify is able to make it even smaller, hence why I made that comment.

Unrelated, but is it possible for you to include a search feature in your app? It'd be nice to quickly search for keywords that match setting names.

**Comment by chaoscreater** [comment]
I would if I'm a programmer lol. I'm just a power user.

**Comment by EleoXDA** [comment]
Never late to learn

**Comment by chaoscreater** [comment]
There's also the time constraint as well.

If money isn't a concern and I never have to work in my life and have all the free time in the world, sure. But to learn a completely new skill from scratch, just to do add a search functionality to an app that is written / developed by someone else, that's time consuming.

I know how to write Powershell scripts, I know DevOps to an extent and I know how to debug certain apps and languages. But that doesn't make me a programmer or Android dev. Looking through thousands of lines of code written by someone else isn't very rewarding and the time could be spent on other things with higher priority.

Anyway, I just thought it'd make more sense for the feature request to be actioned by the creator or the team responsible for developing said application. Thought I'd give it a shot. Maybe 10 years later I'd take a look at doing this myself lol.

Or maybe when ChatGPT gets good enough to look through an entire codebase and tweak things with 99% accuracy, then that'd be worthwhile.

**Comment by EleoXDA** [comment]
> There's also the time constraint as well.
> 
> If money isn't a concern and I never have to work in my life and have all the free time in the world, then sure I'd take a look. But to learn a completely new skill from scratch, just to do add a search functionality to an app that is written / developed by someone else, that's time consuming and not worth the effort.
> 
> I know how to write Powershell scripts, I know DevOps to an extent and I know how to debug certain apps and languages. But that doesn't make me a programmer or Android dev. Looking through thousands of lines of code written by someone else isn't very rewarding and the time could be spent on other things with higher priority.
> 
> Anyway, I just thought it'd make more sense for the feature request to be actioned by the creator or the team responsible for developing said application. Thought I'd give it a shot. Maybe 10 years later I'd take a look at doing this myself lol.
> 
> Or maybe when ChatGPT gets good enough to look through an entire codebase and tweak things with 99% accuracy, then that'd be worthwhile.

Ok. Will be waiting for your PR
