### ISSUE TITLE
[Bug] Power Menu has blue background on full version 

### ISSUE THREAD

**Issue by nyveZz** [siavash79/AOSPMods#675]
### Describe the issue

This shows up directly after flashing the module and rebooting

### Steps to reproduce

1. Long press the power button
2. Power Menu background is blue

### Expected bahavior

Power Menu background would be in its ordinary color

### Your device setup (Please take some time to give correct information here)

- Poco X4 GT CrDroid 9.7

- Android 13 Stable 
- Security Patch: July 7th
- Magisk Delta fdac22ba-delta (25210)
- Apps with su access: AOSPMods, FKM, Pixel Launcher Mods, Revanced Manager and Scene
- Magisk Modules: AOSPMods 2.9.0, Better QS 2.0, Bootprotect Mtk, Dimensity 8000/9000 Voltage Regulator 2.0.0, Dimensity GPU Hybrid Governor 1.3.2, Gboard Lite Installer v13, Pixel Launcher Extended 1.6, Ignore Cutout, Universal Safety Net Fix 2.4.0 Mod 2.0, ByeShit v9, KillerLogger 2.1 Mod, Pixelify v2.2, Scene, modified xaga thermals and LSposed 1.8.6 mod
- LSposed 1.8.6
- LSposed Modules: AOSPMods 2.9.0 Full Version
Camera Control 1.0, CorePatch 4.2, Installer++ 1.0.0330ac1, Scene 6.3.11 and Thanox 4.2.2

**Comment by EleoXDA** [comment]
CrDroid not supported
