### ISSUE TITLE
Add screen off animation

### ISSUE THREAD

**Issue by ukrbugreporter** [siavash79/AOSPMods#677]
Custom screen off animations have been available in custom ROMs for a while already. This feature was also available in Xposed modules like [Screen Off Animation](https://forum.xda-developers.com/t/mod-xposed-4-0-screenoffanimation-v1-3-custom-screen-on-off-animation.2762332/), GravityBox and some others. I would love to see that feature in AOSP mods. Below I attached a screenshot from settings on crDroid, demonstrating this feature.
![image](https://github.com/siavash79/AOSPMods/assets/66782671/9c782443-c5ab-41e9-8dde-c711a447d987)

![image](https://github.com/siavash79/AOSPMods/assets/66782671/45f8e91f-1186-4bbc-b227-fcee203ec1e8)

**Comment by EleoXDA** [comment]
What is the use of it other than "animation"? Any functional benefit? I don't see tbh
