### ISSUE TITLE
Add Reticker notifications pop-ups 

### ISSUE THREAD

**Issue by ShayanFaisal** [siavash79/AOSPMods#678]
What's on your mind?
I really miss reticker, it's not interruptive as well like stock notifications pop-ups that takes alot of space and it's quite annoying 

Is this feature implemented on any other app/mod/rom? please specify
Yes it's present in alot of ROMs,but Alphadroid has the best reticker with it's bouncy effect one,if it's possible do add Reticker from that ROM as animation wise it's quite good,other ROMs that got this are Rising OS,Spark OS, Bananadroid

**Comment by EleoXDA** [comment]
Please search closed tickets before openning new one:
https://github.com/siavash79/AOSPMods/issues/655
