### ISSUE TITLE
Remove QS Tile Label

### ISSUE THREAD

**Issue by anuraag488** [siavash79/AOSPMods#684]
What's on your mind?
Is it possible to remove QS Tile label completely so that we can see only summary.

Is this feature implemented on any other app/mod/rom? please specify
Don't know if any other rom contains it.

**Comment by EleoXDA** [comment]
> What's on your mind? Is it possible to remove QS Tile label completely so that we can see only summary.
> 
> Is this feature implemented on any other app/mod/rom? please specify Don't know if any other rom contains it.

Duplicate https://github.com/siavash79/AOSPMods/issues/573
