### ISSUE TITLE
[Bug] 2.4.1 no longer splits intenet tile to seperate tiles

### ISSUE THREAD

**Issue by nutpantz** [siavash79/AOSPMods#686]
### Describe the issue

using the lastest LineageOS 19.1 for the herolte the internet tile is no linger split and i don think kill foreground app works anymore also   lineage-19.1-20230817-microG-signed-herolte.zip

### Steps to reproduce

install the app and try using the split internet tile or kill foreground app on a updated lineage 19.1 2023 07+

### Your device setup (Please take some time to give correct information here)

 latest everything just the minimum installed magisk lsposed and aospmod fresh install no apps

**Comment by EleoXDA** [comment]
No support for old versions. Use betterinternettiles app from playstore
