### ISSUE TITLE
[FEATURE] Incerase max QS columns count

### ISSUE THREAD

**Issue by tadekdudek** [siavash79/AOSPMods#687]
Like in title. Max 2 columns in landscape - is it a joke? Android has 4 by default.

**Comment by EleoXDA** [comment]
Have you even ONCE have used AOSPMods? It sounds you haven't even. Because we had that YEARS ago

**Comment by tadekdudek** [comment]
Sorry, I had an outdated version. But after update nothing has changed.

![Screenshot_20230822-075027_App will close now  You can open it again by tapping on the new icon](https://github.com/siavash79/AOSPMods/assets/99012892/496c1aa6-c071-4530-8c24-7feaa5af412e)

**Comment by EleoXDA** [comment]
> Sorry, I had an outdated version. But after update nothing has changed.
> 
> ![Screenshot_20230822-075027_App will close now  You can open it again by tapping on the new icon](https://github.com/siavash79/AOSPMods/assets/99012892/496c1aa6-c071-4530-8c24-7feaa5af412e)

Read GitHub ReadMe file and be sure you are using app correctly on a SUPPORTED device and SUPPORTED firmware
