### ISSUE TITLE
add status bar Current and power

### ISSUE THREAD

**Issue by shandianex1** [siavash79/AOSPMods#688]
could you add current and power to status bar like the internet speed?

it display like "159mA/1.5w"

this feature implemented on the lsp app “米客” for miui

**Comment by EleoXDA** [comment]
> could you add current and power to status bar like the internet speed?
> 
> it display like "159mA/1.5w"
> 
> 
> this feature implemented on the lsp app “米客” for miui
> 

What is the benefit of knowing that? And what is the difference of having it on statusbar rather than in lockscreen (which is already included)?

**Comment by shandianex1** [comment]
Place it on the status bar to view power consumption and power at any time, specific to each app. And if you are playing with your phone while charging, you can easily check the charging efficiency.

**Comment by EleoXDA** [comment]
> Place it on the status bar to view power consumption and power at any time, specific to each app. And if you are playing with your phone while charging, you can easily check the charging efficiency.

1. It will never give power consumption per app. You have loads of background services that may intervene. Unless you have veey low RAM or enable "don't have background apps"... which defeats the purpose of having a "smart"phone
2. It is never encouraged to use the device while charging. It degrades your battery no matter how or what are you using.
3. The apps like Ampere can give you information about charge/discharge mA
