### ISSUE TITLE
Notification shade transparency 

### ISSUE THREAD

**Issue by TravisShepherd** [siavash79/AOSPMods#69]
Option to change the transparency of the notification shade.

I know it was used in an Xposed module, I just can't remember which one.
It may have been implemented in rom control for pixel devices.

**Comment by EleoXDA** [comment]
Do you mean like ClearLineage? The transparent (or adjustable transparency) in quick settings?

**Comment by TravisShepherd** [comment]
Yes? I know that I could see the wallpaper or current app when I pulled
down the notification shade.

**Comment by EleoXDA** [comment]
Ok, then it is simply ClearLineage mode you are asking. Well, as with blur QS background, the CL requires all the time to be in background, eating ram, cpu and battery. And to worsen things, you cannot use it with powersave mode. This would mean that AOSPMods will be seen as a battery hog even though it is the mod which is causing battery drain. I, personally would stay away from it for now.

**Comment by TravisShepherd** [comment]
I appreciate the input, thank you for looking into it though.
