### ISSUE TITLE
[Bug] "Lock Screen \ Clock area custom text" not displayed

### ISSUE THREAD

**Issue by omartinsGH** [siavash79/AOSPMods#693]
### Describe the issue

Custom text added to "Lock Screen \ Clock area custom text" field stops being displayed after a few moments

### Steps to reproduce

1. add a custom text to "Lock Screen \ Clock area custom text", i.e. $Nssid, hit OK
2. lock screen and confirm the info is correctly being displayed (in the example it should display SSID of Wi-Fi network which the phone is connected to)
3. after a few moments (minutes or ours), while still being connect to the same Wi-Fi network, the custom text is no longer displayed.

### Expected bahavior

While connected to an Wi-Fi network, custom text shoul be displayed on Lock Screen

### Your device setup (Please take some time to give correct information here)

- Google Pixel 5
- Android 13 Stable version
- August Security Patch
- Magisk 25.1 Stable
- AOSP Mod 3.0.0 stable (279) - Xposed version
- LSPosed 1.9.1 (this bug was present with 1.8.6 as well)
- Other modules: USNF 2.4.0 MOD 2.0; Pixel 5 - VoLTE/WiFi/5F V1.01 StanislawRogasik

**Comment by omartinsGH** [comment]
Hello,

Please find requested logs:

[modules_2023-09-02T09_01_40.75554.log](https://github.com/siavash79/AOSPMods/files/12503519/modules_2023-09-02T09_01_40.75554.log)
[verbose_2023-09-02T09_01_40.750975.log](https://github.com/siavash79/AOSPMods/files/12503521/verbose_2023-09-02T09_01_40.750975.log)

Thank you

**Comment by EleoXDA** [comment]
> Hello,
> 
> Please find requested logs:
> 
> [modules_2023-09-02T09_01_40.75554.log](https://github.com/siavash79/AOSPMods/files/12503519/modules_2023-09-02T09_01_40.75554.log)
> [verbose_2023-09-02T09_01_40.750975.log](https://github.com/siavash79/AOSPMods/files/12503521/verbose_2023-09-02T09_01_40.750975.log)
> 
> Thank you
> 

Is it not fixed for you yet with latest Canary?

**Comment by omartinsGH** [comment]
Yes, it is solved! Thank you!
Nevertheless, I've firstly updated to the canary (283) and it kept not working as intended.
But since @siavash79 added a comment labeling it as solved I've decided to remove the module, reboot, install canary and import settings back. After this, it started working as expected! 
I still had to extract the apk from the zip file, and install it, in order to have it labeled as AOSP Mods.

Thank you all for this great piece of software 😉
