### ISSUE TITLE
Wireless buds battery info in status bar

### ISSUE THREAD

**Issue by cybr47** [siavash79/AOSPMods#695]
What's on your mind?
Adding wireless earbuds' battery info in status bar. If more than one devices are connected, only the active device would show up in the status bar. There's also a battery widget which I believe, could also be modified to show Bluetooth buds' battery info. 

Is this feature implemented on any other app/mod/rom? please specify
There a some open-sourced apps like CAPods and more on Playstore. This feature is also implemented in Evolution X ROM.

**Comment by EleoXDA** [comment]
There is a saying in android development:
- If there is a 3rd party app for that, dont use xposed method ;)
