### ISSUE TITLE
Feature: Press and hold back button to kill foreground app

### ISSUE THREAD

**Issue by woubulbus** [siavash79/AOSPMods#698]
**What's on your mind?**
I would like to be able to hold the back button to kill the foreground app. I like it because sometimes on misbehaving apps, closing it on recents doesn't fully close the app or delete data from the last session. Sometimes on more misbehaving apps, closing the app on recents doesn't actually close it at all because its frozen or something else. 

**Is this feature implemented on any other app/mod/rom? please specify**
This is a feature I loved on LineageOS but lost when I recently got my Pixel 7 phone.

**Comment by EleoXDA** [comment]
There are already gestures implemented for gesture navigation. Please use one of them. 3button navbar is deprecated
