### ISSUE TITLE
Internet Tiles Broken after installing the module

### ISSUE THREAD

**Issue by Fr1ction** [siavash79/AOSPMods#70]
**Describe the bug**
Internet tiles fail to display Mobile data status, It shows Off instead while Wi-Fi is off and Shows Blank Wifi Signal whenever connected to Mobile Data

**To Reproduce**
1. Install the module as usual
2. Open Quick Settings and tap Internet Tiles
3. Toggle the Wi-Fi off or Disconnect from Wi-Fi
4. See that Internet Tiles are broken

**Expected behavior**
Internet Tiles should shows Mobile data Carrier instead of Wi-Fi Status only

**Screenshots**
![Screenshot_20220418-214710_Chrome](https://user-images.githubusercontent.com/34088764/163817405-1cbffa4d-f3d8-4063-9b22-01a76d32d466.png)

![Screenshot_20220418-214658_Chrome (1)](https://user-images.githubusercontent.com/34088764/163817475-720663b5-7f52-4fb4-8b9c-d498c08d987a.png)

 - Device: Redmi Note 7
 - OS: Pixel Experience Plus 12L April Security Patch

**Comment by siavash79** [comment]
The internet tile option in AOSPMods doesn't really play with the system behavior about signals and connection

The **only** thing it does is that it asks Android to show the WiFi and data tiles that it already has, but has decided to hide them. The tiles and their behavior is really managed by your ROM.

I understand what you say, but it's probably a bug in your OS

**Comment by Fr1ction** [comment]
Actually, Before the module is installed the Internet Tiles works as intended. it only breaks whenever the module is installed. Thanks Anyway
