### ISSUE TITLE
Extremely weird systemUI force close upon flashing this module. Android 14 QPR 1, pixel 6 pro[Bug] 

### ISSUE THREAD

**Issue by HiFIi** [siavash79/AOSPMods#700]
### Describe the issue

SystemUI force closes constantly, I flashed it prior and it caused a data corruption as well potentially! Which has happened before in the past too with different things so it's not unheard of

### Steps to reproduce

1. Flash Android 14 QPR 1 on pixel 6 pro
2. Install ruru and lsposed
3. Flash AOSPmods canary 284
4. Reboot phone

### Expected behavior

No systemUI force close

### Your device setup (Please take some time to give correct information here)

Pixel 6 pro
Android 14 QPR 1

### Logs

I do not want to risk data corruption on my phone again which reboots to the bootloader thing and says "factory reset" :(

**Comment by EleoXDA** [comment]
Android 14 QPR 1 is not yet out.

You are using Android 14 QPR 1 BETA build. That one is not yet supported. Please wait 7-14 days for it to be supported.

**Comment by HiFIi** [comment]
Yeah no worries, I was just letting you know. I totally understand and I am a developer myself so I know how it goes. Thank you for everything you di

**Comment by alphapuggle** [comment]
Getting the same issue on Pixel 7 Pro QPR1 14 (U1B1.230908.003).

Something changed in System UI, borked my substratum themes on it too. Hold the volume down button while you're booting and it'll disable your magisk modules and boot into safe mode without any issue. Then you can reboot into the system normally and not lose your data.

**Comment by alphapuggle** [comment]
Not sure which logs you'd want to diagnose the issue, but if you need any lmk I'll install it and see what I can snag

**Comment by EleoXDA** [comment]
Thanks. If you can, please share logs. We are aware of the issue. But as I wrote above it requires a lot of time (7-14 days) due to large number of incompatibilities with android 14 beta 1. Could you join our telegram support group (if you haven't already) as well for a faster communication?

https://t.me/AOSPMods_Support

**Comment by alphapuggle** [comment]
Logs attached below I used the AOSPMods-Full.zip (Canary release 04be95b) for testing. I'm "Nathan Metzger" on the Telegram, but I'm muted for an hour @ join

[kmsg.log](https://github.com/siavash79/AOSPMods/files/12716027/kmsg.log)
[modules_2023-09-25T09_56_23.513928.log](https://github.com/siavash79/AOSPMods/files/12716028/modules_2023-09-25T09_56_23.513928.log)
[props.txt](https://github.com/siavash79/AOSPMods/files/12716030/props.txt)
[verbose_2023-09-25T09_56_23.513368.log](https://github.com/siavash79/AOSPMods/files/12716031/verbose_2023-09-25T09_56_23.513368.log)

**Comment by scarlettekk** [comment]
There is a magisk module that automatically disables modules if systemUI crash loops, which is useful for situations like these. https://github.com/Magisk-Modules-Alt-Repo/systemui-bootloop
Also same behavior on 14QPR1, let me know if more logs is helpful :)

**Comment by HiFIi** [comment]
> There is a magisk module that automatically disables modules if systemUI crash loops, which is useful for situations like these. https://github.com/Magisk-Modules-Alt-Repo/systemui-bootloop Also same behavior on 14QPR1, let me know if more logs is helpful :)

Nice. Thanks

**Comment by HiFIi** [comment]
YEP FIXEDDDDDD
