### ISSUE TITLE
not work in miui 14

### ISSUE THREAD

**Issue by jsjsjsia** [siavash79/AOSPMods#701]
### Describe the issue

not work

### Steps to reproduce

not work

### Expected behavior

not work

### Your device setup (Please take some time to give correct information here)

redmi note 12 pro
android 13 miui 14
magisk 26.3
lsposed 1.9.1
![Screenshot_2023-09-24-18-11-21-425_com topjohnwu magisk](https://github.com/siavash79/AOSPMods/assets/145280448/c6795a41-e5b5-4ff2-a1a6-b03adc5d81f6)
![Screenshot_2023-09-24-18-11-46-265_com android shell](https://github.com/siavash79/AOSPMods/assets/145280448/df87da29-1f62-4144-9124-234697f8abdc)

### Logs

[LSPosed_2023-09-24T18_07_46.225901.zip](https://github.com/siavash79/AOSPMods/files/12708352/LSPosed_2023-09-24T18_07_46.225901.zip)

**Comment by EleoXDA** [comment]
You don't say. Have you heard of ReadMe file? Read it ;)
