### ISSUE TITLE
[Bug] Unable to instantiate activity

### ISSUE THREAD

**Issue by Thisisauser6443** [siavash79/AOSPMods#704]
### Describe the issue

After updating to either one of the last 2 Canary builds, I'm unable to launch the manager. There's also a fair bit of error logs, according to the LSPosed manager

### Steps to reproduce

1. Either clean install/update from 3.0.0 with one of the last 2 canary builds, at the time of writing
2. Reboot, and observe a package name from the app drawer - Last time I tried, this was `com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior`
3. Try to launch it, only to be greeted with the "X keeps stopping" dialog box

### Expected behavior

The manager should launch as expected, and the app icon should be named AOSP Mods, instead of the package name that I specified

### Your device setup (Please take some time to give correct information here)

- Device - Google Pixel 4a 5G (`bramble`)
- Android version - Android 14 (`UP1A.231005.007`)
- Patch - October 2023
- Magisk version - Magisk Delta 26.3 Canary - `0fe46c5a-delta (26301) (D)`
- LSPosed version - 1.9.1 (6990) - Zygisk

[For the root access and Magisk/LSPosed modules, I was forced to upload to my G. Drive, since GitHub has a 10MB file limit, because, oh boy... I've got a fair bit of modules installed (They're all disabled, though)](https://drive.google.com/file/d/1-5lnPzS2PXQmvnkvkKbNjl_iFGBK-OFU/view?usp=drive_link)

### Logs

[Logs from Magisk](https://github.com/siavash79/AOSPMods/files/12841812/magisk_log_2023-10-08T22.26.55.log)
[Logs from LSPosed](https://github.com/siavash79/AOSPMods/files/12841813/LSPosed_2023-10-08T22_26_58.578156.zip)

**Comment by EleoXDA** [comment]
Try installing apk inside zip.

**Comment by Thisisauser6443** [comment]
> Try installing apk inside zip.
> 
> It is a known issue where first time sometimes the app doesn't show up correctly and you need to unzip the magisk zip and install the apk inside the zip 

Yeah, seems like that was the issue, after all
