### ISSUE TITLE
Request: Hide next alarm icon and text on the lockscreen

### ISSUE THREAD

**Issue by creeve4** [siavash79/AOSPMods#71]
An option to hide next alarm icon and text on the lockscreen.

**Comment by siavash79** [comment]
Good suggestion. thank you

**Comment by creeve4** [comment]
[Here is a link](https://github.com/GravityBox/GravityBox/commit/f9eff1ee6261fa7cffda47af39d1bea1b96bfed7) to a commit for Gravitybox that implemented this functionality.

I hope you can work on it soon!
