### ISSUE TITLE
Request: Limit the lower brightness limit for automatic brightness adjustment, and make brightness adjustment faster.

### ISSUE THREAD

**Issue by daiaji** [siavash79/AOSPMods#74]
Basically, it can be considered as a function porting of Resurrection Remix OS. The reason is that Android's automatic brightness adjustment has always been difficult to use. I often encounter automatic brightness adjustment in low-light environments that make the screen brightness too dark, so dark that I can't read the screen.

And the delay of automatic brightness adjustment is a bit high, can this process be made faster?

I am using crDroid 8.4 ROM based on Android 12.1.
 
![user-images githubusercontent com_156196834-d79d5d4b-a95f-4fba-9f21-45e8e81315fc](https://user-images.githubusercontent.com/25875791/164143484-11f01230-043d-4a84-8e34-f0e2044d833f.jpg)

**Comment by EleoXDA** [comment]
I think you can manually adjust the auto brightness adjustment manually - i.e. when you increase brightness in a full dark environment (might require adjustment of several times), it remembers your setting and when you next time enter to similar dark environment it adjusts brightness to your chosen level.

In stock firmware that is how it functions

**Comment by daiaji** [comment]
In fact, I can only say that it is very difficult to use in the current state, and I can't remember how many times I have manually adjusted the brightness in automatic brightness mode in the past few months.

**Comment by siavash79** [comment]
Let's keep it open maybe it can be done some time

**Comment by EleoXDA** [comment]
> Let's keep it open maybe it can be done some time

Is it kernel or framework though? I remember lower brightness to be a kernel substitute back in previous android versions

**Comment by siavash79** [comment]
Control is by kernel. But I think the framework should be in command.
It may or may not be practical. But worths a shot

**Comment by siavash79** [comment]
Added in canary 142

**Comment by daiaji** [comment]
Very useful, basically now I don't need to adjust the screen brightness in the dark
