### ISSUE TITLE
Request: Ported moto gestures from LineageOS.

### ISSUE THREAD

**Issue by daiaji** [siavash79/AOSPMods#75]
I really liked this feature when I was using the Moto Z2 Force (nash). Basically, this feature is very fault-tolerant. You take out your phone and shake it to turn on the flashlight or camera. You don't need to confirm the position of the power button.  The power button menu is called up because the duration of pressing the power button is incorrect.  

And it's actually been available on LineageOS all the time, but it seems to be limited to Motorola phones, but I think it's very useful and worth using for all phones with accelerometers.

I am using crDroid 8.4 ROM based on Android 12.1.
![user-images githubusercontent com_155737078-643eb7f7-5b89-4171-9f12-297a69e8494e](https://user-images.githubusercontent.com/25875791/164146837-f96e9882-f65c-44fd-b6d9-53d34d13a2bb.png)

**Comment by siavash79** [comment]
Seems like a very useful thing!

However, implementing this needs a level of expertise that we don't have at the moment (otherwise: dramatic battery drain, bootloops, etc). I'm not even sure if this is possible through Xposed or not

I'll have to mark it as won'tfix

**Comment by daiaji** [comment]
In fact, I also estimated the difficulty of implementing this function. Earlier I heard that in order to make the soc sleep when this function is implemented, Motorola's engineers have configured a co-processor for Motorola's machines.  But I heard from Lenovo mobile phone users that when Motorola used Lenovo's myOS, the moto gesture was ported for myOS, and almost all Lenovo mobile phones using myOS can use this function, which seems to point to the fact that modern SoCs have  A coprocessor-like feature is implemented, or even if a coprocessor is not required, this feature does not add much additional power consumption, after all, I have not heard Lenovo users complain about the additional power consumption caused by this feature.

**Comment by siavash79** [comment]
That's correct. In order to prevent battery drain, they did the mod in kernel level (power optimization). Kernel level works can't be modded in Xposed. unfortunately

**Comment by Underday** [comment]
Tap tap app is doing something just like that, maybe it's integrated in app of AOSPmods and it's use accessibility settings or something. But yeah if it didn't configure well, it's just nightmare.
