### ISSUE TITLE
Hide navigation bar but keep gestures keyboard space

### ISSUE THREAD

**Issue by Liuhjhj** [siavash79/AOSPMods#78]
What's on your mind?
When the navigation bar is hidden, the keyboard height is too low when using the keyboard if no keyboard space is reserved.

Is this feature implemented on any other app/mod/rom? please specify
Fullscreen/Immersive Gestures magisk mod

**Comment by ElTifo** [comment]
It's possible to achieve that effect if you don't enable the "hide navigation bar", have gestures navigation on system enabled and just reduce the navbar pill width to 0.

**Comment by Liuhjhj** [comment]
> It's possible to achieve that effect if you don't enable the "hide navigation bar", have gestures navigation on system enabled and just reduce the navbar pill width to 0.

But if you do not enable hide the navigation bar and set the length of the navbar pill to 0, the height of the navigation bar is not 0.

**Comment by mingaldrichgan** [comment]
+1, these are two different behaviours. Fortunately the Fullscreen/Immersive Gestures mod does this (and is customizable) so you could just use that for now.
