### ISSUE TITLE
Brightness slider appears in qqs without any actions in app

### ISSUE THREAD

**Issue by old4error** [siavash79/AOSPMods#80]
When you just install module and reboot device, after swiping down brightness slider appears in qqs with 100% value, but in qs brightness is like i set before. In app I didn't touch "Show brightness slider on Panel" option (it's off). Device: poco x3 pro (vayu), rom: arrow os 12.1 (aln kernel)
[LSPosed_2022-04-21T22_12_58.841.zip](https://github.com/siavash79/AOSPMods/files/8534466/LSPosed_2022-04-21T22_12_58.841.zip)

![Screenshot_20220421-222043_AOSP Mods](https://user-images.githubusercontent.com/58698398/164537138-bf99a113-7d92-4076-8de2-784931943512.png)
![Screenshot_20220421-222047_AOSP Mods](https://user-images.githubusercontent.com/58698398/164537172-7dc763bc-ce0a-4e5f-a4ca-004448761d5c.png)

**Comment by siavash79** [comment]
Already fixed and will be live in next canary release
