### ISSUE TITLE
Request: FOD icon enable on Lockscreen

### ISSUE THREAD

**Issue by ArianaMayLL** [siavash79/AOSPMods#81]
It would be cool to see FOD icon enable on Side fingerprint reader using AOSP mod so that I could use this on PE GSi (≧▽≦)

this feature was implemented on Corvus OS vS2.1 GSi Rom Android 12.1

**Comment by siavash79** [comment]
Can you please explain more? What's FOD?

**Comment by ArianaMayLL** [comment]
> Can you please explain more? What's FOD?

It's not really a FOD in a device with under display fp
It just an icon lock of FOD in Lockscreen

Here for example this device doesn't have FOD 
It only has side fingerprint reader
But it enables the FOD icon on Lockscreen
![IMG_20220422_162906_354](https://user-images.githubusercontent.com/104180696/164650404-58651c57-0fb9-4c19-9be7-60189c476fcc.jpg)

**Comment by siavash79** [comment]
What is it useful for? Your device shows whether it's locked or unlocked anyway. Doesn't it?
