### ISSUE TITLE
Feature Request: Quick pin unlock

### ISSUE THREAD

**Issue by EleoXDA** [siavash79/AOSPMods#86]
Hello.
This is not as vital for me, as I am required to input a pin only when rebooting the device, but it would be quite better for people who use a pin/password instead of a fingerprint.

It is available on the latest gravitybox: https://github.com/GravityBox/GravityBox/tree/r/GravityBox/src/main/java/com/ceco/r/gravitybox

**Comment by juliovedovatto** [comment]
@EleoXDA It seems author already replied about 

![image](https://user-images.githubusercontent.com/320507/165841766-2f2f029d-a0e2-47b8-9f22-1d86f970b231.png)


https://forum.xda-developers.com/t/mod-xposed-magisk-pre-release-aosp-mods-system-modifications-for-aosp-based-android-12.4421743/post-86683933
