### ISSUE TITLE
This module invalidates the font module.

### ISSUE THREAD

**Issue by 3166265725** [siavash79/AOSPMods#87]
**Describe the bug**
When both AOSP mods and the module that modifies the system font exist at the same time, the font module will fail.

**To Reproduce**
1. Install any module that modifies the font.
2. Install the AOSP mods.
3. The font module will fail.

**Expected behavior**
Font module takes effect

**Screenshots**

 - Device: Mi10 Pro
 - OS: Evolution X, Android12.1

**LSPosed Log**
AOSP mods is working properly, so there is no need to upload the LSPosed log.

**Comment by siavash79** [comment]
Since this module also includes custom fonts, the xml files conflict.

Not sure what would be the best strategy to avoid this

**Comment by EleoXDA** [comment]
> Since this module also includes custom fonts, the xml files conflict.
> 
> Not sure what would be the best strategy to avoid this

Could there be a way to add a button to "enable custom font features" that requires a reboot? That way you can keep it enabled or disabled from the start. And if the user wants to use their own custom font, they can disable it, reboot, and use their own font.

I also use my own custom font to which I added extra symbols that are not present on the stock font file. So I would also like to have an option to keep custom font features of this mod away from my own font.

**Comment by siavash79** [comment]
Seems like beta 2 has done the trick. What do you think?
