### ISSUE TITLE
Qs tile vibration

### ISSUE THREAD

**Issue by hellobot09** [siavash79/AOSPMods#98]
**Describe the bug**
Quick settings vibrate on touch haptics is too low

**To Reproduce**
1. Go to 'aosp mods and enable qs touch vibration'
2. Click on 'quick settings tile'

**Expected behavior**
ROMs having "qs touch vibration" is high compared to this one, sometimes you can't feel it if you are using any back cover . If possible please increase vibration intensity :-).

**Screenshots**

 - Device: Poco m2 pro Miatoll (gram)
 - OS: Arrow Os 12.1

**LSPosed Log**
Please attach LSposed Module log if you are able to. (Open LSPosed, go to module logs, press save button and attach to this bug report)

**Comment by siavash79** [comment]
please install this file, restart systemUI, and see if the vibration strength has changed (you don't need to uninstall the magisk module)

https://github.com/siavash79/AOSPMods/actions/runs/2254080590

**Comment by hellobot09** [comment]
> https://github.com/siavash79/AOSPMods/actions/runs/2254080590

After updating the apk and rebooting system ui quick settings tile vibration not working & rebooted system but still same.

**Comment by siavash79** [comment]
do other options work?

**Comment by hellobot09** [comment]
Yes
But system ui getting reboot when using custom  system icon except sam, kai and outline facing this issue from the beginning of aosp mods

**Comment by siavash79** [comment]
The custom build that you installed has only a stronger vibration. So if c13 works for you, custom build should also work

**Comment by hellobot09** [comment]
Yes now  it's working, just  added extra system framework permission from lsposed  and did system reboot. But its working only when I set any system icon and did no system ui reboot.

Can you also check  system ui getting reboot when I set custom system icon pack (except default, kai, sam and outline) and tap on bluetooth and hotspot tile.

**Comment by hellobot09** [comment]
Here the log
[full.log](https://github.com/siavash79/AOSPMods/files/8600418/full.log)

**Comment by siavash79** [comment]
Thanks.
First: please give me the first feedback: did vibration get stronger? does it need to be more or less?

**Comment by siavash79** [comment]
Nothing special was noticed from your log, except that lots of features are not compatible with arrowOS

**Comment by hellobot09** [comment]
> Thanks. First: please give me the first feedback: did vibration get stronger? does it need to be more or less?

No now its good enough

**Comment by hellobot09** [comment]
> Nothing special was noticed from your log, except that lots of features are not compatible with arrowOS

Can you reduce qs tile vibration? Its good  for vibration motors but device having different haptics like Miatoll z shocker( spring type) feels odd 
For example I set fluid navigation gesture haptics - default system haptic and it feels very good , almost clicky type).

**Comment by siavash79** [comment]
It's recently set to phone's default click haptic. Hopefully will be better than this

**Comment by siavash79** [comment]
https://github.com/siavash79/AOSPMods/actions/runs/2290629988

This is a test version of it

**Comment by hellobot09** [comment]
> https://github.com/siavash79/AOSPMods/actions/runs/2290629988
> 
> This is a test version of it

Perfect now its really good 😊
